### ISSUE TITLE
A simple example of using the root

### ISSUE THREAD

**Issue by findborg** [hyperapp/hyperapp#10]
I was wondering if you could show me a simple example of the root.  This is what is needed to bind the model to a div correct?

**Comment by findborg** [comment]
For example:  code to render at <div id="app"></div>

**Comment by jbucaran** [comment]
Sure.

```js
app({ 
  model: "Hi.", 
  view: model => html`<h1>${model}</h1>`,
  root: document.getElementById("main")
})
```

[**CodePen**](http://codepen.io/jbucaran/pen/JELvjO?editors=1010)

**Comment by findborg** [comment]
Wow,  you are up.  I guess folks like us never sleep.  I will give it a go.

**Comment by jbucaran** [comment]
Sleep, what's that? 😄

**Comment by findborg** [comment]
works perfectly

**Comment by jorgebucaran** [comment]
###### Summary 

- V1 changed the `root` property to the 4th positional argument to the `app` function.

- V2 _changes_ it back to named properties but the property name is `container`, not ~~`root`~~ to more accurately describe the relation of your VDOM-turned-DOM tree with its parent.
