### ISSUE TITLE
Handle null nodes

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#100]
This is low priority, since you should not be using null anyway, but I'll fix it.

> Basically, it doesn't make sense to have both undefined and null.

**Comment by dodekeract** [comment]
I always considered `null` to be an *explicit `undefined`*.

**Comment by jbucaran** [comment]
@dodekeract Ha, no, you've just crossed over into the Twilight Zone...

**Comment by dodekeract** [comment]
That's even more counter-intuitive than `NaN !== NaN`.

**Comment by leeoniya** [comment]
@dodekeract it's probably worth reading replies and learning from them [1]

[1] https://www.reddit.com/r/javascript/comments/5qae31/how_i_wrote_the_worlds_fastest_javascript/dczbaof/

**Comment by dodekeract** [comment]
@leeoniya Haha, what a small world we live in. I still think it's counter-intuitive though.

**Comment by jbucaran** [comment]
Fixed in https://github.com/hyperapp/hyperapp/commit/e47017ae2e238fce675b3aad29fb9c24affe1329
