### ISSUE TITLE
How to implement constraints for reducers, etc.

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#101]
Maybe it's just my newness to the Elm Architecture, but I'm having a hard time figuring out how to do constraints with reducers, etc. For example, in the GoMix todo example when you click the button, it adds a todo whether the input has a value or not. For keyup I can put a constraint like this:
```js
// If the input has value and the user hits Enter, add todo.
onkeyup={e => (e.keyCode === 13 && e.target.value) ? actions.add() : ""}
```
But for the button click that won't work because it doesn't have access to the input value. Old school way would be on button click check value of input, if it has a value, do stuff, otherwise not. How do you do that with this pattern? This would also come up with form validation. 🤔

**Comment by jbucaran** [comment]
@rbiggs You have access to the input value, indirectly, because you keep track in the model of every input change. Does that make sense?

**Comment by jbucaran** [comment]
```jsx
app({ 
    model: {
        items: [],
        text: ""
    },
    view: (model, actions) => 
        <main>
            <input 
                oninput={e => actions.setText(e.target.value)}
                type="text" 
                value={model.text}
            />
            <button
                onclick={e => model.text !== "" && actions.append()}
            >Add </button>
            <ul>
                {model.items.map(item => <li>{item}</li>)}
            </ul>
        </main>,
    reducers: {
        append: (model) => ({
            text: "",
            items: model.items.concat(model.text)
        }),
        setText: (model, text) => ({ text })
    }
})
```
[**CodePen**](http://codepen.io/jbucaran/pen/pRMKab?editors=0010)

**Comment by dodekeract** [comment]
Alternatively an effect would be better, since it doesn't require any logic in the view-part.

**Comment by tunnckoCore** [comment]
@dodekeract :+1: 

@rbiggs it sounds to me like an effect too. Make an effect, then just pass `e` to it, and do you checking and all that stuff there, not in the view part.

**Comment by rbiggs** [comment]
Yeah, I was thinking an effect was the way to go, but I wan't sure. Thanx. 🍺🍻
