### ISSUE TITLE
If there's only one subscription, let subscriptions be either a function or an array

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#105]
Currently, you can only create subscriptions like this:

```jsx
app({
  ...
  subscriptions: [ f1, f2, f3 ]
})
```

This feature would let you create subscriptions **also** like this:
```jsx
app({
  ...
  subscriptions: f
})
```

**Comment by dodekeract** [comment]
Seems to be unnecessary and the name `subscriptions` actually implies that it's meant for multiple subs.

**Comment by jbucaran** [comment]
Perhaps _nonessential_, yes. You also don't need variables, since everything can be a function 😄.

Maybe you are right and it's a couple of typeof checks we don't really need.

**Comment by tunnckoCore** [comment]
just one arrayify and filter for to be function

**Comment by jbucaran** [comment]
Closing as won't fix!
