### ISSUE TITLE
Consider adding a code of conduct.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#107]
A code of conduct is a set of rules outlining the social norms for an organization. 

Comments?

**See also**:

* https://github.com/reactjs/react-redux/blob/master/CODE_OF_CONDUCT.md
* https://github.com/blog/2039-adopting-the-open-code-of-conduct

**Comment by tunnckoCore** [comment]
Never seen value for such thing. The only thing that you need to do is absolutely always to answer with kindness as most as possible - everyone win and no burnouts.

@sindresorhus (just a mention, which won't ping him - don't surprise if no response from him :)):

**What irritates you most of all in open source?**

> tl;dr Nothing really.
I used to get annoyed a lot by various things in open source; trolls, low-quality issues and pull requests, rude users, etc. But you won’t last long in open source if you let that stuff affect you. Communication on the internet is hard. You have different personalities, cultures, language proficiencies and coding competencies, all trying to communicate together with text. Lots of opportunities for miscommunication and assumptions. See Hanlon’s razor. I’ve found the best way to handle this is with absolute kindness, no matter what. Trolls will hate it, as they’re only seeking a reaction. Rude people will respect it. Nice people will appreciate it. And I feel better. Win win. 

**How do you avoid burnout?**

> I don’t. I embrace it. Burnout is unavoidable when you’re active in open source. Knowing how to handle it is key. Once in a while, I get burned out by all the issues, negativity, demanding user, drama, workload, etc, and I take a couple of weeks break from GitHub. Being away for a little while helps me process it all and refill my batteries.

ref: https://blog.sindresorhus.com/answering-anything-678ce5623798#.aij0hv6xn

**Comment by selfup** [comment]
@jbucaran I tend to follow as much as relevantly possible: https://www.rust-lang.org/en-US/conduct.html

**Comment by tzellman** [comment]
The [Ember.js Code of Conduct](http://emberjs.com/guidelines/) borrows heavily from:

- [Mozilla Code of Conduct](https://www.mozilla.org/en-US/about/governance/policies/participation/)
- [Ubuntu Code of Conduct](https://www.ubuntu.com/about/about-ubuntu/conduct)
- [Twitter Code of Conduct](https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md)

**Comment by jbucaran** [comment]
No one is causing trouble (anymore) so I'll go ahead and close this. We can always come back to it later.
