### ISSUE TITLE
Allow h to receive children as the second argument.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#108]
If this involves a lot of code, then the benefit will not balance the bundle size increase tradeoff, otherwise it would be nice to have.

Instead of:
```jsx
h("h1", {}, "Hello")
```

Allow h to work like this too:
```jsx
h("h1", "Hello")
```

**Comment by lukejacksonn** [comment]
Is this not possible already? Looking at hyperscript docs it says..

> **If** an {} object is passed in it will be used to set attributes.

Here they give an example of constructing a table. There are are no empty attribute objects but maybe that is just for tables.

https://github.com/hyperhype/hyperscript#children---array
```
var h = require('hyperscript')
var obj = {
  a: 'Apple',
  b: 'Banana',
}
h('table',
  h('tr', h('th', 'letter'), h('th', 'fruit')),
  Object.keys(obj).map(function (k) {
    return h('tr',
      h('th', k),
      h('td', obj[k])
    )
  })
)
```
If not I think there are already similar helpers out there:

- https://github.com/ohanhi/hyperscript-helpers does a reasonable similar thing.

**Comment by jbucaran** [comment]
@lukejacksonn It's not possible already, because HyperApp implements its own hyperscript `h` function and I didn't see the point of embellishing a function that is not going to be used directly in most cases.

Most people will either be using Hyperx or JSX right?

**Comment by lukejacksonn** [comment]
Ahh I didn't put two and two together there! I'd assume most people would use HyperX or JSX. It must be something hyperscript devs thought would be a good idea though so maybe not ruling out entirely.

**Comment by jbucaran** [comment]
@lukejacksonn Remember than JSX/Hyperx is transformed into h calls in your dist/bundle.

Some people think a good reason to use vanilla h is to "avoid" the build pipeline, but you are still going to bundle assets and uglify the code anyway, so using pure h calls does not remove the need of a build setup, it just mitigates some of the tooling.

**Comment by lukejacksonn** [comment]
I'l take a look :)

**Comment by jbucaran** [comment]
Closing as won't fix! 😄
