### ISSUE TITLE
Router catch all? handling 404s.

### ISSUE THREAD

**Issue by traducer** [hyperapp/hyperapp#109]
When routes aren't found is there a way to define a catch all route ```"*"``` in the router?

I want to handle 404 pages for any routes or sub-routes not defined in my application.

So if someone goes to ```/this/should/404``` I can catch it and have the server render a 404 page.

**Comment by jbucaran** [comment]
@traducer Currently `/` acts as the wildcard when no other route matches. 

If that's not good enough, we can make `/` match only `/` and `*` match everything when no other route matches.

What do you think?

**Comment by traducer** [comment]
@jbucaran, I think a default route that a user can specify at app creation would be a wise decision. ```/``` should strictly be the indexRoute. If a user wants it to be the default route, they should have the freedom to choose what that default route is. This is basically what [sheet-router](https://github.com/yoshuawuyts/sheet-router) does for unmatched routes. 

So for example, when creating the routes structure:

```javascript
const { h, router, app } = require('hyperapp')

app({
  router: router,
  view: {
    '/': _ => <Home />,
    '/profile': _ => <Profile />,
    '/404': _ => <NotFound />,
    'defaultRoute': '/404' //this can also be a function 

  }
})
```


My suggestions would be instead of returning [```routes['/']```](https://github.com/hyperapp/hyperapp/blob/master/src/router.js#L60)

return the route the user defined at app creation, something like:

```javascript
var dft = routes['defaultRoute']

/* if a default route exists check if it's a string, if it is return the function mapped to that string.
** Ff it isn't a string return the function mapped to defaultRoute. If it doesn't exist at all, return routes['/'] 
*/
return !dft ? routes['/'] : (typeof dft === 'string') ? routes[dft] : dft 
```

**Comment by jbucaran** [comment]
@traducer Yeah, I like that. Now that the router is an optional dependency, I'd love to make the router better.

What about using "*" as a wild card instead of :404? I think :404 is rather confusing.

**Comment by traducer** [comment]
@jbucaran yes an asterisk is probably the best character for a wild card. I'm not sure if there would be any implications in the route matching since you are using regular expressions to match routes.

**Comment by lukejacksonn** [comment]
I'm going to try and implement this tonight, that is.. make `/` an explicit route the default route `*` not had a look at the code yet but how hard can it be 😅

**Comment by jbucaran** [comment]
@traducer Implemented by defining a route with a key: `*`. Not properly yet documented I think.
