### ISSUE TITLE
Made a hyperapp boilerplate repo with webpack 🎉

### ISSUE THREAD

**Issue by selfup** [hyperapp/hyperapp#11]
https://github.com/selfup/hyperapp-one

Let me know what you think of the structure.

Heavily inspired (the view is pretty much the same :joy:) by the simple counter example!

A lot of people like a quick repo that is already wired up. Nothing crazy, just a simple boilerplate 😄

**Comment by jbucaran** [comment]
@selfup Looks great. Clean structure and separation of concerns!

**Comment by jbucaran** [comment]
@selfup Looks great. Clean structure and separation of concerns! My only suggestion would be to use the full `hyperapp-` prefix, since `hyper-` is already popular with the [HyperTerm](https://github.com/zeit/hyper) folks.

**Comment by selfup** [comment]
@jbucaran That is a great point! I'll rename the repo and change the remote on my end!

**Comment by jbucaran** [comment]
@selfup Thanks! Now's perfect.

**Comment by tunnckoCore** [comment]
Looks cool to me too. But I think there can have folders for effects and subs too? :)

**Comment by selfup** [comment]
@tunnckoCore I can add two empty directories for effects and subs :smile: 

The app itself doesn't use them, but it will give an idea as to where to create them when they need it!

Great suggestion

**Comment by jbucaran** [comment]
Thanks @selfup!

**Comment by selfup** [comment]
Going to add hooks tonight as well. Forgot about those 😂

**Comment by selfup** [comment]
Ok added hooks dir and how to remove git history to start as a new repo :tada:

**Comment by aeosynth** [comment]
is hot module reloading possible?

**Comment by selfup** [comment]
@aeosynth I was under the impression that the DOM changed (only what you change) once you hit save in your editor.

Let me double check on that.

**Comment by AutoSponge** [comment]
I created a hyperapp server using neutrino.js: [gomix](https://gomix.com/#!/project/neutrino-hyperapp)

**Comment by jbucaran** [comment]
@AutoSponge This is awesome Paul, thanks for sharing!

**Comment by jbucaran** [comment]
@AutoSponge Do you think this would do a nice [preset](https://neutrino.js.org/creating-presets.html)?

**Comment by jbucaran** [comment]
https://github.com/heygrady/neutrino-preset-standard/blob/master/src/index.js

**Comment by AutoSponge** [comment]
@jbucaran I see a couple of options:

1. Get HRM working and make it a preset that builds on -web
1. Create a preset that steals stuff from -web but ignores HMR

**Comment by jbucaran** [comment]
@dodekeract @lukejacksonn Is this something you folks would find handy? 

Hi @maraisr! Do you have any experience getting HMR working?

**Comment by maraisr** [comment]
@jbucaran I have yeah - its a pain at first, and will need to write some funk re-hibernate type stuff within our code base.

Basically, ou gets a callback for whenever a module has been re-compiled with its new source, so some eval magic, or whatever. My best bet would be to look through the VueJS codebase, and look at how Evan does it.

**Comment by selfup** [comment]
Update to `0.7.1` 🎉

**Comment by dodekeract** [comment]
HMR would be amazing.

**Comment by lukejacksonn** [comment]
I would never turn down the offer of some HMR action!

**Comment by Rob-pw** [comment]
Bump for interest! ^^'

**Comment by selfup** [comment]
Upgrading to 8.1 for the boilerplate as well as a few other changes (webpack config, yarn.lock, package.json)

https://github.com/selfup/hyperapp-one/pull/15

**Comment by andyrj** [comment]
I don't think you have to create anything extra to enable HMR now...  I just slapped a quick example together that simply empties document.body.innerHTML within the module.hot.accept...
`import { h, app } from 'hyperapp';

export default () => {
	app({
		state: 'Hello World!123',
		view: state => <div>{state}</div>
	});
};`

`import app from './app';

document.body.innerHTML = '';
app();

if (module.hot) {
	module.hot.accept('./app', () => {
		document.body.innerHTML = '';
		app();
	});
	module.hot.accept();
}`

my setup is using jsdom to SSR so I have to add that initial document.body.innerHTML = ''; to prevent client render doubling dom, I really don't see a requirement for an extra plugin/mixin like the react-transform-hmr, should be able to save the state in the accept and pass it into your new app as well...

**Comment by jbucaran** [comment]
@andyrj Thanks! I know @MatejMazur would love to see this.

Ref:
- https://github.com/MatejMazur/hyperapp-hmr-experiment

**Comment by MatejMazur** [comment]
@andyrj Hi, could you send me a working example with HMR (ideally repo)? Because your code is only with static state but that's not the use case for HMR.

**Comment by andyrj** [comment]
@MatejMazur I see the issue with HMR you are referring to but I think what is needed is a small change to the hyperapp api to accommodate saving state between module replacements...  I just hacked together the needed changes in a repo and also made an example app that shows your counter saving state during HMR...

granted this approach only saves the state every second, you could essentially change the setInterval to work for your needs, and the only change needed to the hyperapp api is returning an object that can retrieve the current state instance...

Hyperapp fork with necessary change to api: https://github.com/andyrj/hyperapp
Working example repo: https://github.com/andyrj/hyperapp-starter/tree/HMR-example

**Comment by andyrj** [comment]
I am not familiar with the hyperapp minxins, if they have access to the full app.state, then I would guess you could do something similar from a mixin without mucking with hyperapp app.js like I had to there...

**Comment by andyrj** [comment]
@MatejMazur updated the HMR example to not need modifications to hyperapp...  working really well, noticed after looking in docs that I could just add a render event to copy new state into a global and the HMR can just reload from there...  try it out see if this pattern works for your use case I guess, I think it's what I'm gonna use moving forward with hyperapp

**Comment by jbucaran** [comment]
Now that https://github.com/hyperapp/awesome-hyperapp exists, we can close here! Thank you for making this @selfup! You were the first. 💥
