### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#110]
So, we have a logo for the project, but it's kind of overly simplistic. The project needs a killer logo, something with power - a mandala or chakra vortex. I took the letters h and a and transposed them to create a logogram. I was shooting for something that conveys power and trust, a bit of a corporate feel, but not oppressive. Something that would look good as a sticker on a laptop or as a t-shirt. Something that would stick in your head once you saw it. Something visually distinct from the Angular, React, VueJS logos.

I used Avenir Condensed, but I changed the stem widths and curve depths to make the two pieces fit together. The original is just a Sketch file, from which I produced png and svg formats.

Behold:

![hyperapp 2x](https://cloud.githubusercontent.com/assets/249218/23265640/1197deec-f99a-11e6-8a7a-8bace6955edf.png)

What do you guys think?

**Comment by lukejacksonn** [comment]
I think the current logo is pretty killer 💯 this design feels a little soft considering the somewhat brutalist (deliberate plainness) approach hyperapp encourages; clearly abstracted and coherent  parts that come together to create something functional and easy to comprehend. My initial feeling is that the primitive shapes sharp edges of the square and triangle that make up the existing logo depicts this ethos better than this proposed design.

Here are some assets @jbucaran posted on slack that you might find inspiration in. Mainly putting them here as reference for discussion:

![hyperapp-evolution](https://cloud.githubusercontent.com/assets/1457604/23310798/b5b78e90-fa81-11e6-8bfe-1768128c7764.png)

![hyperapp](https://cloud.githubusercontent.com/assets/1457604/23310834/dbbaa1a4-fa81-11e6-85d8-43c6d0f68a76.png)

**Comment by jbucaran** [comment]
@rbiggs Thank you for thinking about this! If I squint my eyes, it reminds me of General Electric's logo, which is pretty cool.

Now, I'm open to suggestions and alternatives based in the current logo.

BTW, while designing this logo I thought about HyperText and HyperMedia, retro design and the 90s. I still chose a "modern" color, since we're building modern frontend apps anyway!

■ ◣

**Comment by jbucaran** [comment]
Just for fun.

![tshirt](https://cloud.githubusercontent.com/assets/56996/23316665/b4598d18-fb0e-11e6-8880-e79e867d227e.png)
![black](https://cloud.githubusercontent.com/assets/56996/23316732/fb096e4a-fb0e-11e6-9538-70ef1ff5ba01.png)

**Comment by userpixel** [comment]
I like the simplicity of the second logo which guess well with the simplicity and light weight of the code. :+1:

**Comment by jbucaran** [comment]
Very nice CSS rendition of the logo by @lukejacksonn.
* http://codepen.io/lukejacksonn/pen/JWXLNo?editors=0100

**Comment by jbucaran** [comment]
Nothing actionable here, so let's close this! 😄
