### ISSUE TITLE
effects are magically part of reducers

### ISSUE THREAD

**Issue by cdeutmeyer** [hyperapp/hyperapp#111]
I'm planning on giving a HyperApp presentation to the other developers at work.
When I explain effects, I'm going to have a sample running in codepen similar to this:
```javascript
app({  
  model: { 
      city: "", 
      wx: { } 
  },
  reducers: {
    setCity: (model, e) => ({ city: e.currentTarget.value }),
    setWeather : (model, formattedData ) => ({ wx: formattedData })    
  },
  effects: {
     getWeather : (model, reducers) => {
          axios.get'http://api.openweathermap.org/data/2.5/weather'....
              reducers.setWeather(obj);            
          })
      }
  },
  view: (model, reducers) => (
      <div>      
        <input type="text" oninput={ (e) => ( reducers.setCity(e)) } />
        <input type="button" value="Get Weather" onclick={ _ => reducers.getWeather() } />
        { Object.keys(model.wx).map((key, index) => (<div>{key} : {model.wx[key]} </div>)) }      
      </div>
   )  
})
```
The part that they are going to be questioning is this:
```javascript
        <input type="text" oninput={ (e) => ( reducers.setCity(e)) } />
        <input type="button" value="Get Weather" onclick={ _ => reducers.getWeather() } />
```

Since reducers are passed into the view and not the effects.. how is it that we can call reducers .getWeather() and it magically uses the effect? How do I explain this eloquently - or can I change the code to make it not seem so magic?

Thanks, 
Chad

**Comment by dodekeract** [comment]
@cdeutmeyer please use

'''javascript
...
'''

With a backtick instead of ' for proper formatting.

**Comment by cdeutmeyer** [comment]
thanks @dodekeract!! I'm kinda new at making posts!

**Comment by dodekeract** [comment]
@cdeutmeyer the `javascript` part in my formatting advice is mandatory to enable syntax highlighting.

**Comment by dodekeract** [comment]
@cdeutmeyer Regarding your question, that's because the signature of `view` is actually `(model, actions)`, not `(model, reducers)`. `actions` are `effects` + `reducers`.

So everything is behaving as intended.

**Comment by tunnckoCore** [comment]
I don't see any magic. Both are `actions`.

Btw, that's why i kinda lika destruction feature. So in my micro app (again elm architecture) i just pass one single `context` argument to the views, reducers, effects and subscriptions - `{ state, actions, props, params, children, data }`. Destruction kinda enforce good names and "best practices" all the time.

**Comment by cdeutmeyer** [comment]
OK, thanks for the formatting help and explanation.. :)

**Comment by jbucaran** [comment]
@cdeutmeyer Thanks for the question! This point is now well explained in the docs. I added cross-ref links and hinted that both reducers and effects conform what HyperApp calls actions.

* https://github.com/hyperapp/hyperapp/wiki/api#reducers
* https://github.com/hyperapp/hyperapp/wiki/api#effects
