### ISSUE TITLE
Question about jsx and props.children

### ISSUE THREAD

**Issue by traducer** [hyperapp/hyperapp#116]
In react when using jsx, you can nest components by using props.children.

Is this possible with hyperapp? I've tried doing it in my views but it isn't working the way I'd expect it to.

For example, this does not work as intended:

```javascript
const { h, app } = hyperapp
/** @jsx h */

const Foo = ({ children }) => (
  <div>
    hello {children}
  </div>
)


app({
  view: _ => <Foo>world</Foo>
})

/* view should return <div> hello world </div> */
```

**Comment by jbucaran** [comment]
> @traducer In react when using jsx, you can nest components by using props.children.

Nope, the signature of a component function is as follows: `(data, children)`.

Components are called as follows:

```jsx
component(data, children || [])
```
[Source](https://github.com/hyperapp/hyperapp/blob/master/src/h.js#L14).

Perhaps you want this?
```jsx
const Foo = (props, children) => 
  <div>
    hello {children}
  </div>
```

**Comment by traducer** [comment]
@jbucaran, awesome explanation, thank you.

I used[choo](https://github.com/yoshuawuyts/choo) quite a bit, so being able to use different virtual dom builders is nice.

**Comment by jbucaran** [comment]
@traducer Choo is very nice too. Thanks! :)
