### ISSUE TITLE
How To Reference An Element?

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#12]
Let's say I want to access an element from a function bound to a button. In react/JSX it'd be possible to use `ref=`. Is there anything similar for hyperapp without manually keeping track of ids or going through the reducer?

**Comment by jbucaran** [comment]
@dodekeract HyperApp supports _lifecycle events_, it's just missing from the docs.

You can use oncreate (or onupdate) to get reference to any DOM element.

#### Lifecycle Events

* oncreate
* onupdate
* onremove

#### Examples

```js
app({ 
  view: _ => html`
    <div oncreate=${e => console.log(e)}>Hi.</div>`
})
```
[**CodePen**](http://codepen.io/jbucaran/pen/apGZoo?editors=0010)

**Comment by jbucaran** [comment]
@dodekeract Does that help? If you give me a more concrete example I can put something together.

**Comment by dodekeract** [comment]
@jbucaran I think that depends on the use-case. It should be possible to assign the element to a variable though, which is nice. Adding this to docs should make a workaround possible for most stuff.

**Comment by selfup** [comment]
@dodekeract When you say keeping track of `ids` do you mean the global variables that ids create referencing their nodes?

Here is an example: http://jsbin.com/yipaka/2/edit?html,js,console

Just making sure that is what you meant 👍

**Comment by jbucaran** [comment]
@dodekeract Think we can close here? Lifecycle Events have been documented. 

Or is there anything else missing?

**Comment by jorgebucaran** [comment]
###### Summary

Hyperapp has no [_refs_](https://reactjs.org/docs/refs-and-the-dom.html), but you can access a virtual node's actual DOM element through lifecycle events.
