### ISSUE TITLE
Why handle className?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#123]
This works:
```jsx
const node = <div class="foo">ok</div>
```

This also works:
```jsx
const node = html`<div class="foo">ok</div>`
```

Maybe I forgot, but I don't see what's the point of supporting className in HyperApp.

**Comment by jbucaran** [comment]
This seems to be related:
* https://github.com/substack/hyperx/pull/22

Unfortunately, this seems to be an issue with how Hyperx creates both classname and class attributes in elements, so we need to support className, otherwise HyperApp would fail to toggle a class name when using Hyperx.

**Comment by tunnckoCore** [comment]
it is not related to anything. just kinda convention because such are keywords in js. that is the case with "for" -> "htmlFor", and http-equiv to httpEquiv

**Comment by jbucaran** [comment]
Sure, I think I know that pretty well. The issue here is that Hyperx adds a `classname` property to elements and there is no way to turn this off which forces us to handle it specifically.

**Comment by ngryman** [comment]
Related: #85.
