### ISSUE TITLE
Performance? 🚀 

### ISSUE THREAD

**Issue by leeoniya** [hyperapp/hyperapp#13]
Hey @jbucaran

The docs seem to lack any mention of "blazing fast" or similar :D

Do you have any of the common benchmarks implemented to know where hyperapp fits into either [1] or [2]?

[1] https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html
[2] http://mathieuancelin.github.io/js-repaint-perfs/

**Comment by jbucaran** [comment]
Thanks! I sent a PR to the js-repaint-perfs repo, let's hope to see it merged.

The good news are, benchmarks indicate that HyperApp is on the fast side. Careful examination of the gif below seems to favor the following order.

#### Inferno/HyperApp → Elm → CycleJS+Snabbdom → VueJS → morphodom

Inferno seems to do just slightly better if at all, but both Inferno and HyperApp outmatch the others and morphodom is particularly slow.

![2017-02-03 13 55 46](https://cloud.githubusercontent.com/assets/56996/22580067/aa9974f2-ea18-11e6-9f34-7aac8f7afca9.gif)

**Comment by jbucaran** [comment]
@leeoniya Thanks! I sent a PR to the js-repaint-perfs repo, let's hope to see it merged.

The good news are, benchmarks indicate that HyperApp is on the fast side. Careful examination of the gif below seems to favor the following order.

#### Inferno/HyperApp → Elm → CycleJS+Snabbdom → VueJS → morphodom

Inferno seems to do just slightly better if at all, but both Inferno and HyperApp outmatch the others and morphodom is particularly slow.

![2017-02-03 13 55 46](https://cloud.githubusercontent.com/assets/56996/22580067/aa9974f2-ea18-11e6-9f34-7aac8f7afca9.gif)

**Comment by sotojuan** [comment]
> The docs seem to lack any mention of "blazing fast" or similar :D

Probably a positive thing. In 2017 sufficient performance is a given—I care more about ergonomics and fun.

**Comment by leeoniya** [comment]
> 2017 sufficient performance is a given

certainly you don't need to be the fastest. but it helps to assure people you're not the slowest either. nothing wrong with objectivity, regardless of what year it is.

**Comment by sotojuan** [comment]
I guess I'm just tired of new libraries claiming they're "blazing fast!!111!!!!" and focusing on that instead of other features. I mean IDK, Backbone was fast enough for me 😅

**Comment by leeoniya** [comment]
yeah, the original comment was meant to be tongue-in-cheek for this reason.

nevertheless, the benchmarks are hugely helpful (even if just to catch accidental lib perf regressions). if you can believe it, there *are* apps out there for which Backbone is grossly insufficient. if you've never had perf issues with Backbone, no one is prying it or jQuery from your hands, heh 😆

**Comment by jbucaran** [comment]
Going to close here in favor of #75.

**Comment by jorgebucaran** [comment]
###### Summary

V2's new patch algorithm (based on [Superfine](https://github.com/jorgebucaran/superfine)) is signifcantly faster than V1. Here are the benchmark results. To maximize performance, the benchmarked example app makes use of memoization to boost the rendering perf of table rows that are not affected by state changes. This technique will eventually make it into core as described in #721.

![Superfine](https://user-images.githubusercontent.com/56996/42416263-ee50cec2-82a4-11e8-99fd-021a23e34f05.jpg)
