### ISSUE TITLE
Should plugins allow extending view and plugins?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#143]
Currently plugins can only extend the following app's options:

* model
* actions
* subscriptions
* hooks

Should plugins also allow extending `view` and `plugins`?

**Comment by dodekeract** [comment]
Plugins wouldn't really make sense. View is possible through the `onRender` hook.

**Comment by jbucaran** [comment]
What about extending the view?

**Comment by dodekeract** [comment]
@jbucaran > view is possible through the `onRender` hook.

What else do you mean? Extracting SVG?

**Comment by jbucaran** [comment]
I meant allowing plugins to export a `view` prop.

But, you're right, let's _not_.

**Comment by dodekeract** [comment]
What about plugins that need UI?

An example would be a plugin that integrates hyperapp updates with https://github.com/mrdoob/stats.js/ or a debugger that includes its own UI.

These plugins could essentially have their own mounting-point, view, etc.. They'd be just like any hyperapp app.

This would also make your idea of `app({}, router, stats, logger)` a reality. The thing I said about this syntax implying that multiple apps are supported — I actually start to think that it makes sense.

What do you think?

**Comment by jbucaran** [comment]
@dodekeract You can create two separate apps using `app` and embed it in sibling containers of a single parent.

**Comment by dodekeract** [comment]
@jbucaran I'm aware of that.

**Comment by jbucaran** [comment]
Awesome! 👍

**Comment by lukejacksonn** [comment]
I only recently discovered that you can have more than one hyperapp on the page at one time!? See [here for example](https://gist.github.com/lukejacksonn/e40c97ce4215ac60b041fa4d928a7d77). Is this just happenstance or was there some intention behind it?

**Comment by jbucaran** [comment]
I'd like to say there was a master plan behind it, but this is probably happenstance. I use this to visually test each version. I have a single page with every single example I've created for hyperapp to date, all in one massive screen. It used to take me 5 seconds to see everything was running smoothly, now it takes me like a minute. 

So, in your own words, happenstance, but it's quite obvious once you see that app can be called multiple times.
