### ISSUE TITLE
Add hook to router

### ISSUE THREAD

**Issue by pcariel** [hyperapp/hyperapp#144]
hi, guys. Is it possible to add some type of validation in the route before activating the view?

OnActivate similar to angular2.

**Comment by dodekeract** [comment]
Could be done with a plugin that hooks into the `onRender` hook.

**Comment by jbucaran** [comment]
@pcariel https://github.com/hyperapp/hyperapp/wiki/api#onrender :)

**Comment by dodekeract** [comment]
@jbucaran https://github.com/hyperapp/hyperapp/wiki/API#onrender

**Comment by lukejacksonn** [comment]
This is quite relevant https://github.com/hyperapp/hyperapp/pull/150.. just looking now at how it could be abstracted out to a plugin or how it can be integrated without having to alter the existing router 👍

**Comment by jbucaran** [comment]
@pcariel Epa Pablo! The router now exposes an event, `route` that may be exactly what you need. I am going to close here, but feel free to reopen or ask other questions! 👋
