### ISSUE TITLE
Make app composable

### ISSUE THREAD

**Issue by AutoSponge** [hyperapp/hyperapp#148]
Here are the changes I think need to be made to `app` and `h` to make sure that apps can be composed over each other. These features will also allow hyperapps to play nicely with independent, non-hyperapp components.

# 1
`app#render()` should not try to `createElement` when `node` is an element:

```js
const isElement = (node) => node instanceof window.HTMLElement
```

# 2
`h()` should skip elements. If `isElement`, return "`tag`"

# 3
`app()` should return `root`.

# 4
~~`render` should check for `root` existence in DOM before trying to `render` (making un-mounted apps less of a burden). When an app.root is added to the DOM by a parent app, a hook should fire `onAppend`. When removed from the DOM, a hook should fire, `onRemove`.~~
`root` should be upgraded to a node but should not be mounted to the DOM automatically.

Let's discuss :)

**Comment by jbucaran** [comment]
@AutoSponge What you are saying is that you want to pass app into app?

```jsx
const MyApp = app({...})

app({ view: model => <div><MyApp /><OtherStuff/></div>
```

**Comment by jbucaran** [comment]
> app() should return root.

This is easy to do. Does this imply that app will not mount itself automatically? I kind of like that.

**Comment by AutoSponge** [comment]
@jbucaran I think it would look more like 

```js
app({
  view: (model) => <div>{ app({...}) }</div>
})
```

**Comment by jbucaran** [comment]
1 and 2 also look easy, although I'd like to see what are the benefits of this, `h` is heavily optimized and one little more if you add there only slows everything down.

These concerns are probably "worthless". I am basically using js-framework-benchmark as a base. 0.7.1 currently scores ~1.30, which is pretty good.

**Comment by AutoSponge** [comment]
>> app() should return root.

> This is easy to do. Does this imply that app will not mount itself automatically? I kind of like that.

Currently, you can provide a `root` that's not on the DOM. I think that's how you can make an app "lazy". Only when the parent appends the returned element would the subcomponent try to render (although actions, subscriptions, etc. will still fire depending on how they're coded).

**Comment by jbucaran** [comment]
> Currently, you can provide a root that's not on the DOM.  I think that's how you can make an app "lazy".

That sounds interesting and worthy of its own separate issue. We could totally have that before any of the other stuff.

**Comment by AutoSponge** [comment]
> That sounds interesting and worthy of its own separate issue. We could totally have that before any of the other stuff.

```js
const component = app({
  view: (model) => My Component,
  root: <div></div>
})

app({
  view: (model) => <div>{ component }</div>
})
```


This would require changes [#1], [#2]

**Comment by jbucaran** [comment]
Sure, 1 and 2 are very possible and easy to do. So, what would this enable you to do?

**Comment by AutoSponge** [comment]
Complicated/expensive widgets like maps or animating components need to not be reset by a `render()` call.

**Comment by AutoSponge** [comment]
I can probably create the PR this weekend if you're interested.

**Comment by jbucaran** [comment]
@AutoSponge Sure! It would be most useful if you can also provide an example that demonstrate the feature.

**Comment by AutoSponge** [comment]
This is on hold, waiting for community need. See the example app here: https://glitch.com/edit/#!/picayune-postbox

**Comment by jbucaran** [comment]
@AutoSponge Do you think we can close here? Keys help with some of the issues describe in this thread, but I don't think `app(props)` if coming to hyperapp.

**Comment by AutoSponge** [comment]
@jbucaran to be clear, `app(props)` was not the request. It was the ability to "skip" rendering of another app component, leaving it to be autonomous. Keys may be able to do this, I'll have to test.

**Comment by jbucaran** [comment]
@AutoSponge Can you have a look at the fractal-app branch and let me know if that's close to what this wat about? 🙏

**Comment by AutoSponge** [comment]
@jbucaran I think it's exactly what I intended. You may want to adopt the tests I used: https://github.com/hyperapp/hyperapp/pull/151/files to verify.
