### ISSUE TITLE
Declare browser support 

### ISSUE THREAD

**Issue by naugtur** [hyperapp/hyperapp#149]
Readme doesn't specify which browsers can run hyperapp. 
Also, is babel required?

**Comment by jbucaran** [comment]
There's a page on the wiki, but it's needs more information and to be more prominent.

* https://github.com/hyperapp/hyperapp/wiki/Browser-Support

**Comment by jbucaran** [comment]
> Also, is babel required?

If you use JSX you will need to compile your templates to vanilla JavaScript.

This is explained in detail in the docs. See:

* [Getting Started](https://github.com/hyperapp/hyperapp/wiki/Getting-Started)
* [Build Setup](https://github.com/hyperapp/hyperapp/wiki/Build-Setup)

**Comment by dodekeract** [comment]
> if you use hyperx you need to compile

Are you sure? Hyperx uses tagged template literals which should work without transpiling.

**Comment by jbucaran** [comment]
@dodekeract Right, you don't _have_ to, but if you don't you'd be sending the entire parser which is like 10 times larger than HyperApp itself and makes it 500% slower (obviously).

I've fixed my previous comment, thanks.

**Comment by jbucaran** [comment]
@naugtur Hi again. Long time no follow up. So, I am not sure where I should put this info on the README. If you have any ideas, feel free to send a PR.
