### ISSUE TITLE
user guide of hyperapp in the gitbook can't access (404)

### ISSUE THREAD

**Issue by crixusshen** [hyperapp/hyperapp#154]
HI, hyperapp is a great framework, simple, small,to study the cost is low and combines the ideas of the Redux, I am in gitbook learned before the project, but can't access (404) today, also gitbook will maintain ?

https://www.gitbook.com/read/book/hyperapp/hyperapp/

**Comment by jbucaran** [comment]
Hi @crixusshen! I moved the user guide to the wiki. I find the wiki easier to maintain and collaborate with others! 🙏

**Comment by crixusshen** [comment]
@jbucaran Ok, I will continue to focus on this framework, hope to have more features !
