### ISSUE TITLE
Is onUpdate correct?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#156]
We're calling onUpdate _not_ inside the `if (shouldUpdate(node, oldNode)) {` clause, but the one afterwards. Essentially, onUpdate will fire for every element when its props/attrs are updated, which is basically on every cycle. I am not sure if the current behavior makes sense.

**Comment by farism** [comment]
I think onUpdate should only fire inside shouldUpdate check, but right now shouldUpdate is not advanced enough (no deep checking on attr/props) to reliably fire onUpdate. Which makes me think that some type of immutable library with cheap referential checking would be helpful.

The confusing part may be how it's called `shouldUpdate` when it's more along the lines of something like `shouldRecreate`? Or perhaps I'm reading it incorrectly.

**Comment by jbucaran** [comment]
The name choice may be bad and could change :)

**Comment by dodekeract** [comment]
`onUpdate` is actually incorrect on a different level.

If you do a partial model change it will **not** make `nextModel` the full model. `nextModel` will be the partial update.

**Comment by jbucaran** [comment]
@dodekeract Yeah, onUpdate works because it will get called when the view is rendered, but it's not correct. It should be called in shouldUpdate.

**Comment by lukejacksonn** [comment]
Related: https://hyperappjs.slack.com/archives/C41ECC0V6/p1499698015602500

> The onupdate event is fired every time the element's data is updated.

Currently onupdate gets called every time the _state_ changes not every time the _element's data_ changes. It should probably behave as described in the docs, that would make sense.

@ngryman pointed toward [app.js#L178](https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L178)

I have had a go at refactoring `updateElementData ` to only call `onupdate` when some attribute changes. Here is the function https://github.com/lukejacksonn/hyperapp/blob/onupdate-fix/src/app.js#L141

Here is a CodePen test with the old code replaced with the proposed  https://codepen.io/lukejacksonn/pen/JJeLre

Not sure how useful any of this is but it reopening until we fix the docs at least.

**Comment by ngryman** [comment]
Also, does `onupdate` bubbles up to parents?

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp/commit/010172ca36596deef445ec2292478cd99c0c1a5b
