### ISSUE TITLE
What about setState?

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#159]
Recently `effects` and `reducers` got merged into `actions`. Now the way to set the state is by just retuning an object.

What about exposing a `actions.setState` function which can be called from everywhere where `actions` are available instead? This way an effect could still return whatever it wants when called by a different action (I actually used that a lot) and code like this becomes easier to do:

```javascript
function example () {
	actions.room.set(room) // reducer
	actions.room.socket.join() // effect
	// the key here is that socket.join depends on model.room
}
```

```javascript
function example () {
	actions.setState({room})
	actions.room.socket.join()
}
```

This would also fix use-cases where big actions need to be split into multiple actions, but need to return data that is not a promise. Hard to describe, but I actually also used that for WebRTC SDP patching. I worked around this, but overall I think that this might make hyperapp easier to use for more advanced apps.

And yes, I'm aware that `setState()` would basically be implemented as `setState: (_, data) => data`.

**Comment by jbucaran** [comment]
> @dodekeract And yes, I'm aware that setState() would basically be implemented as setState: (_, data) => data.

Then, why not just add this to your actions?

**Comment by jbucaran** [comment]
@dodekeract 

I looked at your example above and I still can't understand what's the problem.

**Comment by dodekeract** [comment]
@jbucaran exactly what I said. `socket.join` depends on `model.room`. So I can't `return` and then run another action since that's not how `return` works.

**Comment by jbucaran** [comment]
@dodekeract What is `example`? Sorry, if you don't try harder, don't expect further replies.

**Comment by dodekeract** [comment]
@jbucaran It's an `action`.

**Comment by jbucaran** [comment]
And what's the problem again?

**Comment by dodekeract** [comment]
@jbucaran That `model.room` is required for `socket.join` to work. If I'd just use a `return {{room}}` there it wouldn't work since `return` cancels the function. That's why the example code **needs** a reducer or a `setState` method.

**Comment by jbucaran** [comment]
Sorry, the example is not clear to me. If you can create a simple CodePen demonstrating what's the problem I'd take a look.

**Comment by dodekeract** [comment]
@jbucaran http://codepen.io/dodekeract/pen/zZzRPX?editors=0010

**Comment by zaceno** [comment]
I like this proposal!

I too have found myself making a generic reducer-action `setState: (_, data) => data,` just to be able to update the model at multiple points within an effect. It's "boilerplate:y" enough that it might as well be built in.

**Comment by jbucaran** [comment]
@dodekeract I get it now. Thanks for making the pen, and save everyone time! :)

So, you want to use an action to return some intermediary value which will be used by another action, etc.

Though you could, wrap that in a Promise, I think you have two options, communicate only via the model, so you could update the model with some intermediary data or create a regular function that returns what you want.

I think the best approach is using a function that returns what you need.

**Comment by dodekeract** [comment]
@jbucaran The functions I have in my use-cases ARE actions though. And it makes no sense to use the model for that. The content of function results don't belong into the model. They never get rendered, they aren't important in the long-run (more than 10ms) and they might even overwrite each other. They depend on both the model and other actions. This is one of the reasons why I didn't like the effects/reducers mixup - it breaks a lot of functionality for the sake of **looking** more minimalistic.

**Comment by jbucaran** [comment]
> And it makes no sense to use the model for that. 

Yes, I agree, I wouldn't use the model for that either. I think what works is creating one or more function that can help modularize your action.

**Comment by jbucaran** [comment]
> I too have found myself making a generic reducer-action setState: (_, data) => data, just to be able to update the model at multiple points within an effect. It's "boilerplate:y" enough that it might as well be built in.

If you really need to update the model, that's okay, but I think @dodekeract does not want to update the model for intermediary values he needs inside an action. For that I would just make one or more functions.

**Comment by jbucaran** [comment]
> @dodekeract A non-hyperapp function would be a possible workaround, but you'd have to pass both `model` and `actions` which seems to be quite weird if it's not a hyperapp action.

That's not a workaround, that's one way (if not _the_ way) to go about this.

**Comment by dodekeract** [comment]
@jbucaran A function that takes `model`, `actions` and `data`. Hmm - where do I know this concept from? Oh, right - an action.

**Comment by jbucaran** [comment]
@dodekeract You can still try to come up with a real example that shows why the approach I proposed would be an obvious disadvantage! 😊

**Comment by dodekeract** [comment]
@jbucaran I can't share the source. It's proprietary.

**Comment by jbucaran** [comment]
@dodekeract Sure. Create one you can then. Things don't get done just by asking, you need to demonstrate the problem.

**Comment by zaceno** [comment]
@dodekeract 

>  I'm also proposing that return does what it's supposed to do - return a value to the caller. What's your opinion about that? (see codepen for details on why I think this is good)

Well, I'm certainly no expert on the design philosophies in hyperapp, but fwiw I think it makes sense. 

When the decision was made to combine effects and reducers, we ended up in this situation where actions are supposed to be either a reducer (which should return a new state, hence it's name) or an effect which should be able to return anything. It seems like an odd place to be in now. This proposal would make things elegant again. (Again, from my non-expert perspective)

So yes, I believe I agree with this aspect too, of your proposal. Sure it means lots of people will have to rewrite their actions, but hyperapp is still in it's infancy and this is exactly the time to get it right, and not worry too much about backwards-compatibility.

**Comment by jbucaran** [comment]
@zaceno Sorry, but we are not separating actions into reducers and effects again, unless it is demonstrated why that would be better than having only actions.

**Comment by dodekeract** [comment]
@jbucaran This proposal never separated actions into effects and reducers. I actually see it like the proper way to merge both perfectly.

**Comment by jbucaran** [comment]
@dodekeract If you need to have a setState action, then why can't you just create it? I don't really see what's the point of a framework providing such a minimal boilerplate. What about people that don't need it? I certainly don't.

**Comment by dodekeract** [comment]
@jbucaran The point is to **free** `return` and to make async patterns easy.

**Comment by jbucaran** [comment]
@dodekeract What async patterns are currently not easy? I think they are extremely simple now.

**Comment by dodekeract** [comment]
@jbucaran Look at my example. It needs a reducer that only exists because it's unable to use `return` since that'd quit the function.

**Comment by jbucaran** [comment]
@dodekeract That has nothing to do with "async patterns".

**Comment by jbucaran** [comment]
@dodekeract Can you create a new issue? 

> #### Add actions.setState new default action

**Comment by dodekeract** [comment]
@jbucaran The proposal also includes changing the `return` behavior back to how it used to work.

Actually, now that I think about it your approach was to merge `effects` into `reducers` (reducer is default) and my approach is to merge `reducers` into `effects`. :smile:

**Comment by jbucaran** [comment]
@dodekeract Ah, that makes things more clear. The reason you'd need setState is because we'd be removing reducers.

**Comment by lukejacksonn** [comment]
@dodekeract how hard would it be to create a PR for this? If the diff is not huge, which it shouldn't be right? Then usefulness vs cost can be better assessed. For what it is worth I can see some value in it, not sure if this is the ideal solution but I think trying to determine what actions return and how to chain them is a valuable discussion to have.

**Comment by dodekeract** [comment]
@jbucaran Well. Not "really" removing, but make them optional.

I'd still consider `(model, data, {setState}) => setState({/*...*/})` a reducer.

**Comment by dodekeract** [comment]
@lukejacksonn It's trivial to create a PR, excluding tests that is. Quite sure that there'd be a lot of changes in those.

**Comment by jbucaran** [comment]
Yeah, now I finally understand what you mean.

**Comment by jbucaran** [comment]
This is more opaque. For example, instead of:

```jsx
app({
  model: 0,
  actions: {
    add: model => model + 1,
    sub: model => model - 1
  },
  view: (model, actions) =>
    <div>
      <h1>{model}</h1>
      <button onclick={actions.add}>Increment</button>
      <button onclick={actions.sub}>Decrement</button>
    </div>
})
```

You'd need to do it like this:

```jsx
app({
  model: 0,
  view: (model, actions) =>
    <div>
      <h1>{model}</h1>
      <button onclick={_ => actions.setState(model + 1)}>Increment</button>
      <button onclick={_ => actions.setState(model - 1)}>Decrement</button>
    </div>
})
```

Which is **less** code, but it's also worse code, because you have now coupled the view with the implementation of the action, which among other abominable things, makes it more difficult to create reusable components, and mocks the entire model+view+actions architecture.

Sure, you could also do this:

```jsx
app({
  model: 0,
  actions: {
    add: (model, _, actions) => actions.setState(model + 1),
    add: (model, _, actions) => actions.setState(model - 1)
  },
  view: (model, actions) =>
    <div>
      <h1>{model}</h1>
      <button onclick={actions.add}>Increment</button>
      <button onclick={actions.sub}>Decrement</button>
    </div>
})
```

But now that's **more** code and more boilerplate.

**Comment by dodekeract** [comment]
@jbucaran Yes, I see the boilerplate issue. Part of it gets solved by using `set` instead of `setState` (we don't use the word state anyway, only chose it since react used that) and maybe changing how actions are called.

**Comment by jbucaran** [comment]
@dodekeract I think we can all agree that the name is not the real issue here. If we are offering TEA out of the box (and we **are**), incorporating this default `set` action would be a major sin in the Elm doctrine.

**Comment by dodekeract** [comment]
@jbucaran I think that's just about semantics. The only thing that changes is that `return` is now `set()`.

**Comment by jbucaran** [comment]
> @dodekeract I think that's just about semantics. The only thing that changes is that return is now set().

No, it's not. It changes the model. Like I said above, I don't want to mix the implementation of an action with the view code. That's basically how React works without Redux.

The way I think about actions is that they are all "sync", so their ultimate goal is to update the model, one way or another.

Now, if only that would be good enough. If a lot of your code is doing async stuff, so how do you use actions to do async stuff? Return a Promise! Which makes sense. 

Now, if only that would be good enough. [Not everyone can return a Promise](http://caniuse.com/#search=promise). So, we let you return nothing which is familiar to callback hell adventurers.

I thought this was enough, but it seems you've found an "edge" case (correct me if I'm wrong). Which is, you want sync actions that return some value which could be part of some work you may be doing inside one of these async actions.

My solution would be to simply use functions.

**Comment by dodekeract** [comment]
@jbucaran

> I don't want to mix the implementation of an action with the view code

That only happens if users decide to do it. If I'd implement `setState` myself it'd be possible with the current codebase as well. Nothing unique to my suggestion.

**Comment by jbucaran** [comment]
> @dodekeract Right now an async action can't return a new state update:

```jsx
  app(
    actions: [
      (model, data, actions) => {
        setTimeout(() => {
          // won't work
          return { n: "ewState" }
        })
      }
    ]
  )
```

> It is forced to use a reducer. Having setState or whateverYouWantToCallIt would make this just the same as the usual model update.

It's pretty evident this won't work the way you expected given our current, and still primitive, understanding of the laws of physics. 

Inside setTimeout, you usually want to do call another action that updates the bit of the model that you care about.

**Comment by jbucaran** [comment]
> If I'd implement setState myself it'd be possible with the current codebase as well. Nothing unique to my suggestion.

Yes, but you'd have to implement it first, out of the box, HyperApp won't let you shoot yourself in the foot 😄.

**Comment by dodekeract** [comment]
@jbucaran The point of that example is that there are currently two ways to update the model. Either use `return` or add a `reducer`. `return` won't always work.

**Comment by jbucaran** [comment]
@dodekeract AFIK `return` always work. If you need to update the model, just return something!
 
```jsx
actions: {
  love: model => ❤️
}
```

It works.

**Comment by dodekeract** [comment]
@jbucaran You just quoted the example where it wouldn't work.

**Comment by jbucaran** [comment]
Which is obvious, because you are inside a callback. Sorry, are you suggesting that the behavior of callbacks in JavaScript is confusing or something like that?

```jsx
actions: {
  writeToDb: (model, data, actions) => {
    myDB.write(data, ok => ok ? actions.happyReducer() : actions.sadReducer())
  }
}
```

**Comment by dodekeract** [comment]
@jbucaran Of course it's obvious. I always try to pick obvious examples. Still doesn't change the fact that there are currently **two ways to update the model**.

1. `return`
2. `reducer => return`

**Comment by jbucaran** [comment]
Sorry, I don't understand. There is only one way to update the model.

```
actions: {
   updateTheModel: _ => newModel
}
```
