### ISSUE TITLE
Add linting script

### ISSUE THREAD

**Issue by tiaanduplessis** [hyperapp/hyperapp#166]
Awesome project! How would you feel about adding linting? Maybe as a `pretest` script.  The code already conforms pretty well to [standard style](https://github.com/feross/standard).  Will be happy to make the PR.

**Comment by jbucaran** [comment]
Hi @tiaanduplessis! Sorry for the lack of response. How would the project benefit from using a linter?

Also, the code does not conform to standard since I use `"` and not `'`.

**Comment by selfup** [comment]
@jbucaran it would help contributors know that their code is good to go before submitting a PR in terms of style, and also linters let people know if the variable they are referencing exists or not.

It's kind of like mild static typing in a way 😂

**Comment by tiaanduplessis** [comment]
@selfup summarized it perfectly 😄

**Comment by tiaanduplessis** [comment]
@jbucaran the [standard](https://github.com/feross/eslint-config-standard) config can also be extended and customized to suit your preference 👍

**Comment by jbucaran** [comment]
@tiaanduplessis @selfup Now that prettier supports semi: false out of the box, I've started using it. I'm using the vscode extension that formats my code on save.

Perhaps we could add a note on the wiki or add a CONTRIBUTIONS file with this info among other?

**Comment by selfup** [comment]
@jbucaran So glad you like the auto format. I love it too haha ❤️ 

yea we should add a CONTRIBUTIONS file 👍

**Comment by jbucaran** [comment]
> @dodekeract Does prettier support editorconfig?

No idea, but it would be _pretty_ good!

**Comment by jbucaran** [comment]
@tiaanduplessis We're using https://github.com/prettier/prettier now, are you familiar with it?

If you can still work on that PR that would be lovely! 🙏
