### ISSUE TITLE
Using the object's hashcode avoid duplication of rendering

### ISSUE THREAD

**Issue by crixusshen** [hyperapp/hyperapp#167]
```js
var previousModelJSONStr = JSON.stringify(model)
model = merge(model, result)
var nowModelJSONStr = JSON.stringify(model)
if (hashCode(previousModelJSONStr) !== hashCode(nowModelJSONStr)) {
    render(model, view, name)
}
```

@jbucaran 
For the model, If the each change is same, render function will be repeated calls, although the virtual dom very fast, but it will waste performance, whether it is feasible to do so?

**Comment by jbucaran** [comment]
@crixusshen Nice. The real question is, which one is is faster: `JSON.stringify` or `render(model)`?

😄

**Comment by jbucaran** [comment]
@dodekeract What do you think?

**Comment by dodekeract** [comment]
@jbucaran I have 3 issues with this:

1. `JSON.stringify` is not guaranteed to be deterministic. If it is, that's an implementation detail - not a standard.
2. To "not update" we should just look if the action returned a model change. If it did it's reasonable to assume that the model is actually different.
3. `JSON.stringify` isn't able to stringify everything. For example `Map`s, `Set`s, etc.. I think that's makes it the wrong tool for the job.

So all in all I'd just suggest to look at what the action returns to determine if a render should happen.

**Comment by crixusshen** [comment]
@jbucaran Now the route module, if the browser is frequent forward and backward, will appear such problems, but the model did not change.In the immutable.js,the principle of ` immutable. Is() ` and hashcode are similar, have optimized space? （My English level is very poor, please understand ^_^）

**Comment by jbucaran** [comment]
@dodekeract There's also circular reference errors. 🤔

**Comment by leeoniya** [comment]
`JSON.stringify` will crawl. you're better off delegating to userland sCU or an immutable data store (and auto-sCU). i personally like https://github.com/arqex/freezer

**Comment by jbucaran** [comment]
@crixusshen To optimize the render pipeline, we should look into requestAnimationFrame first.

How often an action that _is_ supposed to update the model doesn't actually update anything?

**Comment by dodekeract** [comment]
@jbucaran If you introduce `requestAnimationFrame` I desperately need a way to hook into the next update. I currently have to measure dimensions of an element in my code that may change its size when the model gets updated.

**Comment by jbucaran** [comment]
@dodekeract Nothing yet, so no worries.

**Comment by jbucaran** [comment]
Don't think I am going to use JSON.stringify in the near future so closing. Thanks @crixusshen 👋.
