### ISSUE TITLE
Can you use the Class to define the Action layer ？

### ISSUE THREAD

**Issue by crixusshen** [hyperapp/hyperapp#169]
Because the methods of Class is non-enumerable, the execution of a code fragment cannot be assigned:

function init(container, group, lastName) {
    Object.keys(group).forEach(function (key) {

`Object.keys(group)`cannot enumerabled. Do you have any good solution using the Class?

**Comment by jbucaran** [comment]
@crixusshen Sorry, I don't understand what you are asking.

**Comment by crixusshen** [comment]
Is it possible to use es6 Class to define the action？

**Comment by dodekeract** [comment]
@crixusshen We don't use classes, so I suppose it isn't possible. I have no idea what you're trying to accomplish though.

**Comment by jbucaran** [comment]
@crixusshen Okay, I got it now :)

The answer is no, you can't use a class.

In hyperapp, [`actions`](https://github.com/hyperapp/hyperapp/wiki/Application#actions) is a just JavaScript object. The key is the name of the action and the action is a function. 

**Related**:
* http://stackoverflow.com/questions/31054910/get-functions-methods-of-a-class

**Comment by jbucaran** [comment]
@crixusshen Out of curiosity, what were you trying to do / why were you trying to use a Class?

**Comment by crixusshen** [comment]
@jbucaran  Want to make the code more standardized, and use some new grammar features

**Comment by jbucaran** [comment]
@crixusshen Cool, thanks. You might be able to create a class that wraps an entire hyperapp application.

**Comment by crixusshen** [comment]
@jbucaran  Thanks your suggestion！I think about it. I'm going to use some annotations to increase scalability
