### ISSUE TITLE
Rename model to state.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#173]
Please 👍 or 👎.

**Comment by nichoth** [comment]
Those terms make no difference to me, so no need to change it.

**Comment by selfup** [comment]
Since we changed updates to actions, following the redux/Vuex semantics would be nice. Renaming to state makes sense 👍

**Comment by arturi** [comment]
Model is something from MVC frameworks to me, and I still get confused for a second when I stumble upon it in Hyperapp. Choo, yo-yo, React/Preact all call it state, so I’m in favor of renaming for consistency.

**Comment by dodekeract** [comment]
@jbucaran I'm in favor of `state` since a friend of mine was confused about the difference between `model` and `state` and this terminology is one of the things he considers confusing about hyperapp.

Of course that's https://yourlogicalfallacyis.com/anecdotal, but I don't care.

**Comment by jbucaran** [comment]
I don't mind either, and the reason I chose model was TEA, but I also agree with some people finding model confusing since the most widespread term is state anyway.

**Comment by jbucaran** [comment]
Hi @SkaterDad @nichoth @cdeutmeyer!

If you have a second to spare, can you explain why you dislike / disapprove this notion?

**Comment by leeoniya** [comment]
i upvoted `state`, but if you intend to stay close to TEA, then it may be worth using its terminology [1].

[1] https://guide.elm-lang.org/architecture/

**Comment by jbucaran** [comment]
@leeoniya You're right, but TEA also has the word update which we don't use anymore

@dodekeract Does your friend find hyperapp confusing just because of the world model? Seems an extreme position to take just because of a word. Just curious.

**Comment by dodekeract** [comment]
@jbucaran No, mainly because of the differences to react/redux. He's currently trying to learn how to create SPAs and react/redux is the stuff he's currently attempting to learn.

**Comment by jbucaran** [comment]
Gotcha. Good choice anyway. Reminds me of [this](https://twitter.com/jbucaran/status/841890540153131008).

**Comment by cdeutmeyer** [comment]
I'm really fine with it either way.. I just like sticking as close as possible to Elm terminology.

**Comment by danigb** [comment]
In my mind "model" is more related to MVC and other OOP paradigms, and state are more connected to functional programming (where state management is made explicit instead of implicit). Mixed with the previous departure from the Elm architecture nomenclature, I'd go with "state".

**Comment by leeoniya** [comment]
my reasoning was same as @danigb

**Comment by dodekeract** [comment]
@jbucaran The community is mostly in favor of this change. Can we implement it?

Also something somewhat related: when we link to code pens we should **make sure they don't use hyperapp@latest** since hyperapp is currently not stable enough for that. We should always link to **hyperapp@0.8.x** or similar.

**Comment by jbucaran** [comment]
@dodekeract You are right, but latest refers to the published npm version, which is working fine AFIK.

**Comment by jbucaran** [comment]
> Can we implement it?

Yes, let's do so after #172 is merged please.

**Comment by dodekeract** [comment]
@jbucaran Yes, it's working fine. **right now**. This leads to **all hyperapp codepens** breaking as soon as we publish breaking changes.

**Comment by jbucaran** [comment]
@dodekeract Fortunately, CodePens URLs don't change, so I just need to update the code. JSFiddle URLs do change, so I'll have to rewire everything or ditching JSFiddle.

**Comment by dodekeract** [comment]
@jbucaran You don't see the problem. People **fork** our examples. This means they inherit this time bomb that destroys their code pens as soon as we introduce another breaking change.

**Comment by jbucaran** [comment]
@dodekeract Ah, you're right... 😥

**Comment by selfup** [comment]
If the codepens use specific versions (as they should) then everything will be fine 😄

**Comment by AG-Systems** [comment]
Why not just offer both versions?

**Comment by jbucaran** [comment]
@AG-Systems Do you mean both model and state? 

I guess we could, but the idea is to come up with a clear API that is easy to teach and learn, also that would waste some bytes for no good reason.

Check out #177, we're renaming model to state in 0.8.0.

**Comment by AG-Systems** [comment]
Yes @jbucaran 
Oh okay sweet
