### ISSUE TITLE
Performance facility

### ISSUE THREAD

**Issue by ngryman** [hyperapp/hyperapp#182]
Hey,

I just released a tiny library where I really focused on perf and optimizations: https://github.com/ngryman/tree-crawl.

I was thinking about bringing some stuff I've learned on the way here. I think we could add some benchmark, profiling and tracing to the repo.

Multiple goals:
- Keep track of performance evolution.
- Isolate chunks of code that are potentially slow and optimize them.
- Make the code optimizer friendly (monomorphic, avoid deopts and bailouts).

@jbucaran I would gladly focus on this part if you are interested :)

PS: My first optimization would probably focus on the stack used in `h`. Basically implementing a really basic stack and avoiding `pop` as much as possible gave a nice `+15%` boost in my library.

**Comment by jbucaran** [comment]
@ngryman **Yes**, please!

**Comment by jbucaran** [comment]
> @ngryman  Basically implementing a really basic stack and avoiding pop as much as possible gave a nice +15% boost in my library.

`h` and `patch` are the bottlenecks, whatever improvements on `h` will have a huge impact on hyperapp! 👍

**Comment by ngryman** [comment]
@jbucaran Is the `string`/`number` concatenation feature of `h` mandatory?
Correct me if I'm wrong, but except if you are using `h` directly (which is unlikely), you don't need such a facility. The perf/memory impact of this feature is huge compared to the usage IMHO.

**Comment by jbucaran** [comment]
> Is the string/number concatenation feature of h mandatory?

It doesn't have to be mandatory? 🤔

**Comment by jbucaran** [comment]
@ngryman Closing in favor of your other issue #183.
