### ISSUE TITLE
Don't process nested children

### ISSUE THREAD

**Issue by ngryman** [hyperapp/hyperapp#185]
Let's continue on this topic here.

So, from what I see in `hyperxify` [examples](https://github.com/substack/hyperxify/blob/master/example/vdom.js), they are using [virtual-dom](https://github.com/Matt-Esch/virtual-dom). `virtual-dom` does not seem to handle nested children: https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/index.js.

My guess is that those nested children are only text nodes, but when a real node is met, a `h` call is made. Given the fact that `virtual-dom` does not handle this, I'm pretty confident we could get rid of this.

@jbucaran How could we validate that it's not mandatory?

**Comment by jbucaran** [comment]
> @ngryman How could we validate that it's not mandatory?

You mean other than changing the code and run a few hyperx examples and see if everything still works?

**Comment by jbucaran** [comment]
Hyperx generates nested children which are arrays and sometimes may contain further nested arrays, it's why h is a mess.

**Comment by ngryman** [comment]
@jbucaran Ok, do you have an example of this code? Thanks!

**Comment by ngryman** [comment]
Linking the potential implementation: https://github.com/hyperapp/hyperapp/issues/183#issuecomment-294284671

**Comment by ngryman** [comment]
Ok, I've generated an output from `hyperxify` taking their example.
From what I see we don't have to manage nested children.

```js
function render(state) {
  return html`<div>
    <h1>clicked ${state.times} times</h1>
    <button onclick=${onclick}>click me!</button>
  </div>`
}
```

```js
function render(state) {
  return h("div", {}, [
    "\n",
    h("h1", {}, [
      "clicked ",
      state.times,
      " times"
    ]),
    "\n",
    h("button", { "onclick": onclick }, [
      "click me!"
    ]),
    "\n"
  ])
}
```

**Comment by ngryman** [comment]
Next potential implementation:
```js
```

**Comment by jbucaran** [comment]
@ngryman That didn't pass the tests.

**Comment by jbucaran** [comment]
Closing in favor of your other issue #183. 

> Ok, I've generated an output from hyperxify taking their example.
> From what I see we don't have to manage nested children.

Try with this:

```js
html`
  <div class="someClass">
    <ul>
      ${[1, 2, 3, 4].map(i => html`
      <li>
        ${i}:
        <ul>${[9, 8, 7, 6].map(i => html`
          <li>
            ${i}
          </li>`)}
        </ul>
      </li>
      `)}
    </ul>
  </div>`
```

**Comment by ngryman** [comment]
Ok 😞

For info here is the output:
```js
function render(state) {
  return h("div", {}, [
    "\n",
    h("ul", {}, [
      "\n", 
      [1, 2, 3, 4].map(i => h("li", {}, [
        "\n",
        i,
        ":\n",
        h("ul", {} , [
          [9, 8, 7, 6].map(i => h("li", {}, [
            "\n", i, "\n"]
          )),
          "\n"
        ]),
        "\n"]
      ))
      ,"\n"]
    ),
    "\n"
  ])
```

**Comment by jbucaran** [comment]
To be clear, so that future onlookers don't misunderstand: hyperx is creating an array inside an array, that is, a doubly nested array, so it's not possible to process the tree without a recursive algorithm or an intermediary stack (approach currently chosen by hyperapp).
