### ISSUE TITLE
Make emit an action instead of a wandering function.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#192]
Instead of passing the emit function as the last argument to actions and events, why not provide emit as an action in the `actions` object?

```js
actions.emit("myCustomEvent", { data: 1 })
actions.emit("error", "Boom")
// etc
```

**Comment by jbucaran** [comment]
Ah, not possible because emit can return data, which would make it a reducer-like action. 

@dodekeract 😅

**Comment by dodekeract** [comment]
@jbucaran Sooooo, will we reconsider #162?

**Comment by jbucaran** [comment]
@dodekeract Yeah, not impossible, just inconvenient.

I want to think of actions.emit VS (state, actions, data, **emit**) as a tradeoff. 

An effect, `actions.emit` is maybe cleaner (I felt that way when I opened the issue), but not perfect either. The emit function still needs to be documented. Ideally, I wish we didn't need `emit` at all. But then how to do custom events? 

I'll argue that in general, using `emit` is rather rare, unless you are a building a plugin.
