### ISSUE TITLE
Rename plugins to mixins.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#194]
What the title says.

Ref: https://github.com/hyperapp/hyperapp/issues/189

**Comment by jamen** [comment]
@jbucaran Not sure if this is a relevant place to discuss, but...  Is there any value in adding support for plugins/mixins that are just objects:

```js
app({
  plugins: [ { ...partialApp } ]
})
```

I think this is a better mechanism for plugins that don't want the app options, but rather just some localized options.  This is good if you have one plugin who depends on another, and you don't want the dependency's options to bleed through `app(opts)`.

So, they could be designed something like this:

```js
app({
  plugins: [ plugin(opts) ]
})
```

Or using it inside another plugin,

```js
Object.assign({
  state: { foo: 123 },
  // ... other plugin stuff
}, depPlugin(opts))

**Comment by jamen** [comment]
Actually, thinking over what I posted there.  I don't like how it introduces some more complexity into the API...  What I describe is technically already possible, with a little bit of extra work.   E.g.:

```js
var bar = opts => app => Object.assign({
  state: { ... },
  // others
}, foo(opts)(app))
```
