### ISSUE TITLE
commit workflow

### ISSUE THREAD

**Issue by leeoniya** [hyperapp/hyperapp#196]
hey @jbucaran 

i'm watching hyperapp, but the very frequent force-push commits really pollute my feed and i am sure other watchers' feeds. it also doesnt help that each commit is the same generic commit message, so is not even interesting.

perhaps it makes sense to create a separate repo or delay pushing the commits until they are in a more-or-less final form? or maybe something else?

**Comment by leeoniya** [comment]
![capture2](https://cloud.githubusercontent.com/assets/43234/25442619/1ccc3446-2a6b-11e7-80b0-65042317cfcc.PNG)
![capture](https://cloud.githubusercontent.com/assets/43234/25442620/1ce12ea0-2a6b-11e7-90b0-0b0225e4740c.PNG)

**Comment by jbucaran** [comment]
@leeoniya This sucks. You pointed out "force-push", but is that relevant to the issue? I imagine it will show on your feed regardless of the type of commit it is.

Seems like GitHub could be more useful by collecting the commits under a collapsible list item.

Well, I wasn't really aware that this is how it looks as I don't watch many repos. 

> perhaps it makes sense to create a separate repo or delay pushing the commits until they are in a more-or-less final form? or maybe something else?

I'll try to do this.

**Comment by dodekeract** [comment]
@jbucaran You could just work on `hyperapp` the same way any other contributor does, by having a fork. This will also help you see issues that other contributors have because you'd do it the same way.

This would also allow people to subscribe to your changes by watching your "private" fork.

**Comment by leeoniya** [comment]
yeah, that seems like the way to go

**Comment by jbucaran** [comment]
@dodekeract Never occurred to me to do that. Great idea! 👍
