### ISSUE TITLE
Updating the state inside an element's oncreate event fails.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#218]
When the oncreate event is fired for an element, it gets passed a reference to the actual DOM element. At this point in time, the element has been created using `document.createElement` or `document.createTextNode`, but it's still not appended to the DOM (because we haven't had time to call patch yet!). 

When you call an action that updates the state, we'll try to render the app ahead of time, we'll have a new node, but not an old one, which will cause an exception.

See also: https://github.com/hyperapp/hyperapp/issues/208#issuecomment-304130612

**Comment by jbucaran** [comment]
@dodekeract Good news! We were able to fix this by introducing a new [`oninsert`](https://github.com/hyperapp/hyperapp/blob/master/docs/lifecycle-events.md#oninsert) lifecycle event.

> Fired after an element is created and inserted into the DOM. Use this event to wrap third party libraries that require a reference to a DOM node, etc.

**Comment by dodekeract** [comment]
@jbucaran Hmm, I still think it's very odd that hyper app crashes when I do something with the state in the `oncreate` hook.

**Comment by jbucaran** [comment]
@dodekeract I it won't even crash in `oncreate` after #286 since rendering is now effectively async.

**Comment by jbucaran** [comment]
@dodekeract Having said that, "for the record", you shouldn't probably be calling `actions` inside `oncreate`, that's not what it exists for.
