### ISSUE TITLE
Errors for input tags in template strings

### ISSUE THREAD

**Issue by zaceno** [hyperapp/hyperapp#22]
A simple demo: 

```
app({
  model:  'hello',
  view: model => html`<div><input type="text" value="anything"></div>`
})
```

... errors out with:

`TypeError: undefined is not an object (evaluating 't.data')`

See here [http://codepen.io/anon/pen/mRKJdZ](http://codepen.io/anon/pen/mRKJdZ)

It can be simplified even further: just a plain `<input>` with no attributes has same result. Also trying to close it various ways ( `<input />`, `<input></input>` ... ) makes no difference.

Looks like it happens in the hyperx part of the code. However, I'm not familiar enough with hyperx to debug it or know how to submit a bug report to them. Or perhaps I'm doing something fundamentally wrong?

**Comment by tzellman** [comment]
I added a check for valid/present sub-nodes in PR #23, but like you said, there is likely a bug in hyperx creating these undefined tree nodes.

**Comment by jbucaran** [comment]
@zaceno #17 was a regression. I just fixed it and pushed a working release. Thanks for reporting!

Let me know if you're good now so I can close this.

**Comment by jbucaran** [comment]
We'll be more careful in the 🙇 future!

**Comment by zaceno** [comment]
@jbucaran All good, you may close this issue. Kudos for the swift response!
