### ISSUE TITLE
Examples on Github ?

### ISSUE THREAD

**Issue by sylvainpolletvillard** [hyperapp/hyperapp#221]
I would like to make a pull request for a bug I found on [HyperApp TodoMVC example](https://hyperapp-todomvc.glitch.me/), but I did not find the examples on Github. Do you plan to add the examples to a repo so that we can PR / report bugs ? Thanks

**Comment by jbucaran** [comment]
@sylvainpolletvillard That's a valid point. We have a lot of examples on Glitch. I think the way to go is to port all of that, including TodoMVC and the examples landing page to a regular GitHub repo.

**Comment by jbucaran** [comment]
Glitch has a nice gem that allows you to export a project to GitHub! 👋😄 

<img width="867" alt="screen shot 2017-07-03 at 5 40 35" src="https://user-images.githubusercontent.com/56996/27773330-3f7fe8e4-5fb2-11e7-9bd1-4e3ba38eaf57.png">

**Comment by sylvainpolletvillard** [comment]
So how do I report the bug ? It's a trivial one on TodoList : the way item ids are handled (list.length) causes id conflicts. Reproduce: add items A and B. Remove A. Add C. Try to remove B. C is also deleted because B and C have the same id.

**Comment by jbucaran** [comment]
@sylvainpolletvillard Ah, I see. Sorry, my mind was somewhere else.

Can you send me a PR [here](https://github.com/jbucaran/todomvc)?
