### ISSUE TITLE
HyperApp vs Mithril

### ISSUE THREAD

**Issue by calvin-evans** [hyperapp/hyperapp#225]
Can someone explain the difference/advantage using this vs Mithril? They look super similar.

**Comment by jbucaran** [comment]
@calvin-evans Both have a built-in Virtual DOM, but other than that HyperApp and Mithril are very different.

Mithril has something called auto-redrawing, that IIRC re-renders the application after calling DOM events. But other than this, there's no default state management architecture. This trait may is desirable if you prefer to experiment with different architectures. I don't know about specific Mithril state managers, but it's like in React you can use setState, Redux, Mobx, etc. 

_HyperApp does not have this flexibility. HyperApp's state management architecture is inspired and heavily draws from the Elm Architecture. So, it's "kinda" like React and Redux. There's no other state management style available/possible._

Mithril has stateful components, which is a simple and useful way to reuse code across your app and easily port to other apps.

_HyperApp components are called "custom tags" and are **stateless** instead. That means they are pure functions that only accept props and know how to render themselves._

Mithril is also bundled with `m.request`, which simplifies making HTTP requests. 

_HyperApp has no built-in facilities to help you make HTTP requests._ I like to use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) with a polyfill if I am targeting an old browser._

**Comment by calvin-evans** [comment]
Thanks for the through writeup - will give it a whirl :)

**Comment by jbucaran** [comment]
Closing! 👋

**Comment by cjh9** [comment]
@JorgeBucaran Also Mithril includes a router by default.. Maybe this should be added to hyperapp if we want to be "Batteries included"?

**Comment by JorgeBucaran** [comment]
@cjh9 Actually, hyperapp's router used to be built-in, but then we concluded that it wasn't a good idea, because not everyone uses routing / navigation on their application, and because it's an anti-pattern to bundle a library into core that could very well stand on its own. For example, if we include the router, then why not include `hyperapp/html` too? 

Another reason to not include it, is to have the freedom to work on a more robust routing solution than the tiny one we'd need to implement because of the size requirement.

**Comment by okwolf** [comment]
> @JorgeBucaran Mithril has stateful components, which are a **simple** and useful way to reuse code across your app and easily port to other apps.

Where simple === easy, unlike in [Clojure](https://youtu.be/rI8tNMsozo0)land... 🙃

**Comment by cjh9** [comment]
@JorgeBucaran After thinking about it, you are absolutely right. I take my proposal back :)

**Comment by JorgeBucaran** [comment]
@cjh9 Great! Glad we understand each other.
