### ISSUE TITLE
Maybe it's good to thanks `Picodom` while `picodom` uses MIT License

### ISSUE THREAD

**Issue by whatwewant** [hyperapp/hyperapp#227]
https://github.com/picodom/picodom/blob/master/patch.js

**Comment by whatwewant** [comment]
https://github.com/picodom/picodom/blob/master/patch.js

**Comment by jbucaran** [comment]
Hi, @whatwewant. Picodom's h and patch functions are derived from HyperApp's h and patch functions in the first place. 👋
