### ISSUE TITLE
Router's replace action

### ISSUE THREAD

**Issue by cloudever** [hyperapp/hyperapp#228]
Is it possible add a `replace` action to the router? It seems to be a good practice to use it just like in the `react-router` for example.

**Comment by lukejacksonn** [comment]
What is the `replace` action going to do exactly? I presume it is going to employ `history.replaceState` instead of `history.pushState` would that be it?

**Comment by rileytg** [comment]
i've used replace in cases where i want to redirect from /myModule -> /myModule/section1 akin to 301

**Comment by jbucaran** [comment]
@cloudever @rileytg Let's move this discussion to https://github.com/hyperapp/router. 👋
