### ISSUE TITLE
Using Bootstrap or Design Material with HyperApp 🎨

### ISSUE THREAD

**Issue by vikaskyadav** [hyperapp/hyperapp#24]
can we bring responsiveness using material design concept or bootstrap in hyperapp. It would be an awesome combo.

**Comment by dodekeract** [comment]
How is this even remotely fitting the scope of hyperapp?

**Comment by vikaskyadav** [comment]
You have mentioned the word "UI applications" . You are telling "modern applications" and not even considering Elements of UI design!

**Comment by selfup** [comment]
`UI` here means how to construct and manage state for a UI. The Design aspects are up to the developer to sprinkle in. Hopefully that makes sense 😄 

Vue/React/Inferno/Elm/etc.. are ways of constructing a modern UI (trigger an event on the DOM, state changes, dom updates).

**Architecture vs. Design**

From the React website:

```text
React
A JAVASCRIPT LIBRARY FOR BUILDING USER INTERFACES
```

**Comment by jbucaran** [comment]
> @vikaskyadav can we use material design or bootstrap with hyperapp?

Sure! You should be able to use any CC framework you like with HyperApp. Here is a trivial [example](http://codepen.io/jbucaran/pen/jyKywv?editors=0010) with Bootstrap.

Let me know if this answers what you were asking.

**Comment by vikaskyadav** [comment]
@selfup . Yeah, I misinterpeted UI for designing framework. Understood ! Thanks. :)
@jbucaran Thanks man. That sums up the utility of hyperapp. Awesome job people ! :)

**Comment by jbucaran** [comment]
@vikaskyadav Thanks for the kind words :)

Think we can close here?
