### ISSUE TITLE
Integrated size and perf tests 

### ISSUE THREAD

**Issue by lukejacksonn** [hyperapp/hyperapp#240]
Is worth adding some npm scripts that would allow you as a developer to see if changes made had any impact on:

- Bundle size (after being minified and gzipped)
- Performance (measured by js-framework-benchmark or similar)

Is this even possible, I've never tried automating benchmarking?

**Comment by jbucaran** [comment]
That's what @ngryman is trying to do with https://github.com/hyperapp/hyperapp/pull/186.

@ngryman Also had a PR to add a bundle size badge to the README, but having a script tell you that would be better.

Something like:
```
npm run build && zopfli --i3000 dist/hyperapp.js > dist/hyperapp.js.gz && stat -f%z dist/hyperapp.js.gz
```

**Comment by lukejacksonn** [comment]
Nice! A combo of those two could work great.. I will try them out

**Comment by PaulBGD** [comment]
I'm a contributor to Svelte and for it I wrote a very basic system to use selenium to run the tests on a PR + previous versions. Feel free to adapt it: https://github.com/PaulBGD/svelte-bench/tree/selenium

**Comment by jamen** [comment]
I found this module [`bundlesize`](https://github.com/siddharthkp/bundlesize) that just makes it easier to specify a threshold and deploy on Travis CI.  Might be worth looking into.  :smile:

**Comment by lukejacksonn** [comment]
Looks tidy! Would you say this more useful than a CLI tool that can be used to check size locally before pushing up? I can see advantages and disadvantages of both 🤔

**Comment by Swizz** [comment]
[`bundlesize`](https://github.com/siddharthkp/bundlesize) looks awesome, and Hyperapp seem to be the typical use case for that !

**Comment by jbucaran** [comment]
So, I went ahead and added bundlesize to package.json. 😎 

As for benchmarks, well, there's ngryman's https://github.com/hyperapp/hyperapp/pull/186. I don't think it is feasible (or even a good idea to try to integrate) js-framework-benchmark benchmarks, but I am open to other suggestions.

@lukejacksonn I'd prefer to close here in favor of #186, but feel free to keep it open if you want to add something else.

**Comment by lukejacksonn** [comment]
@jbucaran now that size is being monitored by bundlesize (nice find @jamen!) then all that remains is some perf testing so 🏓 https://github.com/hyperapp/hyperapp/pull/186

I tested @ngryman's PR the other day and it works.. not half as pretty and perhaps insightful as if we got it wired up to https://github.com/ngryman/speedracer 😏

**Comment by mindplay-dk** [comment]
Speedracer looks neat :-)
