### ISSUE TITLE
hyperapp-hmr and hyperapp-webpack-hmr

### ISSUE THREAD

**Issue by andyrj** [hyperapp/hyperapp#246]
Opening this as mentioned from Slack to discuss the different HMR mixins that have emerged.

I want to explain why I created [hyperapp-webpack-hmr](https://github.com/andyrj/hyperapp-webpack-hmr) instead of using the existing [hyperapp-hmr mixin](https://github.com/jamen/hyperapp-hmr).

From what I could gather looking at hyperapp-hmr that plugin is still built around refreshing/reloading the page, which I have always called hot-reload/live-reload where as hot module replacement doesn't require a refresh/reload of the page.

I didn't see a way to simply integrate with the hyperapp-hmr functionality primarily due to that and I thought it was better to have a very simple mixin to save the state to a global, instead of bringing in the functionality of the hyperapp-persist mixin which uses localstorage.

I am happy to merge/move/transfer/change as long as the functionality can remain the same for saving state to a global instead of localstorage.

EDIT: clarifying

I re-read my above and it sounds bad, I was trying to learn the mixin system with something simple and the hyperapp-hmr pulling in the functionality of the hyperapp-persist mixin was a bit confusing for me.  I am happy to open a PR to hyperapp-hmr with added options to save state to global, and thinking about it, it would be pretty cool to actually HMR from local-storage too... I will gladly merge/remove my repo etc.. heh, didn't mean to come over as negative or anything.  Tired is all ;)

**Comment by jamen** [comment]
> From what I could gather looking at hyperapp-hmr that plugin is still built around refreshing/reloading the page, which I have always called hot-reload/live-reload where as hot module replacement doesn't require a refresh/reload of the page.

I think we are on the same page: `hyperapp-hmr` does not do "live-reloading" for you out of the box.  That is, it will not reload the page when you save your files.

I touched on this in [the readme of `hyperapp-hmr`](https://github.com/jamen/hyperapp-hmr#what-about-live-reloading) I can paste again here for reference:

> Live-reloading is not provided out of the box in `hyperapp-hmr` because:
> 
>  - There are standalone auto-reload servers you can opt-in to using with this package with no problems. For example, see [`budo`](https://npmjs.com/budo) for a prototyping tool that lets you live-reload _super easy_.
>  - There may be people who are uninterested in what it takes to setup auto-reloading, and don't mind just hitting F5 with the same HMR benefits.
>  - [Otherwise] It would significantly increase the complexity of the package, as there would need to be a server-side so we could detect file changes, and communicate that to client-side for reloading, etc. which makes it less appealing to some.

But, I definitely think your package is a better solution for webpack, and it still relatively simple.  It would be awesome if you could introduce something similar  

> I was trying to learn the mixin system with something simple and the hyperapp-hmr pulling in the functionality of the hyperapp-persist mixin was a bit confusing for me.

Let me know if I can help understand.  In a nutshell:

 - You have `state.previous` which is the `state` of the previous session.
 - When the session ends, `state` is saved to `persist({ storage })` on local storage
 - When next session starts, the stored state is loaded as `state.previous`, and the cycle continues.

There is also `state.version`, used when the stored state is no longer compatible with the current state (mismatching keys or types).  By default, it just tosses it, but you can rescue it if you need to support users.

**Comment by andyrj** [comment]
The more I look and think about this the more I feel these should be separate mixins...  The fact that hyperapp-hmr was designed for persisting through refresh is a big difference from my implementation that persists on each render since we have no way to predict when hmr may occur.

I would like to get others input on this though.

**Comment by andyrj** [comment]
closing in favor of #249
