### ISSUE TITLE
Small issue with the doc

### ISSUE THREAD

**Issue by mauron85** [hyperapp/hyperapp#248]
On page
https://github.com/hyperapp/hyperapp/blob/master/docs/core.md#view-and-state

last example is missing `actions` view param

```
const Counter = () => ({
  mixins: [Logger],
  state: {
    count: 0
  },
  actions: {
    up: state => ({ count: state.count + 1 }),
    down: state => ({ count: state.count + 1 })
  }
})

app({
  mixins: [Counter],
  view: (state, actions /* this is missing*/) =>
    <div class="counter">
      <button onclick={actions.up}>+</button>
      <span>{state.count}</span>
      <button onclick={actions.down}>-</button>
    </div>
})
```

**Comment by naugtur** [comment]
disclaimer: I'm not a contributor to this repo, just butting in.

You can click the little pencil on github on the file, fix it and 3 clicks later you have a pull request. It's even less work than posting this.

Even if you don't want to - it's nice that you reported it!

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp/commit/6e542556837ee8a157b3cf59d4d3b89af4be50d6

I've decided to remove the example because as #238 is implemented, the Mixins API may change and mixin composition is already a bit of an obscure feature.
