### ISSUE TITLE
[question] using real dom nodes

### ISSUE THREAD

**Issue by yoshuawuyts** [hyperapp/hyperapp#25]
heya, cool lib!

Got a question: have you considered using real dom nodes rather than virtual ones for this lib? Something we've got going with `choo` is that anything that produces real dom nodes will work natively - e.g. charts, forms, all the stuff.

Figured it might be cool if `hyperapp` instances could interop with `choo` and the other way around - making it easy to mount inside each other and like reuse packages and stuff. I think especially with [nanomorph](https://github.com/yoshuawuyts/nanomorph) slowly stabilizing this might become exciting.

Was mostly wondering about your reasoning - thanks! :sparkles:

#### see also
- https://github.com/hyperhype/hyperscript
- https://github.com/shama/bel
- https://github.com/shama/yo-yoify
- https://github.com/patrick-steele-idem/morphdom
- https://github.com/yoshuawuyts/nanomorph
- https://github.com/yoshuawuyts/nanocomponent
- https://github.com/yoshuawuyts/nanocomponent-adapters

**Comment by jbucaran** [comment]
Hey @yoshuawuyts! Thanks for stopping by.

Here's the issue that touched on HyperApp [design goals](https://github.com/hyperapp/hyperapp/issues/9#issuecomment-276879292). 

> Was mostly wondering about your reasoning?

We've had an exchange on Twitter about this at some point. Essentially, poor integration with 3rd party components like CodeMirror or Ace9.

For the record, HyperApp's first prototype used morphodom.

**Comment by jbucaran** [comment]
Going to close here as using a vdom is key concept in HyperApp.
