### ISSUE TITLE
Async Routing

### ISSUE THREAD

**Issue by andyrj** [hyperapp/hyperapp#250]
I know that the bundle size is a much better situation with hyperapp but I am still interested in the possibility of having an async routing solution, after reading #176 I thought I would open an issue to just hash out what I think would be an interesting implementation and whether it should be it's own fork of the current router or if I could piece together a PR to add it as a feature to the current router.

This may not go over well with many here since it is webpack specific, as far as I understand currently.  But the gist of it is kind of covered in [react-loadable](https://github.com/thejameskyle/react-loadable) and [webpack async code splitting](https://webpack.js.org/guides/code-splitting-async/#components/sidebar/sidebar.jsx) .  

My first stab at implementing this would be to fork the current router (or whatever repo it ends up in), and make the minimum necessary changes for it to accept a promise as a view, instead of expecting only a function.  Might also need a small helper function to do the bit react-loadable takes care of where it displays a loading indicator while the async route is downloaded and then rendered.

Do any of you have thoughts about async routing or concerns about the 20,000 foot outline above?  I think if I did it right it could be compatible with require.ensure() as well which would make it more webpack agnostic.

**Comment by lukejacksonn** [comment]
> I know that the bundle size is a much better situation with hyperapp but I am still interested in the possibility of having an async routing solution

It would be great to have an established pattern or implementation for async routes. There are a few other little bits we could add to the router but I'm not sure what @jbucaran thinks to adding more code. Abstracting the router to hyperapp/router would give us more freedom.

The more I think about routing in general the more I start to think a lot of this could be done with custom elements (_views_ that just accept props and children) and the router mixin just becomes a mechanism for maintaining/updating the state of the browsers address bar and the state.router object.

What is the router really doing to the view that couldn't be achieved with something like:

```
const page = (s) => (a) => (p,c) =>
  s.router.match === a.router.match(p.route) && h('page-', p, c)

view: (s,a) => h('app-', {}, [
  page({ route: '/' }, HomePage),
  page({ route: '*' }, LostPage),
])
```

A very basic example but that page component could be extended to do lots of other cool things.. like show a spinner view until some state exists, fetch data on create or redirect on bad data.

They are just my thoughts on client-side routing as a whole at the moment (you asked you got) kind of inspired by the trials, tribulations and most recent version of react-router and this [video I watched](https://www.youtube.com/watch?v=Vur2dAFZ4GE) which made me rethink.  

Would love to see how you plan on implementing async still!

**Comment by andyrj** [comment]
I was thinking some more about this and I don't know that I actually need to change anything on the Router mixin actually.  Obviously not 100% on this but generally I am thinking along these lines...

```js
import Router from 'hyperapp'
import Loading from './Loading'

const async = (state, actions, thunk, loader) => {
  // "pseudo code"
  // check state for thunk, if defined return that view
  if (state.router.async[location.pathname] !== undefined) {
    return state.router[location.pathname]
  } else { // otherwise return loader
    return loader
  }
}

app({
  state,
  view: [
    ['/', async(state, actions, () => import('./Home'), Loading)]
    ...
  ],
  mixin: [ Router ]
}
```

**Comment by jbucaran** [comment]
@andyrj Can we move this discussion to https://github.com/hyperapp/router/issues? 🙏
