### ISSUE TITLE
Reduce file size by 666 bytes

### ISSUE THREAD

**Issue by joshuahiggins** [hyperapp/hyperapp#252]
The final gzipped size of this library is 1666 bytes, or **166% of the advertised size!** 

It is rather suspicious that the true size of the plugin is exactly 666 bytes larger than the advertised size. Clearly there is something sinister happening here and it threatens the very fabric of the JavaScript community. 

This must be resolved immediately to ensure the safety of developers worldwide.

**Comment by Sntax** [comment]
This guy fucks.

**Comment by SomethingNew71** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjgl5qc5t7UAhUCzGMKHaArDSoQjRwIBw&url=http%3A%2F%2Fwww.reactiongifs.us%2Ftag%2Ftin-foil-hat%2F&psig=AFQjCNGDhDsVVk2ZrP3Gu_cwNQNqwJSglQ&ust=1498679468029953

**Comment by jbucaran** [comment]
![](https://user-images.githubusercontent.com/56996/27607011-71ef3a6c-5bbd-11e7-8331-aa4d8cef97b4.png)

I suspect it's the built-in Router :)

- #79 
- #176

**Comment by lukejacksonn** [comment]
This https://www.npmjs.com/package/hyperapp-router still exists 😉  removing it from core would shave a good 333KB off perhaps, half of the evil. I just updated the code, tests and README of that repo, and republished. It is now compatible with `hyperapp: ^0.9.3` and promotes the new syntax.

So whenever the time feels right ⛳️ 🏌🏼

**Comment by jbucaran** [comment]
Thanks @lukejacksonn!

Alright, sorry to end the fun, but closing! 👋
