### ISSUE TITLE
Using hyperapp without JSX?

### ISSUE THREAD

**Issue by mrozbarry** [hyperapp/hyperapp#254]
So far, I've only taken a cursory glance at hyperapp, so I don't know if this is already possible, has been road-mapped somewhere I haven't seen yet, or just isn't a good idea.

I'm not strictly against JSX, but I do occasionally use js-relatives like coffeescript where using functions can read significantly better.

I suspect this ends up being a larger question to the community, since I'm sure 99% of devs don't care about a no-JSX solution.

**Comment by Swizz** [comment]
Take a look at the [Getting Started Guide](https://github.com/hyperapp/hyperapp/blob/master/docs/getting-started.md), Hyperx or JSX are introduced a far later.

Hyperapp use vdom for view construction. JSX is only a syntactic sugar.

**Comment by jbucaran** [comment]
@mrozbarry Sure thing!


The examples in the docs use JSX for familiarity, but you are not required to use JSX with HyperApp :)

Here is one using [hyperx](https://github.com/substack/hyperx) and ES6 [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged-template-literals).

[Try it online](https://codepen.io/hyperapp/pen/XgJpgm?editors=0010)

```js
import { h, app } from "hyperapp"
import hyperx from "hyperx"

const html = hyperx(h)

app({
  state: "Hi.",
  view: state => html`<h1>${state}</h1>`
})
```

And here is the example again, this time without using external libraries. 

[Try it online](https://codepen.io/hyperapp/pen/PmjRov?editors=0010)

```js
import { h, app } from "hyperapp"

app({
  state: "Hi.",
  view: state => h("h1", null, state)
})
```

**Comment by mrozbarry** [comment]
I guess one comment on this, which I'm not sure if it's an issue for hyperapp vs hyperx, is it would be nice to use dom elements as functions.

For instance, in react, I can do:

```coffeescript
{ div } = React.DOM

# ...
myComponent = (props) ->
  div {}, "whatever"
```

I guess there's nothing stopping me from writing a script that does something like:

```coffeescript
{ h } = require("hyperapp")

HyperDOM = ["div", "span", "...more here"].map (tag) ->
  (attrs, children) ->
    h(tag, attrs, children)

# ...

{ div } = HyperDOM

app(
  state: null
  view: (state) -> div null, "whatever"
)
```

**Comment by jbucaran** [comment]
@mrozbarry That's pretty cool, but out of the scope of hyperapp's core library. 

Now, I'd be happy to allocate an official slot in the organization for third party utility package like this if someone wants to take upon the challenge.

**Comment by Swizz** [comment]
Here is [hyperscript-helpers](https://github.com/ohanhi/hyperscript-helpers)

```jsx
import { h, app } from "hyperapp"
import helpers from "hyperscript-helpers"

const { div, h1 } = helpers(h)

app({
  state: "Hi.",
  view: state => 
    div(null, [
      h1(null, state)
    ])
})
```

You are right, this is more Elm 😄

**Comment by mrozbarry** [comment]
ohanhi shows up in all the places I check out. It's like I'm stalking him and I didn't even know it!

**Comment by jbucaran** [comment]
@Swizz This is pretty cool. Maybe I should reconsider the scope comment I made.

Imagine:

```js
import { div, h1, ul, li, app } from "hyperapp"

app({
  state: ["Hi", "Hola", "Hallo"],
  view: state => 
    div([
      h1(state), 
      ul(state.map(greeting => li(greeting)))
    ])
})
```

**Comment by Swizz** [comment]
hyperscript-helpers is arround 945 bytes gziped 😕

**Comment by SkaterDad** [comment]
I just write my view code with `h()` calls most of the time.  Same with the code I write in `cycle.js`.

`hyperscript-helpers` is a really cool library.  I bet if you ran your code through something like `prepack`, the extra weight of it would get stripped out at compile time.

Certainly seems out of scope for `hyperapp`, though.  Best served by a user-land library, IMO, which basically already exists fortunately!

**Comment by jbucaran** [comment]
Okay, it seems this issue has been resolved.

**Comment by lukejacksonn** [comment]
> Imagine: `import { div, h1, ul, li, app } from "hyperapp"`

This is why I created the (experimental) [huy](https://github.com/lukejacksonn/huy) library.. primarily it was to cover the tags/functionality hyperapp doesn't support but that there are standard solutions for.. `use` and internal routing with `a[href='/']`.

Then I thought like you.. why not cover _all_ the standard elements! `hyperscript-helpers` looks to have done just that! I'm going to try it out but I already like the idea and would consider the idea of a repo separated from core but maintained by the community `hyperapp/dom` or something?

**Comment by jbucaran** [comment]
@lukejacksonn Don't know why, but I just has this thought that, for official packages, we could use scoped packages. 

```npm i @hyperapp/dom @hyperapp/hmr```

etc.

**Comment by lukejacksonn** [comment]
sounds good to me!
