### ISSUE TITLE
Animation or setState

### ISSUE THREAD

**Issue by jcubic** [hyperapp/hyperapp#270]
I want to morph one svg shape to the different one using [veltman/flubber](https://github.com/veltman/flubber)

I've tried to call action from another action and also returning a promise from action but both don't work. Here is my try (it should change one step of the animation):
```jsx
let morph = interpolate(warning, light_bulb);

app({
  state: {path: warning, step: 0.1, position: 0, animating: false},
  view: (state, actions) => (
    <div>
      <svg width="128" height="128" version="1.1">
        <path d={state.path}  style="fill:#000000"/>
      </svg>
      <button onclick={actions.animate}>morph</button>
      </div>
    ),
  actions: {
    next: state => {
      var pos = state.position+state.step;
      return {path: morph(pos), position: step};
    },
    animate: state => {
      return new Promise((resolve, reject) => {
        if ((state.step < 0 && state.position > 0) ||
            (state.step > 0 && state.position < 1)) {
          requestAnimationFrame(() => resolve(this.next()));
        }
      });
    }
  }
})
```
and when I've clicked on a button I've got error that `this` is not defined.

Here is a [codepen](https://codepen.io/jcubic/pen/VWXENp), 

Is there something like setState in hyperapp? Does it support animation? What I really need is to run something like this:

```javascript
  actions: {
    next: state => {
      var pos = state.position+state.step;
      return {path: morph(pos), position: step};
    },
    animate: state => {
        if ((state.step < 0 && state.position > 0) ||
            (state.step > 0 && state.position < 1)) {
          requestAnimationFrame(() => {
              setState(this.next()); // there is obviously on setState function
              this.animate(state); // this is undefined
          });
          return {animating: true};
        } else {
          return {animating: false};
       }
    }
  }
```

Is something like this possible?

**Comment by SkaterDad** [comment]
Using `this` goes against `hyperapp`'s reason-to-be, so you won't need to use it.

When I run your Codepen in Chrome I don't get any errors in the console.  Every time I click the button the morphing goes one step further along.

To access the actions within another action, simply pass it as the 2nd argument.

```js
actions: {
  animate: (state, actions) => { ... }
}
```

**Comment by SkaterDad** [comment]
Got it working, I think!  You don't need the Promise wrapping in your animate action, and if you call the `next()` action before checking if you're done animating, you can recursively call `animate()` until it completes.

https://codepen.io/anon/pen/awYQKw?editors=0010

```js
app({
  state: {path: warning, step: 0.05, position: 0, animating: false},
  view: (state, actions) => (
    <div>
      <svg width="128" height="128" version="1.1">
        <path d={state.path}  style="fill:#000000"/>
      </svg>
      <button onclick={actions.animate}>morph</button>
      </div>
    ),
  actions: {
    next: state => {
      var pos = state.position+state.step;
      return {path: morph(pos), position: pos};
    },
    animate: (state, actions) => {
        actions.next()
        if ((state.step < 0 && state.position > 0) ||
            (state.step > 0 && state.position < 1)) {
          console.log('I should animate')
          requestAnimationFrame(() => actions.animate());
        }
    }
  }
})
```

**Comment by jbucaran** [comment]
@jcubic There's no `this` in hyperapp. 😈😄 

But actions are passed the `actions` object so you can simply run:

```js
actions.animate()
```

inside `animate` as @SkaterDad suggested.

**Comment by jcubic** [comment]
Great, thanks, this is exactly what I need and thanks for this awesome framework/library.
