### ISSUE TITLE
Rename custom tags to Components

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#271]
This is a documentation change proposal.

After discussing the issue with @zaceno, I'd like to rename custom tags to stateless components or components for short.

**Comment by lukejacksonn** [comment]
They actually **are** stateless/functional components.. right?

At least by the common reference:

- https://facebook.github.io/react/docs/components-and-props.html
- http://vuejs.org/v2/guide/render-function.html#Functional-Components
- https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0
- https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc
- https://toddmotto.com/stateful-stateless-components
- https://github.com/vuejs/vue/issues/4037

They kind of also depict Custom Elements (but with _much_ nicer syntax)

- https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements

Perhaps what is most important here is that there is some clear hierarchy. If these sateless components are the leaf nodes, let's say we call them components, then what are we going to call the stateful components (if they materialise) and are stateless always children of stateful? Then maybe these are Elements and containers of elements are called Components.

I'm asking myself _why_ are we naming this thing, what is it meant to mean in the grand scheme of things.

**Comment by jbucaran** [comment]
> They actually are stateless/functional components.. right?

Yes, so basically we're doing the right thing now.

**Comment by lukejacksonn** [comment]
So long as there is sufficient emphasis on the fact that these are *stateless* or *functional* or *stateless functional* components then I'd say so. At least, it would be inline with the common definition of the _thing_.

In the react guide it says quite clearly 😂

> We call such components "functional" because they are _literally_ JavaScript functions.

**Comment by jbucaran** [comment]
SGTM

**Comment by SkaterDad** [comment]
+1 to calling them **functions** or **functional components**.

**Comment by zaceno** [comment]
As per @jbucaran's request:

My argument against the use of "custom tags" for functions of the type `(props, children) -> vnode`, is that they are only similar to actual html-tags in the context of JXS, where such a function named `Counter` can be callled and embedded in a vtree like this: `<div><Counter /></div>`.  If you're using hyperx, it looks like this `<div>${Counter()}</div>`.
