### ISSUE TITLE
Rename appOptions.events to appOptions.on

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#278]
Related #277.

**Comment by zaceno** [comment]
One thing I liked from #277 is that the idea of passing the emit function to mixins (as well as returning it from app)  Could we still do that, please?  As a follow on, we could *stop* passing the emit in arguments to each ~event~ on and action.

**Comment by jbucaran** [comment]
@zaceno Yeah, definitely that too. I forgot to mention it.

**Comment by lukejacksonn** [comment]
I'm not entirely convinced on this one.. seems like change for the sakes of change 🤔

What is so wrong with the name `events`..

At the moment there is app `state, actions, events, view` all of those words represent _things_ where as the word `on` really isn't too descriptive.

We are all going to know what it means, but will in confuse new starters more than it will aid us?

That said, sometimes it is confusing explaining to people that these are **app** events not **dom** events like `onclick`.

**Comment by jbucaran** [comment]
We could go back to hooks?

**Comment by jbucaran** [comment]
> @lukejacksonn At the moment there is app state, actions, events, view all of those words represent things where as the word on really isn't too descriptive.

Hmmmmmmmm, I guess you are right.

**Comment by zaceno** [comment]
Personally, the change of 'events' to 'on' is not important to me. In fact it would break things, and I see @lukejacksonn 's point. 

But I still do want the stuff I mentioned above :)

**Comment by SkaterDad** [comment]
I agree with @lukejacksonn and @zaceno that the current naming is good.

Whats the use case for passing the emit function to a mixin outside of the current way through actions?

**Comment by jbucaran** [comment]
@SkaterDad https://github.com/hyperapp/hyperapp/pull/280


So it all boils down to this:

```js
app({
  on: { ready: () => alert("OK") }
})
```


vs


```js
app({
  events: {  ready: () => alert("OK")  }
})
```

**Comment by zaceno** [comment]
@SkaterDad 

Now that app returns emit, it makes emit available in the scope of the appOpts.actions and events, so we could make the api cleaner by removing emit from the paramters to actions and events. 

... Unless you're defining those functions elsewhere and are merging together the appOptions.

But you could and probably should be merging in actions and events via mixin. So we should pass the emitter to mixins as well.

Beyond just making the API nicer (imo): if you are hacking on patterns for mixing in view-functions, then having the emit passed to your mixin definition means your mixed in views have access to emit, just like the main view does today. And that could enable some neat patterns I imagine.

**Comment by zaceno** [comment]
But it would break this pattern, if someone was using it:

```
import moduleA from 'modulea'
import moduleB from 'moduleb'

app({
  state: {
    modulea: moduleA.state,
    moduleb: moduleB.state,
  },
  actions: {
    ...moduleA.actions,
    ...moduleB.actions,
  },
  events: {
    (not exactly sure how people might be mergeing events)
  } 
})

```

... but that's exactly why we have mixins. So I see no harm.

**Comment by jbucaran** [comment]
Closing here since:

@lukejacksonn's argument

> state, actions, events, view ... represent things ... the word on really isn't too descriptive.

changed my mind.
