### ISSUE TITLE
"ready" event not firing 

### ISSUE THREAD

**Issue by eschaefer** [hyperapp/hyperapp#284]
Hey there, 

I'm playing around with the app events, and cannot get "[ready](https://github.com/hyperapp/hyperapp/blob/master/docs/api.md#ready)" to fire. Here's a minimal example, with [JSBin example](http://jsbin.com/xafufonoco/2/edit?js,console,output). "render" fires just fine, but the "ready" event does not get called:

```
const { h, app } = hyperapp;

const initialState = {};

const view = (state, actions) => (
  <div class="container">
    Hey.
  </div>
);

const events = {
  ready: () => console.log('ready'),
  render: () => console.log('render')
}

app({
  state: initialState,
  view: view,
  events: events
})
```

Not sure if it's a bug, or if I'm doing it wrong. Much thanks!

**Comment by jamen** [comment]
This has been changed on GitHub, but not yet released through npm.  It was renamed from `loaded` to `ready`, so you can use the former for now.  Sorry for the confusion, we have been polishing up for a v1 release.
