### ISSUE TITLE
Array as state is cast to Object

### ISSUE THREAD

**Issue by zaceno** [hyperapp/hyperapp#291]
This example does not work as expected: https://codepen.io/zaceno/pen/RgqOzL

It fails becasue the state is initialized as `state: ['X', 'Y']`, but then internally transformed into: `{'0':'X, '1': 'Y'}` (which does not have `join`, `map` or other array methods)

I believe this is a bug. Or it should be documented.

**Comment by jbucaran** [comment]
@zaceno Yes, you are right. Currently the only supported state types are object, string and number. We should write a proper essay on the state property and include this detail [here](https://github.com/hyperapp/hyperapp/blob/master/docs/state.md).

**Comment by jbucaran** [comment]
Whoops! 😉

**Comment by jbucaran** [comment]
@zaceno Added it to #244.
