### ISSUE TITLE
[Examples] Cool project, but the FX+SUBS example is potentially dangerous...

### ISSUE THREAD

**Issue by jskrzypek** [hyperapp/hyperapp#293]
You should add some kind of seizure warning to the FX+SUBS example, it made me feel a bit ill, and I *dont* have epillepsy. 😄 

Seriously though, just adding `(Seizure warning)` next to the example link or a little popup would prevent a lot of people from having really bad days after visiting your site.

**Comment by jbucaran** [comment]
@jskrzypek I know what you mean! I've updated the example to slow down color changes, without making

![2017-07-12 19 09 13](https://user-images.githubusercontent.com/56996/28112920-a85d682a-6735-11e7-8615-a2fe216fa080.gif)

What do you think?

**Comment by lukejacksonn** [comment]
or smooth it out with `transition: background Xs` 😉

**Comment by jbucaran** [comment]
@lukejacksonn Woah, thanks! That's way better. I think we can definitely close now.

Thanks @jskrzypek!

**Comment by jskrzypek** [comment]
Much better now!
