### ISSUE TITLE
Algernon 1.5 specifically supports HyperApp

### ISSUE THREAD

**Issue by xyproto** [hyperapp/hyperapp#296]
Hi,

If HyperApp code (typically starting with a call to `app`) is saved as a file ending with `.hyper` or `.happ`, [algernon](https://github.com/xyproto/algernon) has built-in support for transpiling from JSX to JS and wrap the resulting JavaScript in HTML and serve it. The server is a single executable that relies on no external libraries or executables.

Please give it a spin and see if this approach makes sense!

The "counter" example, served by Algernon 1.5 (only for testing, may disappear at any time), is running at:

http://safelr.com/counter/

Cheers,
Alexander Rødseth

**Comment by jbucaran** [comment]
@xyproto Sweet! Thanks for letting us know! 😏👍

If the file's extension was .hyper.jsx or .hyper.js, then syntax highlighting would be available in most editors out of the box without much fiddling with your configuration. Would you consider supporting those extension combinations as well?

**Comment by xyproto** [comment]
Released Algernon 1.5.1 with support for the `.hyper.jsx` and `.hyper.js` extension.

There is also support for styling with the `--theme` flag (select from one of 4 built-in themes) or a `style.gcss` file being present. The style from [hyperapp.glitch.me](https://hyperapp.glitch.me/) is now being used by default for HyperApp, hope that's fine (I could not find a license file for [style.css](https://hyperapp.glitch.me/style.css)). Of course, using the traditional combination of HTML + CSS + JS/JSX is also possible.

Algernon aims to provide a complete build pipeline, where only the server executable + a small `.hyper.jsx` file is needed to get started with HyperApp.

**Comment by jbucaran** [comment]
Great news! Thanks. 👍
