### ISSUE TITLE
A problem with the TodoMVC demo

### ISSUE THREAD

**Issue by infinnie** [hyperapp/hyperapp#298]
The code below in index.js (https://glitch.com/edit/#!/hyperapp-todomvc?path=index.js:242:5 )

> ```jsx
> [
>     "/",
>     (state, actions) =>
>         <TodoApp
>             state={state}
>             actions={actions}
>             slug={state.router.params.slug}
>         />
> ]
>```

causes the app to fail to show all items when navigating to `/` using browser history.

A fix:
```jsx
[
    "/",
    (state, actions) =>
        <TodoApp
            state={state}
            actions={actions}
            slug={FilterInfo.All}
        />
]
```

**Comment by jbucaran** [comment]
Thanks @infinnie! It should be fixed now.
