### ISSUE TITLE
Namespacing wrong when adding children to SVG tag

### ISSUE THREAD

**Issue by w-mcilhagga** [hyperapp/hyperapp#299]
I have an app which makes random svg circles (test case for a bigger project). Initially there are three circles, but a button lets you add more.

The new circle elements are added, but with the **wrong** namespace: xhtml rather than svg (tested in Chrome 59.0.3071.115). This can be seen by opening the developer tools, going to elements, and then clicking "Add Circle". A new circle tag is added but the namespace URI is wrong, so svg ignores it and it is not rendered. 

The "Move" button is not part of the bug report; it was added to see if altering attributes (position) works - it does. 

The code  is below:

[Note also usage of Object.assign in h( ) call - if I just pass this.attr, the change in attributes isn't picked up]

```html
<script src="https://unpkg.com/hyperapp"></script>
<body></body>
<script>
var h = hyperapp.h;
var app = hyperapp.app;

function randInt(a,b) { // random integer in [a,b]
    return Math.floor(Math.random()*(b+1-a))+a;
}

// random circle object

function Circle() {
    this.attr = {
        cx: randInt(1,400),
        cy: randInt(1,400),
        r:  randInt(10,30)
    }
}

Circle.prototype = {
    h: function() {
        // a change in attributes isn't picked up unless Object.assign is used!
        return h("circle", Object.assign({}, this.attr))
    },
    move: function() {
        this.attr.cx = randInt(1,400);
        this.attr.cy = randInt(1,400);
        return this;
    }
}

// the app

app({
    state: { // just a list of objects
        objects: [],
    },

    view: function v(state, actions) {
        return h("div",{},[
            // buttons
            h("button", {onclick: actions.addObj}, 'Add circle'),
            h("button", {onclick: actions.move}, 'Move'),
            h("hr"),
            // svg area
            h("svg", {width:400, height:400, style:{backgroundColor: 'lavender'}}, 
                state.objects.map(obj => obj.h())
            )
        ])
    },

    actions: {
        addObj: function(state) {
            // add a new object
            return {
                objects: state.objects.concat(new Circle())
            }
        },
        move: function(state) {
            // moves all the objects
            return {
                objects: state.objects.map(obj => obj.move())
            }
        }
    },

    events: {
        init: function(state, actions) {
            // put 3 random objects in the state
            actions.addObj(state)
            actions.addObj(state)
            actions.addObj(state)
        }
    }
})

</script>
```

**Comment by w-mcilhagga** [comment]
soz, the code missed out a body tag at the start

**Comment by jbucaran** [comment]
@w-mcilhagga You can edit posts on GitHub. Click on the little pencil next to the add reaction button.

Also have a look at [Code Blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) on GitHub docs. 

@ngryman Do you have any idea what's happening with the SVG here?

**Comment by w-mcilhagga** [comment]
**@jbucaran** thanks, edited & simplified bug report. Somewhere along the line the namespace is being lost for the new circle elements. Noticed that patch doesn't have an isSVG flag or seem to pass it along. Does that matter?

**Comment by ngryman** [comment]
For now `hyperapp` only namespace the `svg` tag: https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L129.
Since you are adding a `circle` svg tag, it's not namespaced.

**Comment by w-mcilhagga** [comment]
**@ngryman** Not sure I understand that - the first 3 circles in the svg tag (provided on init) are correctly namespaced, because createElement passes on the isSVG flag to its children. It's the new ones (inside the svg tag) that fail. Is that because patch **doesn't** pass an isSVG flag??

**Comment by ngryman** [comment]
@w-mcilhagga Yes right. Children of a `svg` tag inherit the `isSVG` flag. So when you first render it they are namespaced. But as you manually add a `circle` tag later, it does not inherit `isSVG` from a parent `svg` tag. So it's not namespaced.

**Comment by ngryman** [comment]
Basically that would involve that `hyperapp` checks for every `svg` elements possible and patch the give code like this:

```js
var element = (isSVG = isSVG || svgTags.includes(node.tag))
```

But that would make the bundle size explode.

**Comment by ngryman** [comment]
@jbucaran Could we propagate the `isSVG` flag when patching by checking if the current `vnode` is a `svg` here: https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L288?
That would make any new children as flagged as `svg` element.

**Comment by w-mcilhagga** [comment]
**@ngryman** but it would make it work too. I know 1KB is an incredible figure for something so capable, but exploding to 1.1KB is still plenty of boasting rights

**Comment by ngryman** [comment]
@w-mcilhagga See my above comment, I think it could be solved without this brute force method.

**Comment by jbucaran** [comment]
> @ngryman could we propagate the isSVG flag when patching by checking if the current vnode is a svg...?

What do you mean by "current vnode is a svg"?

**Comment by w-mcilhagga** [comment]
OK, patched the patch function. This works:

```javascript
      function patch(parent, element, oldNode, node, isSVG) {
        if (oldNode == null) {
          element = parent.insertBefore(createElement(node, isSVG), element)
        } else if (node.tag != null && node.tag === oldNode.tag) {
          updateElementData(element, oldNode.data, node.data)
          isSVG = isSVG || (node.tag==='svg')
          
          var len = node.children.length
          var oldLen = oldNode.children.length
          var reusableChildren = {}
          var oldElements = []
          var newKeys = {}

          for (var i = 0; i < oldLen; i++) {
            var oldElement = element.childNodes[i]
            oldElements[i] = oldElement

            var oldChild = oldNode.children[i]
            var oldKey = getKey(oldChild)

            if (null != oldKey) {
              reusableChildren[oldKey] = [oldElement, oldChild]
            }
          }

          var i = 0
          var j = 0

          while (j < len) {
            var oldElement = oldElements[i]
            var oldChild = oldNode.children[i]
            var newChild = node.children[j]

            var oldKey = getKey(oldChild)
            if (newKeys[oldKey]) {
              i++
              continue
            }

            var newKey = getKey(newChild)

            var reusableChild = reusableChildren[newKey] || []

            if (null == newKey) {
              if (null == oldKey) {
                patch(element, oldElement, oldChild, newChild, isSVG)
                j++
              }
              i++
            } else {
              if (oldKey === newKey) {
                patch(element, reusableChild[0], reusableChild[1], newChild, isSVG)
                i++
              } else if (reusableChild[0]) {
                element.insertBefore(reusableChild[0], oldElement)
                patch(element, reusableChild[0], reusableChild[1], newChild, isSVG)
              } else {
                patch(element, oldElement, null, newChild, isSVG)
              }

              j++
              newKeys[newKey] = newChild
            }
          }

          while (i < oldLen) {
            var oldChild = oldNode.children[i]
            var oldKey = getKey(oldChild)
            if (null == oldKey) {
              removeElement(element, oldElements[i], oldChild)
            }
            i++
          }

          for (var i in reusableChildren) {
            var reusableChild = reusableChildren[i]
            var reusableNode = reusableChild[1]
            if (!newKeys[reusableNode.data.key]) {
              removeElement(element, reusableChild[0], reusableNode)
            }
          }
        } else if (
          element != null &&
          node !== oldNode &&
          node !== element.nodeValue
        ) {
          var i = element
          parent.replaceChild((element = createElement(node, isSVG)), i)
        }

        return element
      }
    }
```

**Comment by w-mcilhagga** [comment]
For the far future, might be an idea to replace isSVG with a namespace (defaults to xhtml) and just use ```createElementNS``` all the time. That way, can use mathml with hyperapp as well.

**Comment by w-mcilhagga** [comment]
BTW forgot to say, cool framework. Really like it.

**Comment by jbucaran** [comment]
@w-mcilhagga Thanks! I'll refactor this patch a bit and create a commit soon with other small refactors I am working on (unless you really want to send me a PR). 

I'll make sure to thank you in the message!

BTW good job, got this to work too! 🎉 

![2017-07-15 22 01 26](https://user-images.githubusercontent.com/56996/28239530-5205de82-69a9-11e7-88ae-7a45a99b7614.gif)

**Comment by w-mcilhagga** [comment]
that's pretty insane.

**Comment by jbucaran** [comment]
> @w-mcilhagga [Note also usage of Object.assign in h( ) call - if I just pass this.attr, the change in attributes isn't picked up]

Hmmm. Can you comment on this?

**Comment by w-mcilhagga** [comment]
Not really. Comes up when you hit the move button. I figured your change detection just checks to see if the node attribute object is the same as before (i.e. same pointer) but doesn't check to see if the contents of the attribute object has changed. 

This is probably justifiable in terms of functional programming, immutable objects etc. etc. but might need flagging in the docs.

**Comment by ngryman** [comment]
@w-mcilhagga Thanks for you patch, that's exactly what I meant 👍

**Comment by w-mcilhagga** [comment]
You're welcome, I was fairly sure the issue was in patch, maybe just needed a nudge from u to go ahead and try to fix it.
