### ISSUE TITLE
Keyed benchmark comparison

### ISSUE THREAD

**Issue by rosenfeld** [hyperapp/hyperapp#300]
Are there any reasons why hyperapp is only mentioned in the non-keyed section of the referred benchmark in the documentation? It seems hyperapp already supports keyed reconciliation. Is it complicated to update the benchmarks to include HyperApp in the keyed comparison table as well?

https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html

**Comment by jbucaran** [comment]
No particular reason. When I first added it, there was no difference and I was still hoping I could find a good compromise between the two, but that never happened. It should be added at some point.

**Comment by andyrj** [comment]
When I get js-framework-benchmark running I will send a PR with 0.10.0 in keyed comparison.

**Comment by jbucaran** [comment]
@andyrj Sounds good. Let's do it after we figure out recycling #297.
