### ISSUE TITLE
Undefined element after initial patch

### ISSUE THREAD

**Issue by andyrj** [hyperapp/hyperapp#301]
Just wanted to create this issue to be sure and not forget that this bug was spotted by @ngryman while messing with the recycle PR.  

https://hyperappjs.slack.com/archives/C41ECC0V6/p1499996121395572

**Comment by jbucaran** [comment]
@andyrj Can you explain the bug instead of posting a link?

**Comment by andyrj** [comment]
@ngryman noticed that element === undefined, beyond the first patch() call when it shouldn't be.

He was debugging it and mentioned the part of the patch function that appeared to cause the bug in that slack message.

```js
      ifnewKeys[oldKey]) {
          i++
          continue
        }
```

**Comment by andyrj** [comment]
Bleh on phone can't edit the above code block, refer to the slack message.

**Comment by jbucaran** [comment]
@ngryman How can I repro the bug?

**Comment by andyrj** [comment]
I tested on dbmon with console.log and also saw what he did.

**Comment by andyrj** [comment]
Repro code for app.js
```js
  var undefElmCount = 0
  function patch(parent, element, oldNode, node) {
    if (element === undefined) {
      undefElmCount++
    }
    if (undefElmCount > 1) {
      debugger;
    }
    if (oldNode == null) {
```

this is a branch of a repo updated to use local build of hyperapp on my machine you may have to edit the hyperapp/index.html to point to wherever on disk it is relative to this project.

https://github.com/andyrj/js-repaint-perfs/tree/repro-undef-elm

**Comment by andyrj** [comment]
This isn't a bug, sorry stepped through repro and it's working as intended on this sorry for noise...
