### ISSUE TITLE
More docs for mixins

### ISSUE THREAD

**Issue by jcubic** [hyperapp/hyperapp#302]
It would be nice to have more docs about mixins (how they work and what the API is) right now only logger mixin in docs and [hyperapp/router](https://github.com/hyperapp/router) (don't know if there are any more mixins), the second one is more complex mixin but it don't have any comments in it.

Comments are fine as docs, it would be nice if router have them.

**Comment by lukejacksonn** [comment]
@jcubic 👋 more docs and/or comments would be great! Did you manage to get your head around the router mixin? It now lives at https://github.com/hyperapp/router if you have time to go through and comment it we'd review the PR.

Could you outline what wasn't made clear in the docs, so we can make them better?

**Comment by jcubic** [comment]
I would love to add comments or more into to the docs but have hard time to figure out what is what in the router.

The docs for mixin is just one example with logger that have actions event (one only API in that example) that's execute on every actions that have been called, and router have lot more parts and I don't know which one came from mixin api and which one is just helpers.

Are there any more mixin examples out there?

**Comment by jbucaran** [comment]
@jcubic I've added a new item to the roadmap. Do feel free to add more comments here and continue the conversation, but I'll close here and track this on #244.

**Comment by jbucaran** [comment]
@jcubic Still WIP :)

- https://github.com/hyperapp/hyperapp/blob/master/docs/mixins.md
