### ISSUE TITLE
Question: Do you support immutable.js for the state?

### ISSUE THREAD

**Issue by JustFly1984** [hyperapp/hyperapp#303]

**Comment by jbucaran** [comment]
@JustFly1984 Do you mean using the [immutable.js](https://facebook.github.io/immutable-js/) library and HyperApp?

**Comment by JustFly1984** [comment]
exactly)

**Comment by jbucaran** [comment]
HyperApp can certainly be used (and has been used in the past) with immutable.js, ramda, rxjs, lodash, etc. Feel free to try it out with any of them and break it! 😄:+1:

**Comment by lukejacksonn** [comment]
Just a word on this @JustFly1984.. HyperApp only supports primitive javascript types (int, string, array, object, etc.) states, most commonly JavaScript objects. Immutable JS doesn't work with real javascript objects. If you are only only get out JS objects from state and anre only allowed to put JS objects into the state.. then you find yourself doing  [`.fromJS()`](https://facebook.github.io/immutable-js/docs/#/fromJS) and [`.toJS()`](https://facebook.github.io/immutable-js/docs/#/Map/toJS) a lot.

There are some alternatives though (I am sure there are many more)..

- Lenses - for getting, setting, updating objects at depth (e.g. [R.lens](http://ramdajs.com/docs/#lens) and [R.assocPath](http://ramdajs.com/docs/#assocPath))
- Collections - that take the heavy lifting out of immutable updates (e.g. [collectjs](https://github.com/ecrmnn/collect.js))

**Comment by JustFly1984** [comment]
There is an Record API, which has similar ( but not completely ) API to
vanilla JS.

2017-07-18 8:19 GMT+08:00 Luke Jackson <notifications@github.com>:
