### ISSUE TITLE
load or loaded

### ISSUE THREAD

**Issue by tscholl2** [hyperapp/hyperapp#324]
I'm a little confused. The [docs](https://github.com/hyperapp/hyperapp/blob/master/docs/events.md#load) (and the [code](https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L26)) say "load" but the [cdn](https://unpkg.com/hyperapp@0.10.1) says "loaded". The cdn says version 10.1 which seems like the most recent?

Either way, this was the cause of a little confusion when I was trying to play around. I'd be happy to help fix the docs, if I know which it is suppose to be.

**Comment by jamen** [comment]
That event has gone through quite the journey of names and behavior changes:

`loaded` -> `ready` -> `init` -> `load`

My guess is that this is not released yet because it was _just_ introduced in #317. But I hope we can settle on some event names soon.  :stuck_out_tongue:

**Comment by tscholl2** [comment]
That makes sense. Naming things is always difficult. Since the docs are correct, I assume this issue will fix itself with the next release. I'm fine closing this, unless you think it would be helpful to have until the cdn is updated.

**Comment by Swizz** [comment]
The documentation follows the master branch evolution of Hyperapp.
Some code/features/naming could be unpublished yet.

**Comment by lukejacksonn** [comment]
@tscholl2 keep this open until the release is synced up with master sounds like a good idea, it will stop further confusion and might act as a motivator for @jbucaran to type `npm publish` 😛

**Comment by jbucaran** [comment]
@tscholl2 Sorry for the delay, @0.11.0 is out!
