### ISSUE TITLE
Invert mixin initialization order.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#329]
Currently we are initializing the app, _then_ mixins. This makes it impossible for the app to overwrite a definition added by a mixin. 

Your app should have the highest precedence and not mixins.

**Comment by zaceno** [comment]
That makes sense!

**Comment by Swizz** [comment]
Totally agree !

**Comment by andyrj** [comment]
💯 agree app should take precedence

**Comment by jbucaran** [comment]
💯

I'll create a PR with the changes.

**As a side effect**, I'd prefer to drop `presets` with this change since it complicates the implementation somewhat. 

Less is more remember? @zaceno :)

**Comment by zaceno** [comment]
I don't think that the current idea of "presets" (or "mixins in mixins") is especially important anyway. In fact it only complicates things when you're trying to do things like scoped mixins. 

Anyhow, presets, or bundling mixins, can still be done in an ok-nice way with array spreads.

```
const MyMixinPreset = [MixinA, MixinB]

app({
  mixins: [AMixin, ...MyMixinPreset, AnotherMixin],
  ...
})


```
