### ISSUE TITLE
Implement a CI in order to get build stats like code coverage etc.

### ISSUE THREAD

**Issue by maraisr** [hyperapp/hyperapp#33]
Thinking if we use [CircleCI](https://circleci.com) along with [Codecov](https://codecov.io) and get our branches built through to we can safely say that any PR will pass our linting rules #32 and our tests #31, plus we'd be able to put a nice snazzy [shields.io](shields.io) shield to show off our 100% code coverage report (once we get to it).

![high-five](https://cloud.githubusercontent.com/assets/599459/22631337/b817bc98-ec56-11e6-8e2f-0c859678325a.gif)

**Comment by jbucaran** [comment]
@maraisr Yes, CircleCI or Travis or both are fine! We need tests first though.

**Comment by jbucaran** [comment]
We have tests running on travis and coverage too. All thanks to @maraisr for introducing this!
