### ISSUE TITLE
allow for namespacing or nesting of events

### ISSUE THREAD

**Issue by RikuVan** [hyperapp/hyperapp#334]
It is really nice that I can nest my actions in a mixin, like

```javascript
actions: {
  auth: {
      login: () => {}
   }
}
```
But if I have an event in the same mixin, I can't do the same. Would it be worth making something like emit('auth.expired') possible? I realize this is a minor convenience and would definitely not be in favour unless it is not too complicated to do.

**Comment by Swizz** [comment]
Keys in object can be a string, so what about the following ?

```jsx
const emit = app({
  events: {
    'auth:expired': () => {}
  }
})

emit('auth:expired')
```

**Comment by RikuVan** [comment]
yeah, that is good enough for me really

**Comment by jbucaran** [comment]
@RikuVan And for me too, but what we want to know is: is it good enough? What would be the cons of implementing your proposal?

**Comment by lukejacksonn** [comment]
I have nearly always used the `namespace:event` syntax when using this kind of thing (pubsub especially). As @Swizz points out they are all just strings used as unique identifiers in a global space.

My first experience with events was with https://github.com/marionettejs/backbone.radio their docs explain the idea of `channels` and use a `:` delimiter.

If you were to nest them then how would you propose siblings, parents/children communicate. Who listens to what, what are the rules? Not impossible but quite the rabbit hole 🐰

**Comment by Swizz** [comment]
Events act like reducers accross Mixins and App. So, I tried some things, but even if this is easy to split the event name to obtain a key river `"foo:bar:baz ==> appEvents[foo][bar][baz]`, I dont know if this feature would be easy to reason about.

**Comment by jbucaran** [comment]
Ping @dodekeract.

**Comment by dodekeract** [comment]
As long as `emit` is called with a string, I disagree with the proposal. In case we decide to change that to a more action-like API, I'd suggest merging `events`, and `actions` if possible or implement this feature request.

**Comment by jbucaran** [comment]
@RikuVan I know this is not what you asked for, but what about this?

```
const Auth = () => ({
  events: {
    expired() { ... }
  },
  // Other stuff here!
})
```

The event is still global, but the associated code is encapsulated in the Auth mixin and this already works right now.

**Comment by RikuVan** [comment]
yeah, that works too, although I think I will just use the string solution 'auth:expired' for now. Thanks the consideration!
