### ISSUE TITLE
Browser support? 👾

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#34]
What browsers should we aim to support?

**>= IE11** ?
**>= IE10** ?

**Comment by dodekeract** [comment]
IE10 would be great. That'd allow me to use this. ;)

**Comment by jbucaran** [comment]
Yeah, that makes sense.

**Comment by dodekeract** [comment]
@jbucaran I used this for an app I had to write for university. I'll check if anything doesn't work properly on it. Would be nice if it's an official goal to support IE10 though.

**Comment by jbucaran** [comment]
Not a lot of feedback here. I think IE11 is a must-support, but I'll aim at IE10.

**Comment by VinSpee** [comment]
Hi,

I realize this issue is old, but I still don't see any out-right declaration of browser support in the docs. Should I assume IE10+?

**Comment by jbucaran** [comment]
@VinSpee Correct! :)

**Comment by okwolf** [comment]
@jbucaran this should probably make its way into the docs for clarity.

**Comment by jorgebucaran** [comment]
###### Summary

IE10 and IE11 are still officially supported, but you may need to add your own polyfills to fix some odd issue here and there. #690, https://github.com/jorgebucaran/superfine/pull/140

<img width="957" alt="screen shot 2018-08-31 at 16 07 43" src="https://user-images.githubusercontent.com/56996/44897833-0c3e8d80-ad38-11e8-8fbe-b9922190c5d0.png">
