### ISSUE TITLE
API adjustments needed

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#340]
The current API of view, actions and events boils down to this single function signature:

```
(state, actions, data)
```

Inside an app call it looks like this:

```js
app({
  view(state, actions) {

  },
  action: {
    someAction(state, actions, data)
  },
  events: {
    load(state, actions, root) {

    },
    render(state, actions, view) {

    },
    action(state, actions, data) {

    },
    resolve(state, actions, data) {
        
    },
    update(state, actions, data) {

    }
  }
})
```

This is usually good enough, but we still have couple of loose ends. How to know which action triggered a state update? How to know the name of the action inside events.resolve? There are workarounds, but nothing good yet.

#339 is a good start, but it means some events signature would change to this:

```
resolve(state, actions, data, { action, data })
```

and 

```
update(state, actions, newState, { action, data })
``` 

which is not as elegant as I would hope, but if it's the best we can do then so be it.

I would like to explore alternatives in this thread. 

I don't think there are unlimited possibilities, we just need to make sure we can accommodate action information for resolve and update.

If you have any ideas, please share them. I'll be adding proposals to this issue as I come up with them.

👋

**Comment by jbucaran** [comment]
This idea has a few variations, but it involves getting rid of the "reduce"-like functionality of events and changing the API to this.

```js
app({
  view(state, actions) {},
  action: {
    someAction(state, actions, data) {}
  },
  events: {
    load(state, actions, root) {},
    render(state, actions, view) {},
    action(state, actions, { action, value }) {},
    resolve(state, actions, { action, value }) {},
    update(state, actions, { action, next }) {}
  }
})
```

**Comment by jbucaran** [comment]
This idea does not get rid of the "reduce"-like functionality of events but changes the API to this.

```js
EVENTS
load    (state, actions, root)

render  (state, actions, view)

action  (state, actions, value, actionName)

resolve (state, actions, value, actionName) 

update  (state, actions, nextState, actionName)
```

**Comment by jbucaran** [comment]
Here is another option that looks cool, but it has other disadvantages like inability to destructure the state or actions.

```jsx
EVENTS

load    ({ state, actions, value })

render  ({ state, actions, value })

action  ({ state, actions, name, value })

resolve ({ state, actions, name, value })

update  ({ state, actions, name, value })
```

**Comment by lazarljubenovic** [comment]
> inability to destructure props from the state or actions.

@jbucaran Nested destruction is possible.

```js
const fn = ({state: {props: {foo, bar}}}) => [foo, bar]

fn({state: {props: {foo: 1, bar: 2}}}) // => [1, 2]
```

**Comment by jbucaran** [comment]
@lazarljubenovic TIL 💥

**Comment by jbucaran** [comment]
This would involve changing how the actions and view works (because we are trying to keep the same signature everywhere). So, while nested destructuring is really nice, I am swaying towards this instead.

```js
action  (state, actions, { name, value })
resolve (state, actions, { name, value })
update  (state, actions, { name, value })
```

**Comment by MatejMazur** [comment]
@jbucaran Agree, [this](https://github.com/hyperapp/hyperapp/issues/340#issuecomment-325187084) one is nice and clean.. not so much brackets. 👍

**Comment by jbucaran** [comment]
But a single object is pretty cool too... 😏 

Tough decisions! 😄

**Comment by MatejMazur** [comment]
Yes, it's nice because you can skip unused argument's keys which is really handy but by the time it looks a little bit messy if you have everywhere different inputs in different orders..

**Comment by lazarljubenovic** [comment]
I like [this](https://github.com/hyperapp/hyperapp/issues/340#issuecomment-325187084) as well. `state` and `actions` is here to stay for sure, and those are the mostly likely commonly used arguments. Any additional things we need goes into this last object, so addition of new things will not be a breaking change.

I love the single object thing when it's tough to determine which argument the consumer would probably need (which saves us from `(_, __, ___, ____, thereYouAreMyDearArgument)`), or when the object's keys are dynamic (so the consumer needs to specify what to grab from there anyway).

**Comment by okwolf** [comment]
@jbucaran I like the symmetry of [this](https://github.com/hyperapp/hyperapp/issues/340#issuecomment-325187226) but I'm a bit confused on what `value` would be in `events.resolve` and `events.update`. Ideally I would like access to the original action `name` and `data` from `events.resolve` and `events.update` the same way it's already available in `events.action`.

**Comment by jbucaran** [comment]
Closing for the same reason as https://github.com/hyperapp/hyperapp/pull/339.

Feel free to add your thoughts on this anway! 🌮👋

**Comment by okwolf** [comment]
@jbucaran I understand we're not changing the API, but I have a usage question. It's clear that the first two arguments to any of the `events.*` handlers are `state` and `actions` but should the last argument have any consistent shape? Since emit only allows a single additional argument receiving multiple things in your event handler will require either an object with keyed properties for each of your arguments (I used this in my logger) or an array where you must know the position of where to expect arguments. Should there be any general guidance here?

**Comment by jbucaran** [comment]
> but should the last argument have any consistent shape?

Nope, what it _is_ depends on the event. events.render's data is a View and events.resolve's data is an ActionResult.

You could pass an object like ActionInfo.
