### ISSUE TITLE
How does actions change the state?

### ISSUE THREAD

**Issue by codingphasedotcom** [hyperapp/hyperapp#344]
I'm wondering How does actions change the state? Is it similar to redux? I'm looking at the counter example which is pretty simple but is it immutable? 

```jsx
actions: {
    down: state => ({ count: state.count - 1 }),
    up: state => ({ count: state.count + 1 })
  }
```

##Lets say an example like this

```jsx
var state = {
  property: {
    propertyChild: [{
        city: 'New York'
      },
      {
        city: 'Santiago'
      },
      {
        city: 'Tokyo'
      }
    ]
  }
}
```

what if I wanted to change the second object in propertyChild?

what would be the proper way to update that?

**Comment by selfup** [comment]
I would think:

```javascript
return {
  property: {
    propertyChild: newArrayOfStuff 
  },
};
```

So essentially you would need to have something that modifies that array how you see fit and then pass it in to the return value

**Comment by codingphasedotcom** [comment]
Ok cool got it. Any good libraries that you can recommend currently using immutability-helper

**Comment by selfup** [comment]
Hmm I think @andyrj @zaceno can help with that 🎉

**Comment by andyrj** [comment]
@codingphasedotcom I would recommend sticking with plain old JavaScript until you have to get into really nested state, at which point qim is a pretty nice library if you aren't happy with immutability-helper.  The default for return of an action is a shallow merge like @selfup said.  It would be like redux only having 1 reducer that just does, ```state = Object.assign({}, state, actionResult)```.  You could also change that with a custom resolve if you want different behavior.

**Comment by jbucaran** [comment]
@codingphasedotcom 

> I'm wondering How does actions change the state? 

We wrap each action you pass to the app call in a function like this:

```js
wrappedAction = function(someData) {
  var result = yourAction(appState, appActions, someData)
  update(result)
}
```

This way we can update the state every time an action returns. This in turn causes a UI re-render. Note that in detail, this is more efficient than just re-rendering every time. We batch state updates and only re-render the UI on the [next browser repaint](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame).

> Is it similar to redux? 

Yes. Very much.

> I'm looking at the counter example which is pretty simple but is it immutable?

Yes, it immutable. The way we update the current state is by replacing it with a new state, never mutating the previous one.

**Comment by jbucaran** [comment]
@codingphasedotcom I think the question has been answered, but if you have any other ask away! 👋
