### ISSUE TITLE
Pass emit to events and make mixins either a function or object.

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#349]
Recently we've talked about making mixins a function (by convention, not strictly), so instead of:

```js
mixins: [logger]
``` 

...prefer:

```js
mixins: [logger()]
```

This got me thinking about how to simplify mixins.

To me mixins are a no-brainer, but to a newcomer, it might be frustrating how mixins that take options must be a function that returns a function. 🤔 

~~What if we go back to passing `emit` to events? This would allow us to make mixins either a function that takes some options or just an object.~~

Instead of passing emit to events, we can try a midway approach, allowing mixins to behave either as a function that returns a function or a function that returns an object.

For example, @okwolf's logger could be changed to the following (since emit is not necessary):

```js
function logger(options) {
  // Initialize...
  return {
    events: {
      action: function(state, actions, action) {
        // ...
      },
      resolve: function(state, actions, result) {
        // ...
      },
      update: function(state, actions, nextState) {
        // ...
      }
    }
  }
}
```

And if you want `emit`, then use it as usual (no API break).

**Pros**
- Allow mixins to be simple objects.
- Make mixins that don't use emit simpler to write.
- No API break.

**Cons**
- Mixins can take more shapes now. All of the following are valid mixins:

```js
// Basic free plan
const a = {
  events: {
    load() {
      console.log("ok")
    }
  }
}

// Basic free plan with options

function a(options) {
  return {
    events: {
      load() {
        console.log("ok")
      }
    }
  }
} 

// Premium plan with emit

function a(emit) {
  return {
    events: {
      load() {
        console.log("ok")
      }
    }
  }
} 

// Premium plan with emit & options
function a(options) {
  return function(emit) {
    return {
      events: {
        load() {
          console.log("ok")
        }
      }
    }
  }
}
```

**Comment by okwolf** [comment]
@jbucaran is this how each of the different "plans" would be used or am I missing something?
```js
// Basic free plan
mixins: [a]

// Basic free plan with options
mixins: [a(options)]

// Premium plan with emit
mixins: [a]

// Premium plan with emit & options
mixins: [a(options]
```

**Comment by jbucaran** [comment]
> @okwolf Could there be confusion/errors from a user passing in a mixin function that took options and returned a mixin object VS a mixin function that takes emit and returns a mixin object?

Not sure. But  probably yes, there could be.

**Comment by lazarljubenovic** [comment]
> to a newcomer, it might be frustrating how mixins that take options must be a function that returns a function. :thinking:

Anyone diving into an Elm-like architecture will sooner or later have to deal with higher-order functions. With proper documentation and good explanations, I don't think that this should be an issue.

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp/commit/5b4a705df02595dd6b6a28bcdb205a1ab530b37e

Thank you everyone for your input.
