### ISSUE TITLE
"Try it online" codepen link in the docs is down

### ISSUE THREAD

**Issue by Stanley-Jovel** [hyperapp/hyperapp#350]
`hyperapp/docs/getting-started.md` file has a link at the end that redirects to  https://codepen.io/hyperapp/pen/NvYdma?editors=0010
which seems to be broken redirecting to a 404 page.

**Comment by jbucaran** [comment]
@Stanley-Jovel Thanks for reporting. What page in the docs?

**Comment by Stanley-Jovel** [comment]
Sorry, I did not elaborate. I updated the issue with more details

**Comment by jbucaran** [comment]
It's fixed, thanks! 🎉

**Comment by Stanley-Jovel** [comment]
That was a very fast response, thanks! 👍
