### ISSUE TITLE
Travis CI not being triggered properly?

### ISSUE THREAD

**Issue by selfup** [hyperapp/hyperapp#359]
It seems that lately (new PRs/commits (maybe)) are not triggering Tavis CI 🤔 

Could be some limit we have hit? Or this repo might have broken webhooks on the GitHub side of things?

Anyways, just wanted to officially keep track of this behavior!

For example these two:

1. https://github.com/hyperapp/hyperapp/pull/355
2. https://github.com/hyperapp/hyperapp/pull/358

**Comment by jbucaran** [comment]
@selfup I don't understand what happened, but they were all unchecked. Now they are all checked.

<img width="768" alt="screen shot 2017-09-11 at 8 47 10" src="https://user-images.githubusercontent.com/56996/30254079-e3c2062e-96cd-11e7-8c38-2fb8bb9013d9.png">

**Comment by selfup** [comment]
Great! Thanks 🙏

**Comment by jbucaran** [comment]
Should be good, so let's close here.
