### ISSUE TITLE
Support for components that return Promises

### ISSUE THREAD

**Issue by infinnie** [hyperapp/hyperapp#363]
Follow-up to #362 .

Many times, we need asynchronously loaded components. Wouldn’t it be good for a component to return a promise and only do the actual update when it gets resolved?

**Comment by andyrj** [comment]
api is kind of rough atm more verbose and "loady" than I'd like but if you mean functionality like [react-loadable](https://github.com/thejameskyle/react-loadable) , I made https://github.com/andyrj/hyperapp-loadable

**Comment by infinnie** [comment]
But I guess the Promise API would be clean and simple when viewed from outside.

**Comment by infinnie** [comment]
It might not really be required for components to return Promises.

See also https://github.com/infinnie/infinnie.github.io/issues/11

**Comment by jbucaran** [comment]
Sorry, I was late to the party, but I would be open to incorporate this functionality to core only if it's impossible (or extremely difficult) to replicate in userland using a HOF of `h()`. 😄

**Comment by jbucaran** [comment]
And by the way, thanks @infinnie for the suggestion.
