### ISSUE TITLE
Make events.action More Functional

### ISSUE THREAD

**Issue by okwolf** [hyperapp/hyperapp#368]
Today the following [default events](https://github.com/hyperapp/hyperapp/blob/master/docs/events.md#default-events) may return a value to be used by the app in some way: `events.load`, `events.resolve`, `events.update`, and `events.render`. The astute among you may have already noticed that `events.action` was missing from that list, which is because today its return value is [completely thrown away](https://github.com/hyperapp/hyperapp/blob/3ab5a1e483fc0520447b3280c52ec67c84f66ff1/src/app.js#L39) and so it can only be used for the purpose of side effects.

So what might a return value from `events.action` be used for? Well, the `name` of the action has already picked which action function to call, so it doesn't really make sense to allow returning a different name. However, since `data` was what was passed to the original action function, it might make sense for `events.action` to allow returning a different set of data to act as a sort of middleware for action data. ~~A bonus feature would be allowing the return of `false` to completely cancel an action (perhaps due to some value in `state` that makes the action invalid), but I'm not sure if `false` would ever legitimately be used as the data value for an action.~~

**Comment by jbucaran** [comment]
>  I'm not sure if false would ever legitimately be used as the data value for an action.

It is and it might be a totally normal data to pass to the action.

**Comment by jbucaran** [comment]
@okwolf This is a conversation I wanted to have for a long time! Thanks for bringing it up.

**Comment by okwolf** [comment]
Technically `events.resolve` can already be used to cancel everything an action does except for calling other actions as side effects, so that's probably not needed.

**Comment by IamCarbonMan** [comment]
If you're looking for a way to cancel actions by returning data, might I suggest following what Redux and many Redux ecosystem tools do, and simply using some string that you can't imagine being used for anything else. For example, returning `"__HYPERAPP_CANCEL_ACTION__"` or something similarly unmistakable.

**Comment by JorgeBucaran** [comment]
@zaceno @lukejacksonn Do you guys have any opinion about this?

I thought about it a bit more and I can't think of anything useful to do in this event that you can't already do with `resolve`.

**Comment by IamCarbonMan** [comment]
> Technically events.resolve can already be used to cancel everything an action does except for calling other actions as side effects

I really think that when you start building complex apps, you'll want a dedicated way to cancel an action without worrying about the possible side effects that need to be canceled as well.

**Comment by JorgeBucaran** [comment]
> @IamCarbonMan you'll want a dedicated way to cancel an action...

I honestly can't think of why I would ever want to do that. 🤔 

@okwolf BTW is this a real use case you had?

**Comment by SkaterDad** [comment]
@JorgeBucaran 
> I honestly can't think of why I would ever want to do that

One use case I can think of is cancelling the `router.go('/blah')` action (typical route guarding, based on some state like user auth).  Currently, you can't even redirect while that action is still in progress without wierd things happening.  Since that action has a side effect on the browser history, it's not something easily "undone" in the `resolve` event hook.

**Comment by Swizz** [comment]
Maybe a kind of thunk (again ; love that). I dont know which one between `accept` or `reject` is better.

```js
app({
  events: {
    action(state, actions, { name, data }) {
      return (reject) => {
        if(name === "go" && data === "/failed") {
           reject()
        }
      }
    }
  }
})
```

**Comment by JorgeBucaran** [comment]
@SkaterDad So would this work?

```js
if (!emit("action", { name: name, data: data }))) {
 // our regular business 
}
```

**Comment by SkaterDad** [comment]
Wouldn't that cancel all actions?  Since actions return a state object, it'll always be true.

On the router example, we can probably fix it by adding another hook which evaluates before messing with browser history, so canceling the action is probably not needed in reality.  (`emit("beforeRoute")` in router snippet below). 

Might be a good convention to promote for actions that have side effects?

```js
      actions: {
        router: {
          set: function(state, actions, data) {
            return {
              router: data
            }
          },
          go: function(state, actions, path) {
            if (emit("beforeRoute") && location.pathname + location.search !== path) {
              history.pushState({}, "", path)
              actions.router.set({
                path: path
              })
            }
          }
        }
      },

```

**Comment by JorgeBucaran** [comment]
@okwolf 🏓 

> @SkaterDad Might be a good convention to promote for actions that have side effects?

Good idea.

**Comment by okwolf** [comment]
@JorgeBucaran if we're not going to use the results of `events.action`, and it really does only exist for side effects, couldn't we remove `events.action` and just use `events.resolve`? Any side effects that `events.action` does could instead be done in `events.resolve` if `events.resolve` received the original `action` object. This would be a breaking change to the API though 😞

**Comment by JorgeBucaran** [comment]
@okwolf It would make using `resolve` more complicated though. Do you have an actual proposal? What code changes would you like to introduce exactly?

**Comment by andyrj** [comment]
@SkaterDad, I wonder if that gated routing wouldn't be better in the router itself.  For instance it would be easy to add a function to evaluate prior to returning the matched route which could cancel the navigation.  It's something I have been considering adding to my router.

**Comment by okwolf** [comment]
@JorgeBucaran I don't really have a simple proposal for using `resolve` unless we want to allow for multiple data parameters to `emit`. Probably not worth it.

I'm torn about this issue since `events.action` is needed for some devtool/test use cases, but not as useful in production. 🤔
