### ISSUE TITLE
Add it to microjs

### ISSUE THREAD

**Issue by ginsterbusch** [hyperapp/hyperapp#369]
Maybe add this to [microjs](http://microjs.com) ? It certainly falls into the "less than 5 kb" category ;)
Github: https://github.com/microjs/microjs.com 

cu, w0lf.

**Comment by jbucaran** [comment]
@ginsterbusch Cool! Do you know the maintainers?

**Comment by JorgeBucaran** [comment]
@charlike Are you one of the maintainers of Microjs? What do we need to do so that Hyperapp shows on your website?

/cc @SimonWaldherr

**Comment by charlike** [comment]
Yea, I'm. But the site is pretty outdated. We need much work there to update the whole site. We regularly merge some PRs, but if i remember correctly they are not shown on the site currently.

You can send PR and once we do our work it will be shown :)

**Comment by JorgeBucaran** [comment]
Thanks @charlike.

/cc @ginsterbusch

**Comment by JorgeBucaran** [comment]
I'd love for Hyperapp to be added to microjs, but I don't have time to deal with that, so if anyone wants to beat me to it, feel free to add it and ping me then! Thanks @ginsterbusch.

**Comment by SimonWaldherr** [comment]
FYI @ginsterbusch, @JorgeBucaran, @charlike: done
via https://github.com/microjs/microjs.com/commit/f3fc8bc03f1eac5796055b0d8a3c0193bbc623c6
