### ISSUE TITLE
Provide a list of example apps to help build community

### ISSUE THREAD

**Issue by rajaraodv** [hyperapp/hyperapp#370]
I created a list of examples that I'd love to see built by us (I'm happy to contribute). All these are taken from the React ecosystem. We can use this list as a guidelines and top-level things that the community will need to come onboard and be successful.  Note: We may already have some ready to be used.

In JS, we can solve everything 100s of ways. I'm looking to provide a set of "prescribed" ways of doing things (both for small and large apps) - even if it comes with some caveats. 

---

## Examples from React To Be Ported To Hyperapp
The purpose of this is to have links to examples that shows Hyperapp's core concepts, organizing large projects, dealing with 3rd party libraries and so on.

### All the examples should try to have: 
1. Have a testable UI (i.e. not just concepts)
2. Have Comments/documentation
3. Closer and similar to "Elm" architecture than "React" architecture.
   1. Use Functional programming tehniques
   2. Use Functional libraries like Ramda (if needed)
   3. Use Flow (if possible) for type checking.
   4. Use "MayBe" or Null checks to avoid all run-time errors.

## Explain Concepts
1. React Tutorial - https://facebook.github.io/react/tutorial/tutorial.html (final app: https://codepen.io/gaearon/pen/gWWZgR?editors=0010)
    1. What is Model-View-Update
    2.  States and Lifecycle - https://facebook.github.io/react/docs/state-and-lifecycle.html
    3. Passing data through "props"
    4. Handling Actions
    5. Handling DOM events
    5. React's classes vs Hyperapp's functions
    6. Conditional Rendering https://facebook.github.io/react/docs/conditional-rendering.html
    6. Immutablilty https://facebook.github.io/react/tutorial/tutorial.html#why-immutability-is-important
    7. Keys in lists - https://facebook.github.io/react/tutorial/tutorial.html#keys

3. Forms https://facebook.github.io/react/docs/forms.html
4. "Refs" and DOM equivalent https://facebook.github.io/react/docs/refs-and-the-dom.html
5. "Composition vs inheritance" - https://facebook.github.io/react/docs/composition-vs-inheritance.html
6. "Higher-order components" https://facebook.github.io/react/docs/higher-order-components.html
7. "Reconciliation" equivalent in HyperApp https://facebook.github.io/react/docs/reconciliation.html
8. Testing - Jest? 
9. Namespace resolution
10. Mixins - Why and How

## Styling
1. Examples that shows how to style components
2. How to use various CSS libraries like "Styled components".

## Explain How To Organize Code And Build Realistic Apps
1. Provide a large app and uses 3rd party libraries, Has authentication routes, has at least 10 different components.
    1. For example: Shopify clone that uses shopping cart, user authentication, products list, products details, emails, change password etc.
2. https://wrapbootstrap.com/theme/ant-reactjs-admin-web-app-WB034D136

## Build Fun Apps:
1. Tetris With States - https://github.com/skidding/flatris (currently in React)
2.  Gopherize me  - https://gopherize.me/ (Go language)
2. Emoji Search - https://github.com/ahfarmer/emoji-search (currently in React)
3. Product comparison - https://github.com/Rhymond/product-compare-react
4. Todo Example
5. HackerNews Clone

## Integrating 3rd party apps
https://facebook.github.io/react/docs/integrating-with-other-libraries.html
1. Integrating With jQuery plugin - https://facebook.github.io/react/docs/integrating-with-other-libraries.html#integrating-with-jquery-chosen-plugin
2. Google Analytics in React - https://github.com/react-ga/react-ga
2. Stripe Checkout in React - https://github.com/azmenak/react-stripe-checkout
3. D3 in React https://github.com/emeeks/d3_in_action_2/tree/master/chapter9/reactd3 (D3 in React) Blog link: https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71

## Hyperapp Reusable components
1. Create a partial list of awesome-react-components: https://github.com/brillout/awesome-react-components
2. React-Bootstrap https://react-bootstrap.github.io/

---

[[Source]](https://github.com/rajaraodv/hyperapp-examples)

**Comment by okwolf** [comment]
@rajaraodv thanks for getting the ball rolling on this! Other sources of inspiration we could look to are the [Elm examples](http://elm-lang.org/examples) and [Vue.js examples](https://vuejs.org/v2/examples).

**Comment by JorgeBucaran** [comment]
@rajaraodv I feel this should be a check list, otherwise this issue will stay open forever.

**Comment by 1zaak** [comment]
+1 for Graphql example

**Comment by webeli** [comment]
I found the examples over at [next.js](https://github.com/zeit/next.js/tree/canary/examples) very helpful when i started out. I feel alot of times i don't need to see the result of it, just some example code of how to get started with different implementations.

**Comment by okwolf** [comment]
We have [`hyperapp/awesome`](https://github.com/hyperapp/awesome) for cataloging example apps already built with Hyperapp. What I think we need is a list of example apps **not** yet built but that we would _like_ to see built with Hyperapp. Maybe even come up with some non-monetary bounty incentive. 🤔

**Comment by JorgeBucaran** [comment]
Free Hyperapp stickers and random Japanese gift.

**Comment by ismamz** [comment]
Hi @JorgeBucaran! I have seen that you are working on improving the documentation. I have also seen that you have created a [`awesome` list](https://github.com/hyperapp/awesome) and you have examples in [Codepen](https://codepen.io/hyperapp/) that are not linked in that list. I have created two examples that I saw in this thread and were not created yet: [Markdown Editor](https://codepen.io/ismamz/pen/wpNvmy) (nice example of `dangerouslySetInnerHTML`) and [Emoji Search](https://codepen.io/ismamz/pen/ppGMWM).

I would like to be able to add these examples to the documentation, but I am not clear about the guidelines to do it. Would it be nice to add them in a list of examples in [`hyperapp / awesome`](https://github.com/hyperapp/awesome)? Or maybe on [Tutorials section](https://github.com/hyperapp/hyperapp/tree/master/docs/tutorials)?

**Comment by JorgeBucaran** [comment]
@ismamz Let's add them to hyperapp/awesome, can you create a PR there?

To add the examples to the tutorials section, perhaps start with one, write the tutorial, create the PR and we'll review it. Sounds good? 😄

**Comment by ismamz** [comment]
Perfect! I've added examples to the `awesome` list.
I could start writing a tutorial, if you find it useful.

**Comment by JorgeBucaran** [comment]
@ismamz Rather than another tutorial, I'd like to add documentation for currently undocumented concepts like slices, modules, etc. So, IMO a more useful contribution would be to write an original tutorial and publish it on your blog, gist, GitHub, etc. 

What do you think? :)

**Comment by ismamz** [comment]
I think it's a good idea!

**Comment by zaceno** [comment]
Here's a (quite simple) example app written with Hyperapp https://github.com/zaceno/happy

**Comment by zaceno** [comment]
Oh and since someone mentioned Tetris, here's a start if someone wants to finish it (needs scoring, levels, main menu, prettiness...)
https://codepen.io/zaceno/pen/JreKPN?editors=0010

**Comment by JorgeBucaran** [comment]
Let's see what we have accomplished so far. We have [better documentation](https://github.com/hyperapp/hyperapp/blob/master/README.md). We have a [CodePen](https://codepen/hyperapp) with basic examples and a Medium Publication [Hyperapp Vox Populi](https://medium.com/hyperapp). 

We also have an unofficial [LearnHyperapp](https://github.com/LearnHyperapp) by @mrozbarry, if you want to join Alex in that adventure, all you need is ask him to add you as a collaborator of that organization.

We are on Twitter, follow  [@HyperappJS](https://github.com/HyperappJS) for news and announcements. If you make something cool with Hyperapp and want exposure, <samp>@</samp>mention us. You can also share it on [/r/Hyperapp](https://www.reddit.com/r/hyperapp) or submit it to [hyperapp/Awesome](https://github.com/hyperapp/Awesome).

It's not much, but it's a solid start.
