### ISSUE TITLE
Improve Mixins doc

### ISSUE THREAD

**Issue by rajaraodv** [hyperapp/hyperapp#374]
Mixins are very versatile in Hyperapp. [Mixins doc](https://github.com/hyperapp/hyperapp/blob/master/docs/mixins.md#mixins ) are used to perform various things says the following: "Use mixins to encapsulate your application behavior into reusable modules, to share or just to organize your code." But there are not much examples of how to use it to:

1. Encapsulate application's behavior into reusable modules
2. Integrate with 3rd party (May be something [like this](https://github.com/lukejacksonn/hyperapp-firebase-auth/tree/master/src))

**Comment by zaceno** [comment]
Agree, the mixin docs mostly show off the versatility and what *can* be done. But don't really present any examples of how they can be used to structure your code.

On the other hand an example which adequately demonstrates how to separate concerns of a complex app, using mixins, would necessarily be a quite complex (and hence not very helpful) example. So it's a tough problem.

@lukejacksonn s firebase auth is a good example to link to!

Another good example of a mixin, which definitely should be mentioned, is @hyperapp/router. It is implemented as a mixin. It encapsulates state, actions & events (it even triggers custom events). And it even exports components.
