### ISSUE TITLE
Support Lazy Loading (Dynamic Import)

### ISSUE THREAD

**Issue by selfup** [hyperapp/hyperapp#379]
Just an issue to talk about supporting lazy loading mainly for webpack users 🎉 

Seems **rollup** is not intending on supporting lazy loading after all: https://github.com/rollup/rollup/issues/557#issuecomment-210096228

_One day!_ 🎉 

Mentioned here: https://github.com/hyperapp/hyperapp/issues/244#issuecomment-329909681

**Comment by infinnie** [comment]
My own non-webpack non-rollup implementation of lazily loaded components: https://github.com/infinnie/infinnie.github.io/issues/11

**Comment by infinnie** [comment]
See also #363

**Comment by JorgeBucaran** [comment]
Is this related to https://github.com/hyperapp/hyperapp/issues/439?

**Comment by JorgeBucaran** [comment]
@selfup Ping.
