### ISSUE TITLE
Modernize

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#38]
⚠️ **A decision was made. See the [aftermath](https://github.com/hyperapp/hyperapp/pull/48#issuecomment-277988927).**

---

@maraisr Summarizing the discussion in #29, #30, #31 and #32 we'd like to modernize the code base to use more ES6 idioms and introduce webpack to bundle the distribution.

### Rationale

* Using more ES6 idioms may encourage more contributions.

* Using more ES6 idioms means a smaller bundle for users targetting really modern browsers. For example, in production users may consume our `src` directory directly with their application and don't babelify (or maybe babelify a _some_ things via plugins) and use something like babili to minify modern JavaScript. This means even smaller bundles.

* Other than prototyping, examples, presentations and maybe even real small-ish apps, users will want to bundle their apps using a bundler like browserify, webpack, rollup, etc.

**Comment by jbucaran** [comment]
@SkaterDad There was no consideration since I'm not versed particularly in either rollup or webpack , but I'll take whichever can produce smaller bundles.

**Comment by tunnckoCore** [comment]
Btw, I don't think `iife` is the right thing.

**Comment by SkaterDad** [comment]
@tunnckoCore I used `iife` in that config since @jbucaran had Webpack outputting something similar.

Since that bundle is for the browser, I think it's correct (per [this tutorial](https://code.lengstorf.com/learn-rollup-js/)).

I've heard it said before that Rollup is a great choice for library authors.  Vue.js uses it with Buble (instead of Babel).

**Comment by jbucaran** [comment]
@tunnckoCore We've actually got a smaller bundle, so I'd like to think the current setup is a step in the right direction. @SkaterDad I'd really like to give rollup a try though. Can you help with this?

**Comment by tunnckoCore** [comment]
@jbucaran @SkaterDad I use Rollup + Buble everywhere every day too. It is just amazing combo. But in some cases it is not cool, because Buble adds more bytes as needed - I'm fighting that today and end up just to not use buble haha and write vanilla es5. In my current case 50-100 bytes is important - because the promo slogan. Here if use Rollup + Buble the case would be the same, because of the [app.js#L152-L169](https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L152-L169).

**Comment by jbucaran** [comment]
@tunnckoCore Totally! Try to make the bundle smaller 🙏

**Comment by SkaterDad** [comment]
Sounds like @tunnckoCore  is the right guy for the PR.  I've only been playing with Rollup since this morning.

I was able to change my config to use `buble`, though, and it saved ~0.34 KB compared to the Babel w/ ES2015 preset once minified.

The nicest part is it took zero options!
```javascript
import buble from 'rollup-plugin-buble'
import uglify from 'rollup-plugin-uglify';

export default {
  entry: 'src/app.js',
  plugins: [
    buble(),
    uglify()
  ],
  targets: [
    {
      dest: 'dist/app.buble.js',
      format: 'iife',
      moduleName: 'app',
      sourceMap: true
    }
  ]
};

```

For the standalone `app.js` build, here are more exact savings.
Webpack -> Babel w/ ES2015 & Babili presets -> Uglify = 3873 chars.
Rollup -> Babel ES2015 preset -> Uglify = 3443 chars.
Rollup -> Buble -> Uglify = 3078 chars.

I'll run the whole index.js through it now.

**Comment by jbucaran** [comment]
@SkaterDad Are you including `html.min.js` as well right?

In the future you may want to use https://www.npmjs.com/package/yo-yoify so you only include `h` or bable/buble for JSX.

**Comment by SkaterDad** [comment]
The build I'm talking about in my posts is just replicating your library bundle `app.min.js`.

Using yo-yoify for a client app build is definitely a good idea, but outside the scope of this thread, I think.

**Comment by jbucaran** [comment]
@SkaterDad Yes, indeed, my bad for losing the thread of the conversation haha.

**Comment by tunnckoCore** [comment]
@jbucaran yo-yoify is cool, but is part of the Browserify stack, so I don't see how we can integrate it if we use Rollup/Webpack.

**Comment by SkaterDad** [comment]
@tunnckoCore I don't think he was saying to use it in the library bundles, but for the end users.

In my own apps, I'm more likely to just use raw `h` function calls anyway.  One less dep to introduce bugs.

**Comment by tunnckoCore** [comment]
I know that. But it can't be integrated in our dev flow, because we are using Webpack/Rollup. ;d

**Comment by jbucaran** [comment]
@tunnckoCore I'm talking about consumers / users using yo-yoify, not us.

**Comment by jbucaran** [comment]
@maraisr Maybe you can look into this? Rollup instead of webpack thing. Specially if it means less or no configuration at all.

**Comment by tunnckoCore** [comment]
Yea it means. :) I can start it soon.

**Comment by jbucaran** [comment]
@SkaterDad How did you get rollup to create multiple bundles? We have to generate one for each file h, html, app and a big one with everything too.

**Comment by tunnckoCore** [comment]
I believe there is no support for such thing currently. We will need separate `rollup.config.js` files. Convention is to have `build` dir with few rollup configs.

**Comment by terkelg** [comment]
I'd vote for Rollup too. I spent a lot of time comparing them a month ago, and Rollup does indeed produce smaller bundles and it's way simpler to configure. In my opinion webpack is a bit overkill for this project, where the purpose is to keep it simple and tiny.

**Comment by jbucaran** [comment]
@tunnckoCore I'm trying to cram everything in a one liner, so that I can just put everything in package.json.

**Comment by SkaterDad** [comment]
@jbucaran This issue on Rollup's repo discusses the options: https://github.com/rollup/rollup/issues/703

Simplest thing might be to create a `build.js` or something, and just programmatically run Rollup.

**Comment by jbucaran** [comment]
@tunnckoCore How can I call rollup in the cli and specify plugins?

**Comment by maraisr** [comment]
Not sure if either of you are aware - but webpack recently had a massive rewrite. So I'd argue todo another comparison. But even then, I'd go webpack over rollup... you don't wanna box yourself in now with a tool that's limited in flexibility.

**Comment by jbucaran** [comment]
@maraisr Smallest bundle wins.

**Comment by maraisr** [comment]
It's great and all.... but what about in the future when we want optional imports, like ssr. Feel like we're gonna spend more time getting roll up todo what we want it too.... oh well. Maybe there's value.... who knows. All I'll have to say is, you want a tool with a solid community, solid Eco system, and something that makes it almost unusable if you wanna try cli. CLI is bad. You'll find the larger a project gets, and the more contributes you get, you'll start to favour readability.

**Comment by jbucaran** [comment]
@maraisr HyperApp should not get larger by principle. It should remain simple. I want to start building stuff with HyperApp, not continue to build HyperApp ad infinitum.

What do you mean by optional imports?

**Comment by maraisr** [comment]
Just use it. You're the author, you ultimately have final say. Let's just agree to disagree?

**Comment by maraisr** [comment]
And to answer your other question, Yes, I'll migrate to rollup, and amend this PR. Give me 2 hours, gotta get ready for work.

**Comment by tunnckoCore** [comment]
Btw, ES2015-ing also brings more bytes to the final bundle. :D 

Because things like that

```js
const defer = (fn, data) => {
  setTimeout(_ => fn(data), 0)
}
```
a lot smaller would be if it is just defined as function

```js
function defer (fn, data) {
  setTimout(() => {
    fn(data)
  })
}
```
just think a bit. So arrows should be used only when it make sense not just for the sake of ES6.

**Comment by maraisr** [comment]
With this - I mean like, you may as well use proper function statements and not const everything

**Comment by jbucaran** [comment]
@tunnckoCore I can't repro this. Rollup generates a smaller bundle size for the first example using both arrow functions, what did I miss?

**Comment by jbucaran** [comment]
Smallest.

```js
	const defer = (fn, data) => {
		setTimeout(_ => {
			fn(data)
		}, 0)
	}
```

**Comment by tunnckoCore** [comment]
Doesn't make sense. Just think a bit. :) In ES2015 (first case / you "smallest") there would have `var` and `return`. Try that


defer.js
```js
// defer1.js
// const defer = (fn, data) => {
//   setTimeout(() => fn(data), 0)
// }

// defer2.js
// function defer () {
//   setTimeout(() => {
//     fn(data)
//   }, 0)
// }

// defer3.js
const defer = (fn, data) => {
  setTimeout(_ => {
    fn(data)
  }, 0)
}

export default defer
```

and rollup config: buble + uglify plugins

```js
const buble = require('rollup-plugin-buble')
const uglify = require('rollup-plugin-uglify')

module.exports = {
  plugins: [
    buble(),
    uglify({ compress: { warnings: false } })
  ]
}
```

cli

```
rollup -c -f iife -n defer -i defer.js -o dist/defer1.js
rollup -c -f iife -n defer -i defer.js -o dist/defer2.js
rollup -c -f iife -n defer -i defer.js -o dist/defer3.js

ls -al dist
```

output

```
-rw-r--r-- 1 charlike users  106 Feb  7 09:37 defer1.js
-rw-r--r-- 1 charlike users   95 Feb  7 09:37 defer2.js
-rw-r--r-- 1 charlike users  100 Feb  7 09:38 defer3.js

```

**Comment by lukeed** [comment]
@jbucaran If you're aiming for smallest bundle size (I know you are 😉) go with Rollup & Bublé. With only quick glances, I see nothing in Hyperapp that inhibits this combo.

Webpack has a future goal of beating Rollup in footprint size, but they have a way to go.
Bublé is always the right choice.

**Comment by jbucaran** [comment]
@lukeed The source is now pretty much ES3 + CommonJS, with a few ES5 idioms, probably Array.isArray is the only once, which is okay.

And, yes we ended up going with rollup, which yielded the smallest bundles.

Closing as this information is already out dated.

* Related: **EDIT: A decision was made. See the [aftermath](https://github.com/hyperapp/hyperapp/pull/48#issuecomment-277988927).**
