### ISSUE TITLE
Rendered view is appended to the `root` element instead of replacing its contents

### ISSUE THREAD

**Issue by benchristel** [hyperapp/hyperapp#387]
I noticed that when a hyperapp app initializes, the rendered view is appended to the `root` element, leaving any existing content in place. I kind of expected it to replace the existing content. Doing that would allow stuff like showing the user an informative message if the app code fails to run:

```html
<!-- index.html -->
<div id="root">
Please ensure you've enabled JavaScript and your browser is up to date.
</div>
```

```javascript
// main.js
app({
  root: document.getElementById('root'),
  /* ... */
});
```

Any chance the rendering behavior can be changed so the view completely replaces the content of the `root` element?

**EDIT**: Currently, I'm working around this by doing

```javascript
events: {
    load: function() {
      document.getElementById('root').innerHTML = ''
    }
  }
```

**Comment by JorgeBucaran** [comment]
@benchristel The current behavior is consistent with React, so may I ask how would you accomplish the same thing in React? 🤔 

The idea is to get the discussion going.

**Comment by zaceno** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

Would work for part of that case (JavaScript turned off)

**Comment by benchristel** [comment]
@JorgeBucaran In React I'd probably do something similar to the workaround in the OP: before the first render of the root component, empty out the container. It would be slightly awkward, but not too bad.

@zaceno Yeah, `<noscript>` is the way to go for that use case. But other similar cases may not work (e.g. there's a runtime error that prevents the app from rendering).

My actual use case is a bit more complicated, though. I want `app()` to be idempotent because I'm building local apps that store state by saving the DOM and the `state` object to disk. This means that `app()` will potentially be called many times over the lifetime of one DOM as the app is persisted and reloaded. I want the rendered HTML to show the view of only the latest invocation of `app()`, and if I don't use the load-event workaround I see a list of dead app views in addition to the real view.

A [demo](https://druidic.github.io/web-quine-save-bug/) is probably worth a thousand words in this case.

This is obviously not a typical use case, though, so if there aren't other reasons for `app()` to be idempotent and it's desirable to stay close to React's behavior, I'll close this issue.

One reason I can think of for keeping the existing behavior: if someone wants to have multiple apps running in the same root element, having them overwrite each other's view would be surprising.

**Comment by JorgeBucaran** [comment]
> @benchristel One reason I can think of for keeping the existing behavior: if someone wants to have multiple apps running in the same root element, having them overwrite each other's view would be surprising.

This is not as uncommon as you'd think, but I personally would architect my apps so that I only need one.

Don't close this, as I feel this is an issue that deserves more attention and I'd like to hear what other people think as well.

/cc @ngryman @SkaterDad @lukejacksonn

**Comment by okwolf** [comment]
I suspect the reason React originally went this way is to enable their whole story around incremental adoption, and Hyperapp could benefit from the same use case. You should be able to try Hyperapp out for an isolated new feature in an existing app as long as that app doesn't touch the element we append to the root.

**Comment by andyrj** [comment]
@benchristel so the reason we did it this way is to support these two use-cases:

1.  if no root is defined, append to body and do not worry about removing anything already present in render target.
2. if root is specified, we assume your load event will return node, which allows for hydration of SSR.  So if you want it to clear out your content with just what you expected to render you should do something like the following.  

```
function hydrate(element) {
  return element
    ? {
        tag: element.tagName.toLowerCase(),
        data: {},
        children: [].map.call(element.childNodes, function(element) {
          return element.nodeType === 3 ? element.nodeValue : hydrate(element);
        })
      }
    : element;
}

app({
  events: {
    load(state, actions, node) {
      return hydrator(document.getElementById('root'));
    }
})
```

This will allow our initial patch to be aware of your pre-existing dom and prevent the duplicated stale view  problems.

**Comment by ngryman** [comment]
As @okwolf pointed out, HyperApp should be able to share its space with others. We don't want a toddler here 👶.

**Comment by JorgeBucaran** [comment]
@benchristel What other frameworks are you familiar with and how do they behave?

**Comment by JorgeBucaran** [comment]
@ngryman Hyperapp can share space with others, if you give it a root node.

**Comment by ngryman** [comment]
@JorgeBucaran Implicitly saying that we want to keep it that way 😉

**Comment by JorgeBucaran** [comment]
@benchristel The next version will be have as you expected. 🎉

**Comment by benchristel** [comment]
@andyrj Thanks for the explanation!

@JorgeBucaran oh, okay! Thanks!

Out of curiosity, what influenced your decision to change it? (Since I never provided an example of another framework that works this way, I assume it wasn't me 😄 )

**Comment by JorgeBucaran** [comment]
> @benchristel what influenced your decision to change it?

This way we can provide hydration by default. Since we take over your root, we can make assumptions about it, like, if it has any children we assume those were server side rendered and attempt to hydrate nodes.

**Comment by Swizz** [comment]
What abous users who will put their `<script>` into the body instead of using `defer` ?
They will be affected by this new feature ?

**Comment by JorgeBucaran** [comment]
@Swizz They will need to:

1) Provide a `root`, or
2) Put them on their head using defer async.

**Comment by Swizz** [comment]
So the Hello World example is outdated https://github.com/hyperapp/hyperapp/blob/master/docs/README.md#hello-world

**Comment by JorgeBucaran** [comment]
@Swizz Yes, will fix it. 🙇

**Comment by JorgeBucaran** [comment]
@Swizz Yes, will fix it. 🙇

EDIT: Actually, no need to fix anything, because it works, so might leave it as is just for simplicity. What do you think?

**Comment by Swizz** [comment]
It depends are we gonna encourage the use of `defer`/`async` ?

There is absolutly no risk to use it like it is in the example ?

> They will need to:
>
> Provide a root, or
> Put them on their head using defer async.
