### ISSUE TITLE
Reorganize the dom diffing

### ISSUE THREAD

**Issue by tunnckoCore** [hyperapp/hyperapp#39]
I mean, it would be better to separate/reorganize the dom diffing "algorithm". Currently it works "by reference", so I think it would be better to be something like `patch(newNode, oldNode)` which would return the updated element.

I'm playing with this last days. And especially built something similar from scratch - 900bytes gzipped, without the `html` thing - it can be anything from custom to `bel`. Anyway, I'm just playing and currently I'm using `nanomorph`.

edit: hope you get what I'm talking about, haha.

**Comment by jbucaran** [comment]
@tunnckoCore Do you mean change the order of the arguments?

**Comment by jbucaran** [comment]
@tunnckoCore Nothing actionable here. Would love to simplify the DOM diffing even more tho.

**Comment by tunnckoCore** [comment]
I actually did it before few days. Decoupled everything to separate local file module. Diffing is ~300-400 bytes.

It looks like

```js
const microdiff = require('./microdiff')
const update = microdiff(root, 0)

// update later is used in the `onRoute` like that
// signature newEl, oldEl
update(view(model, actons), el)
```

But anyway :) I'll come up with something soon.

**Comment by jbucaran** [comment]
PR welcome.

**Comment by tunnckoCore** [comment]
Damn, my fault, bad mind. it is 650, with umd and soucemap comment.

> PR welcome

yea
