### ISSUE TITLE
What if a certain element gets changed when the component that generates it changes, but the oncreate callback does not get called?

### ISSUE THREAD

**Issue by infinnie** [hyperapp/hyperapp#393]
Say:
```jsx
var Component = function () {
    return <div oncreate={
            function () { /* do something that never gets called? */ }
        }>Some text</div>;
};
app({
    root: document.body,
    view: function (state, actions) {
        return state.condition ? <div class="clickable" onclick={actions.change} /> : <Component />;
    },
    state: {
        condition: true
    },
    actions: {
        change: function () {
            return {
                condition: false
            };
        }
    }
});
```

Would the `oncreate` callback ever get called?

**Comment by andyrj** [comment]
I would say use onupdate here...  But that seems like a contrived example, if some one is going to do this, and not have a different tag or add a key, to cause oncreate to fire, I think it's on them really.  Just my 2 cents.  I suppose we could special case oldNode not having oncreate, and node having it in patch though.

**Comment by JorgeBucaran** [comment]
@infi See the [keys gotchas](https://github.com/hyperapp/hyperapp/blob/master/docs/keys.md#gotchas) from the docs and let me know if that helps.

**Comment by infinnie** [comment]
@JorgeBucaran What if a solution to #362 just supports keys?!

**Comment by JorgeBucaran** [comment]
@infinnie Do you want to give it a shot?

**Comment by infinnie** [comment]
Maybe it would then be required that you reopen #366.

**Comment by JorgeBucaran** [comment]
@infinnie My rationale for closing that issue hasn't changed.

With regards to your view, why don't you just rewrite it like this?

```js
function view(state, actions) {
  return  (
    <main>
      {state.condition ? <div class="clickable" onclick={actions.change} /> : <Component />}
    </main>
  )
}
```

**Comment by infinnie** [comment]
BTW: The example code in https://github.com/hyperapp/hyperapp/blob/master/docs/keys.md mutates the argument passed in.

**Comment by JorgeBucaran** [comment]
@infinnie Which one? There are two.

**Comment by JorgeBucaran** [comment]
@infinnie Ah, `sort`? Whoops.

**Comment by infinnie** [comment]
However, it is not always possible or desirable to wrap them in (yet) another DOM layer. What if the root were a list, a table, or a flex?

**Comment by JorgeBucaran** [comment]
> @infinnie What if the root were a list, a table, or a flex?

Whatever your application's root element is, you can always do this:

```html
<main>
  <!-- Put whatever you want here -->
</main>
```
