### ISSUE TITLE
could you show rollup config file?

### ISSUE THREAD

**Issue by a13821190779** [hyperapp/hyperapp#396]
if you want, please

**Comment by JorgeBucaran** [comment]
@a13821190779 Hi! Sure.

- [Boilerplate: hyperapp + jsx + rollup + buble minimal](https://gist.github.com/JorgeBucaran/f714dd6d64041591e5e53dbff8558439).
- [Boilerplate: hyperapp + jsx + rollup minimal](https://gist.github.com/JorgeBucaran/0c0da8f1256a0a66090151cfda777c2c)

Hope it helps. 👋

**Comment by lukejacksonn** [comment]
@a13821190779 there is also a few project starter boilerplates on [awesome-hyperapp](https://github.com/hyperapp/awesome-hyperapp).

The one I use (with a rollup config) and maintain is **[hyperapp-pwa](https://github.com/lukejacksonn/hyperapp-pwa)**.

**Comment by a13821190779** [comment]
excuse me, how are you minigy html code?
I find long time but no itme

**Comment by lukejacksonn** [comment]
@a13821190779 there is no minification of HTML in these pipelines. In `hyperapp-pwa` there is very benefit of doing so. However all javascript (including views written with `h` or `JSX`) and all styles get bundled and minified by `rollup-plugin-uglify`.

**Comment by a13821190779** [comment]
but ```rollup-plugin-uglify``` minify js only, all right, I will try it one mone time, hope done and thank you

**Comment by lukejacksonn** [comment]
@a13821190779 why do you want to minify HTML?

**Comment by a13821190779** [comment]
habit, even the speed is slightly improved, worth it

**Comment by lukejacksonn** [comment]
I see.. well I tried minifying the `index.html` from `hyperapp-pwa` out of curiosity and it saves **~58 bytes**. Not sure this is going to make much difference to perf (especially when gzipped) but let me know if you find a rollup solution!

> Original (820b)
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>hyperapp-pwa</title>
    <meta name="description" content="A minimalist progressive web app compliant template for hyperapp projects">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#ffffff">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="manifest" href="/manifest.json">
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/icons/favicon.png">
  </head>
  <body></body>
  <script src="/index.js"></script>
  <noscript>Enable JavaScript</noscript>
</html>
```

> Minified (762b)
```
<!DOCTYPE html><html lang="en"> <head> <meta charset="utf-8"> <title>hyperapp-pwa</title> <meta name="description" content="A minimalist progressive web app compliant template for hyperapp projects"> <meta name="viewport" content="width=device-width, initial-scale=1"> <meta name="mobile-web-app-capable" content="yes"> <meta name="apple-mobile-web-app-capable" content="yes"> <meta name="theme-color" content="#ffffff"> <meta http-equiv="x-ua-compatible" content="ie=edge"> <link rel="manifest" href="/manifest.json"> <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png"> <link rel="icon" type="image/png" href="/icons/favicon.png"> </head> <body></body> <script src="/index.js"></script> <noscript>Enable JavaScript</noscript></html>
```
