### ISSUE TITLE
0.14.0 breaks the use of CSS Modules?

### ISSUE THREAD

**Issue by johanalkstal** [hyperapp/hyperapp#402]
I have a simple app in progress @ https://github.com/johanalkstal/faceoff-client

Updating Hyperapp from `0.12.1` to `0.14.0` breaks the use of CSS Modules through Webpack.

Before, all styles are rendered. After, all elements are rendered without any CSS classes applied.

The only change I do is update the version of Hyperapp and change the following code,

```
// 0.12.1 main.js
const emit = app({
  actions,
  events,
  root,
  state,
  view
})

// Starts the router and passes it a callback to call when routes are matched.
start((view) => emit('updateView', view), state)
```

```
// 0.14.0 main.js
const { updateView } = app({
  actions,
  root,
  state,
  view
})

// Starts the router and passes it a callback to call when routes are matched.
start((view) => updateView(view), state)
```

**Comment by JorgeBucaran** [comment]
@johanalkstal Sorry, I am not familiar with webpack, so I don't know what could be causing this problem. Can you make a simple demo without using webpack, preferably a CodePen that shows the issue?

**Comment by JorgeBucaran** [comment]
I think this is a bug in https://github.com/hyperapp/html caused by them having not upgraded yet to 0.14.0 in which the `VNode` API changed from {tag,data,children} to {tag,props,children}.

/cc @Swizz @lukejacksonn

**Comment by johanalkstal** [comment]
I can add that using `h` instead of `@hyperapp/html` works perfectly, so it is definitely an issue with `@hyperapp/html`.

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/html/issues/2
