### ISSUE TITLE
Uncaught TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by kenota** [hyperapp/hyperapp#404]
Here is  [codepen](https://codepen.io/anon/pen/oGEQBY) triggering the issue.

Steps to reproduce:
1. Launch code pen
2. Open Chrome developer tools console
3. Type one character in the textarea => observe error log in chrome developer tools console.

Seems to be happening only for first character, but I am having similar problems with textfields. 

Update:
This error is happening on Chrome Version 61.0.3163.100 (Official Build) (64-bit), on Mac

**Comment by johanalkstal** [comment]
I got `x.props is undefined` on first keystroke.

**Comment by kenota** [comment]
@johanalkstal which browser did you use?

**Comment by johanalkstal** [comment]
@kenota Firefox

**Comment by lukejacksonn** [comment]
I am looking now 👀  not sure I have permissions to update the pen if I fix it though

**Comment by lukejacksonn** [comment]
Humm.. that is weird. Couldn't pin down exactly what it was.. I created a fork that does (similar) to what I thought you were trying to achieve. Similar pattern of updating an item in a nested state object. I took the `map` level out so it is just a list, no errors https://codepen.io/lukejacksonn/pen/LzQqGa. Let me know if you figure anything out. 

@JorgeBucaran codepen wasn't picking up sourcemaps which makes it hard to debug this sort of thing, not 100% sure why they aren't working but I will try to look into it.

**Comment by lukejacksonn** [comment]
Weird.. if you change the `textarea` to an input with a `value` then it works as expected. 

- https://codepen.io/lukejacksonn/pen/LzQqGa

**Comment by kenota** [comment]
@lukejacksonn Good catch! I am able to narrow it down, it seems that issue happening when you update text in tag from being empty. See updated codepen:

* [https://codepen.io/anon/pen/oGEQBY](https://codepen.io/anon/pen/oGEQBY)

If you remove code `{comment.body}` inside `<p>` then error disappears

**Comment by JorgeBucaran** [comment]
@kenota The good news is that this problem does not occur with [0.12.1](https://unpkg.com/hyperapp@0.12.1/dist/hyperapp.js), which means the fix must not be so difficult (I hope).

If you use 0.12.1 in that CodePen and change the action provisionally to:

```js
state.comments.map[id].body = newText;
console.log('updating text to ', newText);
return state
```

There's no error. That's how I know that the code works in 0.12.1.

**Comment by kenota** [comment]
@JorgeBucaran thank you for suggestion.  

Tbh, I was using 0.12.1 but decided to update to 0.14.0 to use sliced state 😄

**Comment by JorgeBucaran** [comment]
@kenota Sweet. I'll fix this ASAP.

**Comment by kenota** [comment]
@JorgeBucaran wow! In no way I wanted to put pressure on you on the weekend!

**Comment by JorgeBucaran** [comment]
@kenota I found the problem. I introduced a bug in the definition of `getKey`, for no good reason.

The function should be written as:

```js
function getKey(node) {
  if (node && node.props) {
    return node.props.key
  }
}
```

...which actually compresses to 1 byte less! 🎉 

I'll push this later with other minor fixes I am working on at the moment.

<img width="1218" alt="screen shot 2017-10-08 at 2 47 57" src="https://user-images.githubusercontent.com/56996/31310429-1f0cf404-abd3-11e7-8068-52223215cd64.png">

**Comment by kenota** [comment]
@JorgeBucaran 👍 great! I have patched my current version in node_modules with correct getKey -- works like charm. Feel free to close the issue once you push the code.

**Comment by JorgeBucaran** [comment]
@kenota Thanks! Will do.

**Comment by JorgeBucaran** [comment]
Fixed in master! I can't publish a new version right now, but I will get around that soon. 🎉😄
