### ISSUE TITLE
Props null when calling components with Jsx

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#407]
Imagine the following code:
```javascript
const Hello = ({ name = 'world' }, children) => {
  return <div>Hello {name}!<div>
}

app({
  view: () => <Hello />
})
```
When ran, it throws an error because undefined cannot be destructured into `{ name = 'world' }`.

This can be fixed by changing `h.js`:
```javascript
return typeof tag === "string"
    ? // ...
    : tag(props = {}, children)
```

Is this a bug or is it an intentional design decision?

**Comment by JorgeBucaran** [comment]
@Mytrill `: tag(props || {}, children)`

Yes, you found a bug! 😄 🏄

**Comment by Mytrill** [comment]
Will try to push a fix now.
