### ISSUE TITLE
Enhance typescript definitions

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#409]
Several pieces are missing from the typescript definitions:
- [x] proper definition for Thunk (with types for arguments & return type) + example (done in #412)
- [ ] jsx namespace: intrinsic elements + example
- [ ] lifecycle events on VNode + example
- [x] proper definition of module + example
- [x] proper definition of init() + example

If anyone has any other idea, I'll add to this list.

Update: removed HOA, added modules and init.

**Comment by pspeter3** [comment]
Where would you like to work on this?

**Comment by Mytrill** [comment]
Thanks for #412!

I will work next on the definition for HOAs + an example.
Hopefully I will have some time tomorrow/Wednesday.

**Comment by JorgeBucaran** [comment]
Bring it on! 🎰 😄

**Comment by pspeter3** [comment]
I think at this point we can drop HOAs. I also think the JSX typing can be done another time. Init and Modules are more important.
