### ISSUE TITLE
Pass root in second argument to app().

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#410]
The proposal is to remove the app's `root` property and do the same passing it in the second argument to app().

### Before
```jsx
app({  init, view, state, actions, root }) 
```
### After
```jsx
app({ init, view, state, actions }, root) 
```

e.g.

```jsx
app(
  { 
    init, 
    view, 
    state, 
    actions 
  }, 
  document.getElementById("app")
)
```

**Pros**

- Make app() props have to deal only with the state management side of things.
- Other libraries often do the same, e.g., P/React's `render(elm, root)`, Elm's `Elm.Main.embed(root)`, mithril's `m,mount(document.body, Counter)` (the order is reversed here though), Vue's `$mount`, etc.

**Cons**

- There is nothing wrong with the current way of doing things.
- Adds like 10 bytes.
- Complicates the signature of HOAs. Thanks @okwolf.

**Comment by okwolf** [comment]
@JorgeBucaran how would this work with HOAs? Would they need to accept multiple args as well, and call the `app` function with both the `props` and `root`?

**Comment by JorgeBucaran** [comment]
@okwolf Oh, I didn't think about it. I am starting to dislike this proposal haha.

**Comment by pspeter3** [comment]
You could possibly separate the app factory and the render factory.

**Comment by SkaterDad** [comment]
I think the current API works well.  It's nice and clean.

**Comment by lukejacksonn** [comment]
I don't expect many people will actually include a `root` prop that often anyway, but instead let it fallback to default (`document.body`). I like the idea but the cons seem to outweigh the pros.

**Comment by JorgeBucaran** [comment]
Thanks everyone! I'll keep things the way they are. 👍

**Comment by JorgeBucaran** [comment]
Now, with HOA builtin support pushed to userland, we can revive this and as per discussion on Slack, implement it.

**Comment by SkaterDad** [comment]
Out of curiosity, what's the benefit of this change?  I can't access Slack from work to read the conversation.

**Comment by JorgeBucaran** [comment]
Now, with HOA builtin support pushed to userland, we can revive this and as per discussion on Slack. Shall we implement it?

**Comment by pspeter3** [comment]
I prefer it but I do think we should have principles for why to answer @SkaterDad

**Comment by JorgeBucaran** [comment]
The real (not really) question is, how do we feel about formatters like prettier making the code this:

```js
app(
  { 
    init, 
    view, 
    state, 
    actions 
  }, 
  document.getElementById("app")
)
```

**Comment by JorgeBucaran** [comment]
@SkaterDad The convo was basically that since builtin HOA support is out, and:

> Complicates the signature of HOAs. Thanks @okwolf.

...was one of the reasons to turn this down, we can implement it now. Preact/React/Inferno users trying Hyperapp will feel at home and we can save some bytes too.

**Comment by pspeter3** [comment]
I still want to make sure we have consistent reasoning for API changes. As we approach 1.0, the API will become locked.

**Comment by JorgeBucaran** [comment]
Well, let's approach it this way. What's not to like about

```js
app(props, container)
```

```
app(
  { 
    init, 
    view, 
    state, 
    actions 
  }, 
  document.getElementById("app")
)
```


```js
app({ init, view, state, actions }, document.getElementById("app"))
```

**Comment by okwolf** [comment]
@JorgeBucaran FYI this also breaks your [`compose`](https://gist.github.com/JorgeBucaran/53d4c14c15392ff2ed59afbed7e59ce7) function.

**Comment by JorgeBucaran** [comment]
@okwolf Thanks, I'll update it.
