### ISSUE TITLE
Cursor location calculations messed up for the past couple of days 

### ISSUE THREAD

**Issue by guy-kdm** [hyperapp/hyperapp#416]

**Comment by zaceno** [comment]
@guy-kdm I think you posted that issue in the wrong repo :) Perhaps you meant: https://github.com/zeit/hyper

**Comment by guy-kdm** [comment]
haha immediately noticed dammit :)

**Comment by zaceno** [comment]
np

**Comment by zaceno** [comment]
@guy-kdm lol don't worry bout it. But, if by chance you make websites, why not stick around and try out hyperapp ;)
