### ISSUE TITLE
Issue with actions re-using the state

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#418]
The following unit test fails due to infinite recursion:
```javascript

test("Recursive state", done => {
  app({
    view: state =>
      h(
        "div",
        {
          oncreate() {
            console.log(document.body.innerHTML)
            expect(document.body.innerHTML).toBe(`<div>{"child":{}}</div>`)
            done()
          }
        },
        JSON.stringify(state)
      ),
    state: {},
    actions: {
      recurse(state) {
        return { child: state }
      }
    }
  }).recurse()
})
```

```
Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.view (bundle.js:283)
    at render (bundle.js:47)
```

This is because the update assigns `{ child: state }` to `state` making it reference itself.

Is it meant to work like this?

**Comment by JorgeBucaran** [comment]
@Mytrill What were you expecting to happen and why are you doing this? 

> The following unit test fails due to infinite recursion...

Is the infinite recursion caused by Hyperapp or by `JSON.stringify(state)`?

**Comment by Mytrill** [comment]
Hi Jorge. My use case is: I am implementing a UI where I can recursively split the view in 2. So my state is a tree, and I have a split() action that takes a path in the tree (dot separated string) and insert a node at the given path. The unit test you see here is the equivalent of calling this split() action on the root node.

I already changed my code to use Object.assign({}, state) before opening this issue, but I wanted to know if this was intended behavior (users do the assign in this case, saves perf and bytes to HA) or a bug (HA should always copy state before assigning).

It took me some times to debug this, if there ever is a section "common issues" in the doc, this should be there!

Thanks

Thanks for the answer!
