### ISSUE TITLE
Hyperapp throws "length of undefined" when the child component returns an array

### ISSUE THREAD

**Issue by rajaraodv** [hyperapp/hyperapp#420]
I have a Parent component that takes a bunch of children elements and simply returns them. Hyperapp throws length of undefined in the `createElement` function.

Codepen: https://codepen.io/rajaraodv/pen/VMqBNB
Note: 
1. This only happens if the main Parent component is not itself wrapped in something but is the main/direct element for the `view` function.
2. If I wrap the children array in {children} then the resulting DOM shows `<undefined>...children elements... </undefined>`

Expected: It should render the children elements.

```
const { h, app } = hyperapp;
/** @jsx h */

const Parent = ({ state, actions }, children) => {
  return children; //<-- returning w/o "{" "}" causes error in Hyperapp
};
app({
  state: {
    count: 0
  },
  view: (state, actions) => (
    <Parent state={state} actions={actions}>
      <h1>raja</h1>
      <h2> rao</h2>
    </Parent>
  )
});
```
<img width="656" alt="screen shot 2017-10-18 at 3 54 26 am" src="https://user-images.githubusercontent.com/626337/31715655-99651054-b3b9-11e7-8d69-8c5be0d0a0cf.png">

**Comment by zaceno** [comment]
> This only happens if the main Parent component is not itself wrapped in something but is the main/direct element for the view function.

This is a known limitation of hyperapp. Components may return arrays, but `view` specifically may *not*

**Comment by infinnie** [comment]
#362

**Comment by JorgeBucaran** [comment]
@rajaraodv I still don't understand what you expect Hyperapp to do here? #362 will **not** be implemented, so perhaps you were not aware of that? Maybe move this to #417? 

`<undefined></undefined>` is weird though; maybe this issue is about only that?

**Comment by rajaraodv** [comment]
Yeah, probably moving this to #417 is a good idea since there is nothing Hyperapp can do other than warn people.

**Comment by JorgeBucaran** [comment]
#417
