### ISSUE TITLE
The state should be immutable

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#425]
# Current state
Since the addition of modules, the state is no longer immutable: when an action, or a nested action, or an action in a module is called, its result is merged with the current state (or state slice for nested actions/modules).

This prevent users from using memoize functions on the view with simple `===` checks for equality checks and forces to use deep equality.

For example, the following pen should work with immutable state: https://codepen.io/mytrill/pen/WZmVWQ?editors=0010

I believe for large apps, the benefit of having very cheap memoize functions based on immutable state far outweight the cost of maintaining an immutable state (both in terms of performance and source code size).

# Expected behavior
When an action gets executed, the result that it returns should get merged to the state slice/module's state this action operates on and create a new instance of the state and re-use the part of the state that hasn't been touched.
Here is an example: https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Purely_functional_tree_after.svg/438px-Purely_functional_tree_after.svg.png

In this case, when the node "f" is modified ("e" gets added to it) the update function recursively goes up the state tree, creating new nodes when modified and re-using un-touched nodes.

## Advantages
 - Allow debug tools to keep the state history and implement time travel
 - Allow very performant memoization of components/views on large app (deep equality on state can be checked with `===`)

## Drawbacks
 - small performance penalty when executing nested action (need to duplicate a whole branch of the state-tree
 - extra logic/bundle size

# Implementation
PR #426 addresses this issue

**Comment by JorgeBucaran** [comment]
We'll need the three musketeers to help with this, so I'll leave them here for the time being.

```js
function setPath(path, value, source) {
  if (path.length === 0) {
    return value
  }

  var key = path[0]

  return setProp(
    key,
    path.length > 1
      ? setPath(
          path.slice(1),
          value,
          source != null && key in source ? source[key] : path[1] >= 0 ? [] : {}
        )
      : value,
    source
  )
}

function setProp(prop, value, source) {
  var target = {}

  if (prop >= 0 && Array.isArray(source)) {
    target = source.slice()
  } else {
    for (var key in source) {
      target[key] = source[key]
    }
  }
  target[prop] = value

  return target
}

function getPath(path, source) {
  return path.length === 0 ? source : getPath(path.slice(1), source[path[0]])
}
```

**Comment by okwolf** [comment]
I ran into this when updating [`hyperapp-freeze`](https://github.com/okwolf/hyperapp-freeze) for 0.15.1. My workaround to get the functionality working was to freeze deep copies of the state and pass those to `actions` and `view`. Not great for performance, but it should only ever be used in dev, never prod.

Will the performance impact of this be a net win/loss/or draw? I'm not sure what the gains are from memoizing vs immutable updates deep inside objects without using something like [persistent data structures](https://en.wikipedia.org/wiki/Persistent_data_structure).

**Comment by JorgeBucaran** [comment]
I think it would be a **win** for hyperapp long-term. Short-term we are looking at a ±200 bytes increase with negligible perf hit, if at all.

**Comment by okwolf** [comment]
@JorgeBucaran we can still market HA as 1KB so long as it's < 2048 bytes right? 😆

**Comment by JorgeBucaran** [comment]
@okwolf Hyperapp was actually ~1700KB when it was first "officially" released, so we've actually gotten smaller and recently very small at 1397.

**Comment by lukejacksonn** [comment]
Immutable guarantees, cheap memoizing, negligible perf hit and somewhat of an existing implementation.. for ~100b you say 🤔 sounds like good deal to me 💸

**Comment by JorgeBucaran** [comment]
@lukejacksonn BTW, I need more time before merging #424, since I am still not sure if it can interfere with making the state immutable again.
