### ISSUE TITLE
Change `update` to `getState`

### ISSUE THREAD

**Issue by xialvjun** [hyperapp/hyperapp#427]
In thunks, we do not know the current state because maybe some other actions has changed the state during the thunk. So you offered an `update` function.

But a better solution is offer a `getState` function...

**Comment by JorgeBucaran** [comment]
@xialvjun The update function can take a function that receives the state. We find this method a small improvement to React/Redux.

For example, when you don't need the state to calculate the next state.

```js
update({ count: 1 })
```

And if you need the state to compute the next state.

```js
update(state => ({ count: state.count + 1 }))
```

Does that make things clear?

**Comment by xialvjun** [comment]
But if the state has been changed during the thunk, then `state.count` is wrong.

**Comment by JorgeBucaran** [comment]
@xialvjun Right, that problem is solved using:

```js
update(state => ({ count: state.count + 1 }))
```

The state passed to the inner thunk above is always up-to-date.

**Comment by JorgeBucaran** [comment]
@xialvjun In other words:

```js
const actions = {
  upAsyncNaive(state) { // Hey! state may be out-of-sync here!
    return update => update({ count: state.count + 1 }) 
  },
  upAsyncSmart(state) { // No problem here!
    return update => update(state => ({ count: state.count + 1 }))
  }
}
```

**Comment by xialvjun** [comment]
got it. thanks very much.

**Comment by JorgeBucaran** [comment]
Glad you figured it out! 🎉
