### ISSUE TITLE
Odd issue with svg

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#43]
The svg clock example live [here](https://hyperapp.gomix.me/svg_clock) works fine.

But it fails on [CodePen](http://codepen.io/jbucaran/pen/LxEdWN?editors=0010) or when run locally.

**Comment by jbucaran** [comment]
I was able to run the program correctly locally using a simple server. The only instance in which svg fails is on CodePen or when opening an index.html file directly in the browser locally (no server).

This is weird.

**Comment by rbiggs** [comment]
For me, no problem rendering the SVG clock example running on localhost, Chrome and Safari both. But I can't get the setLocal example to work running locally. Maybe something to do with localhost? I see it works fine on the go the Gomix server.

**Comment by rbiggs** [comment]
I was just looking at the error from the svg clock in Codepen. The error is being thrown by the patch function" `var i = e.childNodes[r];`. Something about how you're patching the DOM. I am getting the same error with nichoth's example of counters with child elements when I set it to render with a root element. No problem if it just gets appended to the body. [nichoth's example](https://github.com/nichoth/hyperapp/tree/master/examples). So you might want to look carefully at that patch function for some edge case that is throwing errors.

**Comment by tunnckoCore** [comment]
@rbiggs not the only bug coming from `patch` btw.

@jbucaran when I was playing with the "todo example with components approach" i faced some similar issue or maybe it was kinda "length of undefined" from `for (var i = 0; i < node.tree.length; i++) {` - that's easy fix, but i'm not sure.

kinda related #39

**Comment by selfup** [comment]
@tunnckoCore I ran into that `length of undefined` error but it was just because I didn't close some html tag 😂

**Comment by jbucaran** [comment]
@tunnckoCore 🤔 Any code you could share?

**Comment by tunnckoCore** [comment]
@selfup don't know ;d

@jbucaran i don't think so...

**Comment by jbucaran** [comment]
Ah, components, haven't forgotten about https://github.com/hyperapp/hyperapp/issues/2. We'll get there too, somewhat, somehow.

**Comment by tunnckoCore** [comment]
@jbucaran yep, i'm working on it ;d

**Comment by jbucaran** [comment]
> But I can't get the setLocation example to work running locally. Maybe something to do with localhost? I see it works fine on the Gomix server.

Router examples using a local server should work. Make sure you are not using a buggy release, there were a few of those recently, during the ES6ish rewrite.

**Comment by selfup** [comment]
@tunnckoCore I guess it's one component but with multiple views (stateless functional components in React). Using model as the entire application state tree. Just wanted to try it out haha

**Comment by selfup** [comment]
@jbucaran I am on 0.0.9, I can update to see if I get the same behavior

**Comment by juxtar** [comment]
@jbucaran Hey, SVG rendering is failing for me once again on 0.4.2
It was working up until 0.2.1 I believe (before the updates to reducers renaming) and that's what the [live example](https://hyperapp.gomix.me/svg_clock) seems to be using.

It breaks when you assign attributes to the svg. Here's a CodePen for a [working but useless](http://codepen.io/juxtar/pen/NdQxdL) svg and the [broken one](http://codepen.io/juxtar/pen/bgXEbv).

**Comment by jbucaran** [comment]
@juxtar IIRC `update` is still supported in 0.4.2, but I plan to remove it soon. 

Thanks, I've updated the examples to use `reducers` now. Also thanks for figuring out that attributes is what breaks svg in CodePen, that's a hint.

So, to summarize, SVG works when running from your own server (gomix, localhost), but fails in CodePen, specifically, when using attributes.

Could this be like a CodePen/JsFiddle security feature or something?

**Comment by juxtar** [comment]
@jbucaran It's actually failing in my localhost too. Am I doing something wrong? The code (and the error) is the same as in the CodePens.

**Comment by jbucaran** [comment]
@juxtar Odd indeed. How come it works on Gomix? 

* https://gomix.com/#!/project/hyperapp
* https://hyperapp.gomix.me/svg_clock

**Comment by jbucaran** [comment]
@juxtar You're right, 0.2.1 works, but 0.4.2 doesn't! This bug is fun.

**Comment by jbucaran** [comment]
Okay, this is really weird, but it seems SVG elements namespaces is undefined in **the minified bundles**. Maybe this is an uglifyjs issue or how we're using it.

**Comment by rbiggs** [comment]
hmmm... Maybe it's a Browserify issue with the SVG. I've used SVG with JavaScript in the browser without namespaces before.

**Comment by jbucaran** [comment]
Could this be like a race condition?

**Comment by rbiggs** [comment]
Maybe something about how Browserify injects things into the browser, combined with iframes on GoMix causing, well, iframe pain.

**Comment by jbucaran** [comment]
I'll dig more. Now that I know the cause there fix is simple, but I have to know why .ns is undefined when using the uglified bundle only.

**Comment by rbiggs** [comment]
Well, I noticed on the failing GoMix svg that's JSX that you have viewbox but no namespace. Try putting it in.

**Comment by rbiggs** [comment]
i'm sure the JSX Babel plugin doesn't add it automatically.

**Comment by rbiggs** [comment]
So i'm getting an error: 155:118TypeError: Attempted to assign to readonly property.

**Comment by rbiggs** [comment]
So after looking at the clock and playing with it locally I think I see why it sometimes doesn't work. x2 and y2 are attributes on the svg line. Therefore we're sometimes getting the error: Attempted to assign to a readonly property. That's because the example is trying to set the value of an attribute dynamically directly on that. Bad boy. Gotta use setAttribute in those cases.

**Comment by jbucaran** [comment]
### Bug is/was `"use strict"`! :feelsgood:

**Comment by jbucaran** [comment]
Fixed in 0.5.0! 💥

**Comment by jbucaran** [comment]
@rbiggs @juxtar @selfup Clock example now working.
* http://codepen.io/jbucaran/pen/PWMBLp?editors=0010

**Comment by rbiggs** [comment]
Yup, I notice after I updated my GoMix to 0.5.0

**Comment by selfup** [comment]
Ok I take 5.0 seems to be a healthy version :) I will update all my things to 5.0 now and report back!
