### ISSUE TITLE
Tests with ES modules using .mjs without babel.

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#430]
Just a thought. ☝️😄  

The goal is to remove babel as a dev dependency since we are using it just for the ES modules syntax.

If we write tests in `.mjs` we don't need [these](https://github.com/hyperapp/hyperapp/blob/8551d9bf2f631f8007aa1b6cd2bc67b6f8b2184a/package.json#L33-L37) in pkg.json.

```json
"babel": {
  "presets": "env"
},
"devDependencies": {
  "babel-preset-env": "1.6.0",
```

Using `.mjs` involves moving tests to `tests/*.mjs` and running node (for now) with `--experimental-modules`. The two alternatives I see are:

1. Copy `src/*.js` into `dist/*.mjs` as part of the build process.
```js
// tests/app.test.mjs
import { h,app } from "../src"
...
```

2. Or load hyperapp from the UMD bundle in dist/.

```js
// tests/app.test.mjs
import hyperapp from "../dist/hyperapp"
const { h, app } = hyperapp
...
```

(1) is the best option, but it requires tinkering with the build step and more planning. #417 comes to mind. Option (2) is okay too (better than using require/commonjs) and can be easily done right now. Both options require running node with a flag though. 🤔

**Comment by olstenlarck** [comment]
Impossible. Still. Even with `@std/esm` code coverage tools just not work - still. Last few weeks was trying tons of ways to create my workflow and deps more small and simple.

Not to mention that many services (like CodeClimate and such) not recognize `mjs`. Actually CodeClimate support passing custom rate paths, but seems to not work even that way.

The second way is most close one, but still have problems with coverage. Of course it won't be a problem if you are not paranoid on getting full 100% - all lines, branches, statements, and functions, aka [The TAP 100 (node-tap)](http://www.node-tap.org/100/).

**Comment by JorgeBucaran** [comment]
@olstenlarck I still want to find a way to remove babel as a dev dep. 😭

**Comment by JorgeBucaran** [comment]
Closing for now, but we'll revisit later.
