### ISSUE TITLE
Support to dynamically initialize actions inside other actions

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#431]
# Proposal

Allow users to dynamically initialise actions inside other actions by passing a slightly altered version of the initActions function to actions thunks.

Here is the updated API for a single action implementation:

```javascript
function action(state, actions, data) {
  // returns a thunk
  return function(update, initActions) {
    // ...
  }
}
```

The `initActions` function would returned "initialized" versions of the actions (i.e. take actions with signature `function(state, actions, data)` and return `function(data)`) and has the following (over-simplified) implementation:
```javascript
function initActions(state, actions, stateToLocal, localToState) {
  // the initialised actions
  const result = {}
  Object.keys(actions).forEach(function(key) {
    // for brievty's sake, assume typeof actions[key] === "function". In real life we must handle nested actions.
    result[key] = function(data) {
      const actionResult = actions[key](stateToLocal(state), result, data)
      // for brievty's sake, assume the result is the state to be merged, not a thunk. In real life we must handle thunks as well
      return stateToLocal(update(localToState(actionResult)))
    }
  })
  return result
}
```
`stateToLocal(state)` takes the state and returns the state on which `actions` operates and `localToState(local)` takes the result of `actions` and translates it back to the state of the initialising action. These functions are needed to update the application state properly.

# Why

This API will allow users to create higher order actions that create generic, immutable data structures, and re-use them accross the code-base.
This is very useful for applications that handles collections of complex objects.

## Example
Here is a simplistic example with a Todo List, we can create a generic array action creator and use it to store Todos:
```javascript
// generic action creator for array/lists
// takes actions on a single items, and return the actions on the list of items.
function arrayActions(itemActions) {
  return {
    getActions(state, actions, index) {

      function stateToLocal(state) {
        return state[index]
      }

      function localToState(local) {
        result = state.slice()
        result[index] = local
        return result
      }

      return function(update, initActions) {
        return initActions(state, itemActions, stateToLocal, localToState)
      }
    },
    getItem(state, actions, index) {
      return function(update) {
        return state[index]
      }
    }
    push(state, actions, item) {
      const result = state.slice()
      result.push(item)
      return result
    },
    remove(state, actions, index) {
      const result = state.slice()
      result.splice(index, 1)
      return result
    }
  }
}

// implement actions on a single todo item
const todoActions = {
  setTitle(state, actions, title) {
    return { title }
  },
  setDescription(state, actions, description) {
    return { description }
  },
  setCompleted(state, actions, completed) {
    return { completed }
  }
}

// all actions
const todoModule = {
  state: {
    todos: []
  },
  actions: {
    // todos now contains actions on the list of items
    todos: arrayActions(todoActions)
  }
}

// use actions list this (in a view or whatever):
actions.todos.push({ title: "Go shopping" })
actions.todos.getActions(0).setCompleted(true)

```
Note: I actually don't know if having an array in the state like this would work, but you get the idea.

# Pros

 - support for generic data structures (arrays, maps, sets, trees, etc..) right into core
 - HOAs can support dynamic actions (e.g. the logger)
 - not a breaking change for regular users (not HOAs)
 - the logic is already there, we just re-use/expose it

# Cons

 - probably small increase in size (not sure, we'll add repetition in the code, but GZIP loves repetition...)
 - breaking change API for HOAs: they have to pass along the `initActions()` at the very least
 - could be implemented as a standalone library/HOA

**Comment by JorgeBucaran** [comment]
Interesting! @Mytrill 👋😄    

I am just slightly confused about this part:

> This API will allow users to create higher order actions that create generic, immutable data structures, and re-use them accross the code-base.

...and his relation to #425.

Other than that, I am sure this is going to be a good discussion. I can't wait to hear what others think. I'll add my own feedback when I have time later.

**Comment by JorgeBucaran** [comment]
Sorry, still no time to add any thoughtful feedback. 🙇 

I was expecting more people to join the discussion. I think it's interesting and I would like to see what else this could accomplish, but to be honest, this is too complicated for me, so I am not really in favor of this proposal.

**Comment by dmitry-vakhnenko** [comment]
> could be implemented as a standalone library/HOA

Then, why it should be implemented in core?

(but pros "support for generic data structures (arrays, maps, sets, trees, etc..) right into core" sounds good)

**Comment by JorgeBucaran** [comment]
@dmitry-vakhnenko Nothing prevents you from doing this right now. I think what @Mytrill means is something else. The twist is I am not really sure what he means.

I actually had forgotten about this issue, so I am going to close this for now.

#439
