### ISSUE TITLE
Only implement state slices for modules?

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#436]
Okay, this may be seen by some as a step backward (and it may be...), but I would like to propose the idea anyway.

Adding state slices was awesome, it makes for truly re-usable modules and guides/forces users to have decoupled modules.

This is terrific, but sometimes it would be nice to be able to group actions in different namespaces just for organisation, i.e. actions acts on the same state, but are grouped in separate objects just for convenience.

So the proposed change this the following:
 - for modules, keep state slices as they are, i.e. modules can only access their own state
 - for nested actions inside the same module/app, give the full module's state/actions

here is a very contrived module that deals with a list of todos (how original...) before the proposed change:
```javascript
const todosModule = {
  state: {
    todos: []
  },
  actions: {
    add: ({ todos }, _, todo) => ({ todos: [ ...todos, todo ] }),
    delete: ({ todos }, _, index) => ({ todos: [ ...todos.slice(0, index), ...todos.slice(index + 1) ] }),
    setItemComplete: ({ todos }, _, { index, complete }) => todos.map((todo, id) => id === index ? { ...todo, complete } : todo),
    setItemTitle: ({ todos }, _, { index, title }) => todos.map((todo, id) => id === index ? { ...todo, title } : todo)
  }
}
```

And after:
```javascript
const todosModule = {
  state: {
    todos: []
  },
  actions: {
    add: ({ todos }, _, todo) => ({ todos: [ ...todos, todo ] }),
    delete: ({ todos }, _, index) => ({ todos: [ ...todos.slice(0, index), ...todos.slice(index + 1) ] }),
    item: {
      setComplete: ({ todos }, _, { index, complete }) => todos.map((todo, id) => id === index ? { ...todo, complete } : todo),
      setTitle: ({ todos }, _, { index, title }) => todos.map((todo, id) => id === index ? { ...todo, title } : todo)  
    }
  }
}
```

**Comment by Pyrolistical** [comment]
I'm sorry, maybe I'm dumb, but what is `item`. I don't understand what you are trying to show

**Comment by Mytrill** [comment]
In the example, item would be a single Todo item.

The idea I am trying to demonstrate is that you may have actions on the list itself (e.g. add item, remove item) and actions on the items of the list (e.g. set title, set completed, ...) and that you may want the actions to live in separate namespaces, just for convenience.

I admit this is not the best example, but it is all I could come up with when I thought of this.

**Comment by JorgeBucaran** [comment]
If this was a "feature", then later when looking at my code or someone else's, I would need to remember that if the action is declared in a certain way, then it is just a namespace / stub to organize other actions.

**Comment by olstenlarck** [comment]
Yea, definitely the example isn't good, but i got the idea and :+1:

Another way to backward to that is behind flag/option ;d  So if `slices: true` (default?) it will work as currently. And if anyone want old namespaces he will pass `slices: false` which will mean that they work only on modules.

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/hyperapp/pull/445
