### ISSUE TITLE
Updating a module's state using a global action breaks module actions

### ISSUE THREAD

**Issue by Pyrolistical** [hyperapp/hyperapp#437]
https://gist.github.com/Pyrolistical/882622fe00822418783dc63edcf04bf6

## Demo
![module-state-bug](https://user-images.githubusercontent.com/463642/32080880-f73767be-ba66-11e7-943e-9aa9570a3158.gif)

```
actions: {
  doubleUsingGlobal(state, actions) {
    return {
      counter: {
        count: 2 * state.counter.count
      }
    }
  }
},
modules: {
  counter
}
```
The module seems to get stuck with an old state slice reference. Should be easy to fix, just can't eagerly bind state slice to module actions.

**Comment by Pyrolistical** [comment]
Here it is, in initActions, we bind the state slice to the module forever:
https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L72

**Comment by Pyrolistical** [comment]
#438 is now blocked by this.

**Comment by Mytrill** [comment]
This should be fixed when we merge #426.

**Comment by JorgeBucaran** [comment]
We. Are. Immutable. 🎉

**Comment by JorgeBucaran** [comment]
We. Are. Immutable. 🎉😎 
#445
