### ISSUE TITLE
Fragment state doesn't work when there is a module of the same name

### ISSUE THREAD

**Issue by Pyrolistical** [hyperapp/hyperapp#438]
https://gist.github.com/Pyrolistical/882622fe00822418783dc63edcf04bf6

### Demo
![fragment-state-bug](https://user-images.githubusercontent.com/463642/32080959-71743430-ba67-11e7-8723-dfa0116f5622.gif)

```
actions: {
  doubleUsingGlobal(state, actions) {
    return {
      counter: {
        count: 2 * state.counter.count
      }
    }
  },
  // this doesn't work due to module vs fragment conflict
  counter: {
    doubleUsingFragment(state, actions) {
      return {
        count: 2 * state.count
      }
    }
  }
},
modules: {
  counter
}
```

doubleUsingGlobal breaks the module due to #437, but is unrelated to this issue

**Comment by Pyrolistical** [comment]
Here it is. We add actions.counter.doubleUsingFragment here: https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L77

Then we clobber it when init modules after https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L64

**Comment by Pyrolistical** [comment]
In theory, this should be an easy fix with:
for (var i in module.modules) {
  init(module.modules[i], (state[i] = {}), *actions[i] || *(actions[i] = {}))
}

But it doesn't work due to #437, we bind a the counter data slice eagerly, but once the module updates the state, doubleUsingFragment is stuck with the uninitialized state

**Comment by Mytrill** [comment]
This raises an important question: what do we do when actions occupy the same namespace as sub-modules?

For example:
```
const child = {
  actions: {
    foo() { ... }
}

const module = {
  modules: { child },
  actions: {
    child: {
      foo() { ... }
    }
  }
}
```

Which action gets executed when `child.foo()` gets called? should HA throw an error on initialization in this case? What if both actions don't have the same name but share the same namespace, is this allowed?

**Comment by Pyrolistical** [comment]
Hmm, I think the parent should shadow the child, but not replace the child action.

So we if call child.foo() the parent gets called, but from within the child foo() is still the child's

**Comment by JorgeBucaran** [comment]
> @Pyrolistical Fragment state doesn't work when modules have the same name.

How could two modules have the same name? That's like saying values don't work when variables have the same name. 😄

**Comment by Pyrolistical** [comment]
i mean when a fragment state action is the same name as a module name.

**Comment by JorgeBucaran** [comment]
@Pyrolistical In that case can you please update the issue's title? 🙏

**Comment by JorgeBucaran** [comment]
> @Mytrill This raises an important question: what do we do when actions occupy the same namespace as sub-modules?

The solution to this problem is to remove modules and leave assembling to the user, but modules are nice to have. So, which ones is the least worse?

**Comment by SkaterDad** [comment]
It seems like a good candidate for "dev build" warnings.  Conflicting namespaces just need to be avoided, in my opinion.

Does the current documentation make it clear that modules will occupy the namespace you assigned in the larger state/actions trees?

I see no issue with the current behavior, honestly.

**Comment by JorgeBucaran** [comment]
@Pyrolistical With immutable state, the solution to this issue is simple, but the question remains, what is the right thing to do?

Does it make sense to add actions to an existing module from your app?

**Comment by JorgeBucaran** [comment]
Without a solution for this, there is only one way to monkey patch a module.

```js
doubleUsingGlobal(state, actions) {
  return {
    counter: {
      count: 2 * state.counter.count
    }
  }
}
```

That will replace the entire `counter` slice with a new counter object, instead of updating `count`'s value.

```js
counter: {
  doubleUsingFragment(state, actions) {
    return {
      count: 2 * state.count
    }
  }
}
```

Now, that will work just as if `doubleUsingFragment` was an action under the counter slice and update only `count`.
