### ISSUE TITLE
Merge actions, state, view and modules

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#447]
# Proposal

Currently, apps are written as follow `{ state, actions, view, modules }`,  and modules as follow: `{ state, actions, modules }`.  
When `app()` is called, modules get "merged" together to compose the final `state` and `actions` trees (which has issues on its own, e.g. #438).
This means that adding new features to HA, such as `init()` or `views` or `getters` will keep making both modules and the app more and more complex, especially if these new features need to interact together in useful ways (e.g. `views` should have access to `actions`, `state` and `getters`, `init()` only to actions, etc...) in addition to making the "merging" of modules more complicated.

The idea of this proposal is to switch from app/modules containing multiple objects, each handled differently to  receiving only 1 object (a module), where each attribute is handled in one of 3 ways:
 - if the property is a function: partially apply it
 - if the property is an object: consider it a module and recurse
 - if the property is anything else (boolean, number, array, string, ...): consider it a part of the state

Functions should have the signature:
```javascript
// once partially applied, can be invoked with: myAction() returns anything
const myAction = (module, update) => anything
// once partially applied, can be invoked with: myActionWithData(data) returns anything
const myActionWithData = (module, update) => data => anything
```
`update()` takes in a partial module (state or functions!), merges it to the current module and returns the argument it was called with.

"Special" actions:
 - `view()`: if the app receives a function named "view" in the root module, it is called after each update to the state/modules
 - (OPTIONAL) `init()`: any function called "init" (in the root module, or sub-modules) is executed before the first render

__Why bring `update()` back?__

The main idea of this proposal is to handle the entire object in the same way, including functions on the object.
In addition, there must be a view function that returns a VNode, and has no side-effect, and there must be functions that update the object (i.e. actions), and both **must be handled the same way**. 

Option 1: the simplest option is that the return value of functions is just returned to the user (without re-triggering a call to `view()` or any extra effect) and updating the tree is done via calling a function. 

Option 2: The other possibility would have be to always update the tree with the return value and provide as a second argument a `return` function (or similar) that prevents HA from merging the value to the tree and just return it to the user:
`view: (module, return) => return(<div>this is just returned</div>)`

Option 2, or calling a function to not do anything, is more confusing than option 1.

Here are some examples, followed by the full "API".

# Example 1: counter app

```javascript
app({
  // state 
  count: 0,
  // actions
  down: (module, u) => u({ count: module.count - 1 })
  up: (module, u) => value => u({ count: module.count + value })
  // view
  view: (module) => (
    <button onclick={() => module.down()}>-</button>
    {module.count}
    <button onclick={() => module.up(2)}>++</button>
  )
})
```

# Example 2: counter app 2

```javascript
app({
  // state
  count: 0,
  // possible to call other functions
  down: (module, u) => module.up(-1),
  up: (module, u) => value => u({ count: module.count + value })
  // "pre-wired" component
  Counter: (module) => (
    <button onclick={() => module.down()}>-</button>
    {module.count}
    <button onclick={() => module.up(2)}>++</button>
  )
  // use the wired component
  view: (module) => <module.Counter />
})
```

# Example 3: counter app with modules

```javascript
const counter = {
  // state
  count: 0,
  // actions
  down: (module, u) => module.up(-1),
  up: (module, u) => value => u({ count: module.count + value })
  // "pre-wired" component
  Counter: (module) => (
    <button onclick={() => module.down()}>-</button>
    {module.count}
    <button onclick={() => module.up(2)}>++</button>
  )
}
app({
  // module
  counter,
  // use the wired component
  view: (module) => <module.counter.Counter />
})
```

# Example 4: dynamic modules
This part of the proposal is optional, as it may add extra complexity to the code, but it allows to deal with dynamic imports while following the same philosophy as the rest of the proposal.
```javascript
const counter = {
  index: 0,
  count: 0,
  // call other action
  down: (module, u) => module.up(-1),
  up: (module, u) => value => u({ count: module.count + value })
  // "pre-wired" component
  Counter: (module) => (
    <h1>Counter {module.index}</h1>
    <button onclick={() => module.down()}>-</button>
    {module.count}
    <button onclick={() => module.up(2)}>++</button>
  )
}

app({
  // the number of counters currently registered
  counters: 0,
  // action to register a counter
  addCounter: (module, u) => {
    const name = "counter" + module.counters
    // compute the new update object
    const updates = { counters: module.counters + 1 }
    // get the new counter
    updates[name] = Object.assign({}, counter, { index: module.counters })
    // do the update
    u(updates)
  },
  // view
  view: (module) => {
    // get all the counters' components
    const counters = []
    for(let i = 0; i < module.counters; i++) {
      const counter = module["counter" + i]
      counters.push(<counter.Counter />)
    }

    // render them
    return (
      <div>
        {counters}
        <button onclick={module.addCounter}>Add new counter</button>
      </div>
    )
  }
})
```

# Complete API

```javascript
// a module
const counter = {

  // the state is directly written in the module, no more state: { counter: 0 }
  counter: 0,

  // all functions below are wired, all treated the exact same way, no more views, actions, getters, etc...

  // here is the simplest thing: a getter, once wired, it is called as follow: module.isNegative()
  isNegative: (module) => module.counter < 0
  // a getter with a parameter, called module.isBiggerThan(4)
  isBiggerThan: (module) => n => module.counter > n,

  // a setter, the u parameter is for update, it merges what is passed into it to the current state slice
  add: (module, u) => (value) => u({ counter: module.counter + value }),
  // a setter with no parameters
  add1: (module, u) => u({ counter: module.counter + value }),
  // of course, we can use other getters/setters, here is a second way to write add1:
  add1_otherOption: (module) => module.add(1),

  // now a wired component, compatible with JSX, hyperscript, etc... Called: <module.Counter label="value: " />
  Counter: (module) => (props, children) => <div>{props.label || "Counter value: "}{module.counter}</div>

  // a sub-module
  subModule : {
    // this object contains the same things as above.
    otherValue: 0,
    // of course, module is sliced
    add: (module, u) => value => u({ otherValue: module.otherValue + value })
  },

  // EXPERIMENTAL: if we follow the logic above, the u function should be able to take in new functions or modules and wire them dynamically!
  dynamiclyWireNewAction: (module, u) => u({
    add2: (module2, u2) => u2({ counter: module.counter + 2 })
  })
}

// now an app using the module, the object taken by the app is the exact same signature as above, just a module:
app({
  // use module
  counter,
  // view
  view: (module) => <counter.Counter label="Value: " />
})
```

# Pros
 - simpler API
 - makes the app completely fractal
 - allows to reuse apps as part of other apps (since an app = module now)
 - fixes a lot of issues around this topic
 - adds dynamic module support out of the box
 - adds support for view, views, getters, etc... in modules
 - possibly size reduction as the initialization logic should be simpler

# Cons
 - another (very big) breaking change

# Limitations
 - `app()` should probably return the processed object it got, what to do with the state? since app's updates are immutable, the state will become stale.

**Comment by Mytrill** [comment]
As discussed with Jorge on Slack, this proposal will **not** move forward in Hyperapp, instead I am working on it on a spin-off of Hyperapp.
I started working on it here: https://github.com/hyperstart/frapp

I will now close this.

**Comment by olstenlarck** [comment]
It looks and sounds like a very big mess anyway.

And how will determine what is a submodule and what is state of type object?

**Comment by JorgeBucaran** [comment]
@olstenlarck The core idea is:

> if the property is a function: partially apply it
> if the property is an object: consider it a module and recurse
> if the property is anything else (boolean, number, array, string, ...): consider it a part of the state

...correct me if I am wrong @Mytrill.

**Comment by olstenlarck** [comment]
yea I seen that, exactly because of that im asking. "if object, consider it as module and recurse" when it will consider it as object state.

anyway.. it still seems very unorganized.
