### ISSUE TITLE
Generate "nice" documentation from current markdown files

### ISSUE THREAD

**Issue by eschaefer** [hyperapp/hyperapp#452]
[Gitbook](https://www.gitbook.com) can generate some pretty fantastic layouts for documentation by just using the markdown files that already exist for a project. I love the way that Redux [displays their docs](https://redux.js.org/), which are just generated from markdown files, by Gitbook.

I use the Hyperapp docs quite a bit, but I find the navigation pretty clumsy. Would anyone else benefit from a Redux-like layout? If so, this is something I could start working on, and maybe eventually fold it into the official Hyperapp site at https://hyperapp.js.org/.

**Comment by lukejacksonn** [comment]
This has been proposed and implemented (not with gitbook, but as a hyperapp)! The idea never gained any traction but it is here (serving old docs) https://lukejacksonn.github.io/hyperapp-wiki

**Comment by JorgeBucaran** [comment]
@eschaefer I certainly would! I created https://github.com/hyperapp/website/issues/7 to track the website new design. If we manage to get the docs on the website, then we can make it whatever we want.

**Comment by eschaefer** [comment]
@lukejacksonn Cool! I didn't know that had been implemented. Bonus 

@JorgeBucaran I'm open to anything that can easily generate the docs. I just noticed Gitbook was a pretty turn-key solution that works with the existing markdown structure and is easily themeable. But I like Luke's idea of making it a Hyperapp too 🙌

**Comment by eschaefer** [comment]
Hey guys, I threw together a little [example](https://temp.deadhare.com) of what I had in mind.

It required these steps:
- Restructured the markdown docs slightly, with clear nesting https://github.com/eschaefer/hyperapp/tree/feature/docs-update/docs
- Added a [download script](https://github.com/eschaefer/website-1/blob/feature/docs/docsDownload.js) and [doc generation](https://github.com/eschaefer/website-1/blob/feature/docs/package.json#L32) step to the website build.

Let me know what you think. All feedback welcome. If it seems ok, I can make read PRs out of those changes.

**Comment by Swizz** [comment]
For the record, I made an attempt to generate the website documentation from Hyperapp markdown docs too. A while ago.

https://github.com/Swizz/hyperapp-docs

**Comment by eschaefer** [comment]
@Swizz cool, I just tried running it but it's not quite working as intended, I think. Getting quite a few 404s.

Has anyone taken a look at my example? If it seems like an acceptable first pass, I'm happy to make real PRs to the website and hyperapp docs.

**Comment by JorgeBucaran** [comment]
@eschaefer #502 was merged, so I am going to close here in favor of #510.
