### ISSUE TITLE
Documentation is out of sync with released version

### ISSUE THREAD

**Issue by trescenzi** [hyperapp/hyperapp#461]
As per the title all of the documentation reflects the changes made in #458 but typing yarn install won't provide you with these changes. One thing to note though is that the codpen in the readme is still on 0.16.0.

This issue manifests itself, to me, as `TypeError: node.props is undefined`. The simplest fix for now is to pull down master `yarn add git+https://github.com/hyperapp/hyperapp.git#master`, or convert back to a not point free syntax.

**Comment by Swizz** [comment]
We should show [the latest tag](https://github.com/hyperapp/hyperapp/tree/0.16.0) as DOC entrypoint instead of master.

**Comment by JorgeBucaran** [comment]
@trescenzi 0.16.1 published. 👍
