### ISSUE TITLE
`let` over `var`?

### ISSUE THREAD

**Issue by robmuh** [hyperapp/hyperapp#463]
I notice in the examples `const` is used but in the source `var` is all over the place. I suppose this is one of those *why-fix-it-if-it-works* things, but I have to ask what was the thinking behind using the more problematic, functionally scoped `var` over `let`?

Truth be told I am convinced (and helping to convince my students) of the dangers of `var` in general and that its time has past. Am I missing a solid reason not to say this?

**Comment by lukejacksonn** [comment]
The source code is written in ES3/5 (with the exception of the `export` keyword used for bundling only). I believe the main reason for this is that there is then no need for a transform step which gives us complete control over the built code which results in a better minified bundle size.

**Comment by robmuh** [comment]
Makes sense. I was confused by the use of `const` (a JavaScript 2015 thing along with `let`) in the example code in the main readme. That implied an assumption of at least that version required in the framework.

**Comment by JorgeBucaran** [comment]
@robmuh If we ship Hyperapp in ES6 disregarding other browsers, we are basically alienating every potential developer out there, with the exception of very few. There's absolutely **no** benefit of doing that. Now, I'd love to introduce more ES6-isms in the code, but that would require having a compilation step, and I want to avoid that.

**Comment by JorgeBucaran** [comment]
👋😄

**Comment by robmuh** [comment]
Yeah, I wanna be clear I was not suggesting you drop everything but ES6, only that I am looking for a framework brave enough to do so.

**Comment by JorgeBucaran** [comment]
@robmuh Most modern frameworks are written in ES6 or a subset of ES6, e.g., Preact. But what you are actually running in your browser, is an ES3/ES5 UMD bundle. They are compiled.

Now here is the twist, Hyperapp **is** actually written in ES6 **and not compiled**, because we are using ES modules already.

Proof? Copy and paste the following into your browser's address bar, then hit enter. 😎 

```
data:text/html,<head><script type="module">import{app}from"https://rawgit.com/hyperapp/hyperapp/master/src/index.js";app({view:()=>"Hello!"})</script></head>
```

**Comment by Swizz** [comment]
To follow backward compatibility ES6 come with most of the ES5 feature. 
So writing ES5 is actually writing ES6. 

I mean by that you can still use `var` and claim you are using ES6 as `let`, `const` and `var` are part of the specification. They are all three a different meaning.
