### ISSUE TITLE
Hyperapp in Typescript?

### ISSUE THREAD

**Issue by benalbahari** [hyperapp/hyperapp#465]
Perhaps someone's done this already, but anyway, here's a quick port of hyperapp to typescript (some of the variables typed to "any" could be typed more specifically, but couldn't figure out what they should be):
https://gist.github.com/benalbahari/119312ff95104d26f69676e0eb308695

Transpilation gives you a clean .js file:
https://gist.github.com/benalbahari/5cb6ecb982d190e7303934555b5b1aa9

This way you don't have to maintain syncing the .d.ts with the .js file. I also find it helps me understand hyperapp's implementation when I can readily see a variable's type.

FWIW I believe in Erik Meijer's _"[Static Typing Where Possible, Dynamic Typing When Needed](https://pdfs.semanticscholar.org/c803/59566e9feb4d8e2f39a3883148082c57a191.pdf)"_ philosophy.

**Comment by okwolf** [comment]
@benalbahari this might introduce a barrier to entry for contributions from non TS gurus. Personally I started my career on the statically typed side but have recently been embracing dynamic typing more and more. Also is there a way to tell the compiler to leave out this extra junk?

```js
define(["require", "exports"], function (require, exports) {
  "use strict";
  Object.defineProperty(exports, "__esModule", { value: true });
  ...
  exports.app = app;
  ...
  exports.h = h;
});
```

Think of the bytes! 😂

**Comment by JorgeBucaran** [comment]
@okwolf We got rid of that with [this line](https://github.com/hyperapp/hyperapp/blob/0c952d7174d151c59c3b1af71a50ec1dc23415e7/package.json#L26) in the minify script.

**Comment by JorgeBucaran** [comment]
@benalbahari Looks awesome and thanks! I don't think we are going to move from a JS project to a TS project, but perhaps you could help us out with the declarations file? 🙏

**Comment by benalbahari** [comment]
Is there anything specific you need help with on the declarations file, or do you just need help in general keeping it up to date?

**Comment by JorgeBucaran** [comment]
@benalbahari Yes! We need help with maintaining that file, if you would like to help with that I would be super grateful.
