### ISSUE TITLE
onremove won't fire for children elements

### ISSUE THREAD

**Issue by 4lejandrito** [hyperapp/hyperapp#468]
Please see https://github.com/hyperapp/hyperapp/pull/467 with a failing test for this. 

Basically when an element its removed only its `onremove` method seems to be called. None of the `onremove` lifecycle events are called for its children. 

My specific use case is:

Modal Dialog Component
|__ Camera custom component (`oncreate` calls [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) and `onremove` closes the stream).

When I close the modal, the `onremove` method of my camera is not called.

Thanks for all your work!

**Comment by 4lejandrito** [comment]
Looks like I need to dig into this a little bit more, I will reopen if necessary.

**Comment by JorgeBucaran** [comment]
Maybe related. https://github.com/picodom/picodom/issues/61

**Comment by SkaterDad** [comment]
Here's a Codesandbox where a parent element waits for children `onremove`:
https://codesandbox.io/s/r1yzxl3kwo

I implemented all of the `onremove` functions as Promises so you can wait for async things like animation, but the same idea applies for sync things which just teardown objects & listeners.

It's not much code to implement this, but since it would imply a perf hit on every `onremove`, I would suggest it either goes to a new (optional) lifecycle event, or is left up to devs.

```js
// recursive, so can be slow on large trees
function collectChildrenOnremove(result, child) {
  if (child.onremove) {
    result.push(
       // call child onremove before pushing it to the array
      child.onremove(child, function() {
        // Fake done() function
      })
    )
  }
  if (child.children != null) {
    const arr = Array.prototype.slice.call(child.children)
    return arr.reduce(collectChildrenOnremove, result)
  }
  return result
}

// put this on the parent element
function waitForChildrenOnremove(element, done) {
  let promises = Array.prototype.slice
    .call(element.children)
    .reduce(collectChildrenOnremove, [])

  return Promise.all(promises).then(done)
}

...

// use it later
 h('div', { onremove: waitForChildrenOnremove } , [ ... ])
```

**Comment by 4lejandrito** [comment]
Hi @SkaterDad,

I appreciate you spending the time to provide a workaround that would work without patching Hyperapp (I might actually use it for the time being). However I think this is such a common use case that it should somehow be added to the core (see https://github.com/hyperapp/hyperapp/pull/470). 

Thanks!

**Comment by JorgeBucaran** [comment]
@4lejandrito I totally agree, this needs to be added to core. Not sure in what form exactly, but right now, I am swaying in favor of your comment here: https://github.com/hyperapp/hyperapp/pull/470#issuecomment-349049424.
