### ISSUE TITLE
Unsupported Node.js version for CI

### ISSUE THREAD

**Issue by okwolf** [hyperapp/hyperapp#473]
Currently, [Travis is building with Node.js versions 7 and 8](https://github.com/hyperapp/hyperapp/blob/master/.travis.yml#L3-L4). Node.js 7 is no longer supported (last release 2017-07-11), and we dropped Node.js 6 even though it is still under LTS (last release 2017-11-06).

My suggestion would be to stick with the actively supported versions of Node.js: 6, 8, and 9.

**Comment by JorgeBucaran** [comment]
Sure, no problem.

**Comment by okwolf** [comment]
FYI here is the schedule for Node support:
![](https://raw.githubusercontent.com/nodejs/Release/master/schedule.png)

**Comment by selfup** [comment]
Thanks for bringing it up @okwolf!

PR has been merged: #475

Closing 😄
