### ISSUE TITLE
Introduce models?

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#479]
This is a spin-off proposal based on #477 with a subset of its benefits, but less problems.

Here is the counter.

```jsx
app({
  state: {
    count: 0
  },
  actions: {
    down: () => model => ({ count: model.count - 1 }),
    up: () => model => ({ count: model.count + 1 })
  },
  view: model => (
    <main>
      <h1>{model.count}</h1>
      <button onclick={model.down}>–</button>
      <button onclick={model.up}>+</button>
    </main>
  )
})
```

As you can see all that's changed from actual Hyperapp is that we have merged state and actions into one object "model" and give into your view and actions.

This doesn't interfere with how you assemble the state and actions, saving to and reading from local storage, etc.

It means you still need some boilerplate to wire multiple modules to your app's state and actions, but it means you have a simpler time passing modules to components.

```jsx
view: model => 
 <main>
   <h1>Hello</h1>
   <AComponent A={model.A} />
   <ZComponent A={model.A} B={model.B}/>
 </main>
```

**Comment by SkaterDad** [comment]
Vue does this sort of thing for all of their components data/computed/methods, and I never cared for it.  Thats the sort of framework magic that trips people up eventually.  Part of hyperapp's appeal when I found it was the lack of such features.

I havent really found it difficult to pass 2 parameters to a view function. More often than not, I'm passing individual properties and actions to make the components more reusable and explicit.  It's probably more annoying for JSX users, but it seems to be a common practice in React land also.

**Comment by JorgeBucaran** [comment]
@SkaterDad I agree with you about useless features, but could you please reconsider? Have a look at this:

```jsx
view: state => actions =>
  <main>
    <h1>Hello</h1>
    <AComponent A={{ ...state.A, ...actions.A}} />
    <ZComponent A={{ ...state.A, ...actions.A}} B={{ ...state.B, ...actions.B}} />
  </main>
```

VS

```jsx
view: model => 
 <main>
   <h1>Hello</h1>
   <AComponent A={model.A} />
   <ZComponent A={model.A} B={model.B}/>
 </main>
```

A reason why I like this idea is because of our slices. Slices always work as a state and action pair, not just the state or actions, so very often you have the dilemma presented above.

**Comment by SkaterDad** [comment]
I'm not opposed to the models idea in general.  I would just prefer the previously discussed version in #477 which doesn't merge my state/actions behind-the-curtains.

You've mentioned in previous PRs/issues that you wanted what the developer writes to be similar to how the code actually gets used.   For example, switching the order of params to actions.  I think that's a nice philosophy, but this proposal violates it.

**Comment by JorgeBucaran** [comment]
@SkaterDad I am glad you brought that up. 

> I think that's a nice philosophy, but this proposal violates it.

This is a contentious issue, because as you well know, the actions you received in the view/actions are not the same original actions. So, even by changing the order of params, we can't hide the truth.

The model kind of makes it obvious that it's not the state or actions you are getting, but a different thing. Also, I feel it would help clear the typing nomenclature: State, Actions, Model, instead of State, Actions and... MyActions 😉

**Comment by olstenlarck** [comment]
I'm against. the other proposal is a lot better in any means. This only confuses the things more and more. You always should mess with your mind and thing what is what and what is free to use - for example what about `up` state property? It won't be possible, because you have `up` action.

It is fact, that `model.actions` screams explicitly what you are doing, what you are trying to do and what is the intent of the code. Applying conventions and such small things are always the best way. You should not always think how to "simplify" or how to tweak it to be "more don't-know-what" kinda thing - not leading to good things.

**Comment by JorgeBucaran** [comment]
Yeah, I started agreeing with everyone about this one. It's all or nothing.
