### ISSUE TITLE
Change vnode type

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#481]
Just wondering what would happen if we change the VNode type from:

```js
const vnode = {
  type: "h1",
  props: { class: "heading" },
  children: "Hello"
}
```
to this:

```js
const vnode = ["h1", { class: "heading" }, "Hello"]
```

To generate the vnode you call `h("h1", { class: "heading" }, "Hello")` as usual.

This is a private API, so it would not be a breaking change unless you were creating vnodes directly without `h()`.

**Comment by okwolf** [comment]
This reminds me of some performance advice from Elm:
> **Prefer arrays over dictionary objects.** Crawling an array is much faster than crawling an object. for (var key in object) is just never going to be as fast as for (var i = 0; i < len; i++). Whenever there is a dynamic number of things, find a way to allocate them one-by-one at the end of an array.

[Source](http://elm-lang.org/blog/blazing-fast-html-round-two#technical-details)

**Comment by leeoniya** [comment]
you should bench this. javascript JITs will recognize the object by its consistent shape and optimize it via a hidden class. arrays are only faster for iteration. i dont think you intend to iterate vnode properties so it's likely a net perf regression.

**Comment by JorgeBucaran** [comment]
I experimented with this and found it yielded less code, because it removes `h()`, but then we need to make up for `h` param normalization with more checks which are only likely to slow us down.

**Comment by Swizz** [comment]
😔

**Comment by JorgeBucaran** [comment]
@Swizz We can still have a function that turns a VNode into a cool array VNode though.
