### ISSUE TITLE
Can we export h from app?

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#483]
This is how you import your hyperapp goodies:

```js
import { h, app } from "hyperapp"
```

I was thinking, what if we did it like this instead:

```js
import app from "hyperapp"

// or

import { app } from "hyperapp"
```

So, where did `h` go? Well, it's a prop of the app function.

```js
const { h } = app
```

**Comment by dmitry-vakhnenko** [comment]
No, please.

`app` may be needed in places, where `h` not needed (because we import ready to use Components).

`h` may not be needed in places, where app app needed.

**Comment by olstenlarck** [comment]
@dmitry-vakhnenko agree :+1: :100:

**Comment by lukejacksonn** [comment]
Named exports win for me every time. Pretty relevant [article](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad).
