### ISSUE TITLE
The events property was removed?

### ISSUE THREAD

**Issue by zhaotoday** [hyperapp/hyperapp#485]
The `events` property was removed? I set it, but it doesn't work.

**Comment by JorgeBucaran** [comment]
@zhaotoday Yes. What were you using them for? I can give you an alternative.

**Comment by zhaotoday** [comment]
Watch the changes of state. I now use `@hyperapp/logger`  to do it.

**Comment by JorgeBucaran** [comment]
@zhaotoday Sounds good to me.
