### ISSUE TITLE
What's wrong with this code? 😉

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#488]
Can you find the "problem" with the following code? Disclaimer: This may not be a problem.

```jsx
import { h, app } from "hyperapp"

const angle = t => 2 * Math.PI * t / 60000

const model = {
  time: Date.now(),
  tick: () => ({
    time: Date.now()
  })
}

const view = model => (
  <svg viewBox="0 0 100 100" width="200">
    <circle cx="50" cy="50" r="45" fill="blue" />
    <line
      x1="50"
      y1="50"
      x2={50 + 40 * Math.cos(angle(model.time))}
      y2={50 + 40 * Math.sin(angle(model.time))}
      stroke="white"
    />
  </svg>
)

app(model, view)

setInterval(model.tick, 1000) // ← How does this work?
```

For starters, it doesn't work yet, but it will (probably) just like that in 0.17.0.

The call to `app(model, view)` injects code into functions in your model (`tick` above) so that calling them causes a view re-render, but you know this already right? The interesting part here is that we are using the same model we declared above, not the object returned by `app`.

How do you feel about this? 

BTW, the following works too.

```js
export { model } // ← Now you can import this app from another file and call actions in it!
```

There is this option too.

```jsx
const initial = { /* ... */ }
const view = model => <svg />
export const model = app(initial, view)
```

Which one is better and why?

**Comment by okwolf** [comment]
@JorgeBucaran are you telling me that `app()` is going to mutate my poor, helpless `model`? 🤯

**Comment by JorgeBucaran** [comment]
@okwolf It's implemented like this on my PR, but it could change. I am gathering feedback. :)
