### ISSUE TITLE
Sourcemaps 🗺 

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#49]
Could we have sourcemaps for the minified versions? Would make debugging so much easier. You can do it with Webpack.

**Comment by jbucaran** [comment]
Or with rollup too. Yes, that sounds like something we can all agree!

**Comment by tunnckoCore** [comment]
Yea. Rollup with `rollup-plugin-buble` and `rollup-plugin-uglify` and passing just sourceMap: true to Rollup, gives zero config and sourcemaps.

**Comment by jbucaran** [comment]
@rbiggs SourceMaps are now available:

* https://unpkg.com/hyperapp@0.0.12/dist/hyperapp.js.map
* https://unpkg.com/hyperapp@0.0.12/dist/hyperapp.hx.js.map

**Comment by rbiggs** [comment]
Yup, I just noticed. Thanks. Will make it a whole lot easier to debug now.

**Comment by tunnckoCore** [comment]
We can close this :)

**Comment by jbucaran** [comment]
Hi @rbiggs, can you share how you are using source maps to debug? I don't use them, so I really wasn't paying much attention when this issue was created, but now that I thought about it a bit, hyperapp is written in ES5, so what's the benefit of distributing a source map?

**Comment by jbucaran** [comment]
@dodekeract Are you using https://unpkg.com/hyperapp@0.7.1/dist/hyperapp.js.map?

**Comment by jbucaran** [comment]
> I was using a dev server to test hyperapp. In production you'll be using the minified/uglified version of hyperapp, so sourcemaps are very useful to have!

The last line in [`hyperapp.js`](https://unpkg.com/hyperapp)

```
//# sourceMappingURL=hyperapp.js.map
```

makes the Dev Console download/load hyperapp's [source map](https://unpkg.com/hyperapp/dist/hyperapp.js.map) during a debug session, when an exception occurs, etc. 

<h3><b>Without</b> source maps 😞</h3>  
<img width="380" alt="screen shot 2017-04-07 at 12 41 36" src="https://cloud.githubusercontent.com/assets/56996/24784762/c0e29902-1b8f-11e7-87df-ac9890535797.png">
<img width="530" alt="screen shot 2017-04-07 at 12 41 47" src="https://cloud.githubusercontent.com/assets/56996/24784768/c3e4a3fc-1b8f-11e7-991b-b246c3765989.png">

<h3><b>With</b> source maps 😄</h3>  

<img width="531" alt="screen shot 2017-04-07 at 12 42 01" src="https://cloud.githubusercontent.com/assets/56996/24784775/ccae88fe-1b8f-11e7-8a82-1d4fa73b7084.png">
<img width="532" alt="screen shot 2017-04-07 at 12 42 08" src="https://cloud.githubusercontent.com/assets/56996/24784776/cef91476-1b8f-11e7-902f-224e8b1f0308.png">
