### ISSUE TITLE
Object.assign and browser support: IE11 y/n?

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#495]
@Alber70g claimed to have used Hyperapp with IE9 without no changes, but I presume he was just lucky. 😄🎉   

I am using it with IE11 in production, which is closer to what we really support, although we claim IE10. See also: https://github.com/hyperapp/hyperapp/issues/466

If we drop IE11, we could get rid of the stand-in merge/assign function as well as (potentially) introduce some ES6isms.

```js
function assign(target, source) {
  var result = {}

  for (var i in target) result[i] = target[i]
  for (var i in source) result[i] = source[i]

  return result
}
```

What do you think?

**Comment by whaaaley** [comment]
Personally, I'd like to keep IE11 for now.

**Comment by SkaterDad** [comment]
IE11 is my only supported browser at work for internal apps, so I'd prefer to keep it also.  I'm sure I'm not alone.

The fact that I can just drop hyperapp in a script tag and get right to work without polyfills is great.

**Comment by JorgeBucaran** [comment]
@SkaterDad Same story at my company, so I hear you.

**Comment by JorgeBucaran** [comment]
@SkaterDad @whaaaley What about something like this? (half-joke half-serious).

```jsx
  app(
    state,
    actions,
    view,
    container,
    Object.assign ||
      function assign(target, source) {
        var result = {}

        for (var i in target) result[i] = target[i]
        for (var i in source) result[i] = source[i]

        return result
      }
  )
```

**Comment by leeoniya** [comment]
IE11 is 7.6% of our ecommerce traffic and it converts quite well.

**Comment by whaaaley** [comment]
TBH, a custom merge function would complete everything I'd want from Hyperapp, because I don't want one. 😬 

Could we brainstorm ideas for adding a merge as an HOA?

**Comment by JorgeBucaran** [comment]
> @whaaaley ...a custom merge function would complete (almost) everything I'd want from Hyperapp, because I don't want one

I understand you want one, but I still don't understand why. Can you please explain in detail why you'd want this?

**Comment by Alber70g** [comment]
> @Alber70g claimed to have used Hyperapp with IE9 without no changes, but I presume he was just lucky. 😄🎉

Please, keep Hyperapp support for IE9. I'm using it and works fluently. Especially now that we have a vital part of a banking application running with Hyperapp for 4 million customers (Login screen), it'd be awesome to keep it working with future versions.

**Comment by okwolf** [comment]
I think as long as Microsoft continues to support IE11 you will have users that will also need to support IE11. I think anything earlier we should be able to drop support for if we need to.

`let`/`const` here we come? 🤣

**Comment by JorgeBucaran** [comment]
Sounds good everyone, let's keep things the way they are.
