### ISSUE TITLE
Force model to be object and always be immutable?

### ISSUE THREAD

**Issue by tunnckoCore** [hyperapp/hyperapp#50]
@jbucaran what you think about the model to be object and freeze it, using `Object.freeze` or `deep-freeze`?

**Comment by jbucaran** [comment]
@tunnckoCore What's the advantage?

**Comment by jbucaran** [comment]
> what you think about the model to be object 

choo does this IIRC. HyperApp is more flexible allowing the model to be a string, number, array or object.

**Comment by tunnckoCore** [comment]
> choo does this IIRC

That's why I'm asking. I think it is immutable for reason. And that isn't only in choo, actually. "immutable" and "functional" are kinda trending these days.

I'm not so frontend, but I like that and I believe that's correct trend.

**Comment by jbucaran** [comment]
Can you freeze a number or an array or is it limited to objects?

What about simply not changing the model? The only reason you'd want to freeze the model is to avoid mutations, but you can also avoid mutations by not mutating the model yourself.

**Comment by tunnckoCore** [comment]
> Can you freeze a number or an array or is it limited to objects?

No. In ES2015 it will return it, in below versions it will throw TypeError.

> What about simply not changing the model?

For same reason, that most devs use `flow`/`typescript` - guarantees, I kinda still don't like them, as I don't like the native `assert` and massive usage of it then "unassertifyfyfyfyfyf" (like Yosh and browserify & co devs does).

**Comment by jbucaran** [comment]
Thanks for supporting HyperApp, I like it too ;) but let's not derail this thread or any other to criticize choo. choo was a big source of inspiration for HyperApp. 

With regards to the issue at hand, I have nothing against object.freeze, but I don't know if it is worth having at all.

Let's keep this issue open to encourage the discussion.

**Comment by tunnckoCore** [comment]
>  but let's not derail this thread or any other to criticize choo. choo was a big source of inspiration for HyperApp.

Yea, it is great in anyway, I just sharing my view points.

**Comment by jbucaran** [comment]
@tunnckoCore Feel like we can close this?

**Comment by tunnckoCore** [comment]
yea, it is clear :)

**Comment by okwolf** [comment]
There's a mixin solution for this: https://github.com/okwolf/hyperapp-freeze

**Comment by charlike** [comment]
@okwolf that's cool idea, but any reasonable and logical reason to hardcode the `deep-freeze` package instead of including it as normally and expose cjs, es and umd bundles (with rollup for example, it's pretty easy)?

**Comment by jbucaran** [comment]
@charlike Yeah, I think he was in hurry. 

@okwolf This should be good to get you started. 

- https://github.com/okwolf/hyperapp-logger/pull/1

Same applies to hyperapp-freeze, etc.

**Comment by okwolf** [comment]
@charlike yes @jbucaran is correct, `hyperapp-freeze` will get cleaned up after the `hyperapp-logger` refactor is complete.
