### ISSUE TITLE
Add immutability docs

### ISSUE THREAD

**Issue by aeosynth** [hyperapp/hyperapp#501]
The quickstart briefly states "An action must never mutate the state directly", but no reason is given, and nothing seems to break if the state is mutated. Related, memoization support is never mentioned; an example on how to implement it would be nice.

**Comment by JorgeBucaran** [comment]
@aeosynth I'd love this as well. Can you help us? What were you trying to do?

> nothing seems to break if the state is mutated

It does break! Look:


```js
// The only recommended way. State updates and view re-renders.
setValue: value => state => ({ value })


// No state update or re-render.
setValue: value => state => {
  state.value = value
  return state 
  //  This actually works (only for shallow copies, no deep updates), but why would you
  // do it like this when you have a better option (first choice above).
  // return Object.assign({}, state) 
}
```

**Comment by aeosynth** [comment]
I'm updating an array:

```js
// mutate
setValue: i => state => {
  state.array[i].n = 5
  return {}
}

// copy
setValue: i => state => {
  const array = state.array.map((el, index) =>
    i === index ? Object.assign({}, el, { n: 5 }) : el
  )
  return { array }
}
```

state slices don't work on arrays, so I have to drop immutability in favor of simplicity.

**Comment by JorgeBucaran** [comment]
@aeosynth I prefer the immutable approach, but if you are okay with adding little hacks into your actions and you can make sure it doesn't explode I don't oppose! 😏

**Comment by okwolf** [comment]
@JorgeBucaran done is better than perfect, regardless of the way we want the world to be.

**Comment by JorgeBucaran** [comment]
@aeosynth Oh, nice hehe. Do keep in mind that this is not the way it is intended to be used. If it works, then it works and that's great, but when it breaks you are on your own. 😄

**Comment by andyrj** [comment]
@aeosynth Addy Osmani has a good memoization(), https://www.google.com/url?sa=t&source=web&rct=j&url=https://addyosmani.com/blog/faster-javascript-memoization/&ved=0ahUKEwia0auVsZrYAhUJxmMKHQyZBpYQFgglMAA&usg=AOvVaw3VF6oIUqLCT1LWnw4Ywl9h.  But for simplicity, you can save your vnode reference and reuse it with just a variable if it's static.  Example codepen I made when helping add the patch shortcircuit for memoization, this codepen was used to get perf numbers on the memo vs no-memo for comparison.  https://codepen.io/andyrj/pen/yzzmLo

**Comment by Swizz** [comment]
(@andyrj I eddited your comment to fix the link)

**Comment by JorgeBucaran** [comment]
I am going to close as I touched on the concept a bit in the latest push. Perhaps not the most adequate, but it's something.

> Every state update is immutable and produces a new object, allowing cheap memoization of the view and components using a strict `===` check.

**Comment by gamebox** [comment]
I know this is closed, but something I've noticed that sticks out like a sore thumb is calling multiple actions within an action and them not returning the new state, but somehow it just working?  An explanation of the mechanic here would be helpful.  Seems like if actions can be "composed", then we should be getting back the new state from each such call.

**Comment by JorgeBucaran** [comment]
@gamebox Actions actually return what the action returns. I find this behavior more intuitive.  

```js
myAction: data => data
```

The action returns `data`. This means you'll usually get the substate back from actions, which is what you are saying essentially.

> ...calling multiple actions within an action and them not returning the new state, but somehow it just working?

Hmm. I am not sure what you mean. Yes, you can call other actions inside other actions. Those kind of actions are conventionally called "side effects".

> I know this is closed...

Oh, that doesn't mean much! If you think this is not done or something could be done better, please create a PR or hop on slack and tells us about it! 😄
