### ISSUE TITLE
Monorepo?

### ISSUE THREAD

**Issue by okwolf** [hyperapp/hyperapp#505]
Today the official Hyperapp ecosystem consists of [four](https://github.com/hyperapp/hyperapp) different [repositories](https://github.com/hyperapp/html) hosted [in](https://github.com/hyperapp/router) the same [organization](https://github.com/hyperapp/logger). The supporting libraries all have `devDependencies` and `peerDependencies` on particular versions of `hyperapp` that need to be kept up-to-date. Managing them all as a single repository would allow for refactoring/testing/releasing compatible versions of all at once. Perhaps this coordination isn't too painful with four packages, but it's still there.

Monorepos are already used by many successful projects like [Babel](https://github.com/babel/babel/tree/master/packages), [React](https://github.com/facebook/react/tree/master/packages), [Angular](https://github.com/angular/angular/tree/master/modules), [Ember](https://github.com/emberjs/ember.js/tree/master/packages), [Meteor](https://github.com/meteor/meteor/tree/devel/packages), [Jest](https://github.com/facebook/jest/tree/master/packages), and others. If we decided to move forward with this approach, there are tools to assist with managing multiple packages in a single repo such as [Lerna](https://github.com/lerna/lerna#about).

**Comment by JorgeBucaran** [comment]
I don't understand what's the problem monorepos is trying to solve.

**Comment by okwolf** [comment]
> @JorgeBucaran I don't understand what problem "monorepos" are trying to solve.

It's similar to the differences between a monolith app architecture vs microservices. If the different packages are isolated enough to minimize dependencies (both literal code and in terms of testing) then it's more of an issue of style/management than a technical problem.

Even though our libraries do have some interdependencies, I'm not currently convinced that moving to a monorepo would be an improvement. I was mostly bringing this up since this is a common practice I have seen on other projects and I hadn't seen a discussion on it here before.

**Comment by selfup** [comment]
I vote no. Our current structure works, and I have seen a lot of orgs work like we do. Especially Vue 🎉

**Comment by okwolf** [comment]
Does anyone else want to weigh in on this, or are we unanimous and should close?

**Comment by JorgeBucaran** [comment]
@lukejacksonn @SkaterDad Ping.

**Comment by okwolf** [comment]
Also _poke_ @Alber70g who 👍 'd this

**Comment by JorgeBucaran** [comment]
And @BenGale too

**Comment by SkaterDad** [comment]
Keeping the repositories separate seems fine.  Especially now that the API is likely to be stable.

**Comment by Alber70g** [comment]
In retrospect I'd say it'd be better to have it when the API was still in 'breaking' mode. Right now I still think it would be nice to have it all together and releasing using Lerna. But it's more of a "niceity" than a necessity. 

Unless of course we're already planning on version 2.x and we want to create a 2.0-alpha. Then it's nice to have it all toghether so we can update the several packages in one go.

**Comment by okwolf** [comment]
I like @Alber70g suggestion, so maybe let's revisit this when we start thinking about 2.x? 🤔

**Comment by JorgeBucaran** [comment]
Considering how simple Hyperapp is, both the source code and the bundling step (we are not even using a rollup config file!) I think that introducing a Lerna is unjustified.
