### ISSUE TITLE
I have problem while using parceljs

### ISSUE THREAD

**Issue by ookangzheng** [hyperapp/hyperapp#506]
<img width="1371" alt="screen shot 2017-12-25 at 7 11 36 pm" src="https://user-images.githubusercontent.com/6301735/34338847-84c63654-e9a7-11e7-8a1f-235ac6bfe0c5.png">
I mean like it can't recognise JSX syntax

**Comment by JorgeBucaran** [comment]
@ookangzheng I am not familiar with parceljs, but maybe you need to add something like:

```
{
	"presets": ["env"],
	"plugins": [
		["transform-react-jsx", { "pragma": "h" }]
	]
}
```

...to your .babelrc file?

**Comment by ookangzheng** [comment]
hmm, Ya, also I've to install this pkg
npm i babel-plugin-transform-react-jsx 
than the problem was solved

**Comment by JorgeBucaran** [comment]
@ookangzheng Great! 😄👍

**Comment by Swizz** [comment]
I use parceljs with Hyperapp since some days, considering using it on all project. It is really good 👍

**Comment by ookangzheng** [comment]
I created a Hyperapp parceljs bundler with node-sass and postcss supported
[](https://github.com/ookangzheng/hyperapp-parcel)

**Comment by JorgeBucaran** [comment]
Wow, this is super useful, thanks @ookangzheng! 🎉
