### ISSUE TITLE
More than one action breaks actions!

### ISSUE THREAD

**Issue by zaceno** [hyperapp/hyperapp#508]
Sorry guys, I know we're chomping at the bit 1.0, but I found this really wierd & serious bug...

See this codepen: https://codepen.io/zaceno/pen/JMWjwQ

Try typing in the input field. Notice that it works. Now: uncomment L12 ( `otherAction: _ => ({otherVal: true})`) 

💥

...the input field breaks. From my debugging, it looks like the `set` action isn't called even.

(... if this is a user error, I'm going to be very embarrassed...)

**Comment by mietennet** [comment]
if i'm change the order of the actions it works again... wired

**Comment by SkaterDad** [comment]
Definitely looks like a bug with 0.18.1.

If you change the script reference to `https://unpkg.com/hyperapp@0.18.0` it works.

**Comment by whaaaley** [comment]
Looks like the `otherAction` is getting called on accident somehow.

**Comment by selfup** [comment]
🤔

**Comment by okwolf** [comment]
I noticed that the [counter example](https://codepen.io/hyperapp/pen/zNxZLP?editors=0010) now only calls the `up` action. [Adding a NOP action](https://codepen.io/okwolf/pen/wpJMBr?editors=0010) breaks the example entirely 😮 

Switching back to 0.18.0 fixes both of these issues for me... 🤔

**Comment by JorgeBucaran** [comment]
@zaceno @okwolf @whaaaley @selfup Can you reproduce this locally or is it only a CodePen problem? 

My local examples work as usual. 🤔

**Comment by JorgeBucaran** [comment]
I think this could be a bug in uglify-js, we're going to need to downgrade.

**Comment by okwolf** [comment]
@JorgeBucaran confirmed that it works with the non-uglified bundle for 0.18.1. How bizarre...

**Comment by JorgeBucaran** [comment]
Maybe related. https://github.com/mishoo/UglifyJS2/issues/2663

**Comment by JorgeBucaran** [comment]
Fixed in 0.18.3! 🎉
