### ISSUE TITLE
svg props don't render

### ISSUE THREAD

**Issue by aeosynth** [hyperapp/hyperapp#509]
```js
const { h, app } = hyperapp
const view = () =>
  h('svg', {},
    h('rect', {
      width: 50,
      height: 50,
      fill: 'black'
    })
  )
app({}, {}, view, document.body)
```

the created `rect` element does not have a width or height

**Comment by JorgeBucaran** [comment]
Whoops, I broke something SVG! 😓 

Working on a fix right now.

**Comment by JorgeBucaran** [comment]
@aeosynth Thanks! Fixed and published as 0.18.3 🔥

**Comment by aeosynth** [comment]
thanks, it displays correctly, but my `onclick` doesn't work on svg now

**Comment by JorgeBucaran** [comment]
@aeosynth Fixed again! 😄
