### ISSUE TITLE
Examples as a standalone repository

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#51]
It's tough copying and pasting code from Gomix or your ready snippets trying to piece them together as something that runs locally. It would be nice if there was another repository under hyperapp for examples.

**Comment by jbucaran** [comment]
Yes. https://github.com/hyperapp/hyperapp/issues/41 comes to mind as well.

**Comment by jbucaran** [comment]
@rbiggs Are you familiar with Gomix? There's tons of examples there and they are downloadable or exportable to GitHub.

**Comment by rbiggs** [comment]
Hmmm... I'm on Gomix but I don't see any option to download your examples. At the same time, seems like Hyperapp is still going through a lot of churn with its API, making it hard to keep separate examples updated. That said, it is brainless easy to download your Codepen examples.

**Comment by jbucaran** [comment]
> Hyperapp is still going through a lot of churn with its API

Internally, yes, but the API is hopefully locked by now. There was an incident recently wrt to camelCase event names, but other than that we're not going to see any major changes. I'll release 1.0.0 when the book is ready and more examples are available, perhaps a live site or two.

For the record, in gomix, go to Project info and options, then select Advanced Options.


<img width="568" alt="screen shot 2017-02-19 at 23 41 59" src="https://cloud.githubusercontent.com/assets/56996/23103352/9f3e561c-f6fd-11e6-8fdb-30978a73c1d7.png">

<img width="771" alt="screen shot 2017-02-19 at 23 41 14" src="https://cloud.githubusercontent.com/assets/56996/23103355/a43e64e0-f6fd-11e6-867d-50a4e99abb6c.png">

**Comment by rbiggs** [comment]
All I see is this
![screenshot](https://cloud.githubusercontent.com/assets/249218/23103785/ad79c0b4-f675-11e6-9b18-a7fa236021e8.png)

**Comment by rbiggs** [comment]
Any way, I did a copy/past from here to local versions. Everything runs local with Webpack building, etc. The only issue I've had was getting setLocation to work without Browserify. But then, you removed that example from GoMix.

**Comment by jbucaran** [comment]
@rbiggs Oh, okay, I see what's going on. You'd think Gomix would allow you to download whatever you wanted, but it seems that's not how it works, instead you need to "Remix This", which is their equivalent of GitHub's fork. 

Then, you'll be the administrator of your own copy and you'll be able to download/export.

**Comment by rbiggs** [comment]
Oh, I see. 🙄 But of course they don't mention that anywhere, so I was clicking on things around in a circle for a half hour. Googled, etc. In the end I got what I wanted by copy/pasting because I didn't what them running with Browserify. I made each example standalone with its own server instance and a Webpack config to create a bundle. That way it's easier to fiddle with each example, add other things, etc.

**Comment by jorgebucaran** [comment]
**Status Update**: We're not using ~~Gomix~~ Glitch to host code examples anymore, but there are many [**examples available on CodePen**](https://codepen.io/search/pens?q=hyperapp&page=1&order=popularity&depth=everything&show_forks=false). I keep my own pens always up-to-date; can't speak for others. I still don't want to maintain code examples in this repository.

---
