### ISSUE TITLE
Putting the content of the docs at more logical places.

### ISSUE THREAD

**Issue by Alber70g** [hyperapp/hyperapp#514]
Guys, I hope I'm not messing up a lot of people, but I felt the docs weren't as usable as I'd like. I've changed it a fair bit and I'd like your opinion. Feel free to set it all aside, it's been not as much work as it looks like. I've added a PR where you can find it all: #513

**Comment by JorgeBucaran** [comment]
Thanks @Alber70g, let's discuss this on #513 then! 👋
