### ISSUE TITLE
Preformance benchmarking

### ISSUE THREAD

**Issue by SilentCicero** [hyperapp/hyperapp#523]
As with dot-dom (another project I helped out with). What is the preformance like against react/preact proper?

A comparison chart would be helpful and potentially up your adoption.

**Comment by okwolf** [comment]
@SilentCicero see #499. We mostly look at [js-framework-benchmarks](https://github.com/krausest/js-framework-benchmark). The latest results are [here](http://www.stefankrause.net/js-frameworks-benchmark7/table.html). We are nearly the fastest in startup time, and toward the middle for most of the others.

**Comment by selfup** [comment]
Also I think we should compare to `Vue/Vuex` and `React/Redux` since we do indeed have a pure and immutable store/single source of truth, instead of just comparing Vue or React alone. 

If not, I completely understand, but we should compare apples to apples 😄 

***

It seems that benchmark is Hyperapp 0.16.x

I wonder if we should update that run.

***

I also am not too clear on how useful these benchmarks are, considering 90+% of apps won't have more than 4k nodes per page (which is a lotttttt for being conservative)...

**Comment by okwolf** [comment]
@selfup we should definitely update our benchmark to 1.0.0 so that is used for the next round of results. If @JorgeBucaran isn't already working on this I could make the PR.

**Comment by selfup** [comment]
Yea I am down for whatever. I guess now we wait 🕥 to find out if it being worked on or not haha

**Comment by okwolf** [comment]
The current keyed version is the only one I can compare directly with [React](https://reactjs.org/)/[Redux](https://redux.js.org):
![screen shot 2017-12-31 at 15 47 34](https://user-images.githubusercontent.com/3735164/34464716-fd5e128c-ee41-11e7-9afd-ff181a862dac.png)

We're in the same ballpark for everything but partial update and remove row. I also threw in [Elm](http://elm-lang.org), for obvious reasons.

**Comment by selfup** [comment]
Thanks for taking the time to do this!

**Comment by JorgeBucaran** [comment]
@SilentCicero Sounds like everyone beat me to it!

See also:
- https://github.com/hyperapp/hyperapp/issues/499
- https://github.com/hyperapp/hyperapp/issues/75

**Comment by JorgeBucaran** [comment]
@SilentCicero If you have any other questions or want to see something else, let me know in #499.

**Comment by jorgebucaran** [comment]
@SilentCicero V2's new patch algorithm (based on [Superfine](https://github.com/jorgebucaran/superfine)) is significantly faster than V1 (#499). Here are the benchmark results. To maximize performance, the benchmarked example app makes use of memoization to boost the rendering perf of table rows that are not affected by state changes. This technique will eventually make it into core as described in #721.

![Superfine](https://user-images.githubusercontent.com/56996/42416263-ee50cec2-82a4-11e8-99fd-021a23e34f05.jpg)
