### ISSUE TITLE
[Question] How to setup Rollup config?

### ISSUE THREAD

**Issue by bdsomer** [hyperapp/hyperapp#524]
What's the proper way to configure my [Rollup configuration](https://rollupjs.org/#using-config-files) to compile `hyperapp`'s JSX into regular JavaScript?

**Comment by selfup** [comment]
@lukejacksonn would know!

I still think rollup should only be used for libraries, but it is very simple to use. So for small projects (that don't need code splitting/dynamic imports/rust/WASM) then rollup will be fine 🎉

**Comment by okwolf** [comment]
Perhaps try this [with](https://github.com/konsumer/rollup-plugin-jsx) with `jsx( {factory: 'h'} )`?

**Comment by selfup** [comment]
https://github.com/lukejacksonn/hyperapp-pwa/blob/master/rollup.config.js

or for a simpler config:

https://github.com/lukejacksonn/hyperapp-starter/blob/master/rollup.config.js

**Comment by JorgeBucaran** [comment]
Hi @bdsomer! Thanks for trying out Hyperapp. The following instructions worked out for me:

In a new directory, create an <samp>index.html</samp> file:

```html
<!doctype html>
<html>

<body>
<script src="bundle.js"></script>
</body>

</html>
```

And an <samp>index.js</samp> file:

```jsx
import { h, app } from "hyperapp"

const state = {
  count: 0
}

const actions = {
  down: () => state => ({ count: state.count - 1 }),
  up: () => state => ({ count: state.count + 1 })
}

const view = (state, actions) => (
  <main>
    <h1>{state.count}</h1>
    <button onclick={actions.down}>-</button>
    <button onclick={actions.up}>+</button>
  </main>
)

app(state, actions, view, document.body)
```

Install dependencies:

<pre>
npm i <a href="https://www.npmjs.com/package/hyperapp">hyperapp</a>
</pre>

Install dev dependencies:

<pre>
npm i -D \
  <a href="https://www.npmjs.com/package/rollup">rollup</a> \
  <a href="https://www.npmjs.com/package/rollup-plugin-babel">rollup-plugin-babel</a> \
  <a href="https://www.npmjs.com/package/rollup-plugin-node-resolve">rollup-plugin-node-resolve</a> \
  <a href="https://www.npmjs.com/package/rollup-plugin-uglify">rollup-plugin-uglify</a> \
  <a href="https://www.npmjs.com/package/babel-core">babel-core</a> \
  <a href="https://www.npmjs.com/package/babel-preset-es2015-rollup">babel-preset-es2015-rollup</a> \
  <a href="https://www.npmjs.com/package/babel-plugin-transform-react-jsx">babel-plugin-transform-react-jsx</a>
</pre>

Create a <samp>rollup.config.js</samp> file:

```jsx
import babel from "rollup-plugin-babel"
import resolve from "rollup-plugin-node-resolve"
import uglify from "rollup-plugin-uglify"

export default {
  plugins: [
    babel({
      babelrc: false,
      presets: ["es2015-rollup"],
      plugins: [["transform-react-jsx", { pragma: "h" }]]
    }),
    resolve({
      jsnext: true
    }),
    uglify()
  ]
}
```

Bundle the application:

<pre>
$(<a href="https://docs.npmjs.com/cli/bin">npm bin</a>)/rollup -cf iife -i index.js -o bundle.js
</pre>

Open index.html on your browser.

```
open index.html
```

**Comment by JorgeBucaran** [comment]
Closing as resolved, but anyone feel free to add your own incantations or recipes to the mix. 👋

**Comment by bdsomer** [comment]
@JorgeBucaran This is perfect, thanks!
