### ISSUE TITLE
Travis is currently having issues with their containers building

### ISSUE THREAD

**Issue by selfup** [hyperapp/hyperapp#528]
### TravisCI

So others are reporting on the TravisCI repo that there are issues.

Here is the most likely candidate (disk quota saturation it seems): https://github.com/travis-ci/travis-ci/issues/8991

### Hyperapp

Here is the failed build for us: https://travis-ci.org/hyperapp/hyperapp/jobs/323756469

_Just letting everyone know before we merge any PRs prior to this being resolved_ 🙏 

***

We can close this issue once TravisCI is building Linux machines ok 🎉

**Comment by selfup** [comment]
So TravisCI is building the machines ok but they seems to be having network issues now 😭

**Comment by SteveALee** [comment]
did it just work? https://travis-ci.org/hyperapp/hyperapp/builds/324652789

**Comment by okwolf** [comment]
@selfup is this resolved now? My Travis projects seem to be building fine.

**Comment by selfup** [comment]
Let me check!

**Comment by selfup** [comment]
Ok well the good news is that not having access to WAN makes the build fail and will force us to restart one of the node builds regardless. 

Issue on TravisCI: https://github.com/travis-ci/travis-ci/issues/9000

So yea, we can close! 🎉
