### ISSUE TITLE
Subs or Substitutions?

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#53]
I really like the API, a complete copy of ElmArchitecture in JavaScript. My only peeve is `subs`. I think it would be better to use the term `subscriptions` like Elm and Choo. I remember the first time I looked at the counter example and saw the sub function in the update method. I immediately assumed it was a singular instance of subs, whatever they were. Then when I saw the subs in actions I was thinking, hmmm... substitutions?, subtractions? subordinations? subscripts? or maybe he wants to give us all foot long subs!!! Yay! I'll have two please. OK,  I know you used `subs` to save a few letters typing, but going forward if you want this project to gain traction it would be better to use the more explicit term `subscriptions` to save people the mental work of constantly translating subs to subscriptions in our heads. Even in your `README` you describe `subs` as: Subscriptions are functions that run once when the DOM is ready. Use a subscription to register global events, like mouse or keyboard listeners. I'm suspecting you probably just lobbed off the tail end of pubsub for the term. My point is explicit terms are always better than implicit terms in API design. It's not like people would have to type the term a thousand times. It's just once. Then when you scan the page and see `subscriptions` it would be immediately clear what you are looking at, even if you were not familiar with this API.

**Comment by jbucaran** [comment]
>  It's not like people would have to type the term a thousand times. It's just once. T

Good point.

What do you folks think? @danigb @itrelease @maraisr @tzellman @evgenykochetkov @terkelg

I'm 💯 with the idea.

**Comment by itrelease** [comment]
I think it's a good idea considering that it's inspired by `Elm.App` it would be nice to go along with same naming for api

**Comment by tunnckoCore** [comment]
I was thinking the same thing. `subscriptions` is better if you want shorter name `subscribes` is better than `subs` too.

**Comment by tzellman** [comment]
I like `subs` for brevity, but I agree that `subscriptions` may be more obvious. You could always settle with `var subs = options.subscriptions || options.subs || {}`.

**Comment by terkelg** [comment]
I agree, good idea!

**Comment by rbiggs** [comment]
subs is an array, so its description should be a noun, not a verb. subscribes would indicate a function.

**Comment by jbucaran** [comment]
@rbiggs Changed to subscriptions. Code still handles and will handle .subs for a while, after 0.0.13, examples have been updated and due mourn time has been given.

**Comment by dodekeract** [comment]
@rbiggs Can this be closed?

@jbucaran Is there anything else to do before releasing `0.0.13`? I'd like to have the `subscriptions` fix  available for usage. 🙂
In addition to that `0.0.12` changed the import to `hyperapp/hx` and the longer we wait to undo this the more people will use that change just to undo it in `0.0.13`.

**Comment by jbucaran** [comment]
Shipped. See the [release notes](https://github.com/hyperapp/hyperapp/releases/tag/0.0.13).
