### ISSUE TITLE
conceptual similarity with emotion-js

### ISSUE THREAD

**Issue by le93us** [hyperapp/hyperapp#536]
Hi, author,

have you plans for "integration" conceptual similar [emotion.js](https://github.com/emotion-js/emotion) css-in-js library with `hyperapp`?

Using both is interesting combination to write web app completely in `js`/`ts`.

**Comment by JorgeBucaran** [comment]
@le93us I am not familiar with emotion.js, but if it can work with any view library, then it can surely work with Hyperapp too! 😄  

See also: [Picostyle](https://github.com/picostyle/picostyle).
