### ISSUE TITLE
Using requestAnimationFrame to improve performance on rendering

### ISSUE THREAD

**Issue by jscriptcoder** [hyperapp/hyperapp#538]
Consider the idea of using requestAnimationFrame for rendering DOM. 

```javascript
function repaint() {
  if (!patchLock) {
    patchLock = !patchLock
    //setTimeout(render)
    requestAnimationFrame(render)
  }
}
```
Not sure if this is a decision just for simplicity. If so, ignore this ticket ;-)... By the way, good job.

Fran

**Comment by Swizz** [comment]
Hi !

Thank you for your issue, I hope you enjoy to use Hyperapp.

Unfortunately this is a debate we had late in the past, here is the issue when we decided to add raf in core #286.
And sometimes after the issue we took the decision to remove it #422.

Plus, now we removed the use of raf and the mandatory on the Vdom. Hyperapp is now fully usable in a Nodejs context 🎉

**Comment by JorgeBucaran** [comment]
@jscriptcoder We naively used to do this, but it actually causes issues with background/inactive tabs, so no, we can't switch to rAF. But nothing prevents you from using rAF in your app to "optimize rendering performance" in whatever it is you are doing. 😄  

> requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life. [Source](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

**Comment by jscriptcoder** [comment]
Hi all,

Wow, that was a super quick answer. Super alive project... Sorry I didn't bother to do some research before dropping the question. I simply landed on the project from an article I read in Medium Digest and first thing I did was to dig into the source code, and found this line.

Once again, great job, and keep it up :-)

Fran

**Comment by JorgeBucaran** [comment]
@jscriptcoder No problem! You had a good question and we answered it, that's all. Cheers and welcome aboard! :)
