### ISSUE TITLE
A fully available project demo

### ISSUE THREAD

**Issue by kingzez** [hyperapp/hyperapp#539]

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/awesome

**Comment by JorgeBucaran** [comment]
Also, check out our [contribution guidelines](https://github.com/hyperapp/hyperapp/blob/master/docs/CONTRIBUTING.md) and let's try to be more considerate when creating an issue. If you just have a question, consider joining our [Slack](https://hyperappjs.herokuapp.com/) team. 👋
