### ISSUE TITLE
Calling actions from within an action

### ISSUE THREAD

**Issue by warwickgrigg** [hyperapp/hyperapp#544]
I am getting some results I'm finding difficult to comprehend when I am calling actions from within an action, eg. the action setS1rS2 (on button S1rS2) compared to action setS1S2 in jsfiddle [https://jsfiddle.net/WarwickGrigg/eo537smc/](https://jsfiddle.net/WarwickGrigg/rqqzqb9n/)

Using latest hyperapp v 1.0.1. Excerpt below:
```
const actions = {
  setS1: dt => (_, actions) => { return {s1: dt} }, // changes state
  setS2: dt => (_, actions) => { return {s2: dt} }, // changes state
  setS1S2: dt => (_, actions) => {
    actions.setS1(dt); // changes state
    actions.setS2(dt); // changes state
  },
  setS1rS2:dt => (_, actions)  => {
    actions.setS1(dt); // no effect (!)
    return {s2: dt};   // changes state for s2
  },
```
Results are different but even more confusing (for me) if I remove the '=> (_, actions)' action function wrapper. Is there something special about calling actions from within an action?

**Comment by JorgeBucaran** [comment]
@warwickgrigg Nice find! I introduced this bug [here](https://github.com/hyperapp/hyperapp/blob/2eddfd65d93f336d5083e83c51626bc9e27165e7/src/index.js#L101-L108).

We need to compute the substate/slice again before merging with the state.

I'll fix this over the weekend.

**Comment by JorgeBucaran** [comment]
Okay, I found the fix changing [line 107](https://github.com/hyperapp/hyperapp/blob/2eddfd65d93f336d5083e83c51626bc9e27165e7/src/index.js#L107) to:

```js
if (data && data !== (slice = get(path, state)) && !data.then) {
  repaint((state = set(path, copy(slice, data), state, {})))
}
```

**Comment by warwickgrigg** [comment]
Thanks, Jorge. And thank you for hyperapp - very promising and elegant. I've created a jsfiddle fork here [https://jsfiddle.net/WarwickGrigg/rqqzqb9n/](url) with the action functions omitting the => (_, actions) wrapper, annotating the results:
`
const actions = {
  setS1: dt => { return {s1: dt} }, // changes state
  setS2: dt => { return {s2: dt} }, // changes state
  setS1S2: dt => {
    actions.setS1(dt); // no effect
    actions.setS2(dt); // no effect
  },
  setS1rS2:dt => {
    actions.setS1(dt); // no effect (!)
    return {s2: dt};   // changes state for s2
  },
  setS1cS2:dt => {
    s1obj = actions.setS1(dt); // assume no effect (?), but returns obj
    return Object.assign([], s1obj, {s2: dt}); // changes state
`

**Comment by JorgeBucaran** [comment]
@warwickgrigg Done! 💪

**Comment by JorgeBucaran** [comment]
@warwickgrigg Published as `1.0.2`! 🎉 

Turns out the [fractals example](https://codepen.io/hyperapp/pres/JJVzBW?editors=0010) was a victim of this bug, but it now works again.

**Comment by infinnie** [comment]
But isn’t it good to never, ever rely on multiple synchronous state updates and merge them before returning something instead?

**Comment by JorgeBucaran** [comment]
@infinnie What?

**Comment by maxbaluev** [comment]
how i can use it now?

**Comment by zaceno** [comment]
@maxbaluev use what?

Calling actions in actions, in the latest release 1.2.6 (or is it 1.2.9?) works as described above.

Calling actions in actions won't work in V2. Instead you will have to compose the actions, like @infinnie suggested earlier in this thread.
