### ISSUE TITLE
Broken link in "Docs/Introduction/Hello-World.md" to "virtual node".

### ISSUE THREAD

**Issue by dance2die** [hyperapp/hyperapp#545]
As I was reading [hello-world -> view section](https://github.com/hyperapp/hyperapp/blob/master/docs/introduction/hello-world.md#view) in the documentation,

I found a broken link to a [virtual node](https://github.com/hyperapp/hyperapp/blob/master/docs/introduction/vnodes.md) documentation.

![image](https://user-images.githubusercontent.com/8465237/34641507-89f3aa14-f2d3-11e7-9a6f-d9beed9c7045.png)

I dug up an old issue [Virtual Node Docs](https://github.com/hyperapp/hyperapp/pull/457), which points to [another location](https://github.com/hyperapp/hyperapp/blob/master/docs/concepts/vnodes.md) for virtual node documentation.

If this is recognized an issue, I could do a PR to update the broken URL to the correct Virtual Node documentation.

**Comment by JorgeBucaran** [comment]
@dance2die Yes, please! 🙏

**Comment by okwolf** [comment]
Looks like it should have probably been https://github.com/hyperapp/hyperapp/blob/master/docs/concepts/vnodes.md
