### ISSUE TITLE
problem with asynchronous action

### ISSUE THREAD

**Issue by adekbadek** [hyperapp/hyperapp#549]
Hi, I'm not sure if it's a bug or just my lack of understanding. Given the following actions:

```jsx
const actions = {
  updateUsername: (username) => (state, actions) => {
    getUserData(username)
      .then(actions.setUserData)
    return {username}
  },
  setUserData: userData => state => ({userData}),
}
```

After `updateUsername`, the `setUserData` is being called, however the view is not updated, and neither is the `state` object. 
Curiously, the state looks as expected in [hyperapp-redux-devtools](https://github.com/andyrj/hyperapp-redux-devtools).

using hyperapp `@1.0.1`

**Comment by SkaterDad** [comment]
Looks like it works when I try?  Here is a Codesandbox to play with:  https://codesandbox.io/s/8lxvxlvwy2

**Comment by adekbadek** [comment]
Turns out the problem was with hyperapp-redux-devtools 😮 , I'll open and issue there
Thank you and sorry for the trouble
