### ISSUE TITLE
Codepen Examples Broken

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#56]
All the Codepen examples broke due to naming changes in version 0.0.12.

**Comment by jbucaran** [comment]
@rbiggs Yes, I'm fixing them now. 👍

**Comment by jbucaran** [comment]
JSX one is working already. http://codepen.io/jbucaran/pen/ggjBPE

**Comment by rbiggs** [comment]
I noticed. By the way, when do you sleep?

**Comment by danigb** [comment]
Congrats! 👏

**Comment by jbucaran** [comment]
@rbiggs All examples updated.

For those interested in the new HyperApp + JSX integration, check out this collection of pens.

[HyperApp + JSX](http://codepen.io/collection/DEgQwW/)

**Comment by rbiggs** [comment]
I forked your Codepen counter example and made it pretty :-P. http://codepen.io/rbiggs/pen/zNJGNz

**Comment by jbucaran** [comment]
@rbiggs Sweet! 👌

**Comment by rbiggs** [comment]
Now I did the todos example: http://codepen.io/rbiggs/pen/BpOoNz
Making this link back to here.

**Comment by selfup** [comment]
@jbucaran @rbiggs I am running into some weird issue with JSX.

The initial component renders fine, but no events fire any updates 🤔 

http://codepen.io/selfup/pen/WRgOrR?editors=0110

**Comment by tzellman** [comment]
I believe your events should be `onclick` instead of `onClick`, and likewise for `onkeyup` and `onkeydown`.

**Comment by selfup** [comment]
I tried that, but I can try again. I was under the impression that JSX preffered `onClick`? *TIL* 👍

**Comment by selfup** [comment]
@tzellman omg that totally worked! I guess **React** prefers `onClick` vs. `onclick`

This can get messy with people using the `class` keyword, but that can be mitigated 😄

**Comment by jbucaran** [comment]
@selfup JSX is transformed to `createElement`, which is the agent parsing the string "onClick".
 
Similarly, with HyperApp, when using the pragma comment directive `/** jsx h */`, the one parsing the event name is the function `h`. 

We could simply introduce a `prop.toLowerCase()`... 🤔

**Comment by selfup** [comment]
@jbucaran that could be very nice! Nice thought

**Comment by tzellman** [comment]
Cool! I am by no means a JSX expert, I just tried the changes in your pen and it worked. TIL for me as well. :-)

**Comment by selfup** [comment]
Ok whew I just made a mistake editing when using `cmd + d` I had:

```javascript
const direction = e.target.classNameName;
```

instead of `className` :rofl: 

False ⏰

**Comment by rbiggs** [comment]
I'd say it's best to automatically convert case for users to avoid unintended errors. Typing habits can be hard to break.

**Comment by jbucaran** [comment]
> @selfup False ⏰

You mean something's broken? 🤔

**Comment by jbucaran** [comment]
@rbiggs Okay.

The relevant code is probably [this](https://github.com/hyperapp/hyperapp/blob/master/app.js#L200).

Can you make a PR w/ that? I'll merge-ge-ge it.

**Comment by selfup** [comment]
@jbucaran I just meant False Alarm. I made a typo 😂
