### ISSUE TITLE
No documentation for actions?

### ISSUE THREAD

**Issue by infinnie** [hyperapp/hyperapp#560]
It is unintuitive that an action should take only one argument, and then return another function that takes state and actions as parameters which then returns the update. Maybe it is better that documentation be written and added for that.

**Comment by JorgeBucaran** [comment]
I definitely want to include a section about actions, but [**this**](https://github.com/hyperapp/hyperapp/blob/master/docs/introduction/hello-world.md#actions) is all I've managed to put together so far.

> It is unintuitive that an action should take only one argument.

It took us almost a year to arrive at the current API, we tried a lot of different alternatives and I am satisfied with the current signature. I don't know if it's perfect or not, but I think it's close enough.

**Comment by infinnie** [comment]
Thanks again for explaining it to me.

**Comment by JorgeBucaran** [comment]
No problem! Keep those questions coming! 🔥

**Comment by infinnie** [comment]
#531
