### ISSUE TITLE
Unify the difficulty of the sample source code

### ISSUE THREAD

**Issue by sndstudy** [hyperapp/hyperapp#573]
About sample code in the Components section copy and paste like HelloWorld
I think that it would be better to be able to run.

Since HelloWorld was at the very beginning of the document and I was able to confirm the operation by copy and paste, I thought that the samples after that will also be copied and pasted.

- Actually, except Copy and Paste except HelloWorld did not work
- Different degrees of difficulty depending on document
- It becomes not confusing by aligning difficulty level

HelloWorld sample code has Hyperapp loaded by script tag, but since we are loading Hyperapp with import statement in Components sample code, please write sample code which can be executed by copy and paste just like HelloWorld.

**Comment by marcusasplund** [comment]
@JorgeBucaran I believe you have to correct the [Hello World codepen](https://codepen.io/hyperapp/pen/zNxZLP)

```javascript
// Line 22 -
app(state, actions, view, document.body)
// Line 22 +
window.main = app(state, actions, view, document.body)
```

**Comment by JorgeBucaran** [comment]
I think we can close here now that #579 was merged. There are still tons to do, but we are in a better place in terms of docs now. Thank you, @sndstudy and @marcusasplund.
