### ISSUE TITLE
Side effects over-write state changes

### ISSUE THREAD

**Issue by mrozbarry** [hyperapp/hyperapp#575]
I came across an issue where I'm using [AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) to create looping beats.

As a minimum example:

```javascript
import { h, app } from 'hyperscript';

const initialState = {
  context: new AudioContext(),
  syncInterval: null,
  currentTime: 0,
  text: '',
};

const actions = {
  start: () => (state, actions) => {
    if (state.syncInterval) clearInterval(state.syncInterval);

    state.context.resume();

    return {
      syncInterval: setInterval(() => actions.setCurrentTime(state.context.currentTime), 10),
    }
  },

  stop: () => state => {
    if (state.syncInterval) clearInterval(state.syncInterval);
    state.context.suspend()
    return { syncInterval: null, currentTime: state.context.currentTime };
  },

  setCurrentTime: time => state => ({ currentTime: time }),

  setText: text => state => ({ text: text }),
};

const view = (state, actions) => (
  <div>
    {state.syncInterval === null && <button onclick={() => actions.start()}>Start</button>}
    {state.syncInterval !== null && <button onclick={() => actions.stop()}>Stop</button>}
    <div>Time: {state.currentTime}</div>
    <input value={state.text} onchange={(e) => actions.setText(e.target.value)} />
  </div>
);

const loop = app(initialState, actions, view, document.getElementById('app'));
loop.stop();
```

When you click the start button, try and type anything into the input box. The changes do no persist because setCurrentTime is merging with an old state.

Is this a bug or is there a better way to write this code?

**Comment by SkaterDad** [comment]
Hi!

I believe the reason your code wasn't working is because the `<input onchange=...>` only fires when the input is "blurred" (loses focus).  Because of this, your keystrokes get thrown away since the `value` of the input is being set = the current `state.text`.

Changing your code to use `<input oninput=...>` works as expected, and fires on every keystroke.   A good way to verify this behavior is to `console.log()` inside of the action.

Here is a Codepen showing that `oninput` works (converted to plain `h` functions instead of JSX):  https://codepen.io/SkaterDad/pen/ddbObb

**Comment by mrozbarry** [comment]
I'm guessing it works because it isn't triggering a re-render which would set the value from state. Is there documentation on the difference between oninput and onchange in hyperapp?

**Comment by SkaterDad** [comment]
@mrozbarry You're probably correct about why it works.

hyperapp doesn't abstract away any of the DOM events, so the docs for regular HTML inputs would be relevant.

I believe frameworks like `React` and `Vue` do some things behind the scenes to make `onchange` behave like `oninput`.

**Comment by okwolf** [comment]
Someone should start compiling a list of all the differences between Hyperapp and (for example) React that are not obvious from the documentation. Might even be worth adding to my [compat helpers for React](https://github.com/okwolf/cra-hyperapp).

**Comment by sergey-shpak** [comment]
@SkaterDad 
> To be honest, I'm confused why it works at all before you click the start button.

State is not updated by timer, input value is not refreshed and contains entered keystrokes

**Comment by SkaterDad** [comment]
@mrozbarry Are we good to close this issue?

**Comment by mrozbarry** [comment]
I think so, thanks for the help and feedback!

**Comment by JorgeBucaran** [comment]
I am glad you folks figured it out.

@mrozbarry If you feel something should be documented, please leave a comment in #531! 🙏
