### ISSUE TITLE
Change action signature from (state, actions) to ({ state, actions })

### ISSUE THREAD

**Issue by Siilwyn** [hyperapp/hyperapp#576]
Current actions signature:
`(value) => (state, actions) => ({ count: 2 })`

Desirable actions signature:
`(value) => ({state, actions}) => ({ count: 2 })`

**Why?**
Passing objects as an argument is becoming very popular now that JS has argument destructuring which allows to omit an argument when not needed.
For async actions `state` is often not used and can be used accidentally using an old state. As [noted in the utility actions hypercraft post](https://zaceno.github.io/hypercraft/post/utility-actions/#generic-reducer) this can overwrite changes made while the async action was busy.
Now the following two forms are often used:
```js
(value) => (state, actions) => Promise.resolve(2).then(actions.set)
(value) => (_, actions) => Promise.resolve(2).then(actions.set)
```

The latter is a poor man's way of 'omitting' the `state` argument.

With an object it simply becomes:
`(value) => ({actions}) => Promise.resolve(2).then(actions.set)`

This is just an idea, maybe there is an obvious reason why this isn't possible because of Hyperapp inner workings. 👀

**Comment by JorgeBucaran** [comment]
We definitely toyed with this idea at some point. The main argument against it was it makes destructuring more awkward. There's no perfect signature, just use the one that has been given to you and don't worry too much about it. I am not keen on the idea of breaking the API.

**Comment by JorgeBucaran** [comment]
Thank you, @Siilwyn for the suggestion, but I don't think I'll implement this, mostly for the reason given above and because changing things would just create new problems. It's like arguing which is better: driving on the left or on the right? Just choose a side and stick to it would be my answer.
