### ISSUE TITLE
Keep actions pure by adding controller

### ISSUE THREAD

**Issue by joshrtay** [hyperapp/hyperapp#581]
[Vdux](https://github.com/vdux/vdux#dom-events--actions) has a notion of a controller so that actions can be pure. Just something to consider.

**Comment by JorgeBucaran** [comment]
Hi @joshrtay. What is vdux? Why are actions not pure? What's a controller?

**Comment by olstenlarck** [comment]
Duh.. What you mean with "keep actions pure"? Impure actions are so-called "effects", pure actions are reducers which change/update/replace state.

Damn. Always will repeat that separation between effects and reducers is just brilliant concept and only this little think to define them separately will lead to better result in human heads. Won't have such issues, imo.

**Comment by JorgeBucaran** [comment]
@olstenlarck Please refrain from posting if you have nothing useful to contribute to the discussion.

**Comment by olstenlarck** [comment]
> if you have nothing useful

Please stop attacking me for nothing when i comment once in a while. I have questions and making clarification of the two types of actions.

Also, looking of the Vdux for me too it's not clear what controller is. From their example it seems that `controller` is the place where you define what we usually call "effect" here and in Elm.

**Comment by JorgeBucaran** [comment]
@olstenlarck You have been warned several times, and now you are banned. I don't usually block people, but this is the second time I've blocked you and I am not unblocking you again this time. Good luck to you!

**Comment by joshrtay** [comment]
Vdux is a framework that @ashaffer developed a couple years ago. Has a lot of the same goals as hyperapp. You should take a deep dive. Has a lot of cool ideas :)

@olstenlarck is right. Actions in hyperapp aren't pure cuz they allow for side effects. Vdux has split actions into controllers and reducers. Reducers are pure and update state. Controllers are not and can coordinate async reducer actions.

The advantage of this approach is it keeps updates to state very testable.

Let me know if you have any other questions.

**Comment by nichoth** [comment]
@joshrtay It seems like you could easily separate pure actions from async actions within your application code by organizing them as such.

**Comment by joshrtay** [comment]
ya. i suppose that's true. just depends on how opinionated the framework want to be.

**Comment by JorgeBucaran** [comment]
Splitting up actions into reducers and effects would not make actions more testable because effects would still be effects under the hood, i.e., actions that can do whatever they want. Introducing a "controlled effects" runtime (commands) like in Elm would be a different story and maybe closer to what you had in mind when you created this issue. 

And yes, that would be interesting to pursue, see [@okwolf/hyperapp-effects](https://github.com/okwolf/hyperapp-effects) for a userland approximation.
