### ISSUE TITLE
Looks like patch is trying to remove an element that doesn't exist

### ISSUE THREAD

**Issue by mrozbarry** [hyperapp/hyperapp#584]
## Bug

When adding `<li>` elements to a `<ul>`, if I add an empty tag, next update through the system throws an error.

## Reproduce it

1. Clone https://github.com/LearnHyperapp/hyper-list , npm install, npm run start
2. http://localhost:8080
3. click the input, hit enter 1x
4. type something in the input box
What should happen:
1 empty item in the list, and some input content
What happens:
1 empty item, and this exception

> Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
>    at done (index.js?ee11:214)
>    at removeElement (index.js?ee11:220)
>    at patch (index.js?ee11:305)
>    at patch (index.js?ee11:276)
>    at patch (index.js?ee11:268)
>    at render (index.js?ee11:58)

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/hyperapp/releases/tag/1.1.2
