### ISSUE TITLE
Examples/Documentation for replacing component local state?

### ISSUE THREAD

**Issue by rssfrncs** [hyperapp/hyperapp#585]
Hi,

I like the look of hyperapp but i can't find any info/best practices on how to replace local component state?

For example, i would love to know how would one implement an extremely basic expand/collapse component? In React the component would simply track state.isExpanded and return either props.children or something else based on the value of it. This is good because you don't have to worry about creating state.expanderXIsExpanded at the root component for every instance of the component in your app!

Many thanks.

**Comment by SkaterDad** [comment]
Hello!

Hyperapp doesn't support local state, so everything has to be added to the single state object.

The term "Component" in hyperapp refers simply to a view function, similar to the stateless functional components in React.

**Comment by zaceno** [comment]
@rssfrncs 

@skaterdad is only partially correct. It's true that hyperapp itself does not implement support for local state in anyway. That does not mean that stateful hyperapp components arent possible though. See https://zaceno.github.io/hypercraft/stateful-components/ for an explanation, or https://github.com/zaceno/hyperapp-nestable for the lib I use (occasionally). Just know that when, if ever, it is a good practice, is a matter of some debate ;)

**Comment by daz4126** [comment]
I'm not an expert on this at all, but doesn't it just require a mindset shift that everything is controlled in the one single state? The state can contain nested objects, so you could manage the state of all your components in a nested object called 'components'. ie:
````
const state = {
  // other state stuff
 components: { componentA: { expand: true },
                           component B { expand: false }
  }
}
````

This nested object would then allow you to track the different states of each individual component.

Alternatively you could switch this round and put the focus on the state of being expanded or not instead:

````
const state = {
  // other state stuff
 expanded: { componentA: true,
                      component B: false 
  }
}
````

Not sure if that helps or not...

**Comment by JorgeBucaran** [comment]
@rssfrncs There is no local component state, but we have a feature usually known as slices, but better explained IMO as simply nested actions, that lets you modularize your state and actions within our single state tree architecture.

It's basically a way to break up your state and actions, so that actions can update a specific section of the state, instead of the whole state.

See: https://github.com/hyperapp/hyperapp#nested-actions

**Comment by JorgeBucaran** [comment]
Seems like we can close here.
