### ISSUE TITLE
Possible to mount and unit test individual component?

### ISSUE THREAD

**Issue by rssfrncs** [hyperapp/hyperapp#587]
Hi,

Can't find any documentation about testing individual hyperapp components, is it possible?

Thanks.

**Comment by rssfrncs** [comment]
Example, I want to be able to access and assert on the created canvas DOM element is this possible?

Component
```
import { h } from "hyperapp";

export const Canvas = ({ data }) => {
  return (
    <canvas
      oncreate={element => {
        clear(element);
        draw(element, data);
      }}
      onupdate={element => {
        clear(element);
        draw(element, data);
      }}
    />
  );
};

const draw = (canvas, data) => {
  const ctx = canvas.getContext("2d");
  data.forEach(d => {
    ctx.fillRect(d.x, d.y, 5, 5);
  });
};

const clear = canvas => {
  const ctx = canvas.getContext("2d");
  ctx.clearRect(0, 0, canvas.width, canvas.height);
};
```
Test
```
import { h } from "hyperapp";
import { Canvas } from "./canvas.js";

test("renders correctly", () => {
  const mounted = <Canvas />;
  expect(mounted).toMatchSnapshot();
});
```

Snapshot
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`renders correctly 1`] = `
Object {
  "attributes": Object {
    "oncreate": [Function],
    "onupdate": [Function],
  },
  "children": Array [],
  "key": undefined,
  "nodeName": "canvas",
}
`;
```

**Comment by selfup** [comment]
Yes it is possible:

https://github.com/selfup/hyperapp-one/blob/master/test/description.test.js
https://github.com/selfup/hyperapp-one/blob/master/test/counter.test.js#L18-L24

This was all derived by how the test were written in this repository itself. I recommend you take some time (as did I haha) and completely understand how the tests are written in this repo: https://github.com/hyperapp/hyperapp/tree/master/test

**Comment by JorgeBucaran** [comment]
@rssfrncs Can we close here? or the example above is not what you were looking for?
