### ISSUE TITLE
Hyperapp do not call oncreate handler when view mounted to document.body

### ISSUE THREAD

**Issue by jmas** [hyperapp/hyperapp#588]
Code:
```js
import { h, app } from 'hyperapp';

function view() {
  return (<div oncreate={() => console.log('log oncreate')} />);
}

app({}, {}, view, document.body);
```

In this case we do not see a message `log oncreate`. It take some time to understand that app mount view to body and this element is not re-created. Maybe I miss something, but I have assumption that this handler should be called in any case when view mounted first time.

I solve a "problem" in this way: just add element with ID and mount view to it.

**Comment by okwolf** [comment]
@jmas what sort of build process are you using? I see you are using modules and JSX. Did you start with one of the boilerplates or configure your own from scratch?

Your code works in a codepen: https://codepen.io/okwolf/pen/LQyXOE?editors=0011

**Comment by JorgeBucaran** [comment]
@jmas I think the problem is that your <samp>document.body</samp> is _not_ empty? Is this assumption correct?

**Comment by JorgeBucaran** [comment]
Currently, if you want to render your app into a non-empty container, you need to create the container first.

```html
<body>
  <div>
    Other Stuff
  </div>
  <div id="my-hyperapp-container"></div>
</body>
```
```js
app(
  state, 
  actions, 
  view, 
  document.getElementById("my-hyperapp-container")
)
```

**Comment by jmas** [comment]
@JorgeBucaran Thanks for explanation. Now I see. I double checked this: if I have non-empty container `oncreate` is not called.

**Comment by JorgeBucaran** [comment]
@jmas Absolutely, https://github.com/hyperapp/hyperapp/pull/590 is also somewhat related to this. Thanks for bringing this up!
