### ISSUE TITLE
DIY chapter in User Guide needed! 📌

### ISSUE THREAD

**Issue by liadbiz** [hyperapp/hyperapp#59]
hi.
I have been using react/vue to build web application, to be honest, both of them are greet, but I really want to known how these modern ui framework are built from scratch.

I found this library accidently, and happy to notice that there are "do it yourself" chapter in the user guide, so my question is when this chapter can be readed. what's more, it would be appreciate if I am able to contribute to make this repo better.

sorry to bother you, and thanks to reply!

**Comment by jbucaran** [comment]
@liadbiz Thanks for asking! Well, I'm trying to find time, since I also have a regular job, but I'm working on it.

I'm glad you found the DIY section interesting, that's the part of the book I'm the most excited about writing.

If you want to help you can offering me your unique view of how frontend and webdev should be taught. I have some of my own ideas and views, but they are slanted because I've been working on the web and with JavaScript for a long time.

If you can layout what _you_ think would be the most useful and interesting sections the User Guide should have, or what other topics you'd like to see explored, I'd be very grateful.

**Comment by liadbiz** [comment]
@jbucaran 
thanks!  
there are so many choices for selecting a ui framework these years, the problem is not to find one that fits our needs, but to find a better one that i can figuer out how it works and what kinds of work can it do, , because they are all good enough. 
I am still a student who has learned front-end development for almost one year, the most significant problem for me to figure out is to understand how the framework design and work rather than how can I use this framework, how to write component, how to organize the code...etc.  

And here are some ideas and views I can offer now about how chapter DIY should be writed.

+ explains the motivation why you want to write this framework(like you did in #9 ) and difference between other awesome repo like react/vue.
+ how you build this repo from scratch , you known it's not good for a project that only the author knowns how the repo are built and how to write a plugin or something else to make it better, for example the webpack project.
+ what's next?  like you said in the use guide, what do you want to build it for.

**Comment by jbucaran** [comment]
@liadbiz Thanks a lot! I'll make sure to address every single bullet in that chapter.

**Comment by liadbiz** [comment]
@jbucaran
you are welcome. Hope to see your fantastic work!

**Comment by jbucaran** [comment]
@liadbiz The User Guide has been moved to the wiki, so I'm going to close here and create a new section in the wiki.

Perhaps [Concepts->Architecture](https://github.com/hyperapp/hyperapp/wiki/Architecture).

What do you think?

**Comment by liadbiz** [comment]
@jbucaran  agree! :+1: let me known if I can help:)

**Comment by jbucaran** [comment]
@liadbiz Yes, you could try looking through app.js, it's not so long! And make notes about what you think seems difficult to understand (I loved your feedback in #127). Then, I can work on adding comments or refactoring the code.

**Comment by liadbiz** [comment]
@jbucaran Thanks! I have readed you PR #127 this morning. I will make some notes soon, and I actually have now.
