### ISSUE TITLE
Feature request: keeping <head>/<title> up-to-date

### ISSUE THREAD

**Issue by dbkaplun** [hyperapp/hyperapp#593]
Would be great if I could use hyperapp or a hyperapp plugin to keep <head> up-to-date, a la [react-helmet](https://github.com/nfl/react-helmet).

Thanks for considering!

**Comment by lukejacksonn** [comment]
You can achieve this in more than one way. What I have done in the past is to create a component that does this for me. This means you can place the update wherever you want in your app (just inside of a route for example).

Something like this in `meta.js`
```js
let lastPath
export const Meta = ({ title = '', description = '' }) => {
  if (lastPath != location.pathname) {
    document.querySelector('title').text = title
    document
      .querySelector('meta[name=description]')
      .setAttribute('content', description)
    lastPath = location.pathname
  }
}
``` 
Then in your app:
```js
import { Meta } from './meta'

const View = (state, actions) =>
  h('main', {}, [
    Meta({ title: 'Home', description: 'Welcome to my app' }),
    ...
  ])
```

**Comment by dbkaplun** [comment]
I'm more hoping for an existing, supported solution that I can just include in my project, rather than writing it myself. Something like react-helmet that lets me write:
```jsx
class Application extends React.Component {
  render () {
    return (
        <div className="application">
            <Helmet>
                <meta charSet="utf-8" />
                <title>My Title</title>
                <link rel="canonical" href="http://mysite.com/example" />
            </Helmet>
            ...
        </div>
    );
  }
};
```

**Comment by JorgeBucaran** [comment]
> @dbkaplun I'm more hoping for an existing, supported solution that I can just include in my project, rather than writing it myself.

There is none at the moment. If you are not willing to build it yourself and share it with the community, then I'll keep in mind to update this issue to ping you when someone builds one! 👋
