### ISSUE TITLE
 Any examples without "html"?

### ISSUE THREAD

**Issue by cbr4yan** [hyperapp/hyperapp#6]
I found this library today and it's fine.
But I wanted some example of how to use it without the "html" part, ie creating components in vanilla javascript.

Thank you.

**Comment by jbucaran** [comment]
@cbr4yan I must clarify that [template literal strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) **are** vanilla JavaScript! :)

Now, here is how you'd use the `h` function and `app` to recreate the counter example.

```js
const { app, h } = require("hyperapp")

app({
    model: 0,
    update: {
        add: model => model + 1,
        sub: model => model - 1
    },
    view: (model, msg) => h("div", {}, [
      h("button", { onclick: msg.add }, ["+"]),
      h("h1", {}, [model]),
      h("button", { disabled: model <= 0, onclick: msg.sub }, ["-"])
    ])
})
```
* See [live](https://hyperapp-plain-h-example.gomix.me/) example.
* See [source](https://gomix.com/#!/project/hyperapp-plain-h-example) code.

**Comment by cbr4yan** [comment]
@jbucaran, you are right, I have not expressed it correctly.

With "vanilla javascript", I meant using "createElement" or "querySelector", etc.

Thanks for the example.

**Comment by tunnckoCore** [comment]
> With "vanilla javascript", I meant using "createElement" or "querySelector", etc.

That's slow. There's no reason to use. Things like `bel` and `yo-yo` sa pretty small and already doing the things the right way.

**Comment by cbr4yan** [comment]
@tunnckoCore yes I know, but I like test first with simple code and after move to library. 
I didn't know `bel`. Thanks you.

**Comment by jbucaran** [comment]
@cbr4yan Using `h` isn't slow. `html` parses HTML and calls `h` behind the scenes (that's how React/Preact/Cyclejs/etc work).

**Comment by cbr4yan** [comment]
@jbucaran , I did not mean that "h" was slow, I was referring to 
> different libraries ...

Well, on the other hand, this weekend will apply the examples of "hyperapp" and your answer.

Thanks for the help :thumbsup:

**Comment by tunnckoCore** [comment]
@jbucaran I was talking about the native doms. Slow in a sense of development time and etc. It's a lot better to use template strings.

**Comment by jbucaran** [comment]
@cbr4yan Here's another example using raw `h` calls.


Using the `h` function directly.

```js
app({
    model: 0,
    update: {
        add: model => model + 1,
        sub: model => model - 1
    },
    view: (model, msg) => h("div", {}, [
      h("button", { onclick: msg.add }, ["+"]),
      h("h1", {}, [model]),
      h("button", { disabled: model <= 0 , onclick: msg.sub }, ["-"])
    ])
})
```
[**CodePen**](http://codepen.io/jbucaran/pen/jyKypX?editors=0010)

**Comment by jbucaran** [comment]
I think we can close here.
