### ISSUE TITLE
How to call an action in a different slice from a nested asynchronous action

### ISSUE THREAD

**Issue by spapas** [hyperapp/hyperapp#601]
I have a (nested) login() action which is inside an `auth` object/namespace  and an `updateLoading` function that is not inside that namespace (it is called from other places in my app). Something like this:

```
const reducers = module.exports = {
    updateLoading: loading => state => ({
	loading
    }),
    auth: {
        login: () => (state, actions) => {
            actions.updateLoading(true)
	}
	// Do the login etc ...
    }, 
    // ...
}
```

Now, since login is asynchronous, I want it to call the `updateLoading()` while doing the http post request to the login API but the `actions` object that it receives contains *only* the actions that are inside the `auth` object/namespace.

Is it possible to call the `upadeLoading` action from inside `auth.login` ?

**Comment by zaceno** [comment]
Short answer: no, not directly like in your example. 

There are several ways to work around it though, each with its own pros and cons. Various ways I've handled this sort of thing in the past:

- Pass a prop `onupdateloading: actions.updateLoading`  to your auth-component. Then in your `onsubmit` of the login form: `onsubmit: ev => actions.auth.login({onupdateloading})`, and finally in the `login` action: `onupdateloading(true)`

- Use a global event bus in your app. In your `login` action: `eventbus.emit('loading', true)`. And during your app setup:

```js
const main = app(state, actions, view, container)
eventbus.on('loading', x => main.updateLoading(x))
```

- Somehow leverage that the state changes when you login, in your view. Perhaps something like:

```jsx
const view = (state, actions) => {
  if (state.auth.attempting && !state.loading) actions.updateLoading(true)
  return (
    <main>
      ...
    </main>
  )
}
```

**Comment by spapas** [comment]
Hello @zaceno thank you very much for the thorough answer! I have tried a modified version of your first solution (the second one adds extra complexity I don't want and the third one is really confusing to me). So, because I actually need more actions when logging in (i.e change the location from the login view) I tried pass the whole `reducers` object down to the login action (instead of only updateLoading) and it is working fine now. 

So my login action is something like this:
```
login: (global_actions) => (state, actions) => {
// I can use every action here using the global_actions object
}
```


However I'd like to also ask wouldn't it be possible for hyperapp to pass by default the `global_actions` a third argument to the async action signature ? I.e something like this:

```
login: () => (state, actions, global_actions) => {
...
}
```

This shouldn't be a big change (and it won't really change the API - you'll just define global_actions if you need it) and would make everything much easier !

**Comment by zaceno** [comment]
That could certainly work! I think I've seen it proposed before too. I can't remember what the opinion was about that then.

I know one reason people might be hesitant to use `global_actions` is that if you're breaking apart your state/actions by namespace into separate modules, then they will depend on global_actions having a certain shape. That makes your modules tightly coupled (they all need to know how the main module puts them together) which is generally seen as problematic.

But other than that I see no problem with passing along global_actions.

BTW I just thought of a fourth method I think could work nicely as well -- esp if you have a lot of such callbacks (or "call-ups") in your app: Have an initialization-chain where you set up callbacks in each namespace. That means storing functions on the state though...(some don't like that). 

I mean, something like this:

```js

const actions = {
  init: () => (state, actions) => {
    actions.auth.init({
      onlogin: _ => actions.updateLoading(true), 
      //... 
    })
  },
  auth: {
    set: x => x,
    init: callups => (state, actions) => {
       actions.set(callups)
       //other auth init stuff
    }
    login: () => (state, actions) => {
       //do login stuff
       state.onlogin()
    }, 
}
...
const {init} = app(state, actions, view, document.body)
init()
```

**Comment by spapas** [comment]
Yes I understand your argument about breaking up the state/actions to different modules but I don't think that having an optional `global_actions` argument would do any harm - if people understand the consequences (their actions object have a specific structure) then why not use it and make their lives easier?

I also tried your fourth solution and it works really nice - although I agree that it feels a little "hackish" and is not very easy to understand.

**Comment by frenzzy** [comment]
Why not to just put everything what you need into the same slice?
```js
const state = {
  auth: { user: null, loading: false }
}
const actions = {
  auth: {
    login: (credits) => (state, actions) => {
      api.post('/token', credits)
        .then(user => actions.setUser(user))
        .catch(error => actions.setUser(null))
      return { loading: true }
    }
    setUser: (user) => ({ user, loading: false })
  }
}
```

**Comment by spapas** [comment]
@frenzzy I want to re-use the `loading` flag and actions from other parts of the application, not only from auth (i.e I don't want to have as many `loading` flags as there are slices). Think that when something is "loading" a big spinner will be displayed that will hide everything.

**Comment by Mytrill** [comment]
A middle ground between passing updateLoading only and passing all actions could be to pass an object containing all common actions to your app, this object will become, little by little, the public interface of all your modules (later you can split this up, even). 
When testing, you can mock this one object an all your modules stay relatively decoupled.

**Comment by JorgeBucaran** [comment]
> How to call an action in a different slice from a nested ~~asynchronous~~ action?

You can't. If you need slices to "talk to each other", then you need to work around it. For example, design your application differently, nest your slices inside a namespace that should act as a controller, or share actions with other actions as props.

**Comment by spapas** [comment]
@JorgeBucaran no problem - as others have pointed out in this thread there are various ways this issue can be solved. 

However, since most users trying to implement non-toy apps will probably stumble upon this problem, I recommend adding some mention of this problem and possible solutions with pros and cons to the docs (or maybe add another doc like best practices where problems like this would be discussed).

**Comment by JorgeBucaran** [comment]
SGTM 🙇

**Comment by sergey-shpak** [comment]
If anyone still interested
```javascript
// root actions
const actions = {
  sub: {
    someMethod: ([globalState, globalActions]) => {
      // now has global access
    },
    bind: global => (state, actions) => {
      Object.keys(actions).forEach(key => {
        actions[key] = actions[key].bind(actions, global);
      });
    }
  },
  init: () => (state, actions) => {
    actions.sub.bind([state, actions]);
    actions.sub.init();
  },
}
```
