### ISSUE TITLE
How to use routing?

### ISSUE THREAD

**Issue by fkereki** [hyperapp/hyperapp#602]
What is the preferred (official?) way of handling routing?
Is there a way to link it to state?

**Comment by JorgeBucaran** [comment]
The official router is https://github.com/hyperapp/router, but I wouldn't discard creating your own smaller / simpler Router if you are so inclined.

It's not 1.0 yet, yet, but it should work with current Hyperapp.

**Comment by jcubic** [comment]
What is the status on hyperapp router? Does it work in version 1.x.x? I was looking at my [old router on codepen](https://codepen.io/jcubic/pen/mwvMBV) but the demo don't work at all (it have old syntax with `app({view; ...})`). I've updated the other demo to version 1.x.x (it have hardcoded that in unpkg so it will not break when 2.0 came out). My router had some issues if I remember correctly but it was mostly working. I think it was not initializing correctly.

It seems that my router was using mixins, does they work in version 1.0 if not is there some replacement.

**Comment by jorgebucaran** [comment]
@jcubic I know, sorry. The router worked the last time I checked, but I haven't checked since in a while as I've been working on V2. V2 will have a working router/navigation package.
