### ISSUE TITLE
Which event should be used to start the code?

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#61]
When I used `window.addEventListener('load', () => app(...))` the `subs` didn't work correctly, as they never seemed to receive the event. How should we handle this without adding the `<script>` to the last line of the HTML?

---

*Note*: It should work with both `<script async ...>` and `<script>` if possible.

**Comment by jbucaran** [comment]
Subscriptions are functions that run once when the [DOM is ready](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded). 

So, I guess by the time the subscription was called, the window.load event had already fired.

What you want to do is make your subscription _the function_ you'd call inside that event listener, the ellipsis (...) in your example.

Yes
```js
subscriptions: [
  myFunction
]
```

Not
```
subscriptions: [
  _ => window.addEventListener('load', myFunction)
]
```

**Comment by dodekeract** [comment]
@jbucaran My bad, I thought it's obvious that `...` is the whole `hyperapp` stuff. Won't it crash when it can't find the DOM yet? React didn't like being called before the 'onload' event.

**Comment by tunnckoCore** [comment]
> Which event should be used to start the code?

What mean "to start the code"? You don't need anything. App should be called before the dom-is-ready. If something in your app should happen when DOM-is-ready put it into subscriptions.

> Won't it crash when it can't find the DOM yet?

No.

**Comment by dodekeract** [comment]
@tunnckoCore I just removed the event listener and it caused a crash, as usual.

```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at 108.module.exports (some-script…:104)
    at Object.475 (some-script…:1184)
    at __webpack_require__ (some-script…:20)
    at some-script…:66
    at some-script…:69
```

**Comment by jbucaran** [comment]
@dodekeract Is the problem the <script async>?

**Comment by dodekeract** [comment]
@jbucaran No, it also appears without `async`.

Actually, now that I tested that it **always** happens when no `async` is used.

**Comment by jbucaran** [comment]
@dodekeract Can you break down the problem into a smaller problem? 

First, try with this HTML
```html
<!doctype html>
<html>

<body>
    <script src="/bundle.js"></script>
</body>

</html>
```

**Comment by dodekeract** [comment]
@jbucaran Loads reliably without crashing.

**Comment by jbucaran** [comment]
@dodekeract So, the problem may be in your other HTML, right?

**Comment by jbucaran** [comment]
![screen shot 2017-02-08 at 20 49 32](https://cloud.githubusercontent.com/assets/56996/22736141/2866977c-ee40-11e6-8391-c468db602926.png)

**Comment by dodekeract** [comment]
@jbucaran I don't think so. I actually only moved the `script` down, didn't change the `src=` part or anything else.

**Comment by jbucaran** [comment]
> @dodekeract How should we handle this without adding the <script> to the last line of the HTML?

Hmm. Can you post the entire code? You can use the details/summary tags, so it doesn't matter if it's long.

**Comment by dodekeract** [comment]
I'll have to create a completely minimal repro then. Current code has some stuff I can't share that's not related to `hyperapp`.

**Comment by jbucaran** [comment]
@dodekeract I just wanted to see if the location where you are embedding the bundle.js that contains both hyperapp and your application.

**Comment by tunnckoCore** [comment]
Still can't understand what we are talking about.

> I'll have to create a completely minimal repro then.

:+1:

**Comment by jbucaran** [comment]
@tunnckoCore Me neither, but I suspect @dodekeract is embedding the bundle.js in the head.

**Comment by dodekeract** [comment]
@jbucaran @tunnckoCore https://github.com/dodekeract/hyperapp-issue-61

`npm run build && npm run start`

`index.html` and `onload.html` work while `broken.html` doesn't work.

**Comment by jbucaran** [comment]
@dodekeract Thanks for creating the demo repo. 

It seems you are embedding your bundle.js in the `<head>` tag, when you shouldn't, because when you run `app(...)` and HyperApp calls document.appendChild(vnode) or something, `document` is still undefined.

**Comment by dodekeract** [comment]
@jbucaran Which is why I'm asking which event I'm supposed to use, as `load` seems to break the `subs`. 😉

**Comment by jbucaran** [comment]
@dodekeract Yup, now I see that's what you were asking indeed.

Isn't the solution to _not_ embed the bundle in the `<head>` tag?

**Comment by dodekeract** [comment]
@jbucaran not possible in my use-case and I think that's actually more of a workaround. Until now I always used `window.onload` with an `async` script.

**Comment by tunnckoCore** [comment]
First to mention that `app()` does not return anything, so 

```js
window.addEventListener('load', app({
```

in `index.onload.js` is wrong thing.

Second, set something in the body and try to add `opts.root`.

**Comment by dodekeract** [comment]
@tunnckoCore Whoops, that's a typo, pushed the fix to the repo. However it actually **did** solve the crash. Don't ask me why though.

**Comment by jbucaran** [comment]
@dodekeract Ah, what @tunnckoCore said. Good job on catching that!

**Comment by dodekeract** [comment]
@jbucaran @tunnckoCore `broken.root.html` is also broken.

**Comment by jbucaran** [comment]
@dodekeract Of course broken.root.html is broken. You are calling `document.getElementById` inside `<head>`.

**Comment by dodekeract** [comment]
@jbucaran I'm aware of that. I didn't expect it to work. As I said I can't expect the script to be at the end of the body in my use-case.

**Comment by jbucaran** [comment]
@dodekeract So the problem is simply you need subscriptions and you're loading HyperApp via the `<head>` tag?

**Comment by dodekeract** [comment]
@jbucaran That's one way to put it, yes.

**Comment by jbucaran** [comment]
Okay, gotcha. Let's track this in #62.

The fix involves adding a bit of code to app.js. We need to check whether the DOM has already loaded before adding the DOMContentLoaded listener to document.

@dodekeract Can you work on a PR?

**Comment by dodekeract** [comment]
@jbucaran Is there any reason why we can't just treat "render app()" as the first sub?

**Comment by jorgebucaran** [comment]
Locking as the entire discussion is entirely out-of-date.

---
