### ISSUE TITLE
Global access to state/actions in actions/components

### ISSUE THREAD

**Issue by jason-whitted** [hyperapp/hyperapp#615]
Slices are convenient when they are helping you out, but they very frequently impede the developer from being able to accomplish a goal.  This is a recurring theme as seen in:

- #601 - @spapas was requesting global access to actions in an action
- #604 - connected components, which make global access to state/actions available in components
- #606 - @frenzzy commenting on possibly adding state/actions to every component's arguments

I have experimented with hyperapp over at [etalisoft/hyperapp-extended](https://github.com/etalisoft/hyperapp-extended) to get this to work.

It modifies the following signatures:
```js
// action signature
value => (state, actions, current) => ...
// component signature
(attributes, children, current) => ...
```

`current` is an object with the following methods:
- `getState()` - returns the global state
- `getActions()` returns the global actions

This allows both actions and components the flexibility to have access to current state/actions even in nested async callbacks.

The `current` object is only created once and frozen and merely passed along as an additional argument, which should have no negative performance impact.

**Comment by JorgeBucaran** [comment]
Closed in favor of #606.
