### ISSUE TITLE
About supporting string type style

### ISSUE THREAD

**Issue by huozhi** [hyperapp/hyperapp#617]
Hey there! I'm trying to write tiny project with hyperapp recently it's really awesome!

One thing I wonder to know is that will hyperapp decided to support string type style value? I think that will be pretty much easier for people to build apps.

```html
<div style="color: blue; backgound-color: red"></div>
```

Currently only object style is supported. If you guys think making compatible work for string style is good here is the pull request https://github.com/hyperapp/hyperapp/pull/618. Otherwise it's still OK if you think supporting may bring redundance. : )

**Comment by JorgeBucaran** [comment]
Hi, @huozhi! Thank you, but I don't want to support this for the reasons given [here](https://github.com/hyperapp/hyperapp/pull/618). 👋

**Comment by huozhi** [comment]
Still many thanks for your quick reply! 👍
