### ISSUE TITLE
Assigning to input list property broke again

### ISSUE THREAD

**Issue by vgalaktionov** [hyperapp/hyperapp#622]
Hey, first of all thanks a lot for your work on hyperapp.
I was getting overwhelmed with all the ceremony in modern frontend dev, hyperapp + parcel have proven to be the remedy.

I've ran into an issue with rendering an input with a list attribute. This has happened before in #179 but was resolved; however, I've updated the example to the latest hyperapp and it appears broken again:

```
index.js:139 Uncaught TypeError: Cannot assign to read only property 'list' of object '#<HTMLInputElement>'
    at setElementProp (index.js:139)
    at createElement (index.js:173)
    at createElement (index.js:169)
    at createElement (index.js:169)
    at patch (index.js:312)
    at render (index.js:58)
```

Example here: https://probable-preface.glitch.me/

**Comment by JorgeBucaran** [comment]
We need to change this:

https://github.com/hyperapp/hyperapp/blob/a7cf41933f98e1474a90b66dec7c8adbb2fe93d6/src/index.js#L140

...to something like this:

```js
if (typeof value === "function" || (name in element && name !== "list" && !isSVG)) {
```

**Comment by vgalaktionov** [comment]
Yeah, that's exactly what I did on my fork and it works for me now. Should I make a PR?

**Comment by JorgeBucaran** [comment]
@vgalaktionov Sure! 👍

**Comment by jorgebucaran** [comment]
Resolved.
