### ISSUE TITLE
Badges not loading on README

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#63]
Seems like shields.io has some serious latency issues. This results in the badges never loading in our README. That looks pretty unprofessional, like we don't know what we're doing. I'd suggest reducing the number of badges to reduce the latency. The Slack badge always loads, the others never. I think having the version is important so I'd suggest leading that one and the Slack one. I'm laying this issue at Shields feet because I'm noticing some serious delays on their own site as well.

**Comment by jbucaran** [comment]
@rbiggs I've been noticing the same thing. It's not just HyperApp, it occurs throughout GitHub consistently. I think we could eliminate the coverage badge then.

**Comment by tunnckoCore** [comment]
Same here for all of my readmes. I hate that times when shields fails to do its job.

I don't think it would be "more professional" without badges. Best would be to just wait, it happens in the virtual world. :) Removing badges is not the cure and I'm against that move.

**Comment by jbucaran** [comment]
I tried removing the coverage badge, and as you can see, it didn't really help. Only slack is okay.

**Comment by rbiggs** [comment]
So I tracked down the guy behind Shileds. Here's a Twitter feed about the current issue: https://github.com/badges/shields/issues/529#issuecomment-277530347

**Comment by jbucaran** [comment]
Thanks @rbiggs. It's still not clear to me what I have to do to fix it, or is it more like we'll just have to wait a few weeks?

**Comment by rbiggs** [comment]
The problem is not us. It's Shields. They're having issues get the info from Github to create the badges properly. They're looking into a fix. It might come soon, or never. It's dependent on Github APIs. Sometimes Github changes that, like when the changed the API and broke the site Opensource ReportCard. So waiting is the best approach for now and see if they can resolve the issue they're having.

**Comment by tunnckoCore** [comment]
> like when the changed the API and broke the site Opensource ReportCard

Heey.. yea really, that was very cool project. <3

As about the Shields... I can't get what they do with Github. I mean, i scrolled over their code base (which is very very bad), but can't remember what they do with Github and why.

In anyway, best thing is to wait some time. Most of our community relies on that project, so removing the badges isn't the right choice.

**Comment by tunnckoCore** [comment]
Badges are back, :100: 

![](https://gifcept.com/rfR1XGS.gif)

**Comment by jbucaran** [comment]
Badges seem to be doing okay now. There's little we can do if they break, so let's close here.

**Comment by rbiggs** [comment]
🎉🎂🥂
