### ISSUE TITLE
Sanitization

### ISSUE THREAD

**Issue by jorgebucaran** [hyperapp/hyperapp#630]
If for any reason you don't use the Virtual DOM mechanism and decide to set the <samp>innerHTML</samp> in an element, you run the risk of cross-site scripting ([XSS](https://en.wikipedia.org/wiki/Cross-site_scripting)) vulnerabilities. Specifically, you must sanitize any user provided data before writing it out to the DOM. We suggest creating your own replacement function to explicitly state the intent of performing an "unsafe" operation

```jsx
const dangerouslySetInnerHTML = html => element => {
  element.innerHTML = html
}

const ItemContent = ({ item: { url, summary } }) => (
  <div class="content">
    <a href={url} oncreate={dangerouslySetInnerHTML(summary)} />
  </div>
)
```

**Comment by okwolf** [comment]
@jorgebucaran Isn't this copied directly out of the existing docs?
 https://github.com/hyperapp/hyperapp/blob/6e7f70f4c9f73bcf02a9da57f18284d14fefb55b/README.md#sanitization

**Comment by frenzzy** [comment]
[Isomorphic](http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) version using [`sanitize-html`](https://github.com/punkave/sanitize-html):
```js
import sanitizeHtml from 'sanitize-html'

const Post = ({ summary }) => (
  <div innerHTML={sanitizeHtml(summary)} />
)
```

**Comment by jorgebucaran** [comment]
@okwolf Lol, yeah. I created this issue because I am going to remove that note from the docs, but didn't want to lose the information. I think an issue is a good place for this, but it's just odd there's a whole section in our "minimal" docs with this stuff.
