### ISSUE TITLE
Is there React Portal concept?

### ISSUE THREAD

**Issue by lifeiscontent** [hyperapp/hyperapp#637]
Hi there, I just started reading about hyperapp I love the idea, I was wondering if you guys have a concept of being able to render into different areas of an app. e.g. something like a React Portal.

Is this possible? Or if its not, is it something of interest within the community?

**Comment by SkaterDad** [comment]
Hyperapp itself doesn't have any concept of portals.

My first question would be:  What do portals give you that hyperapp can't already do?

Since your entire app state is shared/global, you can already render state in multiple places.  I think React needed portals to do this because of local component state?

The party trick of using portals to render content outside of the application's DOM tree is more interesting.  I recall an article showing that you can render a React portal into a popup window and maintain the interactivity.   I haven't looked into how that's implemented.

**Comment by lifeiscontent** [comment]
@SkaterDad yeah, one of the things I have done is used portals on the server to render contents into the head of a document which is nice for setting things like titles/metadata.

**Comment by zaceno** [comment]
@lifeiscontent Interesting! I was just actually thinking about how one would implement something like Vue.js's "slots" and the problem seems very similar to the problem of implementing something like React's portals.

I don't have a solution yet, but I think a solution would require something like React's context -- which also doesn't exist in hyperapp. ( I have a package you could add add it with though: https://github.com/zaceno/hyperapp-context)

**Comment by lifeiscontent** [comment]
@zaceno is hyperapp capable of doing things like `React.fragment`? just to give you an example in pseudo react code.

``` jsx
import Head from './components/Head';

export default () => {
  return (
    <React.Fragment>
      <Head>
        <title>My Page</title>
       </Head>
       <h1>Welcome to my site...</h1>
    </React.Fragment>
  );
}
```

the use case here is to obviously make it so you don't have to render a div or something with the page you're rendering.

**Comment by jorgebucaran** [comment]
@lifeiscontent Your components can return arrays of nodes, but there must be a top-level container for the view. So, it can do what you want, but we don't have proper fragments like React which renders the children to a DocumentFragment which can be keyed.

**Comment by lifeiscontent** [comment]
@jorgebucaran is this something that would potentially be a feature in the future?

**Comment by jorgebucaran** [comment]
@lifeiscontent Fragments? Possibly. (See related: https://github.com/hyperapp/hyperapp/issues/530). Depends on how much code it involves.

Portals? I imagine you are new to Hyperapp, but if and when you know more about it, you'll understand that API doesn't make sense in Hyperapp.

**Comment by lifeiscontent** [comment]
@jorgebucaran so given my initial issue that I talked about with injecting a title into the head of a document, how would that be done within hyperapp?

**Comment by SkaterDad** [comment]
> @lifeiscontent injecting a title into the head of a document, how would that be done within hyperapp?

You could simply set the title with `document.title = "My New Title".

**Comment by lifeiscontent** [comment]
@SkaterDad doesn't that defeat the purpose of 1 way data flow though? I guess a portal also isn't really 1-way, but... it's closer than just a plain old mutation to the document.

**Comment by lifeiscontent** [comment]
I'm also more interested in knowing how to set meta data for things like facebook/twitter social tags.

**Comment by zaceno** [comment]
> @lifeiscontent doesn't that defeat the purpose of 1 way data flow though?

Not really: the DOM (including document.title) is the final stop of a one way flow of data, which originates in the state. Now, if we somehow were storing/reading the state from the DOM, that would be cyclical data-flow, and that would be bad.

**Comment by lifeiscontent** [comment]
@zaceno ok, so in the case of injecting meta information to a page, how would you do that in hyperapp?

**Comment by lifeiscontent** [comment]
@zaceno currently, I'd guess you'd have some array you'd mutate to then write tags into the head so it would work for both client and server. e.g:

``` jsx
headTags = ['meta', {name: "viewport" content: "width=device-width,initial-scale=1,shrink-to-fit=no"];

const Html = ({state, actions}) => (
  <html>
    <head>
      {{state.headTags.map(h)}}
    </head>
  </html>
);
```

**Comment by zaceno** [comment]
@lifeiscontent Frankly I don't think Hyperapp is the right tool for the job of setting metadata. To me that feels like a server-side thing, which I believe is out of scope for Hyperapp.

The example you gave couldn't work because it's trying to describe the DOM of an entire html page, but hyperapp needs to render inside a container, so the DOM already needs to be there for Hyperapp to be able to do anything

I don't know the first thing about server-side rendering with React or Hyperapp, but perhaps you're looking for: https://github.com/hyperapp/render

**Comment by rbiggs** [comment]
Preact has a separate project that provides a special tag for adding things link links, meta data, etc. to the document head. https://github.com/Download/preact-helmet
Preact also has another separate project that provides a Portal tag that allows you to render content outside of the current component. https://github.com/developit/preact-portal.
Seems like the same approach would work for Hyperapp. No need to add more code to Hyperapp, leading to unnecessary project bloat. Offer the functionality in separate projects for those that need them.

**Comment by jorgebucaran** [comment]
I agree with @rbiggs. If anyone wants to give this a shot, I've recently relaxed the way I admin the organization. If anyone can commit to maintain their module and want it to become "official", that is, using npm `@scoped` packages so it installs like `npm i @hyperapp/gizmo`, you are welcome to join the family.

[**Here**](https://gist.github.com/jorgebucaran/533f75c2330cf79afc2e622ad7a07e84) is a starting README/LICENSE template to get started.

**Comment by jorgebucaran** [comment]
> @lifeiscontent I was wondering if you guys have a concept of being able to render into different areas of an app. e.g. something like a React Portal.

You can render into **any* area of an app, so I don't think we have a problem here. If I am wrong, please reopen and improve your explanation. Thanks! 👋

**Comment by infinnie** [comment]
My solution there:
> * Create an ordinary element and insert it into the DOM using good old jQuery or vanilla JavaScript inside a non-component ordinary function.
> * Then initialize a HyperApp application within it.
> * When we need to receive information within the displaced element, we could have the element trigger a custom event or jQuery event, and pass the data into that event.

**Comment by jorgebucaran** [comment]
@infinnie So basically two Hyperapp apps running on the same page an a mechanism for them to communicate with each other?

**Comment by frenzzy** [comment]
We need an unmount feature in hyperapp to be able to properly implement portals without memory leaks. The main idea of portal is to be able to render for example a confirmation dialog in the same route without the need to modify layout or any parent components.

**Comment by jorgebucaran** [comment]
@frenzzy Can you point the unmount equivalent in other frameworks?

**Comment by frenzzy** [comment]
[`ReactDOM.unmountComponentAtNode(container)`](https://reactjs.org/docs/react-dom.html#unmountcomponentatnode)

**Comment by jorgebucaran** [comment]
@frenzzy What about Preact? Vue?

**Comment by jorgebucaran** [comment]
This must be fixed by 2.0, maybe app.unmount().

**Comment by infinnie** [comment]
Or one could reuse the portal container as much as possible to minimize memory leak.

**Comment by frenzzy** [comment]
Just for a history, higher-order app with unmount feature:
```js
function withUnmount(nextApp) {
  return (initialState, actionsTemplate, view, container) => {
    let nextView = view
    return nextApp(
      state,
      {
        ...actionsTemplate,
        unmount: () => state => {
          nextView = null
          return {}
        },
      },
      () => nextView,
      container,
    )
  }
}
```
```js
const main = withUnmount(app)(state, actions, view, container)
main.unmount()
```
Demo: https://codepen.io/frenzzy/pen/KoBKQP/left/?editors=0010

**Comment by jorgebucaran** [comment]
Or return `null`?

**Comment by Swizz** [comment]
Isnt the main concerns about `umount` : events and side effects ?

**Comment by infinnie** [comment]
An example using promises:
```jsx
var showDialog = (function () {
    var root = $("<div>").addClass("portal").appendTo("body"), dlg = app({
        text: "Default text"
    }, {
        changeText: function (text) {
            return { text: text };
        }
    }, function (state) {
        return (<div class="dialog portal__dialog">
            <p class="dialog__text">{state.text}</p>
            <div class="dialog__buttons">
                <button type="button" class="btn btn--primary" onclick={ function () {
                    root.trigger("ok"); } }>OK</button>
                <button type="button" class="btn btn--secondary" onclick={ function () {
                    root.trigger("cancel"); } }>Cancel</button>
            </div>
        </div>);
    }, root.get(0));
    return function (text) {
        dlg.changeText(text);
        root.addClass("portal--active");
        return new Promise(function (resolve, reject) {
            root.on("ok", function () {
                root.off("ok").off("cancel");
                resolve();
            }).on("cancel", function () {
                root.off("ok").off("cancel");
                reject();
            });
        });
    };
})();
```
Then we call it in event handlers:
```jsx
<button type="button" onclick={ function () {
    showDialog("Hello").then(function () {
        // OK clicked.
    }); } }>Show dialog</button>
```

**Comment by infinnie** [comment]
Also to change the title, just set the `document.title` property.

**Comment by frenzzy** [comment]
@infinnie why do you need hyperapp, if you successfully use jQuery? :)

With a plain hyperapp it may look like this:

**Hyperapp Portal**
```js
const Portal = (props, children) => (
  <div
    key={props.key || 'portal'}
    oncreate={element => {
      const portal = {
        view: () => <div class="dialog">{children}</div>,
        container: document.body.appendChild(document.createElement('div'))
      }
      portal.app = app({}, { update: () => ({}) }, () => portal.view, portal.container)
      element.portal = portal
    }}
    onupdate={element => {
      const portal = element.portal
      portal.view = () => <div class="dialog">{children}</div>
      portal.app.update()
    }}
    ondestroy={element => {
      const portal = element.portal
      portal.view = () => null
      portal.app.update()
      portal.container.parentNode.removeChild(portal.container)
      element.portal = null
    }}
  />
)
```
Usage:
```js
{state.showDialog && <Portal>Some Content</Portal>}
```

Demo: https://codepen.io/frenzzy/pen/QmBKKy?editors=0100

**Comment by infinnie** [comment]
Yes. It’s like implementing portals in older versions of React. But lifecycle events are hooked on an extra DOM element instead of the component.

**Comment by infinnie** [comment]
What about propagating messages out of the portal? @frenzzy

**Comment by rbiggs** [comment]
How about using any of the various tiny pubsub libs on NPM for communication?

**Comment by infinnie** [comment]
@rbiggs that would be like something in my example.

**Comment by infinnie** [comment]
Then in @frenzzy’s implementation it would not be hard to handle events: just pass actions to them and things would be done.
