### ISSUE TITLE
Release schedule and docs

### ISSUE THREAD

**Issue by TheNando** [hyperapp/hyperapp#649]
When can we expect the next release? Looks like there are features in the docs that aren't in the lastest release yet.

**Comment by jorgebucaran** [comment]
@TheNando I was waiting to fix the router before publishing, but I realize that's going to block more people that want to try the new features, so I'm preparing the release notes now and should be publishing later today.

**Comment by TheNando** [comment]
Looks like this answers it https://github.com/hyperapp/hyperapp/releases/tag/1.2.0
Thanks!
