### ISSUE TITLE
Equivalent to react's setState callback?

### ISSUE THREAD

**Issue by jpodwys** [hyperapp/hyperapp#654]
I have a need to execute arbitrary logic only after a state change has been applied. In `react` land, I can accomplish this by running `setState(state, cb)`. Based on my extremely limited `hyperapp` experience, this appears to be impossible since, in order to update state, an action must `return`.

Is there already a means of doing what I want in `hyperapp`? If not, is there any interest in adding this feature?

**Comment by mrozbarry** [comment]
Yes and no.

You could have an action to run the callback, and it would look like:

```
const actions = {
  // ...
  afterUpdate: fn => state => {
    fn(state);
  }
  // ...
}
```

To to use it in another action:
```
const actions = {
  doThing: arg => (state, actions) => {
    actions.afterUpdate(newState => console.log('Called after update', newState));
    return { someUpdate: 1234 };
  }
}
```

Hyperapp queues up actions called in actions so they happen after your action is run.

This isn't, by any means, an official solution, but it should work.

**Comment by mrozbarry** [comment]
Actually, I was slightly wrong, this is only for lifecycle events, _but_ I think it would still work.

**Comment by jpodwys** [comment]
That's interesting, thank you! If that's how I have to do it for now, then that's fine. However, I'd prefer something more explicit rather than relying on the order in which `hyperapp` happens to internally queue actions.

What do you think of a global, reserved `setState` action that accepts a callback?

```js
const actions = {
  login: user => (state, actions) => {
    actions.setState({ loggedIn: true }, cb)
  }
}
```

**Comment by SkaterDad** [comment]
> What do you think of a global, reserved setState action that accepts a callback?

It's not a bad idea, but you will lose access to it once you start using nested actions.

Could you provide a more specific example of what you're trying to do?  Maybe there's an alternative way to structure it.

Here's another strategy which I've used, adapted to the idea of performing an action post-login.
```js
const actions = {
  // Small "save this state" action which can be called from another one
  setCredentials: (user) => ({user}),

  // This is what your button click or API response would call
  login: (user) => (state, actions) => {
    console.log("Before login", state)
    actions.setCredentials(user)
    actions.afterLogin()  // statically defined callback
  },

  // This will have access to the "new" state
  afterLogin: () => (state) => {
    console.log("After login", state)
  },
}
```

**Comment by jpodwys** [comment]
> It's not a bad idea, but you will lose access to it once you start using nested actions.

Oh right, I'm not using nested state/actions so I hadn't considered this. Good catch. Your solution makes sense.

Are state patches synchronous? For example, in your snippet above will `setCredentials` always complete its state patch before `afterLogin` runs?

**Comment by zaceno** [comment]
@jpodwys FWIW: I sometimes make a generic `reduce` action, to use, for example as a callback in promises.

```js
actions = {
  reduce: fn => s => fn(s),
  myAction: x => (state, actions) => {
    doSomethingAsync(state.foo).then(result => actions.reduce((state) => {
      //now I have the current state after the update 
    }))
  }
}

```

... it's along the lines of your `setState` action, but without the actual state-setting part ;) 
It suffers from the same problem though: you have to repeat it in every namespace where you'll need it, if you're using nested actions. But since it's not a very common need, and the action is so small, it's no big deal.
