### ISSUE TITLE
Make Components inherit all attributes?

### ISSUE THREAD

**Issue by van-nguyen** [hyperapp/hyperapp#655]
I'm trying to make my image tags tidy by encapsulating my src with a prefix, one thing I find difficult is that the attributes don't "inherit" by default and have to pass all the attributes each one. Is there a cleaner way of doing this? Thanks.

```js
export const Image = (attrs) => (
  <img src={rootState.Prefix + attrs.src} class={attrs.class} width={attrs.width} height={attrs.height} alt={attrs.alt} title={attrs.title} style={attrs.style}/>
);
```

**Comment by jorgebucaran** [comment]
@van-nguyen You could do this.

```jsx
export const Image = ({ src, ...attrs }) => (
  <img src={rootState.Prefix + attrs.src} ...attrs />
)
```

**Comment by van-nguyen** [comment]
Nice @jorgebucaran just what I was looking for. Thanks for the fast reply, cheers.

**Comment by jorgebucaran** [comment]
Glad I could help!
