### ISSUE TITLE
How to get content for Component?

### ISSUE THREAD

**Issue by van-nguyen** [hyperapp/hyperapp#656]
How would I go about creating a `Button` component with text content in it? Is there a way to access the innerHtml without using attributes?

i.e.
```js
const Button = (props) => {
  return (
    <button class="button" {...props}>{props.content?}</button>
  );

  <Button>Click</Button>
};
```

**Comment by van-nguyen** [comment]
Nevermind, found out there was a second argument missing.

**Comment by Swizz** [comment]
A litle bit too late. See [Children Composition](https://github.com/hyperapp/hyperapp#children-composition).
