### ISSUE TITLE
Has anyone successfully used with Parcel bundler and TSX?

### ISSUE THREAD

**Issue by bahmutov** [hyperapp/hyperapp#673]
JSX works great, but when my views use TSX, "h" is not found :(

<img width="855" alt="screen shot 2018-04-01 at 11 38 06 am" src="https://user-images.githubusercontent.com/2212006/38174817-437626be-35a1-11e8-87c9-03efab2ff284.png">

**Comment by jorgebucaran** [comment]
Try adding it manually to your `.babelrc` or `tsconfig.json`. Probably not related, but I've also found that clearing Parcel's .cache often fixes all my issues. 

This doesn't sound like a Hyperapp bug, so consider creating an issue in Parcel's end. 👋

**Comment by Frikki** [comment]
Add `"jsxFactory": "h"` to your `tsconfig.json`.

**Comment by davidchase** [comment]
Seems like an open or related issue in [parcel#1095](https://github.com/parcel-bundler/parcel/issues/1095) trying it out locally and having same issue

**Comment by bahmutov** [comment]
Yes, did not mean to imply this was a bug, just hoped that someone had a solution to this! Closing for now, will follow the parcel issue.

**Comment by davidchase** [comment]
@bahmutov yeah same, let me know if you have better luck :)
