### ISSUE TITLE
undefined element

### ISSUE THREAD

**Issue by tyrsius** [hyperapp/hyperapp#687]
After rendering a [pretty simple app](https://codepen.io/anon/pen/bMWWBJ?editors=1010) the result is

```
<body>
<div id="root"><undefined></undefined></div>
</body>
```

There are no errors in the console. 
I am new to hyperapp, so it seems pretty likely I missed something. If this does turn out to be something simple I would still expect there to be an error in the console.

**Comment by infinnie** [comment]
It is not supported for top-level components to return arrays.

See #362.

**Comment by jorgebucaran** [comment]
@tyrsius Your application requires a root element; you can't return an array from the top level view.

To correct your example you may do:

```js
const App = ({ orders }) => {
  return h("main", { class: "root" }, orders.map(order => h(OrderItem, { order })))
}
```

>  I would still expect there to be an error in the console.

This is a reasonable feature request. Currently I am not offering a "dev" build for Hyperapp, but it has been proposed before and I would be happy to discuss how we could offer one.

**Comment by infinnie** [comment]
But will arrays ever be supported as values returned by top-level components? Or will they be in version 2.0? If not, why not?

**Comment by tyrsius** [comment]
@jorgebucaran @infinnie  oh man, [these docs on the fron page](https://github.com/hyperapp/hyperapp#components) sure make it seem like you can

**Comment by jorgebucaran** [comment]
@tyrsius Components can be arrays, but views can't. In your example, App is the view so it can't be an array.

**Comment by tyrsius** [comment]
@jorgebucaran Thank you for explaining the difference 😄

**Comment by tyrsius** [comment]
I do still think logging an error in this case is a good idea. Outputting `<undefined></undefined>` with no error doesn't make debugging very... possible.

**Comment by jorgebucaran** [comment]
@tyrsius https://github.com/hyperapp/hyperapp/issues/417
