### ISSUE TITLE
Textarea doesn't update it's value

### ISSUE THREAD

**Issue by rumkin** [hyperapp/hyperapp#691]
Textarea message isn't updated on value change. I

```javascript
const textareaView = () => (state, actions) => h(
  'textarea',
  {
    oninput(e) {
      actions.setMessage(e.target.value);
    },
  },
  [state.message]
)
```

Actions has method to reset `state.message`:

```javascript
actions.resetMessage = () => (state) => ({
    ...state,
    message: '',
});
```

When `resetMessage` is called, state's value resets properly and redraws the view except of textarea.

[Example](https://stackblitz.com/edit/js-qj5tr3).

**Comment by jorgebucaran** [comment]
Thanks, @SkaterDad. 

Sounds like this is is resolved now.
