### ISSUE TITLE
Info in app.js not rendering in browser

### ISSUE THREAD

**Issue by Joseppi83** [hyperapp/hyperapp#692]
Thought I fixed this last night, but it bugged out. I've worked on trying to fix this for about 6 hours total now.

This is what my browser looks like and console reads when I run "npm run watch."  It's missing a lot of info from the app.js file that goes through hyperapp.  Should have a purple background and say "Hyperapp" with a codingphase logo and a github star icon button.

Just in case you can't read the console, here's that info:

vendor.js:544 Uncaught TypeError: enhancer(...) is not a function
at createStore (vendor.js:544)
at createStore (vendor.js:544)
at vendor.js:916
at vendor.js:949
at Array.map ()
at app (vendor.js:948)
at Object. (hyper.js:124)
at webpack_require (vendor.js:55)
at webpackJsonpCallback (vendor.js:26)
at hyper.js:1
createStore @ vendor.js:544
createStore @ vendor.js:544
(anonymous) @ vendor.js:916
(anonymous) @ vendor.js:949
app @ vendor.js:948
(anonymous) @ hyper.js:124
webpack_require @ vendor.js:55
webpackJsonpCallback @ vendor.js:26
(anonymous) @ hyper.js:1

The code for the project is here: https://github.com/codingphasedotcom/hyperapp-starterkit

Any clue on a fix?

![hyperappscreenshot2](https://user-images.githubusercontent.com/38846965/40318595-ec0d528e-5cd9-11e8-9051-ffea1f8846ad.png)

**Comment by lukejacksonn** [comment]
You are using a very, very old version of hyperapp. Is this intentional?

**Comment by Joseppi83** [comment]
It was a part of a download starter kit for a hyperapp restaurant app project on coding phase.com.  Would merely updating hyperapp solve the console errors?

**Comment by SkaterDad** [comment]
@Joseppi83 Hyperapp has undergone some big API changes since the version used in that repo, so it's unlikely that upgrading will fix the issue.

Maybe try out some of the boilerplates listed here?  Hyperapp-One looks up to date.
https://github.com/hyperapp/awesome-hyperapp#boilerplates

**Comment by Joseppi83** [comment]
Ah, thank you, sir.  I'm new to frameworks and only have HTML, CSS, and JavaScript experience, so I appreciate the finger pointing in the direction.  I'll see if I can figure it out with some head-scratching after work.

**Comment by SkaterDad** [comment]
Hyperapp is so simple, you can definitely get started without these boilerplates.  You can just add hyperapp as a script tag in your HTML start that way if you prefer.
```html
<script src="https://unpkg.com/hyperapp"></script>
<script>
// window.hyperapp will now be available, with the "h" and "app" properties
</script>
```

The README shows how to get started, with some examples (including Codepen links).   The framework is so small that the README is the full documentation.  https://github.com/hyperapp/hyperapp/blob/master/README.md

**Comment by noobiek** [comment]
While using SkaterDad's suggestion is OK for playing, I would not suggest to go too far in development this way though.
I've had a project which I started this way - without builder, proper App structure, etc. - later I spent a month migrating...

**Comment by Joseppi83** [comment]
Right on!  Thanks everyone.  I just got comfortable enough with JavaScript to begin trying out frameworks, so I'm still mentally at the point where the framework appears more difficult than the vanilla JavaScript.

**Comment by jorgebucaran** [comment]
@Joseppi83 Sounds like you were able to figure this out with everyone's help. Wonderful!
