### ISSUE TITLE
Breaks When Using <br/>

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#7]
I tried to modify the `counter` example. When inserting a line-break `<br/>` it broke. 🙁

## Console

```javascript
InvalidCharacterError (DOM Exception 5): The string contains invalid characters.
```

## Minimal Repro

```javascript
app({
    view: () => html`<div>a<br/>b</div>`
})
```

## Meta

Corresponding [issue on hyperx's repo](https://github.com/substack/hyperx/issues/38).  
Related to substack/hyperx#34.

---

*Note that I do realize that `<br>` works. `<br/>` is more explicit though and as a React-user I'd like to keep this pattern.*

**Comment by jbucaran** [comment]
@dodekeract This seems to be an issue with [Hyperx](https://github.com/substack/hyperx).

The solution is insert a space after the tag's name.

```js
app({
    view: () => html`<div>a<br />b</div>`
})
```

Same applies to other self-closing tags.

**Comment by dodekeract** [comment]
@jbucaran So should I open the upstream issue or will we fix it here?

**Comment by jbucaran** [comment]
@dodekeract The right thing to do is to open an issue there: https://github.com/substack/hyperx/issues/new

**Comment by jbucaran** [comment]
@dodekeract Do you think we can close?

**Comment by dodekeract** [comment]
@jbucaran has this been fixed or is it confirmed to be only related to hyperx? If the answer is yes then feel free to close. 😉

**Comment by jbucaran** [comment]
@dodekeract Yeah, this is not on HyperApp's realm.

And, did you see [this](https://github.com/substack/hyperx/issues/34#issuecomment-276845487) by the way?
