### ISSUE TITLE
0.0.12 failed to import { html }

### ISSUE THREAD

**Issue by crapthings** [hyperapp/hyperapp#70]
import { app, html } from 'hyperapp'

html is not a function

0.0.11 works fine

**Comment by dodekeract** [comment]
@crapthings In `0.0.12` you have to `import {app, html} from 'hyperapp/hx`. This will change back to the old behavior in `0.0.13` if I understood correctly.

**Comment by tzellman** [comment]
Yes, that is correct. I made a similar update [here](https://github.com/tzellman/hyperapp-boilerplate/commit/9eb5a31898e875040aa56527f9041fb696c468d9). You can see what changed after I switched to using the latest/master code.

**Comment by jbucaran** [comment]
Thanks @dodekeract, that's correct.

@crapthings There was a reason for that, but it should be soon before I release 0.0.13 and back to the original behavior.

**Comment by crapthings** [comment]
cheers

**Comment by jbucaran** [comment]
@crapthings IT's a thing now! https://github.com/hyperapp/hyperapp/releases/tag/0.0.13
