### ISSUE TITLE
Can't update state manually when get data from server

### ISSUE THREAD

**Issue by zjhiphop** [hyperapp/hyperapp#701]
Hi, recently i tried to use this framework to build a small application. Now i'm blocked when i try to manually update state.

Imagine one scene like:
1. App loaded first screen
2. Fetch data by http or websocket 
3. Update state to latest data when receive new data

Currently, it's not supported by the framework, even i manually execute the action still not works.

So is there anyway could help to do it?
Thanks.

**Comment by SkaterDad** [comment]
Can you please post a code snippet or Codepen link?  This is a very common use case that works fine in hyperapp.

**Comment by zjhiphop** [comment]
Yes , of course.

```
import { h, app } from "hyperapp";
import { Device } from './views/devices';
import { Layout } from './views/layout-area';
import Client from './mqtt';
import Bus from './states/event-bus';
import * as Shadow from '@cloudtea/iot-shadow';

const state = {
  switches: [],
  devices: []
}

console.log(Device, Layout);

const actions = {
  setDvc: value => state => ({ devices: value })
}

// when server receive new data will send broadcast
Bus.on('cmd/' + Shadow.FRAMES_ENUM.FRAME_CMD.CMD_GET_DEV, (d) => {
	console.log('Get Devices: ', d);

	actions.setDvc(d.subDevices.devices);  // here is what i tried to update state 
})

const view = (state, actions) => (
  <div class="am-g">
  	<h1>编排管理系统</h1>
  	<hr/>
    {
    	state.devices.map(({type, id, status}) => {
    		<Device type={type} id={id} status={status}></Device>
    	})
    }
    <Layout></Layout>
  </div>
);


app(state, actions, view, document.getElementById('container'))
```

**Comment by jorgebucaran** [comment]
@zjhiphop Try

```js
const main = app(state, actions, view, document.getElementById("container"))

Bus.on("cmd/" + Shadow.FRAMES_ENUM.FRAME_CMD.CMD_GET_DEV, d => {
  main.setDvc(d.subDevices.devices)
})
```

And read https://github.com/hyperapp/hyperapp#interoperability

> The app function returns a copy of your actions where every function is wired to changes in the state. Exposing this object to the outside world can be useful to operate your application from another program or framework, subscribe to global events, listen to mouse and keyboard input, etc.
