### ISSUE TITLE
Is there a reason why `var` is used instead of `const` in the whole project?

### ISSUE THREAD

**Issue by nicu-chiciuc** [hyperapp/hyperapp#708]
It's not a big change but it could add a little bit to the intent of the code.

**Comment by jorgebucaran** [comment]
@nicu-chiciuc See: https://github.com/hyperapp/hyperapp/blob/master/CONTRIBUTING.md#style

The reason is that I want to avoid introducing a compile step in the project. It shows that Hyperapp is simple.

One day, when IE11 is no longer supported, we'll use `const`, arrow functions, etc.
