### ISSUE TITLE
Type checking for props

### ISSUE THREAD

**Issue by fralonra** [hyperapp/hyperapp#714]
I love this framework and wish to use it in more projects.

But I am wondering is there a recommanded way to do **type checking** for props (It is very important in some cases) like what [prop-types](https://github.com/facebook/prop-types) do.

I konw it is not a good idea to embed this functionality into the main library, but writing a plugin may be fine.

**Comment by jorgebucaran** [comment]
@fralonra What about using TypeScript or flow?

**Comment by fralonra** [comment]
@jorgebucaran Thanks! I would like to try flow first.

**Comment by okwolf** [comment]
I would say `prop-types` is a very different solution to type checking than something like **Type**Script. The former doesn't require adding a build step and it emits warnings you can fix at your own leisure at runtime instead of errors that break the build.

I've thought about looking into how Hyperapp could add support for `prop-types` with a third party solution. It may or may not work for component props depending on if they are lazy going forward, but it should definately work fine for validating state values.

**Comment by Alber70g** [comment]
I referenced a PR with this issue. This was a mistake. Please ignore this one ~~Fix typing issue with Component<>~~

**Comment by selfup** [comment]
@okwolf so I guess with 2.0 we can apply "`prop-types`" as middleware.

Either dynamic import in non prod, or just no checks in prod given the lib is small enough 🙏

**Comment by rbiggs** [comment]
By the way, this also provides live type checking like with TypeScript, flags unused variables, typos, wrong use of types, wrong number of parameters, wrong types for parameters, etc.

**Comment by jorgebucaran** [comment]
@fralonra Did you have a chance to check flow and what was your impression?

@okwolf What would such a third-party solution look like? Is this something like how you use create-react-app with Hyperapp in [cra-hyperapp](https://github.com/hyperapp/cra-hyperapp)?

**Comment by fralonra** [comment]
@jorgebucaran `flow` is good, but as what @okwolf mentioned above, it seems to be different from `prop-types` which is a runtime type checker.

Btw, what about [flow runtime](https://github.com/codemix/flow-runtime)? I haven't tried it yet.

**Comment by jorgebucaran** [comment]
Cool! @fralonra What else do we need to resolve here?

**Comment by fralonra** [comment]
@jorgebucaran Nothing. Thanks.

**Comment by jorgebucaran** [comment]
@fralonra Thank you! I'm still not clear about what's the relation between flow and prop-types. I understand flow is a type checker, like a minimal, stripped down, savage version of a TS subset. Is prop-types something even narrower in scope?

**Comment by rbiggs** [comment]
The docs: https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes

**Comment by jorgebucaran** [comment]
Thanks!
