### ISSUE TITLE
Why msg?

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#72]
Why are actions called `msg`? Is there any reason for keeping this? I know that (and actually use) they can be renamed, as it's just a "conventional name".

I'd vote for changing it to `actions` though, assuming that there's nothing I'm missing of course.

**Comment by tunnckoCore** [comment]
Yep. I'm for that too and thinking it from day one.

**Comment by jbucaran** [comment]
From the Elm examples. 

```elm
type Msg = Increment | Decrement

update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1
```

Notice that `msg` is not a property exported by HyperApp anywhere, so you're free to use another name, alternative ones I considered:

* dispatch
* post
* send

The problem with those is that they are verbs and HyperApp prefers:

```
obj.actionName(...)
```

as opposed to

```
send("actionName", ...)
```

IIRC, if you browse the git history, you'll find that the `msg` object was implemented in a way that supported both styles above, but I felt that would be a hub of confusion, so I chose the one that does not use "strings" to send actions.

Another good alternative is:

* action

**Comment by tunnckoCore** [comment]
> not use "strings" to send actions.

and

> msg.actionName(...)


Yep. That's another thing that I like in hyperapp. Feels better than the choo's alternative `send(actionName)`

**Comment by jbucaran** [comment]
Yeah, it's not a big deal though. I'm pretty choo could implement this as well, but they already went with the other style, which is okay.

**Comment by liadbiz** [comment]
yeah, I like the ideas that do not use "strings" to send actions like redux actually do.

but I personally think msg is not a good name for a container that keeps all the action , which you called "reducers", and effects in. both reducers and effects both describe some kind of "transformation" or "actions" . maybe these two would be better to understand, And you can make it to "trans" or "acs" for shorter typing.

**Comment by jbucaran** [comment]
@liadbiz I think the best name is `action`, that's how they are described in the docs and the wiki as well. I just used `msg` to mimic Elm conventions. This is just a documentation change, since HyperApp itself does not know anything about a `msg` property.

**Comment by liadbiz** [comment]
@jbucaran   right. just better comprehensible.

**Comment by dodekeract** [comment]
@jbucaran I'd say plural is more appropriate here, otherwise it implies that there is only one action per effect/view.

**Comment by jbucaran** [comment]
@dodekeract I would like to clarify, so as to make sure we're all on the same page here, that HyperApp is not aware of any `msg` named property. This is just a regular identifier for an object that is the result of merging `reducers` and `effects`. You can use the name you find more approachable.

**Comment by dodekeract** [comment]
@jbucaran I was under the impression that you read my inital comment. I'm not retarded. I'm simply suggesting that the docs should use the plural form instead of singular.

**Comment by tunnckoCore** [comment]
Plural yea. `actions` is great.

**Comment by jbucaran** [comment]
@dodekeract I didn't imply you were retarded lmao. Funny. I've renamed it to actions both in the docs and internally! I should be releasing a new version tonight.

**Comment by jbucaran** [comment]
Docs have been updated.

* `msg` ➡️ `actions
