### ISSUE TITLE
Cycle reverse-i-search in bash shortcut collision

### ISSUE THREAD

**Issue by gonzalocasas** [hyperapp/hyperapp#722]
This might be a bit of an edge case, but anyway. I am running `hyper` on Windows 10, and using WSL (Windows Subsystem for Linux), so I am mostly on a bash prompt there. If I want to do reverse-i-search there, `Ctrl+R` works fine, but `Ctrl+shift+R` to cycle forwards does a reload, which -in that specific context- is not what I want ;)

Is there any way to fix that?

**Comment by jorgebucaran** [comment]
Hey, @gonzalocasas. You are looking for [HyperTerminal](https://github.com/zeit/hyper/issues). **Hyperapp** is a JavaScript UI framework. 

Cheers!  👋😄
