### ISSUE TITLE
IOError thrown by fast `stdout` prints

### ISSUE THREAD

**Issue by gonzalocasas** [hyperapp/hyperapp#723]
At first I thought this was a weird issue with my code, but I've eventually realized it's a problem in `Hyper` and one that is actually quite critical and forces me not to use it from time to time.

The error manifests itself as an `IOError` when running python code (perhaps other languages as well, but I have repro steps only for Python), which -at first- seems to indicate the bug is not in hyper, but in the user code, but the code to reproduce clearly shows it's not it ;)

My setup is as follows:
 - Hyper: `2.0.0 (stable)` 
 - Plugins: `none`
 - OS: `Windows 10`
 - Python: `2.7`

## Steps to reproduce

The test code to trigger the bug is:
```python
for i in range(500):
    print(i)
```

Copy the code in a `test.py` file and run it: 

    $ python test.py

## Expected result

500 integers printed out on the console

## Actual result

`IOError` thrown by python at a non-deterministic point in the list traversing.

Screenshot of the code running on a `hyper` console:
![image](https://user-images.githubusercontent.com/933277/42321761-4d6fa66e-805a-11e8-8397-592cfc3d1b27.png)

Screenshot of the same code running on Windows' `cmd` console:
![image](https://user-images.githubusercontent.com/933277/42321782-5d354842-805a-11e8-8f58-d3b5b11971f4.png)

The error occurs *always* on Hyper, sometimes earlier in the loop, sometimes later, but always throws at some point. Adding delays inside the loop (e.g. `sleep(0.08)`) seems to mitigate the issue, so I assume the write rate of stdout is too high for something that is processing internally and it just gives up at some point.

**Comment by gonzalocasas** [comment]
Sorry, wrong repo.

**Comment by jorgebucaran** [comment]
Hey, @gonzalocasas. This is the second issue you open by mistake. https://github.com/hyperapp/hyperapp/issues/722

You are looking for [HyperTerminal](https://github.com/zeit/hyper/issues). **Hyperapp** is a JavaScript UI framework.
