### ISSUE TITLE
Click, fetch link and open new

### ISSUE THREAD

**Issue by alexey13** [hyperapp/hyperapp#729]
Good day to all!

In view link. Onclick on that link action fetch that link and need to open a new fetched link in the same click, but now new link opens in next click.
I try to make click => actionFetchLink => viewNewLink => openNewLink
Now i have click => openOldLink => actionFetchLink => viewNewLink
Why i need it? Amazon links very short live period, need to fetch them.

`a({ href: state.links.filter( z => z.id === x.id),
	onclick: e=> {actions.fetchLink}},
        "linkname"
)`

Thanks in advance! Hyperapp my first frontend tool, not using React, Redux and not plan to start. Love Hyperapp

**Comment by jbmonroe** [comment]
I think I'm missing some vocabulary here.  Fletch: v. to put a feather on an arrow shaft.

Do you mean "fetch?"  I can't find any Google references to "fletch a link."

**Comment by alexey13** [comment]
Yes, fetch. https://docs.pusher.com/chatkit/reference/javascript#fetching-an-attachment

**Comment by zaceno** [comment]
If you can make a codepen / jsfiddle that would help, @alexey13 

But I notice what looks like a mistake in the code you posted above: shouldn’t there be parenthesis after actions.fetchLink() ?

**Comment by jorgebucaran** [comment]
Hi, @alexey13! Thanks for trying out Hyperapp.


@zaceno Is right. This code doesn't run your action.
```js
 onclick: e=> { actions.fetchLink }
```

Now, this code does.

```js
 onclick: e=> { actions.fetchLink() }
```

Hope that helps! 👋 

If you consider this problem resolved, please close the issue to let us know.

**Comment by jbmonroe** [comment]
Thanks Alexey--the vocabulary in this business changes at least once a week.  Viz: "rehydrate" and some other new verb uses for JS frameworks. :)

**Comment by alexey13** [comment]
@zaceno, @jorgebucaran, parenthesis after actions.fetchLink() was mistake yes. Big thanks for your time guys! I made a codepen https://codepen.io/alexzhav/pen/MBwgqW

**Comment by alexey13** [comment]
@jorgebucaran, no and I wouldn't call it problem:)

**Comment by jorgebucaran** [comment]
@alexey13 Can we close here or do you still need help with something else? :)

**Comment by alexey13** [comment]
Guys why in this case https://codepen.io/alexzhav/pen/qydOyK function fire before a href ?
But hyperapp fire it after a href https://codepen.io/alexzhav/pen/MBwgqW ?

**Comment by jbmonroe** [comment]
Not sure--no matter what happens, changing the link text is irrelevant because the href change obliterates the anchor, button, or other element.

The thing is that Javascript RTC guarantees that all the statements are executed (easier to see in the first example), but any scheduled real DOM update _might not occur_ because the browser has already been queued that it has to launch a new HTTP request and a visual update would be pointless.

**Comment by lukejacksonn** [comment]
I didn't know you used hyperapp @alexey13 😅good to hear! I just replied to your comment on the slack-clone.

**Comment by alexey13** [comment]
@jorgebucaran, will explain. Chat using Chatkit , files stored at amazon. Amazon using short live links. 60 seconds and after need to fetch link again. 
@jbmonroe, yes that's why I asked you guys, had a feeling that change href attribute on click is a bad idea. 
@lukejacksonn, glad to see you here!:) Yes I using Hyperapp. Love it.
With @lukejacksonn came to an idea that best solution would be fletch links using setInterval.

**Comment by jbmonroe** [comment]
Changing href on a click isn't a bad idea as long as you do everything else you need to do before that.  Whether doing it directly on an element via onclick is debatable, I agree.

I'm going to spend more time with Hyperapp when I get back to work--I'd started something with Vue in mind and I might just change my mind.
