### ISSUE TITLE
Lifecycle events in HyperApp 2

### ISSUE THREAD

**Issue by dmitrykurmanov** [hyperapp/hyperapp#736]
What about using popular libraries? I think that it is a real use case. For example standard jQuery [datepicker](https://jqueryui.com/datepicker/).  

I've created an example with the datepicker and hyperapp1 with `oncreate` event
https://jsfiddle.net/badgoto/tfoxqd6h

How can I achive this in hyperapp2 ?

Thanks.

**Comment by jorgebucaran** [comment]
@dmitrykurmanov I eventually want to remove lifecycle events from Hyperapp, but I'm most likely going to keep them in HAV2.

See also: #717

**Comment by dmitrykurmanov** [comment]
@jorgebucaran I am sorry. I've missed #717

**Comment by zaceno** [comment]
@dmitrykurmanov detecting when an element is added to the dom, and doing something with it, is possible through the MutationObserver api. So it's still technically possible even if Hyperapp removes lifecycle events.

Having said that, it can easily get very complicated. After having played with MutationObserver  a bit I've become an even bigger fan of the lifecycle-events we currently have. They're just so convenient.

**Comment by dmitrykurmanov** [comment]
@zaceno Thanks, MutationObserver api is interesting variant, I didn't think about it.

PS this issue is duplicate of #717 I've moved my question there.
