### ISSUE TITLE
Typescript questions

### ISSUE THREAD

**Issue by SteveALee** [hyperapp/hyperapp#738]
# View 

A view is a function but the declaration is an interface. Why?
https://github.com/hyperapp/hyperapp/blob/master/hyperapp.d.ts#L73-L79

I'd expect it to like a `app`. What am I missing?
https://github.com/hyperapp/hyperapp/blob/master/hyperapp.d.ts#L90

# Extra char
The prefixed pipe char seems strange and confused me. I see it gives nice alignment but I think should be dropped
https://github.com/hyperapp/hyperapp/blob/master/hyperapp.d.ts#L69

# Components

The readme says a component only takes props and not wired to actions and state but the test example takes actions and state as props. This is confusing to say the least. I suggest the example is changed, `count`, `up` and `down` only! as props and not passing the global objects in.
https://github.com/hyperapp/hyperapp/blob/master/test/ts/Component.tsx#L12

You obviously need to use State and Props as a lazy component can return a View and a View needs the global State and Props.  

Would it be better to have separate `Component` and `LazyComponent`?

**Comment by SteveALee** [comment]
# View
OK so `interface` is equivalent to `type`. at least in this context.

I propose changing to `type` would be clearer - but might just be me :)

**Comment by jorgebucaran** [comment]
@SteveALee Perhaps a PR would be a better way to discuss the types and changes you are proposing? 🤔

**Comment by SteveALee** [comment]
@jorgebucaran Your are quite right! :) It sort of expanded as I was writing it.

**Comment by SteveALee** [comment]
@jorgebucaran see #739

**Comment by jorgebucaran** [comment]
@SteveALee Okay, let's close here then?

**Comment by jorgebucaran** [comment]
Thanks! 👍
