### ISSUE TITLE
Bug when switching nodes of different types in V2

### ISSUE THREAD

**Issue by zaceno** [hyperapp/hyperapp#744]
Using the V2 branch of hyperapp, there seems to be a bug when you swap out a vnode for one with a different tagName.

See here: https://codesandbox.io/s/lp3j0ynqoz

**Comment by zaceno** [comment]
Further development: it only seems to happen when the node you're switching is one level deep. So:

This works:
```jsx
state => <main><div>{state ? <div>bar</div> : <p>Foo</p>}</div></main>
```

This does *not* work:
```jsx
state => <main>{state ? <div>bar</div> : <p>Foo</p>}</main>
```

**Comment by jorgebucaran** [comment]
@zaceno Should be fixed now! 👍

**Comment by zaceno** [comment]
Fix confirmed!
