### ISSUE TITLE
why the document saying it does't support className while it does ?

### ISSUE THREAD

**Issue by lili21** [hyperapp/hyperapp#746]
> Note that non-standard HTML attribute names are not supported, onclick and class are valid, but onClick or className are not.

I don't think it true, cause I can use `className` and it works well.

**Comment by jorgebucaran** [comment]
You are right, but let's call that an _implementation detail_. You are advised to use `class` and not `className` with Hyperapp.

**Comment by lili21** [comment]
Hum, but `class` is keyword.

```jsx
<MyComponent class="custome-class" />

function MyComponent({ class }) {
  // keyword as variable name ?
  ...
}
```

**Comment by jorgebucaran** [comment]
You can this.

```jsx
<MyComponent class="custom-class" />

function MyComponent({ className }) {
   return <div class={className}>...</div>
}
```
