### ISSUE TITLE
State not updated

### ISSUE THREAD

**Issue by sschimmel** [hyperapp/hyperapp#747]
Hi,

I've just started developping using Hyperapp and I run into the problem that state is not being updated from an action and need some help figuring out why. The function called is returning an object so I expect the state to be updated. I've got hyperapp-debug running to check what's in the state and it's not updating nor is the element on the page.

Code is below. The function called by the button renders some SVG that is than converted to JSX using `svg-to-jsx`. It returns a promise so I'm using async await passing the resulting JSX to a different action to update the state.

When I add console.log() I see the SVG is being created and it's converted to JSX. It also is passed to the second function. It just is never stored in the state.

```
import "babel-polyfill";
import { h, app } from "hyperapp";
import debug from 'hyperapp-debug';
import freesewing from 'freesewing';
import pluginBundle from '@freesewing/plugin-bundle';
import brian from '@freesewing/brian';
import svgtojsx from 'svg-to-jsx';

import './index.scss'

freesewing.patterns = {
  brian
};

const state = {
  renderedPattern: 'test'
};

const actions = {
  renderPattern: () => async (state, actions) => {
    console.log('Rendering');
    const brianPattern = freesewing.patterns.brian;

    brianPattern.settings.measurements = {
      bicepsCircumference:   335,
      centerBackNeckToWaist: 480,
      chestCircumference:   1080,
      hipsCircumference:     950,
      naturalWaistToHip:     120,
      neckCircumference:     420,
      shoulderSlope:          55,
      shoulderToShoulder:    470,
      shoulderToWrist:       700,
      wristCircumference:    190
    };

    brianPattern.settings.mode = 'draft';
    brianPattern.settings.sa = 10;
    brianPattern.settings.units = 'metric';

    brianPattern.draft();
    const pattern = await svgtojsx(brianPattern.render());
    actions.updatePattern(pattern)
  },
  updatePattern: (pattern) => (state, actions) => ({renderedPattern: pattern})
};

const view = (state, actions) => (
  <div>
    <button onclick={actions.renderPattern}>Render pattern</button>
    {
      (state.renderedPattern) && <div>
        Test
        <svg> {state.renderedPattern} </svg>
      </div>
    }
  </div>
);

debug(app)(state, actions, view);
app(state, actions, view, document.body);

```

**Comment by jorgebucaran** [comment]
@sschimmel When something like this happens, I make a simple demo to see if I can reproduce the issue. I usually discover I was making a basic mistake in the process and then return to my app. Your code doesn't look wrong at first glance, but there are too many specific details irrelevant to Hyperapp, so I'm not certain if some of those details are causing trouble or not.

What I am basically asking you is to give me a [short, self-contained, correct example](http://sscce.org/). Do you think you could you do that?

**Comment by sschimmel** [comment]
Sure, hope this is helpful. I removed all the specific application logic and replaced it with a simple SVG drawing a red circle. Using this example the debugger still indicates that the state has not updated. The elements do update (checking with the developer tools) and the JSX is inserted as a string. The red circle does not appear.

```
import "babel-polyfill";
import { h, app } from "hyperapp";
import debug from 'hyperapp-debug';
import svgtojsx from 'svg-to-jsx';

const state = {
  renderedPattern: 'test'
};

const actions = {
  renderPattern: () => async (state, actions) => {
    const svg = '<svg height="100" width="100"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /></svg>';
    const jsx = await svgtojsx(svg);
    actions.updatePattern(jsx);
  },
  updatePattern: (pattern) => (state, actions) => ({renderedPattern: pattern})
};

const view = (state, actions) => (
  <div>
    <button onclick={actions.renderPattern}>Render pattern</button>
    {
      (state.renderedPattern) && <div>
        Test
        <svg> {state.renderedPattern} </svg>
      </div>
    }
  </div>
);

debug(app)(state, actions, view);
app(state, actions, view, document.body);
```

**Comment by frenzzy** [comment]
@sschimmel could you please show what `svgtojsx(svg)` returns?
Probably the result is not compatible with hyperapp VDom.
And yes, you can use `<div innerHTML={svg} />` attribute directly without `svgtojsx`.

**Comment by jorgebucaran** [comment]
@sschimmel Have you verified that svg-to-jsx produces a valid Hyperapp VNode?

**Comment by sschimmel** [comment]
Probably svgtojsx did indeed not return compatible code. It's made for React, my guess was it should work it being JSX. Setting innerHTML on the original SVG though did work.

Thanks for all the help! :)
