### ISSUE TITLE
OnBeforeCreate lifecycle event ... or something?

### ISSUE THREAD

**Issue by zaceno** [hyperapp/hyperapp#76]
I've hit a wall in my self-assumed hyperapp tutorial project (app that you just log in & out from). I want the main view (route: /) to render if the user is already logged in, and if not, I want the app rerouted to /login, where the login form is rendered. On successful login, you get routed back to /.

Tried implementing this by calling `msg.setLocation('/login') in an oncreated event on the root-div of the "main view". But I notice that this *does not prevent* the main view from being rendered once before being sent to /login (where the page renders the login view instead)

The problem here, of course, is that hyperapp is already busy rendering my view in the oncreated event, and isn't about to abort that rendering just because I reroute the application. 

So I was thinking, perhaps there should be a view lifecycle event, or a hook maybe, that happens before the 'point of no return'. Allowing for a last minute change of heart, so to speak.

If that doesn't make sense, how do you suggest solving the problem of (as in my example) having an authentication-guard for certain pages that bounces you to a login page if you're not logged in?

**Comment by zaceno** [comment]
After some reflecting: perhaps the right place to put this sort of functionality would be in the routing. But that would necessarily make the router more complex, which may be antithetical to the principles of hyperapp. 

Either way, I'm still curious how (any of) you would solve the basic problem of authenticated access to specific routes.

**Comment by tzellman** [comment]
Do you have an example you could share?

**Comment by zaceno** [comment]
Actually, I think I'm going to close this one.

I was hell-bent on keeping the login page in it's own `/login` route (rather than as a conditionally rendered view), but the more I think about it, the less important that login-route seems. So  I withdraw the question.

**Comment by jbucaran** [comment]
@zaceno Please share your findings back with us when, and if you do finish the project you're talking about. 🙏

**Comment by zaceno** [comment]
Will do!

I am actually porting (incrementally) an app I've already written with vue.js to hyperapp (just for fun :) ).  In vue, I was using the approach of having a special route for the login page, and a guard for the authenticated pages (as I was trying to do in my examples above).

The more I thought about it, I realized that the solution I have in Vue, hinges on the fact that the Vue-router supports a kind of nested component routing (where for example a route '/A/B' means "render parent view A, with the child view B, and route '/A/C' means "render parent view A with child view C")

Since the hyperapp router is intentionally much more simplistic, I undertand I should avoid too much routing-voodoo as I port over. For different tools, solve the same problem in different ways, each appropriate to the respective tool :)

For now, I'll go with conditional rendering. But if I happen to have any neat ideas, I'll be sure to submit a PR.
