### ISSUE TITLE
Don't distribute hyperapp.hx.js

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#78]
Browser usage has a fairly limited use case, so if one is working on a production site, please compile your templates/hyperx/jsx during development-time. How? Use Browserify, Webpack, Rollup. There are some examples in the README. There's also:

* https://github.com/selfup/hyperapp-one
* https://github.com/tzellman/hyperapp-boilerplate

Put this another way, [https://unpkg.com/hyperapp/dist/hyperapp.js](https://unpkg.com/hyperapp/dist/hyperapp.js) should be reserved for prototyping, CodePens, fiddles, etc., not a production site.

With that in mind, I no longer see the value of distributing `hyperapp.hx.js`.

**Comment by liadbiz** [comment]
why close this issue?

**Comment by jbucaran** [comment]
Because the docs were updated.

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp#cdn
