### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by ntrpy** [hyperapp/hyperapp#81]
This is not a big issue, just confuses newcomers, I guess:
now that you separated the router from the rest of the framework, (which is a good thing), the simple example in the getting started docs is no longer working, since the latest version has not been tagged && updated in npm. Of course, installing from git works out of the box.

HyperApp looks and feels really awesome, please continue your terrific work!

**Comment by jbucaran** [comment]
@ntrpy Thanks! 

Extracting the router was a good idea, putting the router in another repo was a bad move. I've brought the router back into HyperApp as a requirable module and updated the docs.

I am going to update the examples to make sure everything is working, then we can close here.

**Comment by jbucaran** [comment]
@ntrpy https://github.com/hyperapp/hyperapp/releases/tag/0.1.0
