### ISSUE TITLE
How to use function for composition

### ISSUE THREAD

**Issue by rbiggs** [hyperapp/hyperapp#82]
In the checkin #77 you mention about returning a function for composition. This is not mentioned in the README. An example would be nice to illustrate how this works. Is this a feature that only works with JSX? Is so, could it also be implemented to work with Hyperx?

**Comment by tunnckoCore** [comment]
Nope, it isn't only JSX. 

You could do 

```js
const { h } = require('hyperapp')

function Foo ({ name, title, children }) {
  return h('section', [
    h('h1.heading', title + ' ' + name),
    h('p', children)
  ])
}
const tree = h(Foo, { name: 'charlike', title: 'Hello' }, 'Hello World')
```

**Comment by tunnckoCore** [comment]
and JSX variant, i believe


```jsx
/** @jsx h */
const { h } = require('hyperapp')

const Foo = ({ name, title, children }) => (<section>
  <h1 className="heading">{title} {name}</h1>
  <p children={children} />
</section>)

const tree = <Foo name="Charlike" title="Hello">Hello World</Foo>
```

**Comment by jbucaran** [comment]
@rbiggs This feature only works for JSX. I'll update the docs to add an example.

In Hyperx you can do like @ungoldman's suggests in https://github.com/substack/hyperx/issues/9), but that's not nearly as convenient as `<MyComponent propts=...>children</MyComponent>`.

@niksy's fork of hyperxify seems to deal with this via Hyperx, but it hasn't been merged yet. 

Our fork of hyperxify to support custom `h` functions hasn't been merged either:

* https://github.com/substack/hyperxify/pull/8

Maybe @substack's is busy?

**Comment by tunnckoCore** [comment]
> @jbucaran  This feature only works for JSX.

Why not to work for raw h calls? It would, since `h` can accept first argument to be function as what tags with uppercased first later is transformed/transpiled to.

```js
const tree = <Foo name="Charlike" title="Hello">Hello World</Foo>
// => h(Foo, { name: 'Charlike', title: 'Hello' }, 'Hello World')
```

**Comment by jbucaran** [comment]
@tunnckoCore Right. I overlooked it **also** works for `h`.

**Comment by tunnckoCore** [comment]
Yea just seen the slider. It looks great!

> when using babel.

Or `rollup-plugin-jsx`

**Comment by jbucaran** [comment]
@rbiggs I think we can close now. Function composition is supported in HyperApp via `h`. As a result, it just works with JSX, but not with Hyperx, unfortunately, and there's nothing actionable we can do here.
