### ISSUE TITLE
Both className and class attributes created.

### ISSUE THREAD

**Issue by tunnckoCore** [hyperapp/hyperapp#85]
There is `classname` and `class` attributes at the created DOM nodes.

![2017-02-13-00 08 36_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22866498/3b9407e2-f180-11e6-96d1-6d54a7064a04.png)

Kinda feel that i faced that while decoupling the dom diffing and fixed it but cant remember how and where it was and where the codes are. (_just did kinda dozen rewrites of few things in a couple of folders; wrote 3-4 new packages that i am lazy to write tests and docs, haha. i'm totally :face_with_thermometer: :imp: :anger:_)

**Comment by selfup** [comment]
I think I have seen something similar here:

http://codepen.io/selfup/pen/WRgOrR

### To reproduce

Make two ideas

Hit X on the latest idea

The X button is still highlighted on the idea that was not clicked 🤔

**Comment by jbucaran** [comment]
@selfup It seems we're talking about two different bugs here?

One with className (safely) polluting the element's HTML and another one which is the one that can be seen in @selfup's CodePen.

Both need fixing, but I'm more interested in fixing the second one as that's a bug that has been bothering me in the TodoMVC implementation for a while.

**Comment by selfup** [comment]
We might very well be, but I am wondering if it has to do with the diffing.

If you want I can submit a new issue :smile: 

Or we can just keep track of it in here

**Comment by jbucaran** [comment]
@selfup I think they're different, but let me investigate further, they might be related after all.

**Comment by jbucaran** [comment]
@selfup @tunnckoCore Could this be a bug/feature of Hyperx? This does not occur when using JSX.

**Comment by tunnckoCore** [comment]
dont think so. try raw h calls?

i'll do a pen and will see if when it appears

**Comment by jbucaran** [comment]
@tunnckoCore I can confirm both class and className are added when using hyperx, but definitely not when using JSX.

**Comment by selfup** [comment]
@jbucaran Both examples with issues are JSX apps.

**Comment by jbucaran** [comment]
@selfup Alrigh, can we open a new issue to track the bug you described [here](https://github.com/hyperapp/hyperapp/issues/85#issuecomment-279255872)?

Let's keep this issue about the class/className bug.

@tunnckoCore Can you confirm this occurs when using JSX too?

**Comment by jbucaran** [comment]
@tunnckoCore @selfup The reason you have both classname and class is because you're using className in the JSX.

See: https://github.com/selfup/hyperapp-one/blob/master/src/views/counter.js#L10.

@selfup Consider using only class? We're not constrained by this.

**Comment by ngryman** [comment]
@jbucaran I have the same initial issue with duplicated `classname` and `class` attributes on each element.
I'm using `hyperx` and the `class` attribute (not `className`).
I don't have any actions, just a static model, so there is no diffing involved (afaik).

Do you have a clue on this particular bug?

**Comment by jbucaran** [comment]
@ngryman Yes, I just had a chance to look at this.

See this [Pen](http://codepen.io/jbucaran/pen/ZeOwgr?editors=0012).

**Comment by jbucaran** [comment]
Hyperx adds a `classname` attribute to the virtual node data object. In Hyperapp we set the className property of the element which causes the class to be set correctly.

I don't understand why Hyperx does this. This is the commit that introduces this functionality in Hyperx.

* https://github.com/substack/hyperx/pull/22

**Comment by ngryman** [comment]
Ok, I get it.
Any chance this does not work for some reason: https://github.com/feross/hyperscript-attribute-to-property/blob/master/index.js#L14?

**Comment by jbucaran** [comment]
@ngryman Well observed, this is definitely odd and requires some investigation. 🤔

**Comment by ngryman** [comment]
@jbucaran On my local machine, only `className` is left so `class` is well deleted.
I can investigate a little on this...

**Comment by jbucaran** [comment]
@ngryman Wait, _it's_ working, so it's `class` what gets deleted.

**Comment by jbucaran** [comment]
In the case of JSX, `<div class="hi">Hello</div>` yields this virtual node:

```jsx
{
  children: ["Hello"],
  data: {
    class: "hi"
  },
  tag: "div"
}
```

**Comment by ngryman** [comment]
Using `hyperx` I have a different result.

**Source**

```js
const { h } = require('hyperapp')
const hyperx = require('hyperx')
const html = hyperx(h)

const vnode = html`<div class="foo">`
console.log(vnode)
```

**Output**

```js
{
  children: [],
  data: {
    className: "foo"
  },
  tag: "div"
}
```

Which with my (limited) understanding makes sense as `hyperscript-attribute-to-property` proxy does replace `class` with `className`. Does `JSX` itself replace `className` in favor of `class`?

**Comment by ngryman** [comment]
It makes sense as `hyperscript-attribute-to-property` proxy does replace `class` with `className`. `hyperx` probably expects the rendering framework to transform `className` into a `class` attribute.

**Comment by jbucaran** [comment]
@ngryman Hmm, that sounds right. But why?

**Comment by ngryman** [comment]
My guess is that they want to be able to put `class` instead of `className` in the markup.
It makes sense as unlike `jsx` markup is a string, so there is no reserved keyword to handle.
But in the same time they also want to be `react`-compatible, `react` only supports `className`.

**Comment by ngryman** [comment]
Either you could patch your code to *revert* `className` to `class` or we could file `hyperx` an issue to ask them if it's possible to add some kind of opt-in for this transform.

**Comment by jbucaran** [comment]
> Either you could patch your code to revert className to class or we could file hyperx an issue to ask them if it's possible to add some kind of opt-in for this transform.

Sounds like a plan: https://github.com/substack/hyperx/issues/48.

**Comment by tunnckoCore** [comment]
hallelujah

**Comment by ngryman** [comment]
@jbucaran Another issue related to this one is that for `svg` elements only `classname` attribute is kept so it's basically impossible to style `svg` elements for now 😢

I have a feeling the `hyperx` issue may take some time to resolve, should we implement a temporary fix that just reverts `className` to `class`?

**Comment by jbucaran** [comment]
@ngryman You against JSX?

**Comment by jbucaran** [comment]
@ngryman I can get that, so then why not fork hyperx, fix the issue (send a PR along upstream too) and use your fork in the meantime.

**Comment by ngryman** [comment]
@jbucaran Good idea.
Haha I'm not against `jsx` but in the quest of a minimal setup with `es6` native solutions ⚔️

**Comment by ngryman** [comment]
@jbucaran fyi https://github.com/substack/hyperx/pull/49

**Comment by ngryman** [comment]
PR has been merged and starting from `hyperx` `2.2.0` you can now disable this:
```js
const { h, app } = require("hyperapp")
const hyperx = require("hyperx")
const html = hyperx(h, { attrToProp: false })
```

**Comment by jbucaran** [comment]
Good job @ngryman! 🍟 🍔

**Comment by jbucaran** [comment]
@ngryman How would a PR for hyperapp that deals with this look like? 

```js
const html = hyperx(h, { attrToProp: false })
``` 

it's kinda ugly.

**Comment by ngryman** [comment]
I totally agree it's ugly 😢

TBH if we think about the full boilerplate, it is kinda heavy too:
```js
import { h } from 'hyperapp'
import hyperx from 'hyperx'

const html = hyperx(h)
```

We should find a solution to wrap and expose this in some way.

## Peer dependency

We could reference `hyperx` as a peer dependency and then export a helper `html`:
```js
// html.js

import { h } from 'hyperapp'
import hyperx from 'hyperx'

export default hyperx(h, { attrToProp: false })
```

So now we can simply do:
```js
import { html } from 'hyperapp'
```

## New package

We could create something like `hyperapp-hyperx` and do the same. It's not my favorite but it preserves SoC.

@jbucaran If you have other ideas? I don't know how others deal with this.

**Comment by jbucaran** [comment]
> We could reference hyperx as a peer dependency and then export a helper html:

It was like that when I first released the project. The problem is: I couldn't find a way to support both Hyperx and JSX in an unopinionated way.

There may be other template literal or JSX-like libraries in the future and I'd like to support them all if possible.

**Comment by jbucaran** [comment]
@ngryman 
> TBH if we think about the full boilerplate, it is kinda heavy too:
>
>  import { h } from 'hyperapp'
  import hyperx from 'hyperx'
  const html = hyperx(h)

There's no way about it unless we make other compromises. I tried something, but was ignored too.

See: https://github.com/substack/hyperxify/pull/8

**Comment by ngryman** [comment]
I get it, why not something like installing any template function and then get it via `hyperapp`?
Naming is subject to change but this is the core idea.

This would be called once to install the template function, in `index.js` for example:
```js
import { app } from 'hyperapp'
import hyperx from 'hyperx'

app(/*...*/, template: hyperx)
```

And would be used like this in the views:
```js
import { html } from `hyperapp'
```

**Comment by jbucaran** [comment]
@ngryman Thanks, but there's absolutely no way to go around hyperx boilerplate, and I tried to address that in substack/hyperxify#8. 

Even if we export an `html` module out of the box, the boilerplate will have to be written somewhere, and **worse**, it will be impossible to use hyperxify to remove the hyperx parser from your application bundle.

The reason for the current boilerplate is not to "punish" hyperx users, on the contrary, it's to make using hyperx with hyperapp not suck (consider the alternative, sending the entire parser down the write, not to mention it's slow, but the bytes!).

Finally, I think the syntax you've proposed doesn't work with JSX either.
