### ISSUE TITLE
Can I use hyperapp with trueadm/t7 template function (rel. hyperx)

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#88]
[**t7**](https://github.com/trueadm/t7) is a template function, similar to hyperx, but more featureful with support for components, splats, control flow and a bunch of other stuff.

* Can it be used with hyperapp's `h`? 
* Can we use it out of the box or PR to trueadm/t7 is required?

**See also**

* Syntax support https://atom.io/packages/t7 for :atom:

**Comment by selfup** [comment]
Oh wow that is really cool!

There is a lexer for vue templates `language-vue` that works for backticks.

I wonder how those work. I think they look for a keyword

**Comment by jbucaran** [comment]
@selfup I wonder if that's a tagged template function like hyperx or something else? Do you happen to know?

**Comment by selfup** [comment]
It turns the string into a render function, so it must be something similar. Let me check the source code!

**Comment by jbucaran** [comment]
🤔 That sounds more like what [hyperxify](https://github.com/hyperapp/hyperxify) does to hyperx.

**Comment by trueadm** [comment]
@jbucaran ping me if you have time on the Inferno slack and I'll be happy to give you permissions on t7 if you want to work with it. I don't have a huge amount of time to dedicate to the project anymore and the codebase could do with a tidy up but I have some pretty awesome ideas on how it can be improved :)
