### ISSUE TITLE
Change update to reducers

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#91]
I used `update` because that's how Elm calls it, but now that I am in the process of documenting HyperApp more thoroughly, I find myself explaining that update is an object composed of reducers, which begs the question, why then not just call it _reducers_?

**Comment by SkaterDad** [comment]
I don't personally like the term "reducers", since I'm not from a computer science background.  I know that term is used a lot in redux & others, but I've never liked it. 

Update functions, as elm uses, is more semantic and obvious in my opinion.

**Comment by jbucaran** [comment]
@SkaterDad I'm not a big fan of the term either, hence my original choice. 

Currently the docs state:

> Update is an object composed of functions called reducers. A reducer describes how to derive the next model from the current model.

In your code, `update` looks cool, but in the docs it's odd to use a verb and say that's an object. 

What do you think?

**Comment by SkaterDad** [comment]
I see your dilemma now.  The object should probably be a plural noun?  `updaters`, `updateFunctions`, etc... are a bit awkward, I suppose.

Vuex calls them `mutations` instead, which is pretty nice.  They're all created in a big object like hyperapp, so it's 1:1 analogous.  Here's the docs: https://vuex.vuejs.org/en/mutations.html

**Comment by jbucaran** [comment]
I think vuex choice is acceptable, since it's really obvious your're mutating a value.

```js
const store = new Vuex.Store({
  state: 1,
  mutations: {
    add (state) { state++ }
  }
})
```

However, in HyperApp, things are slightly different:

```jsx
update: {
  add: model => model + 1
}
```

```jsx
const newModel = add(oldModel, data)
render(view(newModel))
```

We don't mutate the model, rather create a new one from the old one.

---

Now, in reality, hyperapp **does** mutate the model, because that was simpler to implement and maintain than this:

```jsx
const render = model =>
    view(model, (action, model) =>
        patch(element, render(reduce(model, action))))
```

<blockquote><small>From <a href="https://gist.github.com/jbucaran/4dfa567e38ca222c25c46184b3a5df99">yo-yo-app</a>.</small></blockquote>

But now, that's an implementation detail 😆

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp/commit/7a60a8f18163c31ec74c174c18337b7a31ae2dfb

I've changed it to reducers, but still back supporting `update`, which should be deprecated by 0.6.0 or later.
