### ISSUE TITLE
Undefined Parameter Causes Crash

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#95]
### [Broken Code](http://codepen.io/anon/pen/egoRKm?editors=0010)

```javascript
const { h, app } = hyperapp
/** @jsx h */

const Example = ({a}) =>
	<div>
		Item {a}
	</div>

app({ 
    model: "Hi.", 
    view: model => <div><Example/>this should always render</div>
})
```

> TypeError: undefined is not an object (evaluating 'node.data')

### [Working Code](http://codepen.io/anon/pen/wgZeQQ?editors=0010)

```javascript
const { h, app } = hyperapp
/** @jsx h */

const Example = ({a}) =>
	<div>
		Item {a}
	</div>

app({ 
    model: "Hi.", 
    view: model => <div><Example a=""/>this should always render</div>
})
```

---

Again, I'm not sure if this is intentional or a bug. Might be nice to show a better error if the `ENV` isn't `production` in case this is intended.

**Comment by jbucaran** [comment]
@dodekeract Couldn't repro. Both work fine. Neither one render anything.

It would help if you could provide broken examples via a CodePen/Fiddle.

**Comment by jbucaran** [comment]
@dodekeract https://jsfiddle.net/q6Lu62L1/

**Comment by dodekeract** [comment]
Okay, then the issue is weirder than I expected: http://codepen.io/anon/pen/egoRKm?editors=0010

**Comment by jbucaran** [comment]
@dodekeract Thanks! I'll look into this. 💪

**Comment by jbucaran** [comment]
@dodekeract Fortunately this is somewhat related to https://github.com/hyperapp/hyperapp/issues/92, so fixing this might [kill two birds with one stone](http://idioms.thefreedictionary.com/kill+two+birds+with+one+stone.

**Comment by tunnckoCore** [comment]
Btw reference https://facebook.github.io/react/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored

**Comment by jbucaran** [comment]
@tunnckoCore Thanks, that's really useful. I was looking just for that a couple of days ago.

**Comment by dodekeract** [comment]
@tunnckoCore thanks for sharing, wasn't aware of the `.length` "bug"/issue.
