### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceChild' of undefined

### ISSUE THREAD

**Issue by danigb** [hyperapp/hyperapp#98]
Hi, 

I'm writing a simple app with hyperapp and JSX via rollup. The code is similar to this:

```js
const Editor = ({ text }) => <div id="editor">{text}</div>
const view = (model) => <div><Editor text={model.text} /></div>
const reducers = {
  setText: (model, text) => Object.assign(model, { text })
}
```

When I call `setText` via actions object, I get an error [here](https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L203): `Uncaught TypeError: Cannot read property 'replaceChild' of undefined`

If at the beginning of the `patch` function I add: `if (!parent) return`, ~~everything works at expected~~.

Do I'm missing something?

Thanks

----
EDIT: no, it doesn't work: it doesn't update the html.

**Comment by jbucaran** [comment]
Can you create a reproducible example?

BTW, I am not sure if you want to do the following:
```jsx
const reducers = {
  setText: (model, text) => Object.assign(model, { text })
}
```

Object.assign will mutate the model, which may or may not be the cause of the problem you are having. Instead, consider:

```jsx
const reducers = {
  setText: (model, text) => Object.assign({}, model, { text })
}
```

**Comment by danigb** [comment]
Hi, thanks for the quick response. Yes, I know I'm mutating the model, but as far as I know hyperapp doesn't require a new model, am I wrong? 

Anyway, I think the problem it's on my side. I'll keep the issue open until I do more research, but I'm now almost sure that it doesn't have anything to do with hyperapp.

Thanks

**Comment by jbucaran** [comment]
> as far as I know hyperapp doesn't require a new model, am I wrong?

A reducer must return a new model or part of a model. Really, whatever you return will be merged with the current model and assigned to the current model (thus becoming the new model).

>  I'm attaching quill to the #editor div. Probably the source of the problem.

Not sure how that works, but check out this demo using CodeMirror. 
* https://gomix.com/#!/project/hyperapp-code-mirror

**Comment by danigb** [comment]
Hi, 

I can't find the problem. I've made a [codepen](http://codepen.io/danigb/pen/QdXxQK) and here's the full source code:

```js
/** @jsx h */
const { h, app } = hyperapp

const initEditor = (el, onChange) => {
    const quill = new Quill(el)
    quill.on('text-change', (delta, oldDelta, source) => {
        onChange(quill.getText())
  })
}

const log = (t, v) => { console.log(t, v); return v }

const reducers = {
    setText: (model, text) => log('text', text)
}

const view = (model, actions) => 
    <div>
        <p oncreate={(e) => initEditor(e, actions.setText)}>{model}</p>
        <span>words: {model.split(/\s+/).length}</span>
    </div>

app({ 
    model: "Write something here.", 
    reducers,
    view
})
```

Any thoughts?

**Comment by jbucaran** [comment]
@danigb I'll have a look. What's this supposed to do/how to make it trigger the error?

**Comment by danigb** [comment]
Just write something (the div is contenteditable). The problem is that the exceptions are not shown in the codepen console. Probably have to move to gomix. I'm reading CodeMirror example right now.

**Comment by jbucaran** [comment]
I wrote something and no errors were triggered.

**Comment by jbucaran** [comment]
![screen shot 2017-02-20 at 20 50 06](https://cloud.githubusercontent.com/assets/56996/23124024/2c27abc2-f7ae-11e6-84c1-a1667f323e1b.png)

**Comment by jbucaran** [comment]
Why is there a log in the reducer? That will return `undefined` causing the model to become undefined, definitely not something you want.

**Comment by danigb** [comment]
Strange! When I write a letter, words is updated to "4" but then it stop working (I can't edit anymore). In you screenshot 'words' is not updated, so something goes wrong. 

By the way, `log` returns the value, not undefined.

**Comment by jbucaran** [comment]
Is https://unpkg.com/hyperapp@latest resolving to https://unpkg.com/hyperapp@0.4.2?

**Comment by danigb** [comment]
It seems so...

**Comment by jbucaran** [comment]
Okay, just checking that.

**Comment by jbucaran** [comment]
I think I know what you want to do, so let me fiddle with this for a bit.

**Comment by danigb** [comment]
Great! Thanks @jbucaran

**Comment by jbucaran** [comment]
@danigb 

```jsx
/** @jsx h */
const { h, app } = hyperapp

const Editor = ({ setText }) => 
    <div
        oncreate={ e => {
            const editor = new Quill(e)
            editor.on("text-change", _ => setText(editor.getText()))
        }}
    ></div>

app({
    model: "",
    view: (model, actions) => 
        <div>
            <em>{model.length === 0 ? "Type below..." : model}</em>
            <Editor setText={actions.setText} />
            <span>Words: {model.split(/\S+/).length - 1}</span>
        </div>,
    reducers: {
        setText: (model, text) => text.trim()
    }
})
```

**Comment by danigb** [comment]
Thanks! So, the difference is that you didn't set any child nodes inside the quill's div. So, if I want to set a initial value, I should use the `quill` instance methods, isn't it?... Thanks a lot!

**Comment by jbucaran** [comment]
@danigb Maybe? I'm not sure. This way was the one with less code, but you could try other, more composable/modular configurations.

If you need further help, try Slack, unless you discover a bug (they hide well), in that case let me know here :)
