### ISSUE TITLE
&& -> TypeError: replaceChild

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#99]
> TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.

Hyperapp apparently fails to insert a node if it previously decided not to render it.

## [Broken Code](http://codepen.io/anon/pen/jyjoar?editors=0010)

```javascript
const { h, app } = hyperapp
/** @jsx h */

app({
    model: 0,
    reducers: {
        add: model => model + 1,
        sub: model => model - 1
    },
    view: (model, actions) =>
        <div>
            <div>
                {model !== 0 && <h1>{model}</h1>}
            </div>
            <button onclick={actions.add}>+</button>
        </div>
})
```

## [Working Code](http://codepen.io/anon/pen/wgLbpB?editors=0010)

```javascript
const { h, app } = hyperapp
/** @jsx h */

app({
    model: 0,
    reducers: {
        add: model => model + 1,
        sub: model => model - 1
    },
    view: (model, actions) =>
        <div>
            <div>
                {model !== 0 ? <h1>{model}</h1> : <div/>}
            </div>
            <button onclick={actions.add}>+</button>
        </div>
})
```

---

## Meta

Might be related to #98.

**Comment by jbucaran** [comment]
Repro'd. 🤔 This bug was introduced with the feature of not rendering booleans.

**Comment by jbucaran** [comment]
We could go back to the previous behavior of rendering everything, so you must be verbose / use the ternary operator.

Another option would be somehow handling this case; like creating an empty node / dummy element.

**Comment by dodekeract** [comment]
React uses a HTML comment IIRC. Not sure if this works for us.

**Comment by jbucaran** [comment]
@dodekeract Okay, that's an interesting alternative. I play with that too.

In the meantime, I think bools are working correctly now (nulls too, but I commented it out so my head wouldn't explode).

See: https://github.com/hyperapp/hyperapp/tree/bools_and_nulls

**Comment by jbucaran** [comment]
Fixed in https://github.com/hyperapp/hyperapp/commit/e47017ae2e238fce675b3aad29fb9c24affe1329
